-- Generated by scripts/regulation-tables/emit-equations-sql.ts for iso5667_1 (Plan 3). New rows only; existing equations are never updated here (rulings live in scripts/verification/iso5667_1-STAGED-plan3-rulings.sql). Regenerate, do not hand-edit.
BEGIN;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-1-02-D1', 'determinands_count = count_rows(determinands)', ARRAY['determinands']::text[], 'determinands_count', NULL, '§3', 'Plan 3: Anzahl der im Parameterverzeichnis erfassten Bestimmungsgrößen („se debe compilar una lista de parámetros de interés“).', 'imported_unverified', '15.2       PROGRAMAS DE CARACTERIZACIÓN DE LA CALIDAD

Estos programas se proponen estimar uno o más parámetros estadísticos que caractericen la concentración o su variabilidad, o ambos, durante un
período definido. Por ejemplo, la media aritmética o la mediana indican la tendencia central de los resultados, y la desviación estándar indica la
variabilidad. Los resultados se pueden requerir como parte de una investigación de búsqueda, o para la caracterización de factores determinantes
que en la actualidad no sea necesario controlar, o para propósitos de control a largo plazo.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-1-02' AND s.code = 'ISO-5667-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-1-02-D2', 'n_programme = max_rows(determinands, n_required)', ARRAY['determinands']::text[], 'n_programme', NULL, '§15.2, §16.5', 'Plan 3: maßgebende Probenanzahl des Programms = größtes n_required über alle Bestimmungsgrößen; §16.5 bemisst n je Bestimmungsgröße, das Programm muss die anspruchsvollste erfüllen.', 'imported_unverified', 'Si las variaciones cíclicas son inexistentes o pequeñas en comparación con las fluctuaciones aleatorias, el número de las muestras por tomar sólo
tiene que ser lo bastante grande para cumplir la incertidumbre aceptable de la media aritmética de un factor determinante, a un nivel de confianza
dado.

Por ejemplo, si se aplica la distribución normal, de acuerdo con lo anterior, el intervalo de confianza L de la media aritmética de n resultados, a un
nivel de confianza seleccionado, está dado por la fórmula:


                                                                           2 Kσ
                                                                     L =
                                                                              n'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-1-02' AND s.code = 'ISO-5667-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-1-05-D1', 'sites_count = count_rows(sites_1)', ARRAY['sites_1']::text[], 'sites_count', NULL, '§8.1, §8.2', 'Plan 3: Anzahl der erfassten Probenahmestellen („la red de muestreo puede tener cualquier forma desde un solo sitio hasta todo un desagüe de río“).', 'imported_unverified', '8.2        IDENTIFICACIÓN DE LA LOCALIZACIÓN DEL MUESTREO

La identificación de la localización del muestreo permite tomar muestras comparativas en otros momentos. En la mayoría de las situaciones de
ríos, las localizaciones del muestreo se pueden fijar fácilmente mediante la referencia a características del banco ribereño.

En playas descubiertas de estuarios y costas, las localizaciones de muestreo análogamente se pueden relacionar con un objeto estático fácilmente
reconocible. Para el muestreo desde un bote en estas situaciones, se deben utilizar métodos instrumentales para la identificación de la
localización. Las referencias de mapas u otras formas estándar de referencia pueden ser muy valiosas.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-1-05' AND s.code = 'ISO-5667-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-1-07-D1', 'x_mean_calc = mean_rows(historical_results, x_value)', ARRAY['historical_results']::text[], 'x_mean_calc', 'mg/l', '§16.4', 'Plan 3: arithmetisches Mittel x̄ der vorliegenden Einzelergebnisse („las estimaciones de la media aritmética verdadera X … son la media aritmética, X“); Zwilling des Eingabefelds x_mean — Ablösung STAGED (iso5667_1-D-23).', 'imported_unverified', '16.4       DETERMINACIÓN DEL INTERVALO DE CONFIANZA Y DEL NÚMERO DE MUESTRAS

Para cierto número de resultados n, tomados al azar, las estimaciones de la media aritmética verdadera X y la desviación estándar, σ, son la
media aritmética, X , y s respectivamente de acuerdo con la siguiente fórmula:'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-1-07' AND s.code = 'ISO-5667-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-1-07-D2', 'n_hist = count_rows(historical_results)', ARRAY['historical_results']::text[], 'n_hist', NULL, '§16.4', 'Plan 3: Anzahl n der vorliegenden Einzelergebnisse („Para cierto número de resultados n, tomados al azar“). NICHT das n der Gl. 3 (erforderliche Probenanzahl) — iso5667_1-R-1.', 'imported_unverified', '16.4       DETERMINACIÓN DEL INTERVALO DE CONFIANZA Y DEL NÚMERO DE MUESTRAS

Para cierto número de resultados n, tomados al azar, las estimaciones de la media aritmética verdadera X y la desviación estándar, σ, son la
media aritmética, X , y s respectivamente de acuerdo con la siguiente fórmula:'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-1-07' AND s.code = 'ISO-5667-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-1-07-D3', 's_calc = stdev_rows(historical_results, x_value)', ARRAY['historical_results']::text[], 's_calc', 'mg/l', '§16.4', 'Plan 3: Standardabweichung s aus den Einzelergebnissen — Stichprobenform mit dem gedruckten Nenner n − 1 (stdev_rows ist die (n − 1)-Form, in dieser Sitzung an der Engine geprüft). Zwilling der prod-Gleichung 1, deren SUM()-Form die Engine nicht auswertet; die Ersetzung ist STAGED (iso5667_1-R-2).', 'imported_unverified', '                                                                           n

                                                                         ∑ (X − X )
                                                                        i =1
                                                                                    i
                                                                                        2


                                                                 S =
                                                                                 n −1'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-1-07' AND s.code = 'ISO-5667-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-1-08-D1', 'flow_measurements_count = count_rows(flow_measurements)', ARRAY['flow_measurements']::text[], 'flow_measurements_count', NULL, '§19.1', 'Plan 3: Anzahl der erfassten Durchflussmessstellen („Hay tres aspectos del flujo que es necesario medir“). Eine Zählung über method_ok ist NICHT emittiert: eine nicht gedruckte (Aspekt, Verfahren)-Kombination hat keine S21-Zeile, die Zelle bleibt leer und jede Aggregation darüber ginge auf manual_required (iso5667_1-F-1).', 'imported_unverified', 'Hay tres aspectos del flujo que es necesario medir, a saber,

           a)         Dirección del flujo.

           b)         Velocidad del flujo.

           c)         Tasa de flujo.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-1-08' AND s.code = 'ISO-5667-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
