-- Generated by scripts/regulation-tables/emit-equations-sql.ts for m277e (Plan 3). New rows only; existing equations are never updated here (rulings live in scripts/verification/m277e-STAGED-plan3-rulings.sql). Regenerate, do not hand-edit.
BEGIN;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-06-D1', 'greywater_type_code = if(count_rows(grauwasserquellen, source IN {''kitchen_sink'', ''dishwasher''}) > 0, 4, if(count_rows(grauwasserquellen, source == ''washing_machine'') > 0, 3, if(count_rows(grauwasserquellen, source == ''hand_washbasin'') > 0, 2, 1)))', ARRAY['grauwasserquellen']::text[], 'greywater_type_code', NULL, '§5 (type definitions), Tab. 2', 'Plan 3: Grauwassertyp aus den angeschlossenen Quellen — Küche (Spüle/Geschirrspüler) ⇒ 4 (B2), sonst Waschmaschine ⇒ 3 (B1), sonst Handwaschbecken ⇒ 2 (A2), sonst 1 (A1: Badewanne/Dusche); Label und Gesamtbereich je Code in TABLE2_TYPE; Ableitung des manuellen greywater_type STAGED (m277e-D-1).', 'imported_unverified', '- Type A1: greywater from bathtubs and showers
- Type A2: greywater from bathtubs, showers and hand washbasins

I Type B: high grade greywater, i.e. greywater from kitchen drains and/or washing machines
- Type B1: greywater from bathtubs, showers, hand washbasins and washing machines
- Type B2: greywater from bathtubs, showers, hand washbasins, washing machines and/or kitchen.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-06' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-06-D2', 'Q_GW_rows = sum_rows(grauwasserquellen, q_gw_p * persons)', ARRAY['grauwasserquellen']::text[], 'Q_GW_rows', 'l/d', '§9.3, Eq. (2)', 'Plan 3: Σ Q_GW-P,i · P_i über die Grauwasserquellen-Zeilen (Eq. 2); Übernahme als Q_GW auf M277E-07 / -17 STAGED (m277e-R-1 / m277e-C-1).', 'imported_unverified', '\mathrm{Q}_{\mathrm{GW}}=\Sigma\left(\mathrm{Q}_{\mathrm{GW}-\mathrm{P}, \mathrm{i}} \cdot \mathrm{P}_{\mathrm{i}}\right) \quad(\mathrm{I} / \mathrm{d}) \tag{2}'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-06' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-16-D1', 'Q_SW_rows = sum_rows(verbraucher_sw, q_row) + if(count_rows(bewaesserung_sw) > 0, sum_rows(bewaesserung_sw, q_row), 0)', ARRAY['verbraucher_sw','bewaesserung_sw']::text[], 'Q_SW_rows', 'l/d', '§9.2, Eq. (1)', 'Plan 3: Σ Q_SW-P,i · P_i (personenbezogene Zeilen) + Σ Q_SW-A,j · A_j (Bewässerungsflächen; 0 ohne Flächen — mindestens eine personenbezogene Zeile ist nötig, sonst "Keine vollständigen Zeilen"); Ablösung von Eq. (1) STAGED (m277e-R-2).', 'imported_unverified', 'Q_{S W}=\Sigma\left(Q_{S W-P, i} \cdot P_{i}\right)+\Sigma\left(Q_{S W-A, j} \cdot A_{j}\right) \tag{1}'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-16' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-16-D2', 'quality_category_code_rows = if(count_rows(bewaesserung_sw) > 0, 2, max_rows(verbraucher_sw, min_cat))', ARRAY['verbraucher_sw','bewaesserung_sw']::text[], 'quality_category_code_rows', NULL, '§9.2; §6.3, Tab. 4', 'Plan 3: höchste Tab.-4-Mindestkategorie über die Verbraucher-Zeilen (1 = C1, 2 = C2); jede Bewässerungsfläche ⇒ 2 (Tab. 4: Bewässerung nur unter C2, Beispiel §9.2 "C2 due to the irrigation"); Übernahme in quality_category (M277E-14) STAGED (m277e-D-2 / m277e-C-2).', 'imported_unverified', 'Decisive for system dimensioning is the highest quality standard. — Minimum service water quality: C2 due to the irrigation of the kitchen garden.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-16' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-05-D1', 'mbo_authorisation_code = if(storage_capacity_m3 > 50, 1, 0)', ARRAY['storage_capacity_m3']::text[], 'mbo_authorisation_code', NULL, '§4.2', 'Plan 3: 0 = Speichervolumen bis 50 m³ (Anzeige genügt, "mere notification"), 1 = über 50 m³ (Genehmigung); 50 gedruckt L329; storage_capacity_m3 kommt von M277E-01; die Ableitung der manuellen Booleans MBO_notification_only / MBO_authorisation_required STAGED (m277e-D-3).', 'imported_unverified', 'According to the Building Law, the installation of a rainwater or greywater reuse system with a storage capacity up to $50 \mathrm{~m}^{3}$ usually requires a mere notification (Model Building Code: MBO 2002 § 61 Para. 5c).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-05' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-19-D1', 'treatment_method_allowed = if(quality_category == ''C1'', lookup(''TABLE4_PROCESSES'', treatment_method, ''c1_allowed''), lookup(''TABLE4_PROCESSES'', treatment_method, ''c2_allowed''))', ARRAY['quality_category','treatment_method']::text[], 'treatment_method_allowed', NULL, '§6.3, Tab. 4', 'Plan 3: 1 wenn das gewählte Verfahren in der Tab.-4-Liste der Kategorie steht (C1: FB, SF, FLB, Stabilisation; C2: FB, SF, FLB, MBR + UV, UF, RO), sonst 0; die Liste ist "not exhaustive" (L480) — Gate == 1 STAGED (m277e-G-2).', 'imported_unverified', '\hline \multirow{2}{*}{} & & \multirow[b]{2}{*}{FB, SF, FLB, Stabilisation} & FB, SF, FLB, MBR \\
\hline & Exemplary processes and other treatment stages & & + UV, UF, RO \\'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-19' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-21-D1', 'storage_capacity_calc_m3 = sum_rows(speicher_277, volume_l) / 1000', ARRAY['speicher_277']::text[], 'storage_capacity_calc_m3', 'm³', '§4.2; §7.1', 'Plan 3: Σ Speichervolumen über die Speicher-Zeilen (1000 = l → m³); Übernahme als storage_capacity_m3 (M277E-01, MBO-Schwelle 50 m³) STAGED (m277e-R-5).', 'imported_unverified', 'It is recommended that the total buffer volume corresponds to one-day treatment capacity. — According to the Building Law, the installation of a rainwater or greywater reuse system with a storage capacity up to $50 \mathrm{~m}^{3}$ usually requires a mere notification (Model Building Code: MBO 2002 § 61 Para. 5c).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-21' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-24-D1', 'treated_samples_fail = count_rows(ablaufproben_treated, turbidity_ok == 0 OR bod5_ok == 0 OR o2_ok == 0 OR ph_ok == 0 OR total_coliforms_ok == 0 OR e_coli_ok == 0 OR p_aeruginosa_ok == 0)', ARRAY['ablaufproben_treated']::text[], 'treated_samples_fail', NULL, '§6.3, Tab. 4', 'Plan 3: Anzahl vollständiger Ablaufproben mit mindestens einer verletzten Tab.-4-Anforderung der Kategorie (Vergleich je Zeile mit turbidity_limit … p_aeruginosa_limit; unter C1 gelten nur O2 und pH); Gate == 0 STAGED (m277e-G-6).', 'imported_unverified', '\hline \multirow{4}{*}{Biochemical/chemicalphysical parameters} & Turbidity & - & < 2 NTU \\
\hline & $\mathrm{BOD}_{5}$ & - & $<5 \mathrm{mg} / \mathrm{l}$ \\
\hline & O2 Saturation & > 50 \% & > 50 \% \\
\hline & pH & 6.5-9.5 & 6.5-9.5 \\
\hline \multirow{4}{*}{Hygienic parameters} & Total coliforms & \multirow[t]{3}{*}{No requirement} & $<10,000 / 100 \mathrm{ml}$ \\
\hline & E. coli & & $<1,000 / 100 \mathrm{ml}$ \\
\hline & P. aeroginosa & & $<100 / 100 \mathrm{ml}$ \\
\hline & sampling & - & Reservoir/Consumer \\'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-24' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-24-D2', 'treated_samples_count = count_rows(ablaufproben_treated)', ARRAY['ablaufproben_treated']::text[], 'treated_samples_count', NULL, '§6.3, Tab. 4', 'Plan 3: Anzahl vollständiger Ablaufproben (Bezugsgröße für treated_samples_fail).', 'imported_unverified', '\hline \multirow{4}{*}{Biochemical/chemicalphysical parameters} & Turbidity & - & < 2 NTU \\
\hline & $\mathrm{BOD}_{5}$ & - & $<5 \mathrm{mg} / \mathrm{l}$ \\
\hline & O2 Saturation & > 50 \% & > 50 \% \\
\hline & pH & 6.5-9.5 & 6.5-9.5 \\
\hline \multirow{4}{*}{Hygienic parameters} & Total coliforms & \multirow[t]{3}{*}{No requirement} & $<10,000 / 100 \mathrm{ml}$ \\
\hline & E. coli & & $<1,000 / 100 \mathrm{ml}$ \\
\hline & P. aeroginosa & & $<100 / 100 \mathrm{ml}$ \\
\hline & sampling & - & Reservoir/Consumer \\'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-24' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-18-D1', 'V_GW_annual = sum_rows(bilanzperioden, q_gw * days) / 1000', ARRAY['bilanzperioden']::text[], 'V_GW_annual', 'm³/a', '§9.4', 'Plan 3: Jahres-Grauwasseranfall = Σ Q_GW · Tage über die Bilanzperioden (1000 = l → m³); Text-Ableitung ohne gedruckte Formel (m277e-F-2); übernimmt ein bislang manuelles Feld.', 'imported_unverified', 'The daily treatment capacity should be complemented with data on the weekly/monthly capacity of the greywater treatment system.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-18' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-18-D2', 'V_SW_annual = sum_rows(bilanzperioden, q_sw * days) / 1000', ARRAY['bilanzperioden']::text[], 'V_SW_annual', 'm³/a', '§9.4', 'Plan 3: Jahres-Brauchwasserbedarf = Σ Q_SW · Tage über die Bilanzperioden (1000 = l → m³); Text-Ableitung (m277e-F-2).', 'imported_unverified', 'The daily treatment capacity should be complemented with data on the weekly/monthly capacity of the greywater treatment system.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-18' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-18-D3', 'V_treated_annual = sum_rows(bilanzperioden, min(q_gw, q_sw) * days) / 1000', ARRAY['bilanzperioden']::text[], 'V_treated_annual', 'm³/a', '§9.4, Eq. (3) / Eq. (4)', 'Plan 3: Jahres-Behandlungsvolumen = Σ min(Q_GW, Q_SW) · Tage ("the smaller value in each case", Eq. 3/4 je Periode); Text-Ableitung (m277e-F-2).', 'imported_unverified', 'Decisive for the hydraulic dimensioning is the smaller value in each case.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-18' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-18-D4', 'V_surplus_annual = sum_rows(bilanzperioden, if(q_wb > 0, q_wb * days, 0)) / 1000', ARRAY['bilanzperioden']::text[], 'V_surplus_annual', 'm³/a', '§9.4', 'Plan 3: Jahres-Überschuss = Σ Q_WB · Tage der Perioden mit Q_WB > 0 (Überlauf / Versickerung, L747); Text-Ableitung (m277e-F-2).', 'imported_unverified', 'Q_{W B}=Q_{G W}-Q_{S W}=0(l / d) — As a rule, a positive water balance can be determined ( $Q_{W B}>0$ ), which means that the amount of available daily greywater inflow is higher than the demand for service water.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-18' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M277E-18-D5', 'V_topup_annual = sum_rows(bilanzperioden, if(q_wb < 0, -(q_wb * days), 0)) / 1000', ARRAY['bilanzperioden']::text[], 'V_topup_annual', 'm³/a', '§9.4', 'Plan 3: Jahres-Nachspeisung = Σ |Q_WB| · Tage der Perioden mit Q_WB < 0 ("higher drinking water backfeed", L751); Text-Ableitung (m277e-F-2).', 'imported_unverified', 'Q_{W B}=Q_{G W}-Q_{S W}=0(l / d) — If a negative balance is calculated ( $Q_{W B}<0$ ), this means that the available amount of daily greywater inflow is lower than the demand for service water. Therefore, it should be tested whether less service water consumers can be connected to the service water network than was originally planned. If, for economic reasons, this option is not viable, a lower level of drinking water substitution must then be expected (higher drinking water backfeed).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M277E-18' AND s.code = 'DWA-M-277E'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
