-- Generated by scripts/regulation-tables/emit-equations-sql.ts for din1989_1 (Plan 3). New rows only; existing equations are never updated here (rulings live in scripts/verification/din1989_1-STAGED-plan3-rulings.sql). Regenerate, do not hand-edit.
BEGIN;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-1989-1-04-D1', 'sum_a_e = sum_rows(auffangflaechen, a_a * e)', ARRAY['auffangflaechen']::text[], 'sum_a_e', 'm²', '§16.3.6, Gl. 1', 'Plan 3: Σ(A_A · e) über die Auffangflächen-Zeilen (Gl.-1-Term A_A × e je Fläche); Umstellung von Gl. 1 STAGED (din1989_1-R-1).', 'imported_unverified', 'E_{\mathrm{R}}=A_{\mathrm{A}} \times e \times h_{\mathrm{N}} \times \eta \tag{1}'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-1989-1-04' AND s.code = 'DIN-1989-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-1989-1-04-D2', 'bw_person = sum_rows(verbraucher, p_d_eff * n * 365)', ARRAY['verbraucher']::text[], 'bw_person', 'l/a', '§16.3.7, Gl. 2', 'Plan 3: Σ(P_d · n · 365) über die Verbraucher-Zeilen (P_d wirksam = Tab. 4 + 10 l bei Waschmaschine).', 'imported_unverified', '$B W_{\mathrm{a}}=P_{\mathrm{d}} \times n \times 365$'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-1989-1-04' AND s.code = 'DIN-1989-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-1989-1-04-D3', 'bw_flaeche = sum_rows(bewaesserungsflaechen, a_bew * bs_a)', ARRAY['bewaesserungsflaechen']::text[], 'bw_flaeche', 'l/a', '§16.3.7, Gl. 3', 'Plan 3: Σ(A_Bew · BS_a) über die Bewässerungsflächen-Zeilen.', 'imported_unverified', '$B W_{\mathrm{a}}=A_{\text {Bew. }} \times B S_{\mathrm{a}}$'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-1989-1-04' AND s.code = 'DIN-1989-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-1989-1-04-D4', 'bw_a_total = bw_person + bw_flaeche', ARRAY['bw_person','bw_flaeche']::text[], 'bw_a_total', 'l/a', '§16.3.7', 'Plan 3: Betriebswasserjahresbedarf = personenbezogener + flächenbezogener Anteil ("setzt sich zusammen aus … und aus"); Ablösung der beiden BW_a-Zeilen STAGED (din1989_1-R-2).', 'imported_unverified', 'Der Betriebswasserbedarf im Haushalt setzt sich zusammen aus personenbezogenen Angaben (z. B. Toilette) nach'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-1989-1-04' AND s.code = 'DIN-1989-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-1989-1-04-D5', 'tagesbedarf = bw_a_total / 365', ARRAY['bw_a_total']::text[], 'tagesbedarf', 'l/d', '§11, §16.3.7', 'Plan 3: Tagesbedarf an Betriebswasser (Jahresbedarf / 365, der in Gl. 2 gedruckte Jahresfaktor); Grenze für das Hybridbehälter-Volumen (Gate STAGED din1989_1-G-2).', 'imported_unverified', 'Ihr Volumen sollte nicht größer als der halbe Tagesbedarf an Betriebswasser sein.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-1989-1-04' AND s.code = 'DIN-1989-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-1989-1-02-D1', 'nennvolumen = mindestwasservolumen + V_n', ARRAY['mindestwasservolumen','V_n']::text[], 'nennvolumen', 'l', '§16.1', 'Plan 3: Nennvolumen = Mindestwasservolumen + Nutzvolumen (beide von DIN-1989-1-04 übernommen).', 'imported_unverified', 'Das vom Hersteller angegebene Nennvolumen besteht aus dem Mindestwasservolumen und dem Nutzvolumen, das Gegenstand der folgenden Bemessungsverfahren ist.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-1989-1-02' AND s.code = 'DIN-1989-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-1989-1-02-D2', 'speicher_einzelvolumen_sum = sum_rows(speicher_behaelter, einzelvolumen_l)', ARRAY['speicher_behaelter']::text[], 'speicher_einzelvolumen_sum', 'l', '§6.3, §7', 'Plan 3: Σ Einzelvolumen über die Behälter-Zeilen (mehrere Behälter in Reihe).', 'imported_unverified', 'Bei Verwendung mehrerer Behälter zur Speicherung, sind diese unter Berücksichtigung der vorgenannten Faktoren in Reihe zu schalten. Der Zu- und Überlauf ist im ersten Behälter anzuordnen. Die Wasserentnahme sollte im letzten Behälter installiert werden.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-1989-1-02' AND s.code = 'DIN-1989-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-1989-1-02-D3', 'speicheroeffnung_min_erf = max_rows(speicher_behaelter, oeffnung_min_mm)', ARRAY['speicher_behaelter']::text[], 'speicheroeffnung_min_erf', 'mm', '§7, Tab. 2', 'Plan 3: maßgebende Mindestöffnung = größte Tab.-2-Mindestöffnung über alle Behälter-Zeilen (jeder Behälter muss seine Zeile einhalten); Gate speicheroeffnung_dn ≥ speicheroeffnung_min_erf STAGED (din1989_1-G-3).', 'imported_unverified', 'Zur Durchführung von Inspektion und Wartung dürfen die Öffnungen der Speicher die folgenden Durchmesser nicht unterschreiten (siehe auch E DIN 1989-3):'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-1989-1-02' AND s.code = 'DIN-1989-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-1989-1-06-D1', 'wartungsplan_rows = count_rows(wartungsplan)', ARRAY['wartungsplan']::text[], 'wartungsplan_rows', NULL, '§18, Tab. 5', 'Plan 3: Anzahl der im Wartungsplan erfassten Anlagenteile (Tab. 5 druckt 17 — Vollständigkeit ist eine Sichtprüfung, kein Gate).', 'imported_unverified', 'Inspektions- und Wartungsarbeiten an Regenwassernutzungsanlagen müssen durch den Betreiber oder einen Fachkundigen in Zeitintervallen nach Tabelle 5 durchgeführt werden und für die in Tabelle 5 aufgeführten Anlagenteile in folgendem Umfang inspiziert bzw. gewartet werden.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-1989-1-06' AND s.code = 'DIN-1989-1'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
