-- Generated by scripts/regulation-tables/emit-equations-sql.ts for iso59020 (Plan 3). New rows only; existing equations are never updated here (rulings live in scripts/verification/iso59020-STAGED-plan3-rulings.sql). Regenerate, do not hand-edit.
BEGIN;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-04-D1', 'indicators_count = count_rows(indicators)', ARRAY['indicators']::text[], 'indicators_count', NULL, '§7.3.1, Table 3', 'Plan 3: Anzahl der erfassten Indikatorzeilen (Tabelle 3 druckt 13 Kernindikatoren).', 'imported_unverified', '             Table 3 lists the name and a brief description of each core circularity indicator along with a reference to
             the subclause in Annex A that provides additional specifications or recommendations for measurement
             and calculation formulae. These core circularity indicators are in active use as part of circularity indicator
             systems and are recognized as providing an effective and practical measure of circularity performance.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-04' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-04-D2', 'mandatory_missing = count_rows(indicators, ok == 0)', ARRAY['indicators']::text[], 'mandatory_missing', NULL, '§7.3.1', 'Plan 3: verbindliche Indikatoren (Tabelle 3 „Mandatory“), die weder ausgewählt noch als nicht anwendbar erklärt sind („shall be quantified and fully balanced with the use of the mandatory indicators“); Gate CR-009 → iso59020-G-4.', 'imported_unverified', '             The resource inflows and resource outflows of the system in focus shall be quantified and fully balanced
             with the use of the mandatory indicators in Clauses A.2 and A.3, taking changes in stocks into account. If a
             core circularity indicator is not applicable, the organization should explain why and can count the indicator
             value as zero.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-04' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-04-D3', 'na_unjustified = count_rows(indicators, na_justified == 0)', ARRAY['indicators']::text[], 'na_unjustified', NULL, '§7.3.1, A.1', 'Plan 3: als nicht anwendbar erklärte Zeilen ohne Begründung („the organization should explain why“ / „explaining why it is not applicable“); CR-010 → iso59020-G-2.', 'imported_unverified', '             A list and description of core circularity indicators that shall be considered for circularity measurement
             and assessment are provided in this annex. Not all of the core resource inflow circularity indicators are
             necessarily applicable at each system level or every type of system. In cases where an indicator is not
             applicable, it can be counted as zero or declared as “not applicable (N/A)”, explaining why it is not applicable.
             If the relevant data are not available, they should be counted as zero.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-04' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-04-D4', 'mandatory_core_covered = count_rows(indicators, mandatory_flag == 1 AND ok == 1)', ARRAY['indicators']::text[], 'mandatory_core_covered', NULL, '§7.3.1, Table 3', 'Plan 3: erfasste verbindliche Indikatoren (ausgewählt oder begründet nicht anwendbar) — soll die sechs „Mandatory“-Zeilen von Tabelle 3 erreichen (A.2.2, A.2.3, A.2.4, A.3.3, A.3.4, A.3.5).', 'imported_unverified', '                                                                Table 3 — Core circularity indicators
                 Indicator                   Mandatory/       Circularity indicator               Summary description                 Additional
                 category                     optional                                          (see Annex A for technical           information
                                                                                                      specifications)
                                         Mandatory         A.2.2 Average reused             Fraction of input material resources Retaining
                                                           content of an inflow (X)         that are reused components and       resource
                                                                                            products                             value
                                         Mandatory         A.2.3 Average recycled           Fraction of input material resources Add
              Resource
                                                           content of an inflow (X)         that is recycled material            resource
              Inflows
                                                                                                                                 value
                                         Mandatory         A.2.4 Average renewable          Fraction of material resources         Add
                                                           content of an inflow (X)         inflow (X) that is sustainably pro-    resource
                                                                                            duced renewable material               value
                                         Optional          A.3.2 Average lifetime of    Indicator of time that an output     Retaining
                                                           product or material relative resource (e.g. product) will remain resource
                                                           to industry average          in use compared to an industry aver- value
                                                                                        age for the resource
                                         Mandatory         A.3.3 Per cent actual reused Fraction of outflow that is reused         Retaining
                                                           products and components                                                 resource
                                                           derived from outflow (X)                                                value
              Resource
              outflows                   Mandatory         A.3.4 Per cent actual            Fraction of outflow that becomes       Recovering
                                                           recycled material                recycled material                      resource
                                                           derived from outflow (X)                                                value
                                         Mandatory         A.3.5 Per cent actual            Fraction of outflow content that is    Recovers re-
                                                           recirculation of                 recirculated at end of life for safe   source
                                                           outflow in the                   return to the biosphere and meets      value
                                                           biological cycle                 the qualifying conditions for recir-
                                                                                            culation
                                         Optional          A.4.2 Average per cent of        Fraction of net consumed energy        Recovering
                                                           energy consumed that is          that qualifies as renewable energy,    resource
              Energy
                                                           renewable energy                 taking into account both energy        value
                                                                                            inflows and energy outflows




                                                                                       ﻿
                                                                       © ISO 2024 – All rights reserved
Copyright International Organization for Standardization
                                                                                       17
                                                                             ISO 59020:2024(en)

                                                                               Table 3 (continued)
                 Indicator                   Mandatory/            Circularity indicator              Summary description                 Additional
                 category                     optional                                              (see Annex A for technical           information
                                                                                                          specifications)
                                         Optional            A.5.2 Per cent water               Per cent of annual water demand       Maintains a
                                                             withdrawal from                    that is derived from circular sources circular flow of
                                                             inflow circular sources                                                  resources
                                         Optional            A.5.3 Per cent water               Per cent (by volume) of total water Maintains a
                                                             discharged in                      withdrawn that is discharged in ac- circular flow of
              Water
                                                             accordance with                    cordance with circularity principles resources
                                                             quality requirements
                                         Optional            A.5.4 Ratio (on-site or            Reuse cycles of on-site water         Maintains a
                                                             internal) water reuse or                                                 circular flow of
                                                             recirculation                                                            resources
                                         Optional            A.6.2 Material productivity Ratio of revenue generated by total          Indicates
                                                                                         mass of all linear resource inflows          resource
                                                                                                                                      reduction
              Economic
                                         Optional            A.6.3 Resource intensity           Quantitative measure of economic      Indicates
                                                             index                              growth versus total resource use      resource
                                                                                                                                      reduction'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-04' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-04-D5', 'mandatory_core_indicators_included_code = if(count_rows(indicators, indicator == ''A.2.2_reused_content_inflow'' AND ok == 1) == 1 AND count_rows(indicators, indicator == ''A.2.3_recycled_content_inflow'' AND ok == 1) == 1 AND count_rows(indicators, indicator == ''A.2.4_renewable_content_inflow'' AND ok == 1) == 1 AND count_rows(indicators, indicator == ''A.3.3_reused_from_outflow'' AND ok == 1) == 1 AND count_rows(indicators, indicator == ''A.3.4_recycled_from_outflow'' AND ok == 1) == 1 AND count_rows(indicators, indicator == ''A.3.5_biological_recirculation'' AND ok == 1) == 1, 1, 0)', ARRAY['indicators']::text[], 'mandatory_core_indicators_included_code', NULL, '§7.3.1, Table 3', 'Plan 3: 1, wenn jeder der sechs verbindlichen Indikatoren von Tabelle 3 (A.2.2, A.2.3, A.2.4, A.3.3, A.3.4, A.3.5 — L1085–L1111) GENAU EINMAL als ausgewählt oder begründet nicht anwendbar erfasst ist (eine fehlende oder doppelte Zeile ⇒ 0; iso59020-J-2); Zwilling des Eingabefelds mandatory_core_indicators_included (iso59020-D-4 / G-4).', 'imported_unverified', '             The resource inflows and resource outflows of the system in focus shall be quantified and fully balanced
             with the use of the mandatory indicators in Clauses A.2 and A.3, taking changes in stocks into account. If a
             core circularity indicator is not applicable, the organization should explain why and can count the indicator
             value as zero.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-04' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-04-D6', 'inflow_indicators_selected = count_rows(indicators, category_code == ''resource_inflow'' AND selected == true)', ARRAY['indicators']::text[], 'inflow_indicators_selected', NULL, 'Table 3, A.2', 'Plan 3: ausgewählte Zeilen der Kategorie „Resource Inflows“ (A.2.2 – A.2.4).', 'imported_unverified', '                                         Mandatory         A.2.2 Average reused             Fraction of input material resources Retaining
                                                           content of an inflow (X)         that are reused components and       resource
                                                                                            products                             value'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-04' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-04-D7', 'outflow_indicators_selected = count_rows(indicators, category_code == ''resource_outflow'' AND selected == true)', ARRAY['indicators']::text[], 'outflow_indicators_selected', NULL, 'Table 3, A.3', 'Plan 3: ausgewählte Zeilen der Kategorie „Resource outflows“ (A.3.2 – A.3.5).', 'imported_unverified', '                                         Mandatory         A.3.3 Per cent actual reused Fraction of outflow that is reused         Retaining
                                                           products and components                                                 resource
                                                           derived from outflow (X)                                                value
              Resource'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-04' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-04-D8', 'energy_indicator_selected = count_rows(indicators, category_code == ''energy'' AND selected == true)', ARRAY['indicators']::text[], 'energy_indicator_selected', NULL, 'Table 3, A.4', 'Plan 3: ausgewählte Zeilen der Kategorie „Energy“ (A.4.2) — Treiber für CR-020 / den Energieblock von -07 nach iso59020-C-1 / G-1 / M-1.', 'imported_unverified', '                                         Optional          A.4.2 Average per cent of        Fraction of net consumed energy        Recovering
                                                           energy consumed that is          that qualifies as renewable energy,    resource
              Energy
                                                           renewable energy                 taking into account both energy        value
                                                                                            inflows and energy outflows'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-04' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-04-D9', 'water_indicators_selected = count_rows(indicators, category_code == ''water'' AND selected == true)', ARRAY['indicators']::text[], 'water_indicators_selected', NULL, 'Table 3, A.5', 'Plan 3: ausgewählte Zeilen der Kategorie „Water“ (A.5.2 – A.5.4) — Treiber für CR-021 … CR-023 nach iso59020-C-1 / G-1 / M-1.', 'imported_unverified', '                                         Optional            A.5.2 Per cent water               Per cent of annual water demand       Maintains a
                                                             withdrawal from                    that is derived from circular sources circular flow of
                                                             inflow circular sources                                                  resources
                                         Optional            A.5.3 Per cent water               Per cent (by volume) of total water Maintains a
                                                             discharged in                      withdrawn that is discharged in ac- circular flow of
              Water
                                                             accordance with                    cordance with circularity principles resources
                                                             quality requirements
                                         Optional            A.5.4 Ratio (on-site or            Reuse cycles of on-site water         Maintains a
                                                             internal) water reuse or                                                 circular flow of
                                                             recirculation                                                            resources'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-04' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-04-D10', 'economic_indicators_selected = count_rows(indicators, category_code == ''economic'' AND selected == true)', ARRAY['indicators']::text[], 'economic_indicators_selected', NULL, 'Table 3, A.6', 'Plan 3: ausgewählte Zeilen der Kategorie „Economic“ (A.6.2 – A.6.3) — Treiber für CR-024 / CR-025 nach iso59020-C-1 / G-1 / M-1.', 'imported_unverified', '                                         Optional            A.6.2 Material productivity Ratio of revenue generated by total          Indicates
                                                                                         mass of all linear resource inflows          resource
                                                                                                                                      reduction
              Economic
                                         Optional            A.6.3 Resource intensity           Quantitative measure of economic      Indicates
                                                             index                              growth versus total resource use      resource
                                                                                                                                      reduction'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-04' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-04-D11', 'additional_indicators_count = count_rows(additional_indicators)', ARRAY['additional_indicators']::text[], 'additional_indicators_count', NULL, '§7.3.2, Annex B', 'Plan 3: Anzahl der zusätzlichen Indikatoren („supplemented by the additional indicators or recommendations addressed in Annex B“).', 'imported_unverified', '             The core circularity indicators can be supplemented by the additional indicators or recommendations
             addressed in Annex B. However, other indicators can still be needed such as the following:'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-04' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-05-D1', 'inflows_count = count_rows(inflows)', ARRAY['inflows']::text[], 'inflows_count', NULL, 'A.2.1', 'Plan 3: Anzahl der erfassten Zuflüsse X („the “X” in inflow (X) represents a specific resource inflow“).', 'imported_unverified', '             Different types of inflow resources or those that have different circularity characteristics (e.g. have different
             amounts of recycled content) should be measured and recorded separately. In Figure A.1, the “X” in inflow
             (X) represents a specific resource inflow.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-05' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-05-D2', 'm_ti_total = sum_rows(inflows, m_ti)', ARRAY['inflows']::text[], 'm_ti_total', 'kg', 'A.2.1, A.1', 'Plan 3: Σ mTI(X) über alle Zuflüsse („absolute values with units should also be documented“).', 'imported_unverified', '             Many of the indicators provide percentage values (e.g. “average per cent reused content of an inflow”).
             However, in calculating these percentages, absolute values with units should also be documented. This
             allows the scale to be properly assessed and data to be aggregated.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-05' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-05-D3', 'm_reui_total = sum_rows(inflows, m_reui)', ARRAY['inflows']::text[], 'm_reui_total', 'kg', 'A.2.2', 'Plan 3: Σ mREUI(X) („the mass of reused components and products of an inflow (X)“).', 'imported_unverified', '             The calculation of the circularity indicator is performed by applying Formula (A.1):

                                    mREUI( X )              
                      %REUI( X ) =                           ⋅100                                                                     (A.1)
                                    mTI X                   
                                        ( )                 
             where

                       %REUI( X )                     is the average reused content of an inflow (X), in %;

                       mREUI( X )                     is the mass of reused components and products of an inflow (X), in kg or other mass unit;

                       mTI( X )                       is the mass of total input material of an inflow (X), in kg or other mass unit.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-05' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-05-D4', 'm_reci_total = sum_rows(inflows, m_reci)', ARRAY['inflows']::text[], 'm_reci_total', 'kg', 'A.2.3', 'Plan 3: Σ mRECI(X) („the mass of recycled material of an inflow (X)“).', 'imported_unverified', '             The calculation of the circularity indicator is performed by applying Formula (A.2):

                                    mRECI( X )              
                      %RECI( X ) =                           ⋅100                                                                     (A.2)
                                    mTI X                   
                                        ( )                 
             where

                       %RECI( X ) is the average recycled content of an inflow (X), in %;

                       mRECI( X ) is the mass of recycled material of an inflow (X), in kg or other mass unit;

                       mTI( X )              is the mass of total input material of an inflow (X), in kg or other mass unit.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-05' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-05-D5', 'm_reni_total = sum_rows(inflows, m_reni)', ARRAY['inflows']::text[], 'm_reni_total', 'kg', 'A.2.4', 'Plan 3: Σ mRENI(X) („the mass of renewable material of an inflow (X)“).', 'imported_unverified', '             The calculation of the circularity indicator is performed by applying Formula (A.3):

                                    mRENI( X )            
                      PRENI( X ) =                         ⋅100                                                               (A.3)
                                    mTI X                 
                                        ( )               
             where

                       PRENI( X )            is the average renewable content of an inflow (X), in %;

                       mRENI( X ) is the mass of renewable material of an inflow (X), in kg or other mass unit;

                       mTI( X )              is the mass of total input material of an inflow (X), in kg or other mass unitg.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-05' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-05-D6', 'm_linear_total = sum_rows(inflows, m_linear)', ARRAY['inflows']::text[], 'm_linear_total', 'kg', 'A.2.1', 'Plan 3: Σ des linearen (nicht-zirkulären) Zuflusses je Zeile (mTI − mREUI − mRECI − mRENI).', 'imported_unverified', '             These four types of content are intended to be mutually exclusive and add up to represent 100 % of the
             resource inflow (see Figure A.1). The first three types (recycled, reused and virgin, renewable content) are
             considered as circular; whereas the fourth type (virgin, non-renewable content) is the remaining portion
             that is from a non-circular source. The non-circular (linear) inflow can be calculated by subtracting the
             circular inflows from 100 %. For a material to be described as a “renewable material”, it shall adhere to the'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-05' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-05-D7', 'inflows_unbalanced = count_rows(inflows, balanced == 0)', ARRAY['inflows']::text[], 'inflows_unbalanced', NULL, 'A.2.1', 'Plan 3: Zuflüsse, deren zirkuläre Massen die Gesamtmasse übersteigen („add up to represent 100 % of the resource inflow“); CR-014 → iso59020-G-3.', 'imported_unverified', '             These four types of content are intended to be mutually exclusive and add up to represent 100 % of the
             resource inflow (see Figure A.1). The first three types (recycled, reused and virgin, renewable content) are
             considered as circular; whereas the fourth type (virgin, non-renewable content) is the remaining portion
             that is from a non-circular source. The non-circular (linear) inflow can be calculated by subtracting the
             circular inflows from 100 %. For a material to be described as a “renewable material”, it shall adhere to the'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-05' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-06-D1', 'outflows_count = count_rows(outflows)', ARRAY['outflows']::text[], 'outflows_count', NULL, 'A.3.1', 'Plan 3: Anzahl der erfassten Abflüsse X.', 'imported_unverified', '             The sum of the circular outflows and the remaining non-circular outflows represent 100 % of the resource
             outflows from the system in focus, see Figure A.2. The resource outflow circularity indicators specified in
             A.3.3, A.3.4 and A.3.5 shall be calculated and documented. In cases where the circularity indicator is not
             relevant, it can be counted at value zero. The circularity indicators for each outflow can be calculated and
             reported individually or they can be aggregated, based on goal and scope.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-06' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-06-D2', 'm_to_total = sum_rows(outflows, m_to)', ARRAY['outflows']::text[], 'm_to_total', 'kg', 'A.3.1, A.1', 'Plan 3: Σ mTO(X) über alle Abflüsse.', 'imported_unverified', '             Many of the indicators provide percentage values (e.g. “average per cent reused content of an inflow”).
             However, in calculating these percentages, absolute values with units should also be documented. This
             allows the scale to be properly assessed and data to be aggregated.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-06' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-06-D3', 'm_reuo_total = sum_rows(outflows, m_reuo)', ARRAY['outflows']::text[], 'm_reuo_total', 'kg', 'A.3.3', 'Plan 3: Σ mREUO(X) („the mass of outflow (X) that is reused“).', 'imported_unverified', '             where

                       PREUO( X )               is the actual reused products and components derived from outflow (X), in %;

                       mREUO( X )               is the mass of outflow (X) that is reused, in kg or other mass unit;

                       mTO( X )                 is the total mass of outflow (X), in kg or other mass unit.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-06' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-06-D4', 'm_reco_total = sum_rows(outflows, if(traceable_recycling == true, m_reco, 0))', ARRAY['outflows']::text[], 'm_reco_total', 'kg', 'A.3.4', 'Plan 3: Σ mRECO(X) der Zeilen mit rückverfolgbaren Recyclingdaten (sonst 0 — „0 % should be recorded“).', 'imported_unverified', '             If traceable recyclability data are not available for a specific resource outflow, 0 % should be recorded.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-06' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-06-D5', 'm_reno_total = sum_rows(outflows, m_reno)', ARRAY['outflows']::text[], 'm_reno_total', 'kg', 'A.3.5', 'Plan 3: Σ mRENO(X) („the mass of outflow (X) that is renewable recirculation“).', 'imported_unverified', '             The calculation of the circularity indicator is performed by applying Formula (A.7):

                                    mRENO( X )            
                      PRENO( X ) =                         ⋅100                                                                    (A.7)
                                    mTO X                 
                                        ( )               
             where

                       PRENO( X )               is the per cent actual recirculation of outflow (X) in the biological cycle, in %;

                       mRENO( X )               is the mass of outflow (X) that is renewable recirculation, in kg or other mass unit;

                       mTO( X )                 is the total mass of outflow (X), in kg or other mass unit.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-06' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-06-D6', 'm_linear_out_total = sum_rows(outflows, m_linear)', ARRAY['outflows']::text[], 'm_linear_out_total', 'kg', 'A.3.1', 'Plan 3: Σ des linearen (nicht-zirkulären) Abflusses je Zeile („The remaining outflows are considered as linear“).', 'imported_unverified', '             The following three core circularity indicators are intended to represent outflows that are mutually
             exclusive and represent the circular outflows:
             — components and products that are reused (see A.3.3);
             — per cent recycled material derived from outflow (see A.3.4),
             — products and materials for renewable recirculation (see A.3.5).
             The remaining outflows are considered as linear and do not count towards circularity. The linear (non-
             circular) outflow can be calculated by subtracting the circular outflows from 100 %.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-06' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-06-D7', 'outflows_unbalanced = count_rows(outflows, balanced == 0)', ARRAY['outflows']::text[], 'outflows_unbalanced', NULL, 'A.3.1', 'Plan 3: Abflüsse, deren zirkuläre Massen die Gesamtmasse übersteigen („represent 100 % of the resource outflows“); CR-019 → iso59020-G-3.', 'imported_unverified', '             The sum of the circular outflows and the remaining non-circular outflows represent 100 % of the resource
             outflows from the system in focus, see Figure A.2. The resource outflow circularity indicators specified in
             A.3.3, A.3.4 and A.3.5 shall be calculated and documented. In cases where the circularity indicator is not
             relevant, it can be counted at value zero. The circularity indicators for each outflow can be calculated and
             reported individually or they can be aggregated, based on goal and scope.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-06' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-06-D8', 'outflows_untraceable = count_rows(outflows, traceable_recycling == false)', ARRAY['outflows']::text[], 'outflows_untraceable', NULL, 'A.3.4', 'Plan 3: Abflüsse ohne rückverfolgbare Recyclingdaten (PRECO(X) = 0 % nach A.3.4; ein nicht gesetztes Kästchen zählt als „keine Daten“, iso59020-J-7).', 'imported_unverified', '             If traceable recyclability data are not available for a specific resource outflow, 0 % should be recorded.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-06' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-07-D1', 'energy_flows_count = count_rows(energy_flows)', ARRAY['energy_flows']::text[], 'energy_flows_count', NULL, 'A.4.2', 'Plan 3: Anzahl der erfassten Energieflüsse X.', 'imported_unverified', '                       PECONRE( X )                 is the average energy (X) consumed that is renewable energy, in %;

                       E IRENE( X )                 is the renewable energy (X) inflow, in MJ (or in kWh);

                       EORENE( X )                  is the renewable energy (X) outflow, in MJ (or in kWh);

                       E ITE( X )                   is the total energy (X) inflow, in MJ (or in kWh);

                       EOTE( X )                    is the total energy (X) outflow, in MJ (or in kWh).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-07' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-07-D2', 'ei_rene_total = sum_rows(energy_flows, ei_rene)', ARRAY['energy_flows']::text[], 'ei_rene_total', NULL, 'A.4.2', 'Plan 3: Σ EIRENE(X) („the renewable energy (X) inflow, in MJ (or in kWh)“) — in der gemeinsamen Einheit energy_unit_common; nur sinnvoll bei energy_unit_mismatch == 0 (§A.4.2 gemeinsame Einheit, L2271–L2272 — Gate STAGED iso59020-G-6).', 'imported_unverified', '                       PECONRE( X )                 is the average energy (X) consumed that is renewable energy, in %;

                       E IRENE( X )                 is the renewable energy (X) inflow, in MJ (or in kWh);

                       EORENE( X )                  is the renewable energy (X) outflow, in MJ (or in kWh);

                       E ITE( X )                   is the total energy (X) inflow, in MJ (or in kWh);

                       EOTE( X )                    is the total energy (X) outflow, in MJ (or in kWh).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-07' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-07-D3', 'eo_rene_total = sum_rows(energy_flows, eo_rene)', ARRAY['energy_flows']::text[], 'eo_rene_total', NULL, 'A.4.2', 'Plan 3: Σ EORENE(X) („the renewable energy (X) outflow“); nur sinnvoll bei energy_unit_mismatch == 0 (§A.4.2 gemeinsame Einheit, L2271–L2272 — Gate STAGED iso59020-G-6).', 'imported_unverified', '                       PECONRE( X )                 is the average energy (X) consumed that is renewable energy, in %;

                       E IRENE( X )                 is the renewable energy (X) inflow, in MJ (or in kWh);

                       EORENE( X )                  is the renewable energy (X) outflow, in MJ (or in kWh);

                       E ITE( X )                   is the total energy (X) inflow, in MJ (or in kWh);

                       EOTE( X )                    is the total energy (X) outflow, in MJ (or in kWh).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-07' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-07-D4', 'ei_te_total = sum_rows(energy_flows, ei_te)', ARRAY['energy_flows']::text[], 'ei_te_total', NULL, 'A.4.2', 'Plan 3: Σ EITE(X) („the total energy (X) inflow“); nur sinnvoll bei energy_unit_mismatch == 0 (§A.4.2 gemeinsame Einheit, L2271–L2272 — Gate STAGED iso59020-G-6).', 'imported_unverified', '                       PECONRE( X )                 is the average energy (X) consumed that is renewable energy, in %;

                       E IRENE( X )                 is the renewable energy (X) inflow, in MJ (or in kWh);

                       EORENE( X )                  is the renewable energy (X) outflow, in MJ (or in kWh);

                       E ITE( X )                   is the total energy (X) inflow, in MJ (or in kWh);

                       EOTE( X )                    is the total energy (X) outflow, in MJ (or in kWh).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-07' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-07-D5', 'eo_te_total = sum_rows(energy_flows, eo_te)', ARRAY['energy_flows']::text[], 'eo_te_total', NULL, 'A.4.2', 'Plan 3: Σ EOTE(X) („the total energy (X) outflow“); nur sinnvoll bei energy_unit_mismatch == 0 (§A.4.2 gemeinsame Einheit, L2271–L2272 — Gate STAGED iso59020-G-6).', 'imported_unverified', '                       PECONRE( X )                 is the average energy (X) consumed that is renewable energy, in %;

                       E IRENE( X )                 is the renewable energy (X) inflow, in MJ (or in kWh);

                       EORENE( X )                  is the renewable energy (X) outflow, in MJ (or in kWh);

                       E ITE( X )                   is the total energy (X) inflow, in MJ (or in kWh);

                       EOTE( X )                    is the total energy (X) outflow, in MJ (or in kWh).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-07' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-07-D6', 'energy_unit_mismatch = count_rows(energy_flows, unit_ok == 0)', ARRAY['energy_flows']::text[], 'energy_unit_mismatch', NULL, 'A.4.2', 'Plan 3: Energieflüsse, deren Einheit nicht die gemeinsame Einheit ist oder solange keine gemeinsame Einheit gewählt ist („A common suitable measurement unit (e.g. MJ, kWh) shall be selected“); Gates STAGED (iso59020-G-5 block / G-6 warn).', 'imported_unverified', '             A common suitable measurement unit (e.g. MJ, kWh) shall be selected for the quantification of all relevant
             energies (e.g. thermal, electrical) that are involved in the measurement.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-07' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-08-D1', 'data_sources_count = count_rows(data_sources)', ARRAY['data_sources']::text[], 'data_sources_count', NULL, '§7.6.1.2', 'Plan 3: Anzahl der erfassten Elementarkomponenten / Datenquellen (Step A).', 'imported_unverified', '             To enable a systematic data acquisition, and to provide transparency to the acquired data, it is recommended
             that the system in focus is subdivided into its elementary components for which data acquisition can be
             practically executed, such as the identification of data sources for general inflows and outflows.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-08' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-08-D2', 'data_sources_untraceable = count_rows(data_sources, traceable == false)', ARRAY['data_sources']::text[], 'data_sources_untraceable', NULL, '§7.6.2', 'Plan 3: Datenquellen ohne Rückverfolgbarkeit („sufficient documentation to enable verification“).', 'imported_unverified', '             — be acquired and supplied with sufficient documentation to enable verification of how well the data
               represent the above criteria, the reliability of its data source, any known data gaps, and other information
               of significance to the interpretation of the data;
             — be supplied with justification with regards to how well the above criteria are met.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-08' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-08-D3', 'data_sources_secondary = count_rows(data_sources, origin == ''secondary'')', ARRAY['data_sources']::text[], 'data_sources_secondary', NULL, '§7.6.2', 'Plan 3: Datenquellen mit Sekundärdaten („secondary and generic data should be conservatively applied and not overstate the circularity“).', 'imported_unverified', '             — strive towards being specific data based on primary data;
             — be categorized as foreground or background, primary or secondary, specific or generic (secondary and
               generic data should be conservatively applied and not overstate the circularity);'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-08' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-08-D4', 'data_sources_generic = count_rows(data_sources, specificity == ''generic'')', ARRAY['data_sources']::text[], 'data_sources_generic', NULL, '§7.6.2', 'Plan 3: Datenquellen mit generischen Daten.', 'imported_unverified', '             — strive towards being specific data based on primary data;
             — be categorized as foreground or background, primary or secondary, specific or generic (secondary and
               generic data should be conservatively applied and not overstate the circularity);'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-08' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-08-D5', 'data_sources_background = count_rows(data_sources, scope == ''background'')', ARRAY['data_sources']::text[], 'data_sources_background', NULL, '§7.6.2', 'Plan 3: Datenquellen mit Hintergrunddaten.', 'imported_unverified', '             — strive towards being specific data based on primary data;
             — be categorized as foreground or background, primary or secondary, specific or generic (secondary and
               generic data should be conservatively applied and not overstate the circularity);'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-08' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-59020-09-D1', 'complementary_methods_count = count_rows(complementary_methods)', ARRAY['complementary_methods']::text[], 'complementary_methods_count', NULL, '§3.3.7, Annex C', 'Plan 3: Anzahl der angewandten komplementären Methoden.', 'imported_unverified', '             Complementary methods can be applied to measure and assess social, environmental and economic impacts
             and values that are caused by the actions to achieve circular goals. An organization is free to choose'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-59020-09' AND s.code = 'ISO-59020'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
