-- Generated by scripts/regulation-tables/emit-widget-configs-sql.ts from the TS fallback config (Plan 2b). Regenerate, do not hand-edit.
-- Retires: LOOKUP_BINDINGS_FALLBACK.ac_as_ratio_limit (src/lib/eval/lookup-fill.ts) once applied. Apply AFTER 20260911100000_guideline_to_tool_schema.sql.
-- GATED: do not apply before sign-off D-2b-3 is RATIFIED (docs/superpowers/specs/2026-09-11-guideline-to-tool/SIGN-OFF-plan-2b.md).
--
-- Why gated (Plan 2b Task 7): the binding's key symbols `tab6_tier` and `bbz_band` do NOT exist as fields on
-- DWA-A-138-1 today. The server materialiser (src/lib/eval/materialize-tab6-loading.ts, five call sites in
-- src/lib/actions/worksheet.ts) derives them internally (flaechengruppe -> TAB5 tier; bbz_thickness >= 0,30 m ->
-- band) and UPSERTs `ac_as_ratio_limit` as source_type='derived'. The widget therefore renders the symbol in
-- DISPLAY mode (LOADING_CHECK_SYMBOLS marks it server-owned): persisted value read-only, badge
-- "Tab. 6: — (Schlüssel fehlt: tab6_tier, bbz_band) (Grenzwert)", no client write. Applying this migration changes
-- NOTHING the engineer sees (the TS fallback serves the identical binding while widget IS NULL) — it only moves
-- the binding from code to data. The owner rules D-2b-3 between:
--   (a) two derived scalar fields + two equation rows on A138-12:
--       tab6_tier = lookup('TAB5', flaechengruppe, 'tier'); bbz_band = if(bbz_thickness >= 0.30, 'thick', 'thin')
--       — the 0,30 m is THICK_BAND_M (src/lib/eval/tab6-loading.ts); needs the §5.2.3.2 Tab. 6 quote captured
--       in-session (SR-1) before the equation rows are written; then the badge resolves and the widget could take
--       over production from the materialiser (a separate ownership cut-over, not this migration);
--   (b) a `from_expr` key on LookupBinding (zod extension, field-config.ts) so a key can be an expression instead
--       of a symbol — no new fields, but a contract change to the Plan-1 binding shape;
--   (c) leave the widget in display mode with the keys_missing badge and the server materialiser as the single
--       producer (the CURRENT state; this migration is then cosmetic and may be applied or left unapplied).
-- Rollback: scripts/rollback-20260916160000-a138-12-ac-as-ratio-limit-lookup-fill.sql (superseded by the combined
-- scripts/rollback-20260916130000-widget-configs.sql once Plan 2b Task 5 emits it).
BEGIN;
UPDATE fields f SET widget = 'lookup_fill', ui_config = NULL, lookup = '{"table_code":"TAB6","role":"limit","keys":[{"column":"tier","from_symbol":"tab6_tier"},{"column":"bbz_band","from_symbol":"bbz_band"}],"value":"max"}'::jsonb FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.symbol = 'ac_as_ratio_limit' AND s.code = 'DWA-A-138-1' AND f.worksheet_template_id = w.id AND f.widget IS NULL;
COMMIT;
