-- Generated by scripts/regulation-tables/emit-seed-sql.ts — do not hand-edit; regenerate.
BEGIN;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('ISO-5667-10', '2020', 'S4_3_2', 'Probenahmezeitpunkte über ein Jahr: Fórmula (1) Tage (365/n) vs. Fórmula (2) Wochen (52/n) nach Probenanzahl n (§4.3.2)', '§4.3.2, Fórmula (1), Fórmula (2)', NULL, ARRAY['n_band']::text[], '[{"name":"formula","type":"string"},{"name":"period_unit","type":"string"},{"name":"period_length","type":"number"},{"name":"a_min_factor","type":"string"}]'::jsonb, 'anhaltswert', 'si el período de muestreo abarca un año, los días de muestreo pueden determinarse mediante una
fórmula. Un ejemplo es: — Pueden utilizarse fórmulas similares para otros períodos, por ejemplo, un mes, tres meses, seis
meses, etc.', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'gt25', '{"n_band":"gt25"}'::jsonb, NULL, 'n > ~25: Fórmula (1) — días', 0, '{"formula":"1","period_unit":"días","period_length":365,"a_min_factor":"– 365/n"}'::jsonb, 'Fórmula (1) para un número de muestras (n), superior a unas 25 y de la Fórmula (2) para un número de
muestras inferior a unas 25.

La fórmula (1) indica el número de días durante los cuales debe realizarse el muestreo.

                                    365            365𝑥2      365𝑥3          365𝑥𝑛
                               𝐴+       ,     𝐴+         , 𝐴+       ,…., 𝐴 +
                                     𝑛               𝑛          𝑛              𝑛
Donde

n Número de muestras;
A Número aleatorio en un intervalo entre – 365/n y 0.' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S4_3_2'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'lt25', '{"n_band":"lt25"}'::jsonb, NULL, 'n < ~25: Fórmula (2) — semana', 1, '{"formula":"2","period_unit":"semana","period_length":52,"a_min_factor":"– 52/n"}'::jsonb, 'La fórmula (2) indica el número de la semana durante la cual debe realizarse el muestreo. El día de
cada semana debe determinarse de manera que las muestras se tomen todos los días de la semana.

                                       52            52𝑥2      52𝑥3          52𝑥𝑛
                                 𝐵+       ,     𝐵+        , 𝐴+      ,…., 𝐴 +
                                       𝑛              𝑛         𝑛             𝑛
Donde

n Número de muestras;
A Número aleatorio en un intervalo entre – 52/n y 0.' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S4_3_2'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('ISO-5667-10', '2020', 'S7_2_1', 'Höchstintervall zwischen Einzelproben einer diskontinuierlichen Mischprobe (§7.2.1: 2 h → 5 min, 24 h → 30 min)', '§7.2.1', NULL, ARRAY['duration']::text[], '[{"name":"duration_h","type":"number","unit":"h"},{"name":"max_interval_min","type":"number","unit":"min"}]'::jsonb, 'locked', 'continuo es el más adecuado. Para el muestreo discontinuo, seleccione los intervalos más cortos
posibles entre las muestras individuales. No deben superar los 5 minutos para la muestra mixta de 2
horas y los 30 minutos para la muestra mixta de 24 horas. — La duración del muestreo depende de los parámetros especificados en los permisos de vertido de
aguas. La información sobre la duración del muestreo (muestra aleatoria, muestra aleatoria
cualificada, muestra mixta de 2 h, muestra compuesta de 24 h) se basa en la legislación (por ejemplo,
los anexos relacionados con el origen de las aguas residuales de la Ordenanza de Aguas Residuales).', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'h2', '{"duration":"h2"}'::jsonb, NULL, 'Mischprobe 2 h: ≤ 5 min', 0, '{"duration_h":2,"max_interval_min":5}'::jsonb, 'continuo es el más adecuado. Para el muestreo discontinuo, seleccione los intervalos más cortos
posibles entre las muestras individuales. No deben superar los 5 minutos para la muestra mixta de 2
horas y los 30 minutos para la muestra mixta de 24 horas.' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S7_2_1'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'h24', '{"duration":"h24"}'::jsonb, NULL, 'Mischprobe 24 h: ≤ 30 min', 1, '{"duration_h":24,"max_interval_min":30}'::jsonb, 'continuo es el más adecuado. Para el muestreo discontinuo, seleccione los intervalos más cortos
posibles entre las muestras individuales. No deben superar los 5 minutos para la muestra mixta de 2
horas y los 30 minutos para la muestra mixta de 24 horas.' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S7_2_1'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('ISO-5667-10', '2020', 'S7_2_2_1_TUBE', 'Mindest-Ansauggeschwindigkeit nach Innendurchmesser des Ansaugschlauchs (§7.2.2.1: ≥ 9 mm → 0,5 m/s; ≥ 12 mm → 0,3 m/s, NOTA 1)', '§7.2.2.1', NULL, ARRAY['bore_band']::text[], '[{"name":"bore_min_mm","type":"number","unit":"mm"},{"name":"min_velocity_m_s","type":"number","unit":"m/s"}]'::jsonb, 'locked', '- debe tener un diámetro interno mayor o igual a 9 mm; — - Velocidad de aspiración: no debe ser inferior a 0,5 m/s para evitar la segregación de la materia en
suspensión en el', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'ge9', '{"bore_band":"ge9"}'::jsonb, NULL, 'Innendurchmesser ≥ 9 mm: v ≥ 0,5 m/s', 0, '{"bore_min_mm":9,"min_velocity_m_s":0.5}'::jsonb, '- Velocidad de aspiración: no debe ser inferior a 0,5 m/s para evitar la segregación de la materia en
suspensión en el' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S7_2_2_1_TUBE'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'ge12', '{"bore_band":"ge12"}'::jsonb, NULL, 'Innendurchmesser ≥ 12 mm: v ≥ 0,3 m/s (NOTA 1)', 1, '{"bore_min_mm":12,"min_velocity_m_s":0.3}'::jsonb, 'NOTA 1 Pueden ser posibles velocidades de aspiración inferiores si se demuestra que son
satisfactorias. Un ejemplo es cuando el diámetro interno del tubo de aspiración es de 12 mm o más,
en cuyo caso se ha demostrado que una velocidad de aspiración de 0,3 m/s es aceptable[5].' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S7_2_2_1_TUBE'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('ISO-5667-10', '2020', 'S7_2_2_1_PUMP', 'Mindest-Einheitsvolumen nach Pumpentechnologie (§7.2.2.1: Vakuumpumpe 50 ml, Inline-Kolben 25 ml)', '§7.2.2.1', NULL, ARRAY['pump']::text[], '[{"name":"min_unit_volume_ml","type":"number","unit":"ml"},{"name":"gedruckt","type":"string"}]'::jsonb, 'anhaltswert', '- Volumen de la unidad:

- debe ser adecuado para garantizar un muestreo representativo (por ejemplo, al menos 50 ml para
la bomba de vacío o 25 ml para el émbolo en línea);', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'vacuum', '{"pump":"vacuum"}'::jsonb, NULL, 'Vakuumpumpe: ≥ 50 ml', 0, '{"min_unit_volume_ml":50,"gedruckt":"bomba de vacío"}'::jsonb, '- debe ser adecuado para garantizar un muestreo representativo (por ejemplo, al menos 50 ml para
la bomba de vacío o 25 ml para el émbolo en línea);' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S7_2_2_1_PUMP'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'inline_piston', '{"pump":"inline_piston"}'::jsonb, NULL, 'Inline-Kolben: ≥ 25 ml', 1, '{"min_unit_volume_ml":25,"gedruckt":"émbolo en línea"}'::jsonb, '- debe ser adecuado para garantizar un muestreo representativo (por ejemplo, al menos 50 ml para
la bomba de vacío o 25 ml para el émbolo en línea);' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S7_2_2_1_PUMP'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('ISO-5667-10', '2020', 'S7_2_2_4', 'Anwendungsbedingung der zeitproportionalen Mischprobe CTCV (§7.2.2.4: Variationskoeffizient 20 %)', '§7.2.2.4', NULL, ARRAY['criterio']::text[], '[{"name":"cv_max_pct","type":"number","unit":"%"},{"name":"modal","type":"string"}]'::jsonb, 'anhaltswert', 'Este método puede aplicarse, por ejemplo, cuando el caudal instantáneo del efluente varía poco en
el tiempo (coeficiente de variación de la repetibilidad del 20 % por término medio y si la información
recogida demuestra que la carga contaminante no es muy variable durante el período de muestreo). — En este caso, como el caudal no es relevante para los compuestos ponderados por tiempo, se
recomienda que las muestras se recojan en una sola botella para evitar la etapa de transferencia.', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'ctcv', '{"criterio":"ctcv"}'::jsonb, NULL, 'CTCV anwendbar: Variationskoeffizient des Durchflusses ≤ 20 % im Mittel', 0, '{"cv_max_pct":20,"modal":"puede aplicarse"}'::jsonb, 'Este método puede aplicarse, por ejemplo, cuando el caudal instantáneo del efluente varía poco en
el tiempo (coeficiente de variación de la repetibilidad del 20 % por término medio y si la información
recogida demuestra que la carga contaminante no es muy variable durante el período de muestreo).' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S7_2_2_4'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('ISO-5667-10', '2020', 'S3_4', 'Qualifizierte Stichprobe (§3.4): mindestens fünf Stichproben innerhalb von höchstens zwei Stunden, Abstand mindestens zwei Minuten', '§3.4', NULL, ARRAY['definicion']::text[], '[{"name":"min_grabs","type":"number"},{"name":"max_window_h","type":"number","unit":"h"},{"name":"min_interval_min","type":"number","unit":"min"},{"name":"min_grabs_gedruckt","type":"string"},{"name":"max_window_gedruckt","type":"string"},{"name":"min_interval_gedruckt","type":"string"}]'::jsonb, 'locked', '3.4. muestra puntual cualificada
Forma especial de una muestra compuesta (3.1), formada por al menos cinco muestras puntuales,
tomadas y mezcladas en un plazo un período máximo de dos horas y con un intervalo no inferior a
dos minutos.', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'qualified_grab', '{"definicion":"qualified_grab"}'::jsonb, NULL, 'Qualifizierte Stichprobe: ≥ 5 Stichproben, ≤ 2 h, Abstand ≥ 2 min', 0, '{"min_grabs":5,"max_window_h":2,"min_interval_min":2,"min_grabs_gedruckt":"cinco","max_window_gedruckt":"dos horas","min_interval_gedruckt":"dos minutos"}'::jsonb, 'Forma especial de una muestra compuesta (3.1), formada por al menos cinco muestras puntuales,
tomadas y mezcladas en un plazo un período máximo de dos horas y con un intervalo no inferior a
dos minutos.' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S3_4'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('ISO-5667-10', '2020', 'S9_1', 'Homogenisierer nach gesammeltem Volumen (§9.1: > 5 l mechanisch/magnetisch, ≤ 5 l Labormethode)', '§9.1', NULL, ARRAY['volume_band']::text[], '[{"name":"threshold_l","type":"number","unit":"l"},{"name":"comparator","type":"string"},{"name":"homogenizer","type":"enum","values":["mechanical","laboratory_manual"]},{"name":"modal","type":"string"}]'::jsonb, 'anhaltswert', 'Para volúmenes de muestra mayores (por ejemplo, > 5 l), los homogeneizadores con recipientes de
muestra transportables y

con agitador magnético o mecánico deberían utilizarse. — Para volúmenes inferiores recogidos (≤5 l), puede aplicarse el método de laboratorio (por ejemplo,
agitación manual, mezcla con varillas, etc.).', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'gt5', '{"volume_band":"gt5"}'::jsonb, NULL, '> 5 l: mechanischer / magnetischer Homogenisierer', 0, '{"threshold_l":5,"comparator":">","homogenizer":"mechanical","modal":"deberían utilizarse"}'::jsonb, 'Para volúmenes de muestra mayores (por ejemplo, > 5 l), los homogeneizadores con recipientes de
muestra transportables y

con agitador magnético o mecánico deberían utilizarse.' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S9_1'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'le5', '{"volume_band":"le5"}'::jsonb, NULL, '≤ 5 l: Labormethode (manuell)', 1, '{"threshold_l":5,"comparator":"≤","homogenizer":"laboratory_manual","modal":"puede aplicarse"}'::jsonb, 'Para volúmenes inferiores recogidos (≤5 l), puede aplicarse el método de laboratorio (por ejemplo,
agitación manual, mezcla con varillas, etc.).' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S9_1'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('ISO-5667-10', '2020', 'S5_SITE', 'Standortspezifische Vorgaben nach §5 (Kanal: ≥ 3 × D stromab der Drossel, Tiefe 1/3 … 1/2; Kühlsystem: Vorlauf ≥ 30 s)', '§5.1, §5.4', NULL, ARRAY['site']::text[], '[{"name":"restriction_min_diameters","type":"number"},{"name":"depth_fraction_min","type":"number"},{"name":"depth_fraction_max","type":"number"},{"name":"runoff_min_s","type":"number","unit":"s"},{"name":"modal","type":"string"}]'::jsonb, 'locked', 'El punto de toma de muestras debe estar siempre situado aguas abajo de la restricción y, como
norma general, debe situarse al menos tres veces el diámetro de la tubería, o la anchura del canal,
aguas abajo de la restricción. La entrada de la sonda de muestreo debe orientarse preferentemente — En una instalación de muestreo (grifo de muestreo que permita la desinfección, preferiblemente por
flameo, y el vaciado) se dejará correr el agua durante al menos 30 s antes del muestreo. El muestreo', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'sewer_channel_manhole', '{"site":"sewer_channel_manhole"}'::jsonb, NULL, 'Alcantarillas, canales y pozos de registro (§5.1): ≥ 3 × D stromab der Drossel; Tiefe 1/3 … 1/2', 0, '{"restriction_min_diameters":3,"depth_fraction_min":0.3333333333333333,"depth_fraction_max":0.5,"runoff_min_s":null,"modal":"norma general, debe situarse al menos tres veces el diámetro — puede recomendarse un punto de muestreo entre un tercio y la mitad de la profundidad"}'::jsonb, 'El punto de toma de muestras debe estar siempre situado aguas abajo de la restricción y, como
norma general, debe situarse al menos tres veces el diámetro de la tubería, o la anchura del canal,
aguas abajo de la restricción. La entrada de la sonda de muestreo debe orientarse preferentemente
en la dirección del flujo, pero puede orientarse aguas abajo si se producen demasiadas obstrucciones.
La ubicación exacta del punto de muestreo debe evaluarse con respecto a las variaciones del nivel
del agua, los tipos y las concentraciones de los productos, etc. El punto de muestreo debe estar a una
distancia mínima del fondo y de las paredes para evitar la contaminación de la muestra por los
depósitos o las biopelículas que se desarrollan. En general, puede recomendarse un punto de
muestreo entre un tercio y la mitad de la profundidad del agua del efluente por debajo de la superficie
del agua.' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S5_SITE'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'cooling_system', '{"site":"cooling_system"}'::jsonb, NULL, 'Sistemas de refrigeración (§5.4): Vorlauf ≥ 30 s', 1, '{"restriction_min_diameters":null,"depth_fraction_min":null,"depth_fraction_max":null,"runoff_min_s":30,"modal":"se dejará correr el agua durante al menos 30 s"}'::jsonb, 'En una instalación de muestreo (grifo de muestreo que permita la desinfección, preferiblemente por
flameo, y el vaciado) se dejará correr el agua durante al menos 30 s antes del muestreo. El muestreo' FROM regulation_tables WHERE standard_code = 'ISO-5667-10' AND edition = '2020' AND table_code = 'S5_SITE'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
COMMIT;
