-- FLL-GAR-2023 · coverage wave block 5a (2026-09-30): the block-1 tables wired into the worksheets — selections whose options are
-- generated FROM regulation_table_rows at apply time (one source by construction), lookup fills for the printed limits, and the input
-- fields those limits compare against. 25 fields on FLL-GAR-12/-14/-15/-16/-17. Requires block 1 (tables) — the inserts stay empty if a table is missing.
-- Quotes read on the rendered PDF in-session (VA); printed page in source_anchor. All is_required = false. STAGED — not applied.
-- Apply: node scripts/apply-migration.mjs scripts/migrations/20260930100000_fll_gar_2023_widgets_coverage_block5a.sql
-- Rollback: scripts/migrations/rollback-20260930100000_fll_gar_2023_widgets_coverage_block5a.sql
BEGIN;
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'bb_kurzzeichen_tab19', 'Bitumen-/Polymerbitumenbahn — Kurzzeichen nach DIN SPEC 20000-202 (Tab. 19)', 'Bitumen / polymer-bitumen sheet — designation per DIN SPEC 20000-202 (Tab. 19)', 'enum', NULL, false, '§6.1.1.1, Tab. 19', 'Coverage block 5 (A-070): the fourteen printed designations as a selection (SR-1 — printed options are offered, not typed); the free-text bb_bahnentyp stays for products outside the table. Options are generated from TAB19 rows at apply time.', 'verified_against_standard', 'Unter Bezugnahme auf DIN 18535-2 sind die in Tabelle 19 genannten Bitumen- und Polymerbitumenbahnen nach DIN EN 13969 in Verbindung mit DIN SPEC 20000-202, Anwendungstyp BA zu verwenden.', 'FLL-GAR-2023 gedruckte S. 78 — §6.1.1.1, Tab. 19', 'select_one', NULL, NULL, NULL, (SELECT jsonb_agg(jsonb_build_object('value', r.row_key, 'label_de', COALESCE(r.group_label || ' — ', '') || r.label_de, 'order_index', r.order_index + 1, 'regulation_reference', 'TAB19') ORDER BY r.order_index) FROM regulation_table_rows r JOIN regulation_tables t ON t.id = r.table_id WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB19'), (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'bb_kurzzeichen_tab19') AND w.code = 'FLL-GAR-15' AND s.code = 'FLL-GAR-2023' AND EXISTS (SELECT 1 FROM regulation_tables t WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB19');
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'bb_bahnenart_tab19', 'Bahnenart (Tab. 19, aus dem Kurzzeichen)', 'Sheet type (Tab. 19, from the designation)', 'text', NULL, false, '§6.1.1.1, Tab. 19', 'Coverage block 5: Bahnenart of the chosen designation, filled from TAB19.', 'verified_against_standard', 'Unter Bezugnahme auf DIN 18535-2 sind die in Tabelle 19 genannten Bitumen- und Polymerbitumenbahnen nach DIN EN 13969 in Verbindung mit DIN SPEC 20000-202, Anwendungstyp BA zu verwenden.', 'FLL-GAR-2023 gedruckte S. 78 — §6.1.1.1, Tab. 19', 'lookup_fill', '{"source_label":"Tab. 19 (Bahnenart)"}'::jsonb, '{"keys":[{"column":"kurzzeichen","from_symbol":"bb_kurzzeichen_tab19"}],"role":"value","value":"bahnenart","table_code":"TAB19"}'::jsonb, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'bb_bahnenart_tab19') AND w.code = 'FLL-GAR-15' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'bahn_bezeichnung_tab21', 'Bahnbezeichnung nach DIN/TS 20.000-202 (Tab. 21)', 'Sheet designation per DIN/TS 20.000-202 (Tab. 21)', 'enum', NULL, false, '§6.2.1.1, Tab. 21', 'Coverage block 5 (A-085): the 47 printed designations as a selection; (X)² stands for the Verstärkung/Kaschierung after Tab. 20. Options generated from TAB21 rows at apply time.', 'verified_against_standard', 'Tab. 21: Stoffe für die Abdichtung mit Kunststoff- oder Elastomerbahnen nach DIN/TS 20.000-202, Anwendung Typ BA', 'FLL-GAR-2023 gedruckte S. 83 — §6.2.1.1, Tab. 21', 'select_one', NULL, NULL, NULL, (SELECT jsonb_agg(jsonb_build_object('value', r.row_key, 'label_de', COALESCE(r.group_label || ' — ', '') || r.label_de, 'order_index', r.order_index + 1, 'regulation_reference', 'TAB21') ORDER BY r.order_index) FROM regulation_table_rows r JOIN regulation_tables t ON t.id = r.table_id WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB21'), (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'bahn_bezeichnung_tab21') AND w.code = 'FLL-GAR-16' AND s.code = 'FLL-GAR-2023' AND EXISTS (SELECT 1 FROM regulation_tables t WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB21');
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'bahn_stoffgruppe_tab21', 'Stoffgruppe (Kunststoff- / Elastomerbahn, aus Tab. 21)', 'Material group (plastic / elastomer sheet, from Tab. 21)', 'text', NULL, false, '§6.2.1.1, Tab. 21', 'Coverage block 5: Stoffgruppe of the chosen designation, filled from TAB21.', 'verified_against_standard', 'Tab. 21: Stoffe für die Abdichtung mit Kunststoff- oder Elastomerbahnen nach DIN/TS 20.000-202, Anwendung Typ BA', 'FLL-GAR-2023 gedruckte S. 83 — §6.2.1.1, Tab. 21', 'lookup_fill', '{"source_label":"Tab. 21 (Stoffgruppe)"}'::jsonb, '{"keys":[{"column":"bezeichnung","from_symbol":"bahn_bezeichnung_tab21"}],"role":"value","value":"stoffgruppe","table_code":"TAB21"}'::jsonb, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'bahn_stoffgruppe_tab21') AND w.code = 'FLL-GAR-16' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'bahn_bahnenart_tab21', 'Bahnenart (homogen / mit Einlage / verstärkt / kaschiert …, aus Tab. 21)', 'Sheet type (homogeneous / with insert / reinforced / laminated …, from Tab. 21)', 'text', NULL, false, '§6.2.1.1, Tab. 21', 'Coverage block 5: Bahnenart of the chosen designation, filled from TAB21.', 'verified_against_standard', 'Tab. 21: Stoffe für die Abdichtung mit Kunststoff- oder Elastomerbahnen nach DIN/TS 20.000-202, Anwendung Typ BA', 'FLL-GAR-2023 gedruckte S. 83 — §6.2.1.1, Tab. 21', 'lookup_fill', '{"source_label":"Tab. 21 (Bahnenart)"}'::jsonb, '{"keys":[{"column":"bezeichnung","from_symbol":"bahn_bezeichnung_tab21"}],"role":"value","value":"bahnenart","table_code":"TAB21"}'::jsonb, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'bahn_bahnenart_tab21') AND w.code = 'FLL-GAR-16' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'fk_stoff_tab23', 'Flüssigkunststoff — Stoff nach Tab. 23', 'Liquid-applied plastic — material per Tab. 23', 'enum', NULL, false, '§6.3.1.1, Tab. 23', 'Coverage block 5 (A-096): UP / PUR / PMMA as printed; the free-text fk_systemtyp stays.', 'verified_against_standard', 'Die Mindestschichtdicke der ausgehärteten flüssigen Abdichtung muss den Angaben der Zulassung (ETA, AbP gemäß MVV TB) entsprechen. Sie beträgt gemäß Tabelle 23 mind. 2,0 mm. Wenn die in der ETA angegebene Mindestschichtdicke höher ist, gilt der höhere Wert.', 'FLL-GAR-2023 gedruckte S. 89 — §6.3.1.1, Tab. 23', 'select_one', NULL, NULL, NULL, (SELECT jsonb_agg(jsonb_build_object('value', r.row_key, 'label_de', r.label_de, 'order_index', r.order_index + 1, 'regulation_reference', 'TAB23') ORDER BY r.order_index) FROM regulation_table_rows r JOIN regulation_tables t ON t.id = r.table_id WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB23'), (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'fk_stoff_tab23') AND w.code = 'FLL-GAR-17' AND s.code = 'FLL-GAR-2023' AND EXISTS (SELECT 1 FROM regulation_tables t WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB23');
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'fk_schichtdicke_min_mm', 'Mindestschichtdicke nach Tab. 23 (≥ 2,0 mm)', 'Minimum layer thickness per Tab. 23 (≥ 2.0 mm)', 'number', 'mm', false, '§6.3.1.2, Tab. 23', 'Coverage block 5: limit for fk_trockenschichtdicke (REQ-41, 5b).', 'verified_against_standard', 'Die Mindestschichtdicke der ausgehärteten flüssigen Abdichtung muss den Angaben der Zulassung (ETA, AbP gemäß MVV TB) entsprechen. Sie beträgt gemäß Tabelle 23 mind. 2,0 mm. Wenn die in der ETA angegebene Mindestschichtdicke höher ist, gilt der höhere Wert.', 'FLL-GAR-2023 gedruckte S. 89 — §6.3.1.2, Tab. 23', 'lookup_fill', '{"source_label":"Tab. 23 (Schichtdicke)"}'::jsonb, '{"keys":[{"column":"stoff","from_symbol":"fk_stoff_tab23"}],"role":"limit","value":"schichtdicke_min_mm","table_code":"TAB23"}'::jsonb, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'fk_schichtdicke_min_mm') AND w.code = 'FLL-GAR-17' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'fk_eta_mindestschichtdicke_mm', 'Mindestschichtdicke laut Zulassung (ETA / AbP), falls höher', 'Minimum layer thickness per approval (ETA / AbP), if higher', 'number', 'mm', false, '§6.3.1.2', 'Coverage block 5: "Wenn die in der ETA angegebene Mindestschichtdicke höher ist, gilt der höhere Wert." (REQ-41, 5b).', 'verified_against_standard', 'Die Mindestschichtdicke der ausgehärteten flüssigen Abdichtung muss den Angaben der Zulassung (ETA, AbP gemäß MVV TB) entsprechen. Sie beträgt gemäß Tabelle 23 mind. 2,0 mm. Wenn die in der ETA angegebene Mindestschichtdicke höher ist, gilt der höhere Wert.', 'FLL-GAR-2023 gedruckte S. 89 — §6.3.1.2', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'fk_eta_mindestschichtdicke_mm') AND w.code = 'FLL-GAR-17' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'fk_einlage_min_g_m2', 'Mindest-Flächengewicht der Einlage nach Tab. 23 (≥ 110 g/m²)', 'Minimum mass per unit area of the insert per Tab. 23 (≥ 110 g/m²)', 'number', 'g/m²', false, '§6.3.1.1, Tab. 23; §6.3.2', 'Coverage block 5: limit for fk_einlage_g_m2 (REQ-41, 5b).', 'verified_against_standard', 'Abdichtungen mit Flüssigkunststoffen werden i. d. R. vollflächig haftend und mindestens zweischichtig (Träger-, Deckschicht) mit Einlage ausgeführt. Dies kann durch Streichen, Rollen oder Spritzen erfolgen. Es müssen Einlagen (z. B. Glasvlies, Polyestervlies) mit einem Flächengewicht von mind. 110 g/m² eingesetzt werden.', 'FLL-GAR-2023 gedruckte S. 89 — §6.3.1.1, Tab. 23; §6.3.2', 'lookup_fill', '{"source_label":"Tab. 23 (Flächengewicht der Einlage)"}'::jsonb, '{"keys":[{"column":"stoff","from_symbol":"fk_stoff_tab23"}],"role":"limit","value":"einlage_min_g_m2","table_code":"TAB23"}'::jsonb, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'fk_einlage_min_g_m2') AND w.code = 'FLL-GAR-17' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'fk_einlage_g_m2', 'Flächengewicht der eingesetzten Einlage (Glasvlies, Polyestervlies …)', 'Mass per unit area of the insert used (glass fleece, polyester fleece …)', 'number', 'g/m²', false, '§6.3.2', 'Coverage block 5 (A-099): actual value; the free-text fk_armierung stays.', 'verified_against_standard', 'Abdichtungen mit Flüssigkunststoffen werden i. d. R. vollflächig haftend und mindestens zweischichtig (Träger-, Deckschicht) mit Einlage ausgeführt. Dies kann durch Streichen, Rollen oder Spritzen erfolgen. Es müssen Einlagen (z. B. Glasvlies, Polyestervlies) mit einem Flächengewicht von mind. 110 g/m² eingesetzt werden.', 'FLL-GAR-2023 gedruckte S. 89 — §6.3.2', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'fk_einlage_g_m2') AND w.code = 'FLL-GAR-17' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'gtd_geotextil_art_tab14', 'Träger-/Deckgeotextil der GTD (Tab. 14)', 'Carrier / cover geotextile of the GCL (Tab. 14)', 'enum', NULL, false, '§5.5.1.1, Tab. 14', 'Coverage block 5 (A-058): Bändchengewebe / mechanisch verfestigter PP-Vliesstoff as printed.', 'verified_against_standard', 'Die eingesetzten Geotextilien sollen gleichzeitig widerstandsfähig gegenüber Einbaubeanspruchungen sein. Anforderungswerte an die Eigenschaften der Geotextilien werden in Tabelle 14 angegeben.', 'FLL-GAR-2023 gedruckte S. 64 — §5.5.1.1, Tab. 14', 'select_one', NULL, NULL, NULL, (SELECT jsonb_agg(jsonb_build_object('value', r.row_key, 'label_de', r.label_de, 'order_index', r.order_index + 1, 'regulation_reference', 'TAB14') ORDER BY r.order_index) FROM regulation_table_rows r JOIN regulation_tables t ON t.id = r.table_id WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB14'), (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'gtd_geotextil_art_tab14') AND w.code = 'FLL-GAR-14' AND s.code = 'FLL-GAR-2023' AND EXISTS (SELECT 1 FROM regulation_tables t WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB14');
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'gtd_geotextil_flaecheneinheit_min', 'Flächeneinheit MA des Geotextils — Mindestwert Tab. 14', 'Mass per unit area MA of the geotextile — minimum per Tab. 14', 'number', 'g/m²', false, '§5.5.1.1, Tab. 14', 'Coverage block 5: limit for gtd_geotextil_flaecheneinheit_g_m2 (REQ-42, 5b).', 'verified_against_standard', 'Die eingesetzten Geotextilien sollen gleichzeitig widerstandsfähig gegenüber Einbaubeanspruchungen sein. Anforderungswerte an die Eigenschaften der Geotextilien werden in Tabelle 14 angegeben.', 'FLL-GAR-2023 gedruckte S. 64 — §5.5.1.1, Tab. 14', 'lookup_fill', '{"source_label":"Tab. 14 (MA)"}'::jsonb, '{"keys":[{"column":"geotextil_art","from_symbol":"gtd_geotextil_art_tab14"}],"role":"limit","value":"flaecheneinheit_min_g_m2","table_code":"TAB14"}'::jsonb, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'gtd_geotextil_flaecheneinheit_min') AND w.code = 'FLL-GAR-14' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'gtd_geotextil_flaecheneinheit_g_m2', 'Flächeneinheit MA des Geotextils (Ist, DIN EN ISO 9864)', 'Mass per unit area MA of the geotextile (actual, DIN EN ISO 9864)', 'number', 'g/m²', false, '§5.5.1.1, Tab. 14', 'Coverage block 5 (A-058).', 'verified_against_standard', 'Die eingesetzten Geotextilien sollen gleichzeitig widerstandsfähig gegenüber Einbaubeanspruchungen sein. Anforderungswerte an die Eigenschaften der Geotextilien werden in Tabelle 14 angegeben.', 'FLL-GAR-2023 gedruckte S. 64 — §5.5.1.1, Tab. 14', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'gtd_geotextil_flaecheneinheit_g_m2') AND w.code = 'FLL-GAR-14' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'gtd_zugfestigkeit_kn_m', 'Zugfestigkeit der GTD (längs und quer, DIN EN ISO 10319)', 'Tensile strength of the GCL (MD and CD, DIN EN ISO 10319)', 'number', 'kN/m', false, '§5.5.1.1, Tab. 15 Zeile 8', 'Coverage block 5 (A-060): ≥ 10 kN/m (REQ-42, 5b).', 'verified_against_standard', 'Die Anforderungen in den Zeilen 2 bis 7 der Tabelle 15 können produktabhängig abweichen. Für andere Verbindungsverfahren, Bentonitarten und Oberflächenausbildungen gelten hinsichtlich Zugfestigkeit, Zugfestigkeitsdehnung, Verbundfestigkeit, Durchlässigkeitsbeiwert (kf) und Permittivität die in den Zeilen 8 bis 11 festgelegten Mindestanforderungen.', 'FLL-GAR-2023 gedruckte S. 65 — §5.5.1.1, Tab. 15 Zeile 8', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'gtd_zugfestigkeit_kn_m') AND w.code = 'FLL-GAR-14' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'gtd_zugfestigkeitsdehnung_pct', 'Zugfestigkeitsdehnung der GTD (DIN EN ISO 10319)', 'Elongation at tensile strength of the GCL (DIN EN ISO 10319)', 'number', '%', false, '§5.5.1.1, Tab. 15 Zeile 8', 'Coverage block 5 (A-060): ≤ 30 % (REQ-42, 5b).', 'verified_against_standard', 'Die Anforderungen in den Zeilen 2 bis 7 der Tabelle 15 können produktabhängig abweichen. Für andere Verbindungsverfahren, Bentonitarten und Oberflächenausbildungen gelten hinsichtlich Zugfestigkeit, Zugfestigkeitsdehnung, Verbundfestigkeit, Durchlässigkeitsbeiwert (kf) und Permittivität die in den Zeilen 8 bis 11 festgelegten Mindestanforderungen.', 'FLL-GAR-2023 gedruckte S. 65 — §5.5.1.1, Tab. 15 Zeile 8', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'gtd_zugfestigkeitsdehnung_pct') AND w.code = 'FLL-GAR-14' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'gtd_verbundfestigkeit_n_m', 'Verbundfestigkeit der GTD (ASTM D 6496)', 'Peel strength of the GCL (ASTM D 6496)', 'number', 'N/m', false, '§5.5.1.1, Tab. 15 Zeile 9', 'Coverage block 5 (A-060): ≥ 360 N/m (REQ-42, 5b).', 'verified_against_standard', 'Die Anforderungen in den Zeilen 2 bis 7 der Tabelle 15 können produktabhängig abweichen. Für andere Verbindungsverfahren, Bentonitarten und Oberflächenausbildungen gelten hinsichtlich Zugfestigkeit, Zugfestigkeitsdehnung, Verbundfestigkeit, Durchlässigkeitsbeiwert (kf) und Permittivität die in den Zeilen 8 bis 11 festgelegten Mindestanforderungen.', 'FLL-GAR-2023 gedruckte S. 65 — §5.5.1.1, Tab. 15 Zeile 9', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'gtd_verbundfestigkeit_n_m') AND w.code = 'FLL-GAR-14' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'gtd_kf_m_s', 'Durchlässigkeitsbeiwert kf der GTD (DIN EN 16416, i = 150, ca. 27,5 kPa, d = 1 cm)', 'Permeability coefficient kf of the GCL (DIN EN 16416, i = 150, approx. 27.5 kPa, d = 1 cm)', 'number', 'm/s', false, '§5.5.1.1, Tab. 15 Zeile 10', 'Coverage block 5 (A-060): ≤ 5,0 · 10⁻¹¹ m/s (REQ-42, 5b).', 'verified_against_standard', 'Die Anforderungen in den Zeilen 2 bis 7 der Tabelle 15 können produktabhängig abweichen. Für andere Verbindungsverfahren, Bentonitarten und Oberflächenausbildungen gelten hinsichtlich Zugfestigkeit, Zugfestigkeitsdehnung, Verbundfestigkeit, Durchlässigkeitsbeiwert (kf) und Permittivität die in den Zeilen 8 bis 11 festgelegten Mindestanforderungen.', 'FLL-GAR-2023 gedruckte S. 65 — §5.5.1.1, Tab. 15 Zeile 10', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'gtd_kf_m_s') AND w.code = 'FLL-GAR-14' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'gtd_permittivitaet_m_s', 'Permittivität der GTD (DIN EN 16416, i = 150, ca. 27,5 kPa)', 'Permittivity of the GCL (DIN EN 16416, i = 150, approx. 27.5 kPa)', 'number', 'm/s', false, '§5.5.1.1, Tab. 15 Zeile 11', 'Coverage block 5 (A-060): ≤ 5,0 · 10⁻⁹ m/s as printed (REQ-42, 5b).', 'verified_against_standard', 'Die Anforderungen in den Zeilen 2 bis 7 der Tabelle 15 können produktabhängig abweichen. Für andere Verbindungsverfahren, Bentonitarten und Oberflächenausbildungen gelten hinsichtlich Zugfestigkeit, Zugfestigkeitsdehnung, Verbundfestigkeit, Durchlässigkeitsbeiwert (kf) und Permittivität die in den Zeilen 8 bis 11 festgelegten Mindestanforderungen.', 'FLL-GAR-2023 gedruckte S. 65 — §5.5.1.1, Tab. 15 Zeile 11', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'gtd_permittivitaet_m_s') AND w.code = 'FLL-GAR-14' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'frischbeton_lufttemperatur_fall', 'Lufttemperatur beim Betonieren (Fall nach Tab. 9)', 'Air temperature during concreting (case per Tab. 9)', 'enum', NULL, false, '§5.3.2.1, Tab. 9', 'Coverage block 5 (A-040): the three printed cases.', 'verified_against_standard', 'Bei extrem niedrigen oder hohen Lufttemperaturen ist die Betontemperatur zu überwachen. Die Grenztemperaturen des Frischbetons nach DIN 1045-3 von mind. + 5 °C bzw. höchstens + 30 °C müssen eingehalten werden, um eine bleibende Beeinträchtigung der Frischbetoneigenschaften zu vermeiden (s. Tab. 9).', 'FLL-GAR-2023 gedruckte S. 53 — §5.3.2.1, Tab. 9', 'select_one', NULL, NULL, NULL, (SELECT jsonb_agg(jsonb_build_object('value', r.row_key, 'label_de', COALESCE(r.group_label || ' — ', '') || r.label_de, 'order_index', r.order_index + 1, 'regulation_reference', 'TAB9') ORDER BY r.order_index) FROM regulation_table_rows r JOIN regulation_tables t ON t.id = r.table_id WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB9'), (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'frischbeton_lufttemperatur_fall') AND w.code = 'FLL-GAR-12' AND s.code = 'FLL-GAR-2023' AND EXISTS (SELECT 1 FROM regulation_tables t WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB9');
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'frischbeton_temp_min_c', 'Mindesttemperatur des Frischbetons nach Tab. 9', 'Minimum fresh-concrete temperature per Tab. 9', 'number', '°C', false, '§5.3.2.1, Tab. 9', 'Coverage block 5: limit for frischbeton_temperatur_c (REQ-43, 5b); upper limit + 30 °C printed in §5.3.2.1.', 'verified_against_standard', 'Bei extrem niedrigen oder hohen Lufttemperaturen ist die Betontemperatur zu überwachen. Die Grenztemperaturen des Frischbetons nach DIN 1045-3 von mind. + 5 °C bzw. höchstens + 30 °C müssen eingehalten werden, um eine bleibende Beeinträchtigung der Frischbetoneigenschaften zu vermeiden (s. Tab. 9).', 'FLL-GAR-2023 gedruckte S. 53 — §5.3.2.1, Tab. 9', 'lookup_fill', '{"source_label":"Tab. 9 (Mindesttemperatur)"}'::jsonb, '{"keys":[{"column":"fall","from_symbol":"frischbeton_lufttemperatur_fall"}],"role":"limit","value":"frischbeton_min_c","table_code":"TAB9"}'::jsonb, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'frischbeton_temp_min_c') AND w.code = 'FLL-GAR-12' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'frischbeton_temperatur_c', 'Frischbetontemperatur (Ist)', 'Fresh-concrete temperature (actual)', 'number', '°C', false, '§5.3.2.1, Tab. 9', 'Coverage block 5 (A-040).', 'verified_against_standard', 'Bei extrem niedrigen oder hohen Lufttemperaturen ist die Betontemperatur zu überwachen. Die Grenztemperaturen des Frischbetons nach DIN 1045-3 von mind. + 5 °C bzw. höchstens + 30 °C müssen eingehalten werden, um eine bleibende Beeinträchtigung der Frischbetoneigenschaften zu vermeiden (s. Tab. 9).', 'FLL-GAR-2023 gedruckte S. 53 — §5.3.2.1, Tab. 9', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'frischbeton_temperatur_c') AND w.code = 'FLL-GAR-12' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'zementfestigkeitsklasse_tab10', 'Zementfestigkeitsklasse (Tab. 10)', 'Cement strength class (Tab. 10)', 'enum', NULL, false, '§5.3.2.1, Tab. 10', 'Coverage block 5 (A-041): the three printed rows.', 'verified_against_standard', 'Damit der Beton ein Durchfrieren unbeschadet übersteht, muss der Beton gefrierbeständig sein. Diese Gefrierbeständigkeit ist dann erreicht, wenn er mindestens eine Festigkeit von 5 N/mm² aufweist und vor Fremdwasser geschützt wird. Die dafür erforderlichen Erhärtungszeiten in Abhängigkeit von Temperatur, Wasserzementwert und Zementfestigkeitsklasse sind in Tabelle 10 angegeben.', 'FLL-GAR-2023 gedruckte S. 54 — §5.3.2.1, Tab. 10', 'select_one', NULL, NULL, NULL, (SELECT jsonb_agg(jsonb_build_object('value', r.row_key, 'label_de', r.label_de, 'order_index', r.order_index + 1, 'regulation_reference', 'TAB10') ORDER BY r.order_index) FROM regulation_table_rows r JOIN regulation_tables t ON t.id = r.table_id WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB10'), (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'zementfestigkeitsklasse_tab10') AND w.code = 'FLL-GAR-12' AND s.code = 'FLL-GAR-2023' AND EXISTS (SELECT 1 FROM regulation_tables t WHERE t.standard_code = 'FLL-GAR-2023' AND t.edition = '2023-12' AND t.table_code = 'TAB10');
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'erhaertungszeit_tage_bei_5c', 'Erforderliche Erhärtungszeit bis zur Gefrierbeständigkeit bei 5 °C Betontemperatur (Tab. 10, w/z = 0,60)', 'Required curing time to frost resistance at 5 °C concrete temperature (Tab. 10, w/c = 0.60)', 'number', 'd', false, '§5.3.2.1, Tab. 10', 'Coverage block 5: informational fill (the table is printed for w/z = 0,60; the gate is a RULING — none staged).', 'verified_against_standard', 'Damit der Beton ein Durchfrieren unbeschadet übersteht, muss der Beton gefrierbeständig sein. Diese Gefrierbeständigkeit ist dann erreicht, wenn er mindestens eine Festigkeit von 5 N/mm² aufweist und vor Fremdwasser geschützt wird. Die dafür erforderlichen Erhärtungszeiten in Abhängigkeit von Temperatur, Wasserzementwert und Zementfestigkeitsklasse sind in Tabelle 10 angegeben.', 'FLL-GAR-2023 gedruckte S. 54 — §5.3.2.1, Tab. 10', 'lookup_fill', '{"source_label":"Tab. 10 (5 °C)"}'::jsonb, '{"keys":[{"column":"zementfestigkeitsklasse","from_symbol":"zementfestigkeitsklasse_tab10"}],"role":"value","value":"tage_bei_5c","table_code":"TAB10"}'::jsonb, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'erhaertungszeit_tage_bei_5c') AND w.code = 'FLL-GAR-12' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'erhaertungszeit_tage_bei_12c', 'Erforderliche Erhärtungszeit bis zur Gefrierbeständigkeit bei 12 °C Betontemperatur (Tab. 10, w/z = 0,60)', 'Required curing time to frost resistance at 12 °C concrete temperature (Tab. 10, w/c = 0.60)', 'number', 'd', false, '§5.3.2.1, Tab. 10', 'Coverage block 5: informational fill (the table is printed for w/z = 0,60; the gate is a RULING — none staged).', 'verified_against_standard', 'Damit der Beton ein Durchfrieren unbeschadet übersteht, muss der Beton gefrierbeständig sein. Diese Gefrierbeständigkeit ist dann erreicht, wenn er mindestens eine Festigkeit von 5 N/mm² aufweist und vor Fremdwasser geschützt wird. Die dafür erforderlichen Erhärtungszeiten in Abhängigkeit von Temperatur, Wasserzementwert und Zementfestigkeitsklasse sind in Tabelle 10 angegeben.', 'FLL-GAR-2023 gedruckte S. 54 — §5.3.2.1, Tab. 10', 'lookup_fill', '{"source_label":"Tab. 10 (12 °C)"}'::jsonb, '{"keys":[{"column":"zementfestigkeitsklasse","from_symbol":"zementfestigkeitsklasse_tab10"}],"role":"value","value":"tage_bei_12c","table_code":"TAB10"}'::jsonb, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'erhaertungszeit_tage_bei_12c') AND w.code = 'FLL-GAR-12' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'erhaertungszeit_tage_bei_20c', 'Erforderliche Erhärtungszeit bis zur Gefrierbeständigkeit bei 20 °C Betontemperatur (Tab. 10, w/z = 0,60)', 'Required curing time to frost resistance at 20 °C concrete temperature (Tab. 10, w/c = 0.60)', 'number', 'd', false, '§5.3.2.1, Tab. 10', 'Coverage block 5: informational fill (the table is printed for w/z = 0,60; the gate is a RULING — none staged).', 'verified_against_standard', 'Damit der Beton ein Durchfrieren unbeschadet übersteht, muss der Beton gefrierbeständig sein. Diese Gefrierbeständigkeit ist dann erreicht, wenn er mindestens eine Festigkeit von 5 N/mm² aufweist und vor Fremdwasser geschützt wird. Die dafür erforderlichen Erhärtungszeiten in Abhängigkeit von Temperatur, Wasserzementwert und Zementfestigkeitsklasse sind in Tabelle 10 angegeben.', 'FLL-GAR-2023 gedruckte S. 54 — §5.3.2.1, Tab. 10', 'lookup_fill', '{"source_label":"Tab. 10 (20 °C)"}'::jsonb, '{"keys":[{"column":"zementfestigkeitsklasse","from_symbol":"zementfestigkeitsklasse_tab10"}],"role":"value","value":"tage_bei_20c","table_code":"TAB10"}'::jsonb, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'erhaertungszeit_tage_bei_20c') AND w.code = 'FLL-GAR-12' AND s.code = 'FLL-GAR-2023';
COMMIT;
