-- Generated by scripts/regulation-tables/emit-equations-sql.ts for iso5667_6 (Plan 3). New rows only; existing equations are never updated here (rulings live in scripts/verification/iso5667_6-STAGED-plan3-rulings.sql). Regenerate, do not hand-edit.
BEGIN;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-6-02-D1', 'sampling_point_count_calc = count_rows(sampling_points_6)', ARRAY['sampling_points_6']::text[], 'sampling_point_count_calc', NULL, '§5.1.1', 'Plan 3: Anzahl der erfassten Probenahmepunkte (Zwilling des Eingabefelds sampling_point_count — Ablösung STAGED, iso5667_6-D-4).', 'imported_unverified', 'Cuando sea posible, las ubicaciones del sitio de muestreo deberían ser definidas por una coordenada
de referencia, de acuerdo con el sistema de coordenadas internacional que se encuentra en
ISO 19112[9].'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-6-02' AND s.code = 'ISO-5667-6'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-6-02-D2', 'points_depth_fail = count_rows(sampling_points_6, depth_ok == 0)', ARRAY['sampling_points_6']::text[], 'points_depth_fail', NULL, '§7.1', 'Plan 3: Zeilen, deren §7.1-Position nicht erfüllt ist — weniger als 30 cm über der Sohle oder unter der Oberfläche (S7_1) oder nicht eingetragen (Badge 0). Gate STAGED (iso5667_6-G-9).', 'imported_unverified', 'obtenidas de posiciones al menos 30 cm por encima del fondo de un curso de agua y a una distancia
similar debajo de la superficie, suelen ser satisfactorias.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-6-02' AND s.code = 'ISO-5667-6'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-6-03-D1', 'heterogeneity_samples_count_calc = count_rows(heterogeneity_samples)', ARRAY['heterogeneity_samples']::text[], 'heterogeneity_samples_count_calc', NULL, '§5.1.4', 'Plan 3: Anzahl der erfassten Heterogenitätsproben (Zwilling des Eingabefelds heterogeneity_samples_count — Ablösung STAGED, iso5667_6-D-17).', 'imported_unverified', 'la cantidad de trabajo que esto implica. La parte de la sección transversal a través de la cual una gran
parte (alrededor del 90%) de los pasos totales de flujo, se decide aproximadamente. Dentro de esa
parte, se deberían tomar aproximadamente seis muestras repartidas a través de la parte. Los grandes'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-6-03' AND s.code = 'ISO-5667-6'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-6-03-D2', 'heterogeneity_samples_ok = if(count_rows(heterogeneity_samples) >= lookup(''S5_1_4'', ''heterogeneity'', ''samples_approx''), 1, 0)', ARRAY['heterogeneity_samples']::text[], 'heterogeneity_samples_ok', NULL, '§5.1.4', 'Plan 3: 1, wenn mindestens sechs Proben erfasst sind (S5_1_4.samples_approx, „aproximadamente seis muestras“ — als ≥ 6 gelesen wie CR-008, iso5667_6-J-2), sonst 0; die Zahl der verschiedenen Durchflüsse (≥ 3) bleibt Handangabe (iso5667_6-F-1).', 'imported_unverified', 'la cantidad de trabajo que esto implica. La parte de la sección transversal a través de la cual una gran
parte (alrededor del 90%) de los pasos totales de flujo, se decide aproximadamente. Dentro de esa
parte, se deberían tomar aproximadamente seis muestras repartidas a través de la parte. Los grandes'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-6-03' AND s.code = 'ISO-5667-6'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-6-03-D3', 'heterogeneity_spread = max_rows(heterogeneity_samples, value) - min_rows(heterogeneity_samples, value)', ARRAY['heterogeneity_samples']::text[], 'heterogeneity_spread', NULL, '§5.1.4', 'Plan 3: Spannweite (max − min) der Messwerte über die vollständigen Zeilen — Hilfsgröße für die statistische Beurteilung der Heterogenität; nur je Determinante sinnvoll (iso5667_6-J-3); leeres Register ⇒ manuell.', 'imported_unverified', 'parte, se deberían tomar aproximadamente seis muestras repartidas a través de la parte. Los grandes
ríos podrían requerir más muestras laterales y verticales. Para determinar si algunas diferencias
aparentes entre las muestras son provocadas por la distribución no homogénea o por errores analíticos,
es necesario un análisis estadístico de los resultados. Todas esas muestras deberían ser recogidas
lo más cercanas al mismo tiempo como sea posible, para evitar los efectos de la variación temporal.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-6-03' AND s.code = 'ISO-5667-6'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-6-04-D1', 'travel_time_flows_count_calc = count_rows(travel_time_runs)', ARRAY['travel_time_runs']::text[], 'travel_time_flows_count_calc', NULL, '§5.1.3', 'Plan 3: Anzahl der erfassten Fließzeitmessungen (Zwilling des Eingabefelds travel_time_flows_count — Ablösung STAGED, iso5667_6-D-21); CR-009 liest heute den Skalar (iso5667_6-G-3).', 'imported_unverified', 'Las mediciones se deberían realizar en un mínimo de cinco caudales diferentes y los tiempos de
viaje resultantes trazados en relación con los caudales correspondientes, permitiendo así que
se obtengan otros tiempos de viaje mediante la extrapolación o interpolación. Sin embargo, la
extrapolación fuera del 10% de un valor de medición del caudal puede proporcionar información
incorrecta sobre el tiempo de viaje.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-6-04' AND s.code = 'ISO-5667-6'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-6-04-D2', 'travel_time_flows_ok = if(count_rows(travel_time_runs) >= lookup(''S5_1_3'', ''travel_time'', ''flows_min''), 1, 0)', ARRAY['travel_time_runs']::text[], 'travel_time_flows_ok', NULL, '§5.1.3', 'Plan 3: 1, wenn Messungen bei mindestens fünf Durchflüssen erfasst sind (S5_1_3.flows_min, „un mínimo de cinco caudales diferentes“), sonst 0; Gate STAGED (iso5667_6-G-3).', 'imported_unverified', 'Las mediciones se deberían realizar en un mínimo de cinco caudales diferentes y los tiempos de
viaje resultantes trazados en relación con los caudales correspondientes, permitiendo así que
se obtengan otros tiempos de viaje mediante la extrapolación o interpolación. Sin embargo, la
extrapolación fuera del 10% de un valor de medición del caudal puede proporcionar información
incorrecta sobre el tiempo de viaje.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-6-04' AND s.code = 'ISO-5667-6'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-6-04-D3', 'travel_time_extrapolation_max = lookup(''S5_1_3'', ''travel_time'', ''extrapolation_max_pct'')', ARRAY[]::text[], 'travel_time_extrapolation_max', '%', '§5.1.3', 'Plan 3: die gedruckte Extrapolationsgrenze (10 % eines Durchfluss-Messwerts) als Zwilling neben dem Eingabefeld travel_time_extrapolation_limit (iso5667_6-D-22); scalar-only (iso5667_6-I-1).', 'imported_unverified', 'Las mediciones se deberían realizar en un mínimo de cinco caudales diferentes y los tiempos de
viaje resultantes trazados en relación con los caudales correspondientes, permitiendo así que
se obtengan otros tiempos de viaje mediante la extrapolación o interpolación. Sin embargo, la
extrapolación fuera del 10% de un valor de medición del caudal puede proporcionar información
incorrecta sobre el tiempo de viaje.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-6-04' AND s.code = 'ISO-5667-6'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-6-09-D1', 'increment_total_time_calc = sum_rows(increments, duration_min)', ARRAY['increments']::text[], 'increment_total_time_calc', 'min', '§10.8', 'Plan 3: Gesamtzeit aller Inkremente (Σ Dauer über die vollständigen Zeilen; Zwilling des Eingabefelds increment_total_time — Ablösung STAGED, iso5667_6-D-23); leeres Register ⇒ manuell.', 'imported_unverified', 'simples. Para la muestra que se considera como simple y discreta, el tiempo total para todos los
incrementos que se adopten deberían ser tal que no se esperaría ningún cambio en la composición
del río. Si esto no se conoce, el tiempo para todos los incrementos que se adopten debería ser menor
que 5 min.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-6-09' AND s.code = 'ISO-5667-6'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-6-09-D2', 'increment_time_ok = if(sum_rows(increments, duration_min) < lookup(''S10_8'', ''incremental'', ''total_time_max_min''), 1, 0)', ARRAY['increments']::text[], 'increment_time_ok', NULL, '§10.8', 'Plan 3: 1, wenn die Gesamtzeit der Inkremente unter den 5 min des §10.8 liegt (S10_8.total_time_max_min, „debería ser menor que 5 min“ — strikt wie CR-021), sonst 0; leeres Register ⇒ manuell (nie ein Phantom-Pass); Gate STAGED (iso5667_6-G-5).', 'imported_unverified', 'simples. Para la muestra que se considera como simple y discreta, el tiempo total para todos los
incrementos que se adopten deberían ser tal que no se esperaría ningún cambio en la composición
del río. Si esto no se conoce, el tiempo para todos los incrementos que se adopten debería ser menor
que 5 min.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-6-09' AND s.code = 'ISO-5667-6'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
