-- FLL-GAR-2023 · coverage wave block 2a (2026-09-29): fields the guideline prints limits for but the worksheets never asked.
-- 43 fields on FLL-GAR-06/-08/-10/-18/-20/-22/-23/-27 + equation FLL-GAR-06-D1 + one enum-label repair on FLL-GAR-16.
-- Every verification_quote was read on the rendered PDF (C:\Users\Ekowai\Desktop\FLL Guidelines PDF\fll_gewaesserabdichtungsrichtlinien_2023__2 (2).pdf)
-- in-session on 2026-09-29 (VA); the printed page is in clause_reference/description. Generated from scratchpad gen-block2-gar.mjs.
-- SAFETY: all new fields is_required = false (existing instances stay complete); no gate, value or severity changes here —
-- the gate proposals that read these fields are block 2b (separate file, sign-off). Idempotent (NOT EXISTS / ON CONFLICT DO NOTHING).
-- STAGED — not applied. Apply after block 1: node scripts/apply-migration.mjs scripts/migrations/20260929210000_fll_gar_2023_fields_coverage_block2a.sql
-- Rollback: scripts/migrations/rollback-20260929210000_fll_gar_2023_fields_coverage_block2a.sql
BEGIN;
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'baugrund_ev2_mpa', 'Verformungsmodul Ev2 des Baugrundes', 'Deformation modulus Ev2 of the subgrade', 'number', 'MPa', false, '§4.6', 'Coverage block 2 (A-014): gemessener Ev2 aus dem Plattendruckversuch; Grenze 45 MPa (REQ-31, gestuft).', 'verified_against_standard', 'Für eine anforderungsgerechte Tragfähigkeit ist mindestens ein Verformungsmodul Ev2 ≥ 45 MPa (Ev2/Ev1 ≤ 2,5) erforderlich.', 'FLL-GAR-2023 gedruckte S. 29–30 — §4.6', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'baugrund_ev2_mpa') AND w.code = 'FLL-GAR-06' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'baugrund_ev1_mpa', 'Verformungsmodul Ev1 des Baugrundes (Erstbelastung)', 'Deformation modulus Ev1 of the subgrade (first loading)', 'number', 'MPa', false, '§4.6', 'Coverage block 2 (A-014): Eingang des Verhältnisses Ev2/Ev1 (FLL-GAR-06-D1).', 'verified_against_standard', 'Für eine anforderungsgerechte Tragfähigkeit ist mindestens ein Verformungsmodul Ev2 ≥ 45 MPa (Ev2/Ev1 ≤ 2,5) erforderlich.', 'FLL-GAR-2023 gedruckte S. 29–30 — §4.6', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'baugrund_ev1_mpa') AND w.code = 'FLL-GAR-06' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'baugrund_ev2_ev1', 'Verhältnis Ev2/Ev1', 'Ratio Ev2/Ev1', 'number', '-', false, '§4.6', 'Coverage block 2 (A-014): Ausgabe der Gleichung FLL-GAR-06-D1 = baugrund_ev2_mpa / baugrund_ev1_mpa; Grenze 2,5 (REQ-31, gestuft).', 'verified_against_standard', 'Für eine anforderungsgerechte Tragfähigkeit ist mindestens ein Verformungsmodul Ev2 ≥ 45 MPa (Ev2/Ev1 ≤ 2,5) erforderlich.', 'FLL-GAR-2023 gedruckte S. 29–30 — §4.6', 'derived', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'baugrund_ev2_ev1') AND w.code = 'FLL-GAR-06' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'baugrund_dpr_pct', 'Verdichtungsgrad DPr des Baugrundes', 'Degree of compaction DPr of the subgrade', 'number', '%', false, '§4.6', 'Coverage block 2 (A-014): „soll … ≥ 97 %“ (REQ-32 warn, gestuft).', 'verified_against_standard', 'Der Verdichtungsgrad des Baugrundes soll DPr ≥ 97 % betragen.', 'FLL-GAR-2023 gedruckte S. 30 — §4.6', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'baugrund_dpr_pct') AND w.code = 'FLL-GAR-06' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'einbauwassergehalt_w_pct', 'Einbauwassergehalt w', 'Placement water content w', 'number', 'Masse-%', false, '§5.1.1.1, Tab. 3 Zeile 7', 'Coverage block 2 (A-030): Tab. 3 Zeile 7 — Ist-Wert w; Vergleich mit wPr und w0,97Pr (REQ-12-Erweiterung, gestuft).', 'verified_against_standard', '7 Einbauwassergehalt | wPr ≤ w ≤ w0,97Pr — bei w ≤ wPr: Luftporenanteil na ≤ 5 % | DIN 18121-2 und DIN 18127', 'FLL-GAR-2023 gedruckte S. 37 — §5.1.1.1, Tab. 3 Zeile 7', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'einbauwassergehalt_w_pct') AND w.code = 'FLL-GAR-10' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'w_pr_pct', 'Proctor-Wassergehalt wPr', 'Proctor water content wPr', 'number', 'Masse-%', false, '§5.1.1.1, Tab. 3 Zeile 7', 'Coverage block 2 (A-030): untere Grenze des Einbauwassergehalts (DIN 18127).', 'verified_against_standard', '7 Einbauwassergehalt | wPr ≤ w ≤ w0,97Pr — bei w ≤ wPr: Luftporenanteil na ≤ 5 % | DIN 18121-2 und DIN 18127', 'FLL-GAR-2023 gedruckte S. 37 — §5.1.1.1, Tab. 3 Zeile 7', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'w_pr_pct') AND w.code = 'FLL-GAR-10' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'w_097pr_pct', 'Wassergehalt bei 0,97 · Proctordichte (nasse Seite) w0,97Pr', 'Water content at 0.97 Proctor density (wet side) w0.97Pr', 'number', 'Masse-%', false, '§5.1.1.1, Tab. 3 Zeile 7', 'Coverage block 2 (A-030): obere Grenze des Einbauwassergehalts.', 'verified_against_standard', '7 Einbauwassergehalt | wPr ≤ w ≤ w0,97Pr — bei w ≤ wPr: Luftporenanteil na ≤ 5 % | DIN 18121-2 und DIN 18127', 'FLL-GAR-2023 gedruckte S. 37 — §5.1.1.1, Tab. 3 Zeile 7', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'w_097pr_pct') AND w.code = 'FLL-GAR-10' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'luftporenanteil_na_pct', 'Luftporenanteil na (bei w ≤ wPr)', 'Air void content na (when w ≤ wPr)', 'number', '%', false, '§5.1.1.1, Tab. 3 Zeile 7', 'Coverage block 2 (A-030): nur bei w ≤ wPr gefordert, Grenze 5 % (DIN 18121-2).', 'verified_against_standard', '7 Einbauwassergehalt | wPr ≤ w ≤ w0,97Pr — bei w ≤ wPr: Luftporenanteil na ≤ 5 % | DIN 18121-2 und DIN 18127', 'FLL-GAR-2023 gedruckte S. 37 — §5.1.1.1, Tab. 3 Zeile 7', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'luftporenanteil_na_pct') AND w.code = 'FLL-GAR-10' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_nenndicke_mm', 'Nenndicke der PE-Bahn (Ist)', 'Nominal thickness of the PE liner (actual)', 'number', 'mm', false, '§6.4.1, Tab. 24 Zeile 2; §6.4.1.2; Tab. 25', 'Coverage block 2 (A-107): die tatsächliche Bahnendicke; Vergleichswert sind die Tab.-25-Fills peld_nenndicke_min_mm / pehd_nenndicke_min_mm (REQ-33 warn, gestuft — Tab. 25 „Empfohlene Dicke“).', 'verified_against_standard', '2 Dicke nominal | s. Tab. 25 | mm | DIN EN 1849-2 — Die Dicke der PELD- und PEHD-Bahnen ergibt sich aus dem konkreten Anwendungsfall.', 'FLL-GAR-2023 gedruckte S. 95–96 — §6.4.1, Tab. 24 Zeile 2; §6.4.1.2; Tab. 25', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_nenndicke_mm') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'peeh_russverteilung_kat', 'Rußverteilung (Kategorie)', 'Carbon black dispersion (category)', 'number', 'Kategorie', false, '§6.4.1, Tab. 24 Zeile 6', 'Coverage block 2 (A-108): Tab. 24 Zeile 6, Kategorie 2–3 nach ASTM D 5596 (REQ-20-Erweiterung, gestuft); TAB24-Zeile russverteilung.', 'verified_against_standard', '6 Rußverteilung | 2-3 | Kategorie | ASTM D 5596', 'FLL-GAR-2023 gedruckte S. 95 — §6.4.1, Tab. 24 Zeile 6', 'scalar', NULL, NULL, 'pe_werkstoff == ''PEHD''', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'peeh_russverteilung_kat') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'peeh_massaenderung_pct', 'Maßänderung 1 h / 100 °C', 'Dimensional change 1 h / 100 °C', 'number', '%', false, '§6.4.1, Tab. 24 Zeile 7', 'Coverage block 2 (A-108): Tab. 24 Zeile 7, ≤ 2 % nach DIN EN 1107-2; TAB24-Zeile massaenderung.', 'verified_against_standard', '7 Maßänderung 1 h / 100 °C | ≤ 2 | % | DIN EN 1107-2', 'FLL-GAR-2023 gedruckte S. 95 — §6.4.1, Tab. 24 Zeile 7', 'scalar', NULL, NULL, 'pe_werkstoff == ''PEHD''', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'peeh_massaenderung_pct') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'peeh_nctl_h', 'NCTL-Test (Stress crack resistance)', 'NCTL test (stress crack resistance)', 'number', 'h', false, '§6.4.1, Tab. 24 Zeile 8', 'Coverage block 2 (A-108): Tab. 24 Zeile 8, > 500 h nach ASTM D 5397 app.; TAB24-Zeile nctl.', 'verified_against_standard', '8 NCTL-Test Stress crack resistance | > 500 | h | ASTM D 5397 app.', 'FLL-GAR-2023 gedruckte S. 95 — §6.4.1, Tab. 24 Zeile 8', 'scalar', NULL, NULL, 'pe_werkstoff == ''PEHD''', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'peeh_nctl_h') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'peeh_oit_min', 'OIT-Test Stabilisierungsgrad (bei 200 °C)', 'OIT test, degree of stabilisation (at 200 °C)', 'number', 'min', false, '§6.4.1, Tab. 24 Zeile 9', 'Coverage block 2 (A-108): Tab. 24 Zeile 9, > 100 min bei 200 °C nach DIN EN ISO 11357-6; TAB24-Zeile oit.', 'verified_against_standard', '9 OIT-Test Stabilisierungsgrad | > 100, bei 200 °C | min. | DIN EN ISO 11357-6', 'FLL-GAR-2023 gedruckte S. 95 — §6.4.1, Tab. 24 Zeile 9', 'scalar', NULL, NULL, 'pe_werkstoff == ''PEHD''', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'peeh_oit_min') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'peeh_bbodschv_unbedenklich', 'Umweltverträglichkeit gemäß BBodSchVO: unbedenklich', 'Environmental compatibility per BBodSchVO: harmless', 'boolean', NULL, false, '§6.4.1, Tab. 24 Zeile 10', 'Coverage block 2 (A-108): Tab. 24 Zeile 10 — Nachweis-Boolean (kein Prüfwert gedruckt).', 'verified_against_standard', '10 Umweltverträglichkeit gemäß BBodSchVO | unbedenklich | - | -', 'FLL-GAR-2023 gedruckte S. 95 — §6.4.1, Tab. 24 Zeile 10', 'attestation', NULL, NULL, 'pe_werkstoff == ''PEHD''', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'peeh_bbodschv_unbedenklich') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_boeschung_strukturiert', 'Strukturierte PEHD-Bahn in Böschungsfallrichtung verlegt (Böschung ab 1:10 und > 3 m)', 'Textured PEHD liner laid in slope direction (slope from 1:10 and > 3 m)', 'boolean', NULL, false, '§6.4.2', 'Coverage block 2 (A-113): „sollten“ — REQ-34 warn (gestuft); Auslöser steilste Böschung 1:m ≤ 10 (boeschung_steilste_1m, FLL-GAR-07).', 'verified_against_standard', 'Bei Böschungen ab Neigungen von 1:10 und Längen über 3 m sollten Kunststoffbahnen aus PEHD mit strukturierter Oberfläche in Böschungsfallrichtung verlegt werden. Querüberlappungen in Böschungsfallrichtung sind zu vermeiden. Bei Neigungen von 1:3,5 oder steiler sind ggf. verdeckte Bermen vorzusehen. In allen Fällen sollten die relevanten Kontaktreibungswinkel durch Scherversuche ermittelt werden.', 'FLL-GAR-2023 gedruckte S. 97 — §6.4.2', NULL, NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_boeschung_strukturiert') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_querueberlappung_vermieden', 'Querüberlappungen in Böschungsfallrichtung vermieden', 'Transverse overlaps in slope direction avoided', 'boolean', NULL, false, '§6.4.2', 'Coverage block 2 (A-113): „sind zu vermeiden“ — REQ-34 (gestuft).', 'verified_against_standard', 'Bei Böschungen ab Neigungen von 1:10 und Längen über 3 m sollten Kunststoffbahnen aus PEHD mit strukturierter Oberfläche in Böschungsfallrichtung verlegt werden. Querüberlappungen in Böschungsfallrichtung sind zu vermeiden. Bei Neigungen von 1:3,5 oder steiler sind ggf. verdeckte Bermen vorzusehen. In allen Fällen sollten die relevanten Kontaktreibungswinkel durch Scherversuche ermittelt werden.', 'FLL-GAR-2023 gedruckte S. 97 — §6.4.2', 'attestation', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_querueberlappung_vermieden') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_bermen_vorgesehen', 'Verdeckte Bermen vorgesehen (Böschung 1:3,5 oder steiler)', 'Concealed berms provided (slope 1:3.5 or steeper)', 'boolean', NULL, false, '§6.4.2', 'Coverage block 2 (A-113): „ggf.“ — Dokumentation der Entscheidung, kein Gate.', 'verified_against_standard', 'Bei Böschungen ab Neigungen von 1:10 und Längen über 3 m sollten Kunststoffbahnen aus PEHD mit strukturierter Oberfläche in Böschungsfallrichtung verlegt werden. Querüberlappungen in Böschungsfallrichtung sind zu vermeiden. Bei Neigungen von 1:3,5 oder steiler sind ggf. verdeckte Bermen vorzusehen. In allen Fällen sollten die relevanten Kontaktreibungswinkel durch Scherversuche ermittelt werden.', 'FLL-GAR-2023 gedruckte S. 97 — §6.4.2', NULL, NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_bermen_vorgesehen') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_scherversuch_durchgefuehrt', 'Kontaktreibungswinkel durch Scherversuche ermittelt', 'Interface friction angles determined by shear tests', 'boolean', NULL, false, '§6.4.2', 'Coverage block 2 (A-113): „In allen Fällen sollten“ — REQ-34 warn (gestuft).', 'verified_against_standard', 'Bei Böschungen ab Neigungen von 1:10 und Längen über 3 m sollten Kunststoffbahnen aus PEHD mit strukturierter Oberfläche in Böschungsfallrichtung verlegt werden. Querüberlappungen in Böschungsfallrichtung sind zu vermeiden. Bei Neigungen von 1:3,5 oder steiler sind ggf. verdeckte Bermen vorzusehen. In allen Fällen sollten die relevanten Kontaktreibungswinkel durch Scherversuche ermittelt werden.', 'FLL-GAR-2023 gedruckte S. 97 — §6.4.2', 'attestation', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_scherversuch_durchgefuehrt') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_probeschweissung_durchgefuehrt', 'Probeschweißungen vor der Verschweißung durchgeführt (unter Baustellenbedingungen)', 'Trial welds carried out before welding (under site conditions)', 'boolean', NULL, false, '§6.4.2.1', 'Coverage block 2 (A-116): „sind … durchzuführen“ — REQ-35 block (gestuft).', 'verified_against_standard', 'Die Nahtüberlappung sollte je nach verwendetem Schweißautomaten zwischen 100 und 150 mm betragen. Vor der Verschweißung sind Probeschweißungen durchzuführen, um die Schweißgeräte und auch die Nahtqualität zu beurteilen. Die Probeschweißungen sollen unter Baustellenbedingungen ausgeführt werden. Die Probeschweißungen sind idealerweise 1,0 m lang und 30 cm breit mit mittiger Schweißnaht.', 'FLL-GAR-2023 gedruckte S. 97 — §6.4.2.1', 'attestation', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_probeschweissung_durchgefuehrt') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_probeschweissung_laenge_m', 'Probeschweißung — Länge', 'Trial weld — length', 'number', 'm', false, '§6.4.2.1', 'Coverage block 2 (A-116): „idealerweise 1,0 m“ — Dokumentation, kein Gate.', 'verified_against_standard', 'Die Nahtüberlappung sollte je nach verwendetem Schweißautomaten zwischen 100 und 150 mm betragen. Vor der Verschweißung sind Probeschweißungen durchzuführen, um die Schweißgeräte und auch die Nahtqualität zu beurteilen. Die Probeschweißungen sollen unter Baustellenbedingungen ausgeführt werden. Die Probeschweißungen sind idealerweise 1,0 m lang und 30 cm breit mit mittiger Schweißnaht.', 'FLL-GAR-2023 gedruckte S. 97 — §6.4.2.1', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_probeschweissung_laenge_m') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_probeschweissung_breite_cm', 'Probeschweißung — Breite (mittige Schweißnaht)', 'Trial weld — width (centred seam)', 'number', 'cm', false, '§6.4.2.1', 'Coverage block 2 (A-116): „idealerweise … 30 cm breit“ — Dokumentation, kein Gate.', 'verified_against_standard', 'Die Nahtüberlappung sollte je nach verwendetem Schweißautomaten zwischen 100 und 150 mm betragen. Vor der Verschweißung sind Probeschweißungen durchzuführen, um die Schweißgeräte und auch die Nahtqualität zu beurteilen. Die Probeschweißungen sollen unter Baustellenbedingungen ausgeführt werden. Die Probeschweißungen sind idealerweise 1,0 m lang und 30 cm breit mit mittiger Schweißnaht.', 'FLL-GAR-2023 gedruckte S. 97 — §6.4.2.1', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_probeschweissung_breite_cm') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_nahtpruefung_verfahren', 'Verfahren der zerstörungsfreien Nahtprüfung', 'Non-destructive seam test method', 'enum', NULL, false, '§6.4.2.1', 'Coverage block 2 (A-117): die zwei gedruckten Beispiele + „sonstiges“ („eignen sich z. B.“ — keine abgeschlossene Liste).', 'verified_against_standard', 'Alle Nähte müssten zerstörungsfrei auf ihr äußeres Erscheinungsbild über die gesamte Länge der Naht geprüft werden. Als Verfahren zur Nahtprüfung eignen sich z. B. die Druckluftprüfung für Doppelnähte und die Vakuumprüfung für Extrusionsschweißnähte. Die Prüfergebnisse sind zu protokollieren.', 'FLL-GAR-2023 gedruckte S. 98 — §6.4.2.1', 'select_one', NULL, NULL, NULL, '[{"value":"druckluftpruefung_doppelnaht","label_de":"Druckluftprüfung (Doppelnähte)","label_en":"Air-pressure test (double seams)","order_index":1},{"value":"vakuumpruefung_extrusionsnaht","label_de":"Vakuumprüfung (Extrusionsschweißnähte)","label_en":"Vacuum test (extrusion welds)","order_index":2},{"value":"sonstiges","label_de":"sonstiges Verfahren (z. B. — die Liste ist beispielhaft)","label_en":"other method (the printed list is exemplary)","order_index":3}]'::jsonb, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_nahtpruefung_verfahren') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_nahtpruefung_protokoll', 'Alle Nähte zerstörungsfrei über die gesamte Länge geprüft und protokolliert', 'All seams tested non-destructively over their full length and recorded', 'boolean', NULL, false, '§6.4.2.1', 'Coverage block 2 (A-117): „sind zu protokollieren“ — REQ-35 block (gestuft).', 'verified_against_standard', 'Alle Nähte müssten zerstörungsfrei auf ihr äußeres Erscheinungsbild über die gesamte Länge der Naht geprüft werden. Als Verfahren zur Nahtprüfung eignen sich z. B. die Druckluftprüfung für Doppelnähte und die Vakuumprüfung für Extrusionsschweißnähte. Die Prüfergebnisse sind zu protokollieren.', 'FLL-GAR-2023 gedruckte S. 98 — §6.4.2.1', 'attestation', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_nahtpruefung_protokoll') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_riss_entstehung_mm', 'Rissbreite bei Entstehung (abzudichtendes Bauwerk)', 'Crack width at formation (structure to be sealed)', 'number', 'mm', false, '§6.4.2.2', 'Coverage block 2 (A-119): „nicht breiter als 0,5 mm“ — REQ-37 (gestuft); nur bei Bauwerksabdichtung, Auslöser neurissbildung ≠ ausgeschlossen (FLL-GAR-05).', 'verified_against_standard', 'Arbeitsfugen oder Risse von abzudichtenden Bauwerken dürfen zum Zeitpunkt ihrer Entstehung nicht breiter als 0,5 mm sein. Durch eventuelle weitere Bewegung ist eine Aufweitung auf höchstens 2,0 mm und ein Versatz der Risskanten auf höchstens 1,0 mm zulässig. Kunststoffbahnen aus PEHD müssen vorgenannte Risse im Bauwerk überbrücken können.', 'FLL-GAR-2023 gedruckte S. 98 — §6.4.2.2', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_riss_entstehung_mm') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_riss_aufweitung_mm', 'Rissaufweitung durch weitere Bewegung', 'Crack widening by further movement', 'number', 'mm', false, '§6.4.2.2', 'Coverage block 2 (A-119): „Aufweitung auf höchstens 2,0 mm“ — REQ-37 (gestuft).', 'verified_against_standard', 'Arbeitsfugen oder Risse von abzudichtenden Bauwerken dürfen zum Zeitpunkt ihrer Entstehung nicht breiter als 0,5 mm sein. Durch eventuelle weitere Bewegung ist eine Aufweitung auf höchstens 2,0 mm und ein Versatz der Risskanten auf höchstens 1,0 mm zulässig. Kunststoffbahnen aus PEHD müssen vorgenannte Risse im Bauwerk überbrücken können.', 'FLL-GAR-2023 gedruckte S. 98 — §6.4.2.2', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_riss_aufweitung_mm') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'pe_riss_versatz_mm', 'Versatz der Risskanten', 'Offset of the crack edges', 'number', 'mm', false, '§6.4.2.2', 'Coverage block 2 (A-119): „Versatz der Risskanten auf höchstens 1,0 mm“ — REQ-37 (gestuft).', 'verified_against_standard', 'Arbeitsfugen oder Risse von abzudichtenden Bauwerken dürfen zum Zeitpunkt ihrer Entstehung nicht breiter als 0,5 mm sein. Durch eventuelle weitere Bewegung ist eine Aufweitung auf höchstens 2,0 mm und ein Versatz der Risskanten auf höchstens 1,0 mm zulässig. Kunststoffbahnen aus PEHD müssen vorgenannte Risse im Bauwerk überbrücken können.', 'FLL-GAR-2023 gedruckte S. 98 — §6.4.2.2', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'pe_riss_versatz_mm') AND w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'as_schichtdicke_cm', 'Dicke der vergüteten Dichtungsschicht', 'Thickness of the treated sealing layer', 'number', 'cm', false, '§7.2.1.2', 'Coverage block 2 (A-125): eigenes Feld auf dem Alkalisilikat-Blatt — REQ-22 las bisher schichtdicke_abdichtung_cm des Mineral-Blatts (für Alkalisilikat verborgen); REQ-22 wird hierher umgehostet (2b, gestuft).', 'verified_against_standard', 'Die Dicke der vergüteten Dichtungsschicht soll mind. 25 cm betragen.', 'FLL-GAR-2023 gedruckte S. 104 — §7.2.1.2', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'as_schichtdicke_cm') AND w.code = 'FLL-GAR-20' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'as_lockerungstiefe_cm', 'Lockerungstiefe (Durchmischung des Baugrundes)', 'Loosening depth (mixing of the subgrade)', 'number', 'cm', false, '§7.2.2.1', 'Coverage block 2 (A-125): „soll mind. 25 cm“ — REQ-22 warn (gestuft).', 'verified_against_standard', 'Zur Homogenisierung des Baugrundes ist eine Durchmischung des abzudichtenden Bodenschicht, z. B. durch Auffräsen, vorzusehen. Die Lockerungstiefe soll mind. 25 cm betragen. […] Die Dichtungsschicht ist dynamisch und statisch zu verdichten. Die Lagerungsdichte DPr beträgt ≥ 97 %.', 'FLL-GAR-2023 gedruckte S. 104 — §7.2.2.1', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'as_lockerungstiefe_cm') AND w.code = 'FLL-GAR-20' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'as_dpr_pct', 'Lagerungsdichte DPr der Dichtungsschicht', 'Density index DPr of the sealing layer', 'number', '%', false, '§7.2.2.1', 'Coverage block 2 (A-125): „beträgt ≥ 97 %“ — REQ-38 block (gestuft).', 'verified_against_standard', 'Zur Homogenisierung des Baugrundes ist eine Durchmischung des abzudichtenden Bodenschicht, z. B. durch Auffräsen, vorzusehen. Die Lockerungstiefe soll mind. 25 cm betragen. […] Die Dichtungsschicht ist dynamisch und statisch zu verdichten. Die Lagerungsdichte DPr beträgt ≥ 97 %.', 'FLL-GAR-2023 gedruckte S. 104 — §7.2.2.1', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'as_dpr_pct') AND w.code = 'FLL-GAR-20' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'as_kf_m_s', 'Durchlässigkeitsbeiwert kf der vergüteten Dichtungsschicht', 'Permeability coefficient kf of the treated sealing layer', 'number', 'm/s', false, '§7.2.1.1 → §5.1.1.1, Tab. 3 Zeile 5', 'Coverage block 2 (A-125): Tab. 3 gilt über §7.2.1.1 — REQ-38 (gestuft).', 'verified_against_standard', 'Auf homogene Mineralbodenverhältnisse innerhalb der Abdichtung ist zu achten. Der Feinkornanteil < 0,063 mm des anstehenden Bodens soll mind. 20 Masse-% betragen. Zur Anwendung kommen dabei die Prüfungen nach Abschnitt 5.1.1. Abweichend davon ist der Kornanteil < 0,063 mm zu bestimmen. […] Die Anforderungen an die vergütete Dichtungsschicht entsprechen den Anforderungen gemäß Abschnitt 5.1.1. — Tab. 3: „5 Durchlässigkeitsbeiwert kf bei hydr. Gradient i = 30 | ≤ 1 * 10⁻⁹ m/s | DIN EN ISO 17892-11“', 'FLL-GAR-2023 gedruckte S. 103; 37 — §7.2.1.1 → §5.1.1.1, Tab. 3 Zeile 5', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'as_kf_m_s') AND w.code = 'FLL-GAR-20' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'as_organische_substanz_VGL', 'Organische Substanz VGL (vergütete Dichtungsschicht)', 'Organic content VGL (treated sealing layer)', 'number', 'Masse-%', false, '§7.2.1.1 → §5.1.1.1, Tab. 3 Zeile 3', 'Coverage block 2 (A-125): Tab. 3 gilt über §7.2.1.1 — REQ-38 (gestuft).', 'verified_against_standard', 'Auf homogene Mineralbodenverhältnisse innerhalb der Abdichtung ist zu achten. Der Feinkornanteil < 0,063 mm des anstehenden Bodens soll mind. 20 Masse-% betragen. Zur Anwendung kommen dabei die Prüfungen nach Abschnitt 5.1.1. Abweichend davon ist der Kornanteil < 0,063 mm zu bestimmen. […] Die Anforderungen an die vergütete Dichtungsschicht entsprechen den Anforderungen gemäß Abschnitt 5.1.1. — Tab. 3: „3 organische Substanz VGL | ≤ 5 Masse-% | DIN 18128“', 'FLL-GAR-2023 gedruckte S. 103; 37 — §7.2.1.1 → §5.1.1.1, Tab. 3 Zeile 3', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'as_organische_substanz_VGL') AND w.code = 'FLL-GAR-20' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'as_kalkgehalt_VCA', 'Kalkgehalt VCA (vergütete Dichtungsschicht)', 'Lime content VCA (treated sealing layer)', 'number', 'Masse-%', false, '§7.2.1.1 → §5.1.1.1, Tab. 3 Zeile 4', 'Coverage block 2 (A-125): Tab. 3 gilt über §7.2.1.1 — REQ-38 (gestuft).', 'verified_against_standard', 'Auf homogene Mineralbodenverhältnisse innerhalb der Abdichtung ist zu achten. Der Feinkornanteil < 0,063 mm des anstehenden Bodens soll mind. 20 Masse-% betragen. Zur Anwendung kommen dabei die Prüfungen nach Abschnitt 5.1.1. Abweichend davon ist der Kornanteil < 0,063 mm zu bestimmen. […] Die Anforderungen an die vergütete Dichtungsschicht entsprechen den Anforderungen gemäß Abschnitt 5.1.1. — Tab. 3: „4 Kalkgehalt VCA | ≤ 15 Masse-% | DIN 18129“', 'FLL-GAR-2023 gedruckte S. 103; 37 — §7.2.1.1 → §5.1.1.1, Tab. 3 Zeile 4', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'as_kalkgehalt_VCA') AND w.code = 'FLL-GAR-20' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'wurzelfestigkeit_testat_quecken', 'FLL-Testat „rhizomfest gegen Quecken“ liegt vor (Wurzelfestigkeit nach FLL-Dachbegrünungsverfahren)', 'FLL certificate "rhizome-proof against couch grass" available (root resistance per FLL green-roof procedure)', 'boolean', NULL, false, '§4.3', 'Coverage block 2 (A-011): Mindestnachweis bei vorgesehener Bepflanzung (mit_bepflanzung, FLL-GAR-24) — REQ-11 (gestuft). PEHD ist nach §6.4.1.1 befreit („Auf eine Prüfung der Wurzel- und Rhizomfestigkeit kann verzichtet werden“).', 'verified_against_standard', 'Im Einzelfall ist der Nachweis auf Wurzel- und Rhizomfestigkeit zu führen. Bei vorgesehener Bepflanzung ist die Eignung als Abdichtung nach dem „Verfahren zur Untersuchung der Wurzelfestigkeit von Bahnen und Beschichtungen für Dachbegrünungen“ gemäß FLL durchzuführen. Die Mindestanforderungen für Abdichtungen sind mit dem FLL-Testat „rhizomfest gegen Quecken“ erfüllt. Bei Beanspruchung durch wurzelaggressive und rhizombildende Pflanzenarten (z. B. Phragmites australis) ist eine zusätzliche Prüfung nach dem „Verfahren zur Bestimmung der Rhizomfestigkeit von Gewässerabdichtungen“ gemäß FLL erforderlich.', 'FLL-GAR-2023 gedruckte S. 27 — §4.3', 'attestation', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'wurzelfestigkeit_testat_quecken') AND w.code = 'FLL-GAR-22' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'rhizomfestigkeit_gewaesser_pruefung', 'Prüfung nach dem FLL-„Verfahren zur Bestimmung der Rhizomfestigkeit von Gewässerabdichtungen“ liegt vor', 'Test per the FLL "procedure for determining the rhizome resistance of water-body linings" available', 'boolean', NULL, false, '§4.3', 'Coverage block 2 (A-011): zusätzlich erforderlich bei wurzelaggressiven / rhizombildenden Arten (pflanzen_aggressiv_count > 0, FLL-GAR-24; Tab. 29 = TAB29) — REQ-11 (gestuft).', 'verified_against_standard', 'Im Einzelfall ist der Nachweis auf Wurzel- und Rhizomfestigkeit zu führen. Bei vorgesehener Bepflanzung ist die Eignung als Abdichtung nach dem „Verfahren zur Untersuchung der Wurzelfestigkeit von Bahnen und Beschichtungen für Dachbegrünungen“ gemäß FLL durchzuführen. Die Mindestanforderungen für Abdichtungen sind mit dem FLL-Testat „rhizomfest gegen Quecken“ erfüllt. Bei Beanspruchung durch wurzelaggressive und rhizombildende Pflanzenarten (z. B. Phragmites australis) ist eine zusätzliche Prüfung nach dem „Verfahren zur Bestimmung der Rhizomfestigkeit von Gewässerabdichtungen“ gemäß FLL erforderlich.', 'FLL-GAR-2023 gedruckte S. 27 — §4.3', 'attestation', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'rhizomfestigkeit_gewaesser_pruefung') AND w.code = 'FLL-GAR-22' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'sl_baugrund_groesstkorn_mm', 'Größtkorn d des Baugrundes', 'Maximum grain size d of the subgrade', 'number', 'mm', false, '§8.1', 'Coverage block 2 (A-141): d ≤ 2 mm ⇒ Verzicht auf Schutzlagen möglich — Auslöser in REQ-24 (gestuft).', 'verified_against_standard', 'Bei einem Baugrund mit Größtkorn d ≤ 2 mm kann auf Schutzlagen bzw. -schichten verzichtet werden (s. Tab. 26).', 'FLL-GAR-2023 gedruckte S. 109 — §8.1', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'sl_baugrund_groesstkorn_mm') AND w.code = 'FLL-GAR-22' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'sl_schutzlage_unten_dicke_cm', 'Schutzlage unten — Dicke der Sandschicht im verdichteten Zustand (Ist)', 'Lower protection layer — thickness of the compacted sand layer (actual)', 'number', 'cm', false, '§8.2; §8.3.1, Tab. 26', 'Coverage block 2 (A-143): Vergleichswert sl_schutzlage_unten_sand_min_cm (Tab.-26-Fill) — REQ-24 (gestuft).', 'verified_against_standard', 'Darüber hinaus können auch mineralische Schüttstoffgemische als Schutzlagen bzw. Schutzschichten verwendet werden, wenn sie eine dauerhafte Lagerstabilität gewährleisten und folgende Anforderungen erfüllen: Korngrößen 0,063 mm bis 2 mm (Sand SE/SW/SI nach DIN 18196); Dicke im verdichteten Zustand ≥ 50 mm, in Abhängigkeit von der Beanspruchung können größere Dicken erforderlich werden. — Tab. 26 Spalte 2: „Sand 0,063 mm bis 2 mm — Mindestdicke in cm“', 'FLL-GAR-2023 gedruckte S. 110–111 — §8.2; §8.3.1, Tab. 26', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'sl_schutzlage_unten_dicke_cm') AND w.code = 'FLL-GAR-22' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'sl_ueberlappung_cm', 'Überlappung der Schutzlagen aus Kunststoffbahnen / Geotextilien', 'Overlap of protection layers made of plastic sheets / geotextiles', 'number', 'cm', false, '§8.3', 'Coverage block 2 (A-146): „mind. 10 cm dauerhaft“ — REQ-24 (gestuft).', 'verified_against_standard', 'Bei Schutzlagen und -schichten aus Kunststoffbahnen und Geotextilien ist eine Überlappung von mind. 10 cm dauerhaft vorzusehen.', 'FLL-GAR-2023 gedruckte S. 110 — §8.3', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'sl_ueberlappung_cm') AND w.code = 'FLL-GAR-22' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'sl_pruefzeugnis_swk', 'Prüfzeugnis zur Schutzwirksamkeitsklasse der Schutzlage liegt vor', 'Test certificate for the protection-efficiency class of the protection layer available', 'boolean', NULL, false, '§8.3.2', 'Coverage block 2 (A-152): „ist durch ein Prüfzeugnis zu belegen“ — REQ-24 (gestuft); nur bei dynamischer Beanspruchung (swk_klasse gesetzt).', 'verified_against_standard', 'Die für eine Abdichtung erforderlichen objektbezogenen Nachweise der Schutzwirksamkeitsklasse können nur durch Prüfung des Produkts geführt werden. Der Nachweis der Eignung einer Schutzlage bzw. -schicht für die jeweilige Belastungsklasse ist durch ein Prüfzeugnis zu belegen.', 'FLL-GAR-2023 gedruckte S. 113 — §8.3.2', 'attestation', NULL, NULL, 'swk_klasse IS NOT NULL', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'sl_pruefzeugnis_swk') AND w.code = 'FLL-GAR-22' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'randbefestigung_angepasst', 'Angepasste Randbefestigung am aufgehenden Bauteil vorhanden (Reduzierung der Überhöhung auf ≥ 15 cm)', 'Adapted edge fastening at the rising structure present (reduction of the upstand to ≥ 15 cm)', 'boolean', NULL, false, '§4.8', 'Coverage block 2 (A-019): Auslöser des 15-cm-Falls in REQ-23 (gestuft).', 'verified_against_standard', 'An aufgehenden Bauteilen und Bauwerken ist die Oberkante der Abdichtung i. d. R. 30 cm über dem geplanten Höchstwasserstand auszuführen. Durch Verwendung angepasster Randbefestigungen ist eine Reduzierung der Mindestüberhöhung der Abdichtung auf ≥ 15 cm möglich.', 'FLL-GAR-2023 gedruckte S. 32 — §4.8', NULL, NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'randbefestigung_angepasst') AND w.code = 'FLL-GAR-23' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'gewaesser_an_gebaeudeteilen', 'Gewässer an aufgehenden Gebäudeteilen ausgeführt', 'Water body built against rising building parts', 'boolean', NULL, false, '§4.10', 'Coverage block 2 (A-021): Auslöser der Notüberlauf-Pflicht (REQ-40 auf FLL-GAR-27, gestuft).', 'verified_against_standard', 'Werden Gewässer an aufgehenden Gebäudeteilen ausgeführt, ist ein Notüberlauf mit kanalunabhängigem Entwässerungskonzept nach DIN 1986-100 mit örtlicher 100-Jahres-Regenspende r5,100 zu dimensionieren.', 'FLL-GAR-2023 gedruckte S. 33 — §4.10', NULL, NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'gewaesser_an_gebaeudeteilen') AND w.code = 'FLL-GAR-08' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'notueberlauf_vorhanden', 'Notüberlauf mit kanalunabhängigem Entwässerungskonzept vorhanden', 'Emergency overflow with sewer-independent drainage concept present', 'boolean', NULL, false, '§4.10; Anhang 1', 'Coverage block 2 (A-021): REQ-40 (gestuft).', 'verified_against_standard', 'Werden Gewässer an aufgehenden Gebäudeteilen ausgeführt, ist ein Notüberlauf mit kanalunabhängigem Entwässerungskonzept nach DIN 1986-100 mit örtlicher 100-Jahres-Regenspende r5,100 zu dimensionieren. Der Notüberlauf ist als kanalunabhängige Notentwässerung höher als der Regelüberlauf einzubauen.', 'FLL-GAR-2023 gedruckte S. 33; 132 — §4.10; Anhang 1', NULL, NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'notueberlauf_vorhanden') AND w.code = 'FLL-GAR-27' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'notueberlauf_kapazitaet_l_s', 'Abflusskapazität des Notüberlaufs', 'Discharge capacity of the emergency overflow', 'number', 'l/s', false, '§4.10; Anhang 1', 'Coverage block 2 (A-021): Vergleichswert Q_NOT (Gl. 1, FLL-GAR-27) — REQ-40 (gestuft).', 'verified_against_standard', 'Werden Gewässer an aufgehenden Gebäudeteilen ausgeführt, ist ein Notüberlauf mit kanalunabhängigem Entwässerungskonzept nach DIN 1986-100 mit örtlicher 100-Jahres-Regenspende r5,100 zu dimensionieren. — Anhang 1: „Q NOT = [ (r5,100 – (r5,5 * C) ] * (A / 10.000)“', 'FLL-GAR-2023 gedruckte S. 33; 132 — §4.10; Anhang 1', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'notueberlauf_kapazitaet_l_s') AND w.code = 'FLL-GAR-27' AND s.code = 'FLL-GAR-2023';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'notueberlauf_hoeher_als_regelueberlauf', 'Notüberlauf höher als der Regelüberlauf eingebaut', 'Emergency overflow installed higher than the regular overflow', 'boolean', NULL, false, 'Anhang 1', 'Coverage block 2 (A-021): Anhang 1 (informativ) — REQ-40 (gestuft, Anhang-Status beachten).', 'verified_against_standard', 'Der Notüberlauf ist als kanalunabhängige Notentwässerung höher als der Regelüberlauf einzubauen.', 'FLL-GAR-2023 gedruckte S. 132 — Anhang 1', 'attestation', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'notueberlauf_hoeher_als_regelueberlauf') AND w.code = 'FLL-GAR-27' AND s.code = 'FLL-GAR-2023';
-- Equation for the derived field baugrund_ev2_ev1 (§4.6, printed p. 29–30: "(Ev2/Ev1 ≤ 2,5)").
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-06-D1', 'baugrund_ev2_ev1 = baugrund_ev2_mpa / baugrund_ev1_mpa', ARRAY['baugrund_ev2_mpa','baugrund_ev1_mpa']::text[], 'baugrund_ev2_ev1', '-', '§4.6', 'Coverage block 2 (A-014): Verhältnis der Verformungsmoduln aus dem Plattendruckversuch; Grenze 2,5 in REQ-31 (2b, gestuft).', 'verified_against_standard', 'Für eine anforderungsgerechte Tragfähigkeit ist mindestens ein Verformungsmodul Ev2 ≥ 45 MPa (Ev2/Ev1 ≤ 2,5) erforderlich.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-06' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
-- Enum-label repair (source-settled, cosmetic): the 'ja' option of bahn_vorkonfektioniert carried a whole hyphenated sentence as its label.
-- Printed §6.2.1.2 (p. 84): "Bei werkseitig vorkonfektionierten Bahnen für gering beanspruchte Nutzungen (z. B. Gartenteiche) sind Bahnendicken ≥ 1,0 mm zulässig."
UPDATE fields f SET enum_values = '[{"value":"ja","label_de":"ja — werkseitig vorkonfektionierte Bahn für gering beanspruchte Nutzung (z. B. Gartenteich): Bahnendicke ≥ 1,0 mm zulässig","label_en":"yes — factory-prefabricated liner for low-stress use (e.g. garden pond): thickness ≥ 1.0 mm permitted","order_index":1},{"value":"nein","label_de":"nein — Regelfall (Mindestdicke 1,2 mm)","label_en":"no — standard case (minimum thickness 1.2 mm)","order_index":2}]'::jsonb
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND w.code = 'FLL-GAR-16' AND s.code = 'FLL-GAR-2023' AND f.symbol = 'bahn_vorkonfektioniert' AND f.enum_values::text LIKE '%vorkonfektio- nierten%';
COMMIT;
