-- Generated by scripts/regulation-tables/emit-equations-sql.ts for iso5667_10 (Plan 3). New rows only; existing equations are never updated here (rulings live in scripts/verification/iso5667_10-STAGED-plan3-rulings.sql). Regenerate, do not hand-edit.
BEGIN;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-01-D1', 'qualified_grab_count_calc = count_rows(stichproben_qualifiziert)', ARRAY['stichproben_qualifiziert']::text[], 'qualified_grab_count_calc', NULL, '§3.4', 'Plan 3: Anzahl der erfassten Einzel-Stichproben der qualifizierten Stichprobe (Zwilling des Eingabefelds qualified_grab_count — Ablösung STAGED, iso5667_10-D-1).', 'imported_unverified', 'Forma especial de una muestra compuesta (3.1), formada por al menos cinco muestras puntuales,
tomadas y mezcladas en un plazo un período máximo de dos horas y con un intervalo no inferior a
dos minutos.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-01' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-01-D2', 'qualified_grab_count_ok = if(count_rows(stichproben_qualifiziert) >= lookup(''S3_4'', ''qualified_grab'', ''min_grabs''), 1, 0)', ARRAY['stichproben_qualifiziert']::text[], 'qualified_grab_count_ok', NULL, '§3.4', 'Plan 3: 1, wenn mindestens fünf Stichproben erfasst sind (S3_4.min_grabs, „al menos cinco muestras puntuales“), sonst 0; Zeitfenster ≤ 2 h und Abstand ≥ 2 min bleiben Handangaben (iso5667_10-F-2).', 'imported_unverified', 'Forma especial de una muestra compuesta (3.1), formada por al menos cinco muestras puntuales,
tomadas y mezcladas en un plazo un período máximo de dos horas y con un intervalo no inferior a
dos minutos.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-01' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-02-D1', 'stellen_count = count_rows(probenahmestellen)', ARRAY['probenahmestellen']::text[], 'stellen_count', NULL, '§4.2', 'Plan 3: Anzahl der dokumentierten Probenahmestellen („Cada punto de muestreo debe documentarse“).', 'imported_unverified', 'rastreo pueden ser una herramienta útil. Cada punto de muestreo debe documentarse. Es
importante reunir, por ejemplo, la siguiente
'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-02' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-02-D2', 'stellen_site_fail = count_rows(probenahmestellen, restriction_ok == 0 OR depth_ok == 0 OR runoff_ok == 0)', ARRAY['probenahmestellen']::text[], 'stellen_site_fail', NULL, '§5.1, §5.4', 'Plan 3: Zeilen, deren §5-Prüfung nicht erfüllt ist — Kanal: Abstand < 3 × D oder Tiefe außerhalb 1/3 … 1/2 (S5_SITE); Kühlsystem: Vorlauf < 30 s; andere Standorttypen zählen nie (Badges 1). Gate STAGED (iso5667_10-G-6).', 'imported_unverified', 'El punto de toma de muestras debe estar siempre situado aguas abajo de la restricción y, como
norma general, debe situarse al menos tres veces el diámetro de la tubería, o la anchura del canal,
aguas abajo de la restricción. La entrada de la sonda de muestreo debe orientarse preferentemente — En una instalación de muestreo (grifo de muestreo que permita la desinfección, preferiblemente por
flameo, y el vaciado) se dejará correr el agua durante al menos 30 s antes del muestreo. El muestreo'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-02' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-03-D1', 'period_length_calc = lookup(''S4_3_2'', if(number_of_samples > 25, ''gt25'', ''lt25''), ''period_length'')', ARRAY['number_of_samples']::text[], 'period_length_calc', NULL, '§4.3.2', 'Plan 3: Periodenlänge der anzuwendenden Formel — 365 (Tage, Fórmula 1) bei n > ~25, 52 (Wochen, Fórmula 2) bei n < ~25; n = 25 genau fällt auf Fórmula 2 (iso5667_10-J-1).', 'imported_unverified', 'Fórmula (1) para un número de muestras (n), superior a unas 25 y de la Fórmula (2) para un número de
muestras inferior a unas 25.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-03' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-03-D2', 'A_min_calc = 0 - lookup(''S4_3_2'', if(number_of_samples > 25, ''gt25'', ''lt25''), ''period_length'') / number_of_samples', ARRAY['number_of_samples']::text[], 'A_min_calc', NULL, '§4.3.2', 'Plan 3: untere Grenze des Intervalls der Zufallszahl A — „entre – 365/n y 0“ (Fórmula 1) bzw. „entre – 52/n y 0“ (Fórmula 2); die Ziehung von A bleibt Sache des Ingenieurs (SR-2).', 'imported_unverified', 'n Número de muestras;
A Número aleatorio en un intervalo entre – 365/n y 0. — n Número de muestras;
A Número aleatorio en un intervalo entre – 52/n y 0.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-03' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-03-D3', 'A_in_range = if(A >= 0 - lookup(''S4_3_2'', if(number_of_samples > 25, ''gt25'', ''lt25''), ''period_length'') / number_of_samples AND A <= 0, 1, 0)', ARRAY['A','number_of_samples']::text[], 'A_in_range', NULL, '§4.3.2', 'Plan 3: 1, wenn die eingetragene Zufallszahl A im gedruckten Intervall (−365/n bzw. −52/n … 0) liegt, sonst 0; Gate STAGED (iso5667_10-G-9).', 'imported_unverified', 'n Número de muestras;
A Número aleatorio en un intervalo entre – 365/n y 0. — n Número de muestras;
A Número aleatorio en un intervalo entre – 52/n y 0.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-03' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-03-D4', 'termine_count = count_rows(probenahmetermine)', ARRAY['probenahmetermine']::text[], 'termine_count', NULL, '§4.3.2', 'Plan 3: Anzahl der angelegten Termine k (soll = number_of_samples; Fórmula 1 / 2 laufen bis A + 365·n/n bzw. A + 52·n/n); Gate STAGED (iso5667_10-G-9).', 'imported_unverified', '                                    365            365𝑥2      365𝑥3          365𝑥𝑛
                               𝐴+       ,     𝐴+         , 𝐴+       ,…., 𝐴 +
                                     𝑛               𝑛          𝑛              𝑛 —                                        52            52𝑥2      52𝑥3          52𝑥𝑛
                                 𝐵+       ,     𝐵+        , 𝐴+      ,…., 𝐴 +
                                       𝑛              𝑛         𝑛             𝑛'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-03' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-03-D5', 'termine_done = count_rows(probenahmetermine, done == true)', ARRAY['probenahmetermine']::text[], 'termine_done', NULL, '§4.3.2', 'Plan 3: Anzahl der als durchgeführt markierten Termine (Kontrolle gegen systematische Auslassungen, L505–L508).', 'imported_unverified', 'El periodo elegido debe abarcar cualquier variación estacional. Tras determinar los intervalos y el
número de días o semanas, hay que asegurarse de que el muestreo no conlleve ningún riesgo de error
sistemático, por ejemplo, tomando siempre muestras en un día, u omitiendo sistemáticamente los
días de la semana.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-03' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-05-D1', 'ctcv_cv_max = lookup(''S7_2_2_4'', ''ctcv'', ''cv_max_pct'')', ARRAY[]::text[], 'ctcv_cv_max', '%', '§7.2.2.4', 'Plan 3: der gedruckte Variationskoeffizient (20 % im Mittel), bis zu dem die zeitproportionale Mischprobe CTCV anwendbar ist — als Zwilling neben der Eingabe flow_cv_pct.', 'imported_unverified', 'Este método puede aplicarse, por ejemplo, cuando el caudal instantáneo del efluente varía poco en
el tiempo (coeficiente de variación de la repetibilidad del 20 % por término medio y si la información
recogida demuestra que la carga contaminante no es muy variable durante el período de muestreo).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-05' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-05-D2', 'ctcv_applicable = if(flow_cv_pct <= lookup(''S7_2_2_4'', ''ctcv'', ''cv_max_pct''), 1, 0)', ARRAY['flow_cv_pct']::text[], 'ctcv_applicable', NULL, '§7.2.2.4', 'Plan 3: 1, wenn der Variationskoeffizient des Momentandurchflusses ≤ 20 % ist („el caudal instantáneo del efluente varía poco en el tiempo“), sonst 0 — Anhaltswert („puede aplicarse … por ejemplo“), kein Gate.', 'imported_unverified', 'Este método puede aplicarse, por ejemplo, cuando el caudal instantáneo del efluente varía poco en
el tiempo (coeficiente de variación de la repetibilidad del 20 % por término medio y si la información
recogida demuestra que la carga contaminante no es muy variable durante el período de muestreo).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-05' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-06-D1', 'v_n_sum = sum_rows(flaschen_ctcv, v_n)', ARRAY['flaschen_ctcv']::text[], 'v_n_sum', 'ml', '§7.2.2.3, Fórmula (3)', 'Plan 3: Σ Vn über die Flaschen (Vn = Vfinal · (M3n / M3total) je Zeile) — soll Vfinal ergeben; die prod-Gleichung 3 (ein V_n aus einem M3_n) bleibt.', 'imported_unverified', '                                                                  𝑀3 𝑛
                                              𝑉𝑛 = [𝑉𝑓𝑖𝑛𝑎𝑙 𝑥 (            )]
                                                                 𝑀3 𝑡𝑜𝑡𝑎𝑙

Vn: volumen de la muestra (ml) a tomar en la botella n

Vfinal: volumen total (ml) de las botellas del laboratorio

M3total: volumen total descargado (M3)

M3n: volumen descargado durante el muestreo de la botella n (M3)'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-06' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-06-D2', 'm3_n_sum = sum_rows(flaschen_ctcv, m3_n)', ARRAY['flaschen_ctcv']::text[], 'm3_n_sum', 'm³', '§7.2.2.3, Fórmula (3)', 'Plan 3: Σ M3n über die Flaschen — soll M3total („volumen total descargado“) ergeben.', 'imported_unverified', 'Vn: volumen de la muestra (ml) a tomar en la botella n

Vfinal: volumen total (ml) de las botellas del laboratorio

M3total: volumen total descargado (M3)

M3n: volumen descargado durante el muestreo de la botella n (M3)'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-06' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-06-D3', 'flaschen_count = count_rows(flaschen_ctcv)', ARRAY['flaschen_ctcv']::text[], 'flaschen_count', NULL, '§7.2.2.3, §11.1', 'Plan 3: Anzahl der Einzelflaschen (die Zahl der Elementarproben, die §11.1 im Bericht verlangt).', 'imported_unverified', '- número de muestras elementales tomadas o no (en caso de muestreo compuesto)'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-06' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-06-D4', 'suction_velocity_min = lookup(''S7_2_2_1_TUBE'', if(tube_internal_diameter >= lookup(''S7_2_2_1_TUBE'', ''ge12'', ''bore_min_mm''), ''ge12'', ''ge9''), ''min_velocity_m_s'')', ARRAY['tube_internal_diameter']::text[], 'suction_velocity_min', 'm/s', '§7.2.2.1', 'Plan 3: Mindest-Ansauggeschwindigkeit nach dem Innendurchmesser — 0,5 m/s („no debe ser inferior a 0,5 m/s“), ab 12 mm 0,3 m/s (NOTA 1, „se ha demostrado que … es aceptable“); CR-017 prüft fest 0,5 — Umstellung STAGED (iso5667_10-G-4).', 'imported_unverified', '- Velocidad de aspiración: no debe ser inferior a 0,5 m/s para evitar la segregación de la materia en
suspensión en el — NOTA 1 Pueden ser posibles velocidades de aspiración inferiores si se demuestra que son
satisfactorias. Un ejemplo es cuando el diámetro interno del tubo de aspiración es de 12 mm o más,
en cuyo caso se ha demostrado que una velocidad de aspiración de 0,3 m/s es aceptable[5].'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-06' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-07-D1', 'geraete_count = count_rows(probenahmegeraete)', ARRAY['probenahmegeraete']::text[], 'geraete_count', NULL, '§8.2', 'Plan 3: Anzahl der erfassten Probenahmegeräte.', 'imported_unverified', 'Los muestreadores automáticos pueden ser fijos o portátiles y también pueden estar equipados con
una cámara refrigerada.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-07' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-07-D2', 'geraete_unit_volume_fail = count_rows(probenahmegeraete, unit_volume_ok == 0)', ARRAY['probenahmegeraete']::text[], 'geraete_unit_volume_fail', NULL, '§7.2.2.1', 'Plan 3: Geräte, deren Einheitsvolumen unter dem gedruckten Minimum der Pumpentechnologie liegt (S7_2_2_1_PUMP: 50 ml Vakuumpumpe, 25 ml Inline-Kolben) oder nicht eingetragen ist; Technologien ohne gedrucktes Minimum zählen nie (iso5667_10-E-1). Gate STAGED (iso5667_10-G-5).', 'imported_unverified', '- Volumen de la unidad:

- debe ser adecuado para garantizar un muestreo representativo (por ejemplo, al menos 50 ml para
la bomba de vacío o 25 ml para el émbolo en línea);'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-07' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-5667-10-08-D1', 'homogenizer_mechanical_required = if(collected_volume > lookup(''S9_1'', ''gt5'', ''threshold_l''), 1, 0)', ARRAY['collected_volume']::text[], 'homogenizer_mechanical_required', NULL, '§9.1', 'Plan 3: 1 bei gesammeltem Volumen > 5 l („los homogeneizadores … con agitador magnético o mecánico deberían utilizarse“), 0 bei ≤ 5 l („puede aplicarse el método de laboratorio“); Gate auf homogenizer_type STAGED (iso5667_10-G-2).', 'imported_unverified', 'Para volúmenes de muestra mayores (por ejemplo, > 5 l), los homogeneizadores con recipientes de
muestra transportables y

con agitador magnético o mecánico deberían utilizarse. — Para volúmenes inferiores recogidos (≤5 l), puede aplicarse el método de laboratorio (por ejemplo,
agitación manual, mezcla con varillas, etc.).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-5667-10-08' AND s.code = 'ISO-5667-10'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
