-- Generated by scripts/regulation-tables/emit-equations-sql.ts for iso14046 (Plan 3). New rows only; existing equations are never updated here (rulings live in scripts/verification/iso14046-STAGED-plan3-rulings.sql). Regenerate, do not hand-edit.
BEGIN;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-03-D1', 'water_input_total = sum_rows(elementary_flows, if(direction == ''input'', quantity_m3, 0))', ARRAY['elementary_flows']::text[], 'water_input_total', 'm³', '§5.3.2 a)', 'Plan 3: Σ der Mengen aller Eingangszeilen des Registers elementary_flows (5.3.2 a) „cantidades de agua utilizada: masa, o volumen (por ejemplo entradas de agua y salidas de agua)“); Ausgangszeilen tragen 0 bei; ein leeres Register ist manual_required (keine vollständigen Zeilen), nie eine Phantom-0.', 'imported_unverified', 'a) cantidades de agua utilizada: masa, o volumen (por ejemplo entradas de agua y salidas de agua);'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-03' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-03-D2', 'water_output_total = sum_rows(elementary_flows, if(direction == ''output'', quantity_m3, 0))', ARRAY['elementary_flows']::text[], 'water_output_total', 'm³', '§5.3.2 a)', 'Plan 3: Σ der Mengen aller Ausgangszeilen des Registers elementary_flows (5.3.2 a) „salidas de agua“); Eingangszeilen tragen 0 bei.', 'imported_unverified', 'a) cantidades de agua utilizada: masa, o volumen (por ejemplo entradas de agua y salidas de agua);'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-03' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-03-D3', 'water_balance_diff = sum_rows(elementary_flows, if(direction == ''input'', quantity_m3, 0)) - sum_rows(elementary_flows, if(direction == ''output'', quantity_m3, 0))', ARRAY['elementary_flows']::text[], 'water_balance_diff', 'm³', '§5.3.2', 'Plan 3: Bilanzdifferenz Σ Eingänge − Σ Ausgänge (inline wiederholt — nie auf D1 / D2 verkettet, Task 16 trap 2); eine Differenz ≠ 0 ist die „discrepancia en el balance del inventario“, die nach 5.3.2 zu erläutern ist (inventory_balance_explained bleibt die Bestätigung).', 'imported_unverified', 'El inventario de la huella de agua debe incluir entradas y salidas para cada proceso unitario que forme parte del sistema en estudio. Cualquier discrepancia en el balance del inventario debe explicarse.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-03' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-03-D4', 'elementary_flow_count = count_rows(elementary_flows)', ARRAY['elementary_flows']::text[], 'elementary_flow_count', NULL, '§5.3.2', 'Plan 3: Anzahl der vollständigen Zeilen des Registers elementary_flows („El inventario de la huella de agua debe incluir entradas y salidas para cada proceso unitario“); leeres Register ⇒ 0 (berechnet); Grundlage des STAGED Gate-Vorschlags zu REQ-10 (iso14046-G-9).', 'imported_unverified', 'El inventario de la huella de agua debe incluir entradas y salidas para cada proceso unitario que forme parte del sistema en estudio. Cualquier discrepancia en el balance del inventario debe explicarse.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-03' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-03-D5', 'water_input_rainwater = sum_rows(elementary_flows, if(direction == ''input'' AND resource_type == ''rainwater'', quantity_m3, 0))', ARRAY['elementary_flows']::text[], 'water_input_rainwater', 'm³', '§5.3.2 a), b)', 'Plan 3: Σ der Eingangsmengen des Wasserressourcentyps rainwater (5.3.2 b) — der prod-Token von flow_water_resource_type, die gedruckte Liste L652–L657); andere Zeilen tragen 0 bei; die Inventarphase aggregiert nicht über Typen (L675), daher eine Summe je Typ.', 'imported_unverified', 'b) recursos tipo de agua utilizada:
- pluvial;
- agua superficial;
- agua de mar;
- agua salobre;
- agua subterránea (excluyendo agua fósil);
- aguafósil;'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-03' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-03-D6', 'water_input_surface_water = sum_rows(elementary_flows, if(direction == ''input'' AND resource_type == ''surface_water'', quantity_m3, 0))', ARRAY['elementary_flows']::text[], 'water_input_surface_water', 'm³', '§5.3.2 a), b)', 'Plan 3: Σ der Eingangsmengen des Wasserressourcentyps surface_water (5.3.2 b) — der prod-Token von flow_water_resource_type, die gedruckte Liste L652–L657); andere Zeilen tragen 0 bei; die Inventarphase aggregiert nicht über Typen (L675), daher eine Summe je Typ.', 'imported_unverified', 'b) recursos tipo de agua utilizada:
- pluvial;
- agua superficial;
- agua de mar;
- agua salobre;
- agua subterránea (excluyendo agua fósil);
- aguafósil;'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-03' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-03-D7', 'water_input_seawater = sum_rows(elementary_flows, if(direction == ''input'' AND resource_type == ''seawater'', quantity_m3, 0))', ARRAY['elementary_flows']::text[], 'water_input_seawater', 'm³', '§5.3.2 a), b)', 'Plan 3: Σ der Eingangsmengen des Wasserressourcentyps seawater (5.3.2 b) — der prod-Token von flow_water_resource_type, die gedruckte Liste L652–L657); andere Zeilen tragen 0 bei; die Inventarphase aggregiert nicht über Typen (L675), daher eine Summe je Typ.', 'imported_unverified', 'b) recursos tipo de agua utilizada:
- pluvial;
- agua superficial;
- agua de mar;
- agua salobre;
- agua subterránea (excluyendo agua fósil);
- aguafósil;'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-03' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-03-D8', 'water_input_brackish_water = sum_rows(elementary_flows, if(direction == ''input'' AND resource_type == ''brackish_water'', quantity_m3, 0))', ARRAY['elementary_flows']::text[], 'water_input_brackish_water', 'm³', '§5.3.2 a), b)', 'Plan 3: Σ der Eingangsmengen des Wasserressourcentyps brackish_water (5.3.2 b) — der prod-Token von flow_water_resource_type, die gedruckte Liste L652–L657); andere Zeilen tragen 0 bei; die Inventarphase aggregiert nicht über Typen (L675), daher eine Summe je Typ.', 'imported_unverified', 'b) recursos tipo de agua utilizada:
- pluvial;
- agua superficial;
- agua de mar;
- agua salobre;
- agua subterránea (excluyendo agua fósil);
- aguafósil;'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-03' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-03-D9', 'water_input_groundwater = sum_rows(elementary_flows, if(direction == ''input'' AND resource_type == ''groundwater'', quantity_m3, 0))', ARRAY['elementary_flows']::text[], 'water_input_groundwater', 'm³', '§5.3.2 a), b)', 'Plan 3: Σ der Eingangsmengen des Wasserressourcentyps groundwater (5.3.2 b) — der prod-Token von flow_water_resource_type, die gedruckte Liste L652–L657); andere Zeilen tragen 0 bei; die Inventarphase aggregiert nicht über Typen (L675), daher eine Summe je Typ.', 'imported_unverified', 'b) recursos tipo de agua utilizada:
- pluvial;
- agua superficial;
- agua de mar;
- agua salobre;
- agua subterránea (excluyendo agua fósil);
- aguafósil;'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-03' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-03-D10', 'water_input_fossil_water = sum_rows(elementary_flows, if(direction == ''input'' AND resource_type == ''fossil_water'', quantity_m3, 0))', ARRAY['elementary_flows']::text[], 'water_input_fossil_water', 'm³', '§5.3.2 a), b)', 'Plan 3: Σ der Eingangsmengen des Wasserressourcentyps fossil_water (5.3.2 b) — der prod-Token von flow_water_resource_type, die gedruckte Liste L652–L657); andere Zeilen tragen 0 bei; die Inventarphase aggregiert nicht über Typen (L675), daher eine Summe je Typ.', 'imported_unverified', 'b) recursos tipo de agua utilizada:
- pluvial;
- agua superficial;
- agua de mar;
- agua salobre;
- agua subterránea (excluyendo agua fósil);
- aguafósil;'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-03' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-04-D1', 'category_indicator_total = sum_rows(lci_cf_rows, contribution)', ARRAY['lci_cf_rows']::text[], 'category_indicator_total', NULL, '§5.4.4.1, §3.3.14', 'Plan 3: Σ der Beiträge (Sachbilanzergebnis × Charakterisierungsfaktor je Zeile — die gedruckte Definition 3.3.14) über alle Zeilen des Registers lci_cf_rows; NICHT das Indikatorergebnis einer einzelnen Kategorie (Summe je frei eingetippter Kategorie: iso14046-F-1). Prod EQ-01 auf den Einzelfeldern bleibt unverändert (iso14046-R-1); ein leeres Register ist manual_required.', 'imported_unverified', '14.Factor de caracterización. Factor que surge de un modelo de caracterización que se aplica para convertir el resultado del análisis del inventario del ciclo de vida (3.3.6) asignado a la unidad común del indicador de categoría (3.3.12). — Si el cálculo de la huella de agua se basa en categorías de impacto diferentes, los resultados del inventario del ciclo de vida deben asignarse a éstas categorías de impacto diferentes.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-04' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-05-D1', 'significant_issues_count = count_rows(significant_issues_14046)', ARRAY['significant_issues_14046']::text[], 'significant_issues_count', NULL, '§5.5 a)', 'Plan 3: Anzahl der erfassten signifikanten Themen (5.5 a)); leeres Register ⇒ 0; Grundlage des STAGED Gate-Vorschlags zu REQ-16 (iso14046-G-11).', 'imported_unverified', 'a) identificación de las cuestiones significativas basadas en los resultados de la evaluación de la huella de agua por ejemplo: procesos con una contribución significativa al cálculo de las huellas del agua, mecanismos ambientales principalmente afectados, flujos elementales que tienen la mayor contribución a los resultados de la evaluación de la huella de agua;'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-05' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-07-D1', 'review_panel_members_calc = count_rows(review_panel)', ARRAY['review_panel']::text[], 'review_panel_members_calc', NULL, '§7.4', 'Plan 3: Anzahl der Mitglieder des Prüfungsausschusses (vollständige Zeilen von review_panel); Zwilling des Zahlenfelds review_panel_members (iso14046-D-22); leeres Register ⇒ 0.', 'imported_unverified', 'Una revisión crítica se puede realizar como una revisión por las partes interesadas. En este caso, quien encarga el estudio original debería seleccionar un experto externo independiente para presidir un panel de revisión constituido por al menos tres miembros. Con base en el objetivo y el alcance del estudio, el presidente debería seleccionar otros revisores independientes calificados. Este panel puede incluir otras partes interesadas afectadas por las conclusiones extraídas de la evaluación de la huella de agua; tales como agencias gubernamentales, grupos no gubernamentales, competidores e industrias afectadas.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-07' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-07-D2', 'panel_chair_independent = count_rows(review_panel, chair == true AND independent == true)', ARRAY['review_panel']::text[], 'panel_chair_independent', NULL, '§7.4', 'Plan 3: Anzahl der Zeilen mit Vorsitz UND Unabhängigkeit („un experto externo independiente para presidir un panel de revisión“); 0 = kein unabhängiger Vorsitz erfasst (unangekreuzte Kästchen zählen als false).', 'imported_unverified', 'Una revisión crítica se puede realizar como una revisión por las partes interesadas. En este caso, quien encarga el estudio original debería seleccionar un experto externo independiente para presidir un panel de revisión constituido por al menos tres miembros. Con base en el objetivo y el alcance del estudio, el presidente debería seleccionar otros revisores independientes calificados. Este panel puede incluir otras partes interesadas afectadas por las conclusiones extraídas de la evaluación de la huella de agua; tales como agencias gubernamentales, grupos no gubernamentales, competidores e industrias afectadas.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-07' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-14046-07-D3', 'panel_min_members_ok = if(count_rows(review_panel) >= 3, 1, 0)', ARRAY['review_panel']::text[], 'panel_min_members_ok', NULL, '§7.4', 'Plan 3: 1, wenn der Ausschuss mindestens drei Mitglieder hat („constituido por al menos tres miembros“ — die 3 ist die gedruckte „tres“), sonst 0; leeres Register ⇒ 0 (nie ein Phantom-Pass). Gate STAGED (iso14046-G-3; das Modalverb ist „debería“ → warn vorgeschlagen).', 'imported_unverified', 'Una revisión crítica se puede realizar como una revisión por las partes interesadas. En este caso, quien encarga el estudio original debería seleccionar un experto externo independiente para presidir un panel de revisión constituido por al menos tres miembros. Con base en el objetivo y el alcance del estudio, el presidente debería seleccionar otros revisores independientes calificados. Este panel puede incluir otras partes interesadas afectadas por las conclusiones extraídas de la evaluación de la huella de agua; tales como agencias gubernamentales, grupos no gubernamentales, competidores e industrias afectadas.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-14046-07' AND s.code = 'ISO-14046'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
