-- Generated by scripts/regulation-tables/emit-selection-configs-sql.ts from SELECTION_CONFIGS (phase 2). Regenerate, do not hand-edit.
BEGIN;
UPDATE fields f SET widget = 'register', ui_config = '{"title":"Entwickelte Lösungsvarianten","subtitle":"§9.1(5) — alternative Lösungen mit Bewertung","add_label":"+ Variante","columns":[{"key":"kennung","label":"Variante","type":"text","placeholder":"z. B. V1","width":"w-24"},{"key":"beschreibung","label":"Beschreibung","type":"text"},{"key":"gesamtbewertung","label":"Gesamtbewertung","type":"number","width":"w-32"}]}'::jsonb FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.symbol = 'variants' AND s.code = 'DWA-A-272E' AND f.worksheet_template_id = w.id;
COMMIT;
