-- Generated by scripts/regulation-tables/emit-selection-configs-sql.ts from SELECTION_CONFIGS (phase 2). Regenerate, do not hand-edit.
BEGIN;
UPDATE fields f SET widget = 'select_many', ui_config = '{"title":"Anlagentyp-Kandidaten (Versickerungsanlagen)","subtitle":"§6 — in Betracht kommende Versickerungsanlagen","note":"Oberirdische Versickerungsanlagen sind unterirdischen vorzuziehen (§ Grundsätze). Die gewählten Kandidaten werden in den jeweiligen Bemessungs-Arbeitsblättern (A138-16…22) bemessen."}'::jsonb FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.symbol = 'a138_anlagentyp_kandidaten' AND s.code = 'DWA-A-138-1' AND f.worksheet_template_id = w.id;
COMMIT;
