-- Generated by scripts/regulation-tables/emit-equations-sql.ts for din14021 (Plan 3). New rows only; existing equations are never updated here (rulings live in scripts/verification/din14021-STAGED-plan3-rulings.sql). Regenerate, do not hand-edit.
BEGIN;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-14021-01-D1', 'claims_count = count_rows(claims)', ARRAY['claims']::text[], 'claims_count', NULL, '§7.1', 'Plan 3: Anzahl der erfassten Aussagen (vollständige Zeilen des Registers claims — eine Zeile je Aussage; ein Produkt trägt typischerweise mehrere).', 'imported_unverified', '7.2 kompostierbar
7.3 abbaubar
7.4 zerlegbar konstruiert
7.5 verlängertes Produktleben
7.6 zurückgewonnene Energie
7.7 recyclingfähig
7.8 Recyclatgehalt
7.9 reduzierter Energieverbrauch
7.10 reduzierter Ressourcenverbrauch
7.11 reduzierter Wasserverbrauch
7.12 wiederverwendbar und nachfüllbar
7.13 Abfallminderung'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-14021-01' AND s.code = 'DIN-14021'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-14021-01-D2', 'claims_type_fail = count_rows(claims, type_ok == 0)', ARRAY['claims']::text[], 'claims_type_fail', NULL, '§7.6.3 a), §7.14.2, §7.15.2, §7.16.1, §7.17.3.2, §6.3', 'Plan 3: Zeilen, deren berechnete Typprüfung nicht besteht — R−E>0 nicht erfüllt oder nicht eingetragen (§7.6.3 a), uneingeschränkte Erneuerbarkeits-Aussage ohne 100 % (§7.14.2 / §7.15.2), uneingeschränkte CO2-neutral- / nachhaltig-Aussage (§7.17.3.2 / §7.16.1), vergleichender Aussagetyp ohne Vergleich (§6.3); leeres Register ⇒ 0. IF-Guards der Gates STAGED (din14021-G-23 … G-27).', 'imported_unverified', 'a) Die Aussage darf nur erfolgen, wenn $R-E>0$. — Eine uneingeschränkte Aussage zur erneuerbaren Energie ist nur zulässig, wenn 100 \% der Energie erneuerbar ist. Andernfalls müssen Aussagen zur erneuerbaren Energie wie folgt eingeschränkt werden.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-14021-01' AND s.code = 'DIN-14021'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'DIN-14021-01-D3', 'specific_requirements_met_code = if(count_rows(claims) > 0 AND count_rows(claims, type_ok == 0) == 0, 1, 0)', ARRAY['claims']::text[], 'specific_requirements_met_code', NULL, '§7', 'Plan 3: 1, wenn mindestens eine Aussage erfasst ist und keine Zeile ihre Typprüfung verfehlt (die Zählung ist inline wiederholt — nie auf eine andere neue Ausgabe verkettet), sonst 0; ein leeres Register liest 0 (nie ein Phantom-Pass). Zwilling des Hand-Booleans specific_requirements_met auf DIN-14021-06 (din14021-D-25); Vererbung nach -06 STAGED (din14021-C-1).', 'imported_unverified', '7.1.1 Abschnitt 7 gibt Erklärungen und Anwendungshinweise für ausgewählte, häufig in umweltbezogenen Anbietererklärungen verwendete Begriffe. Die Verantwortung des Antragstellers, den in diesem Abschnitt dargelegten Prinzipien zu folgen, darf nicht durch Verwendung ähnlicher Begriffe abgeschwächt werden. Abschnitt 7 ergänzt, ersetzt jedoch nicht die Anforderungen in anderen Abschnitten der vorliegenden Internationalen Norm. — a) Die Aussage darf nur erfolgen, wenn $R-E>0$.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'DIN-14021-01' AND s.code = 'DIN-14021'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
