-- Generated by scripts/regulation-tables/emit-equations-sql.ts for fll_gar (Plan 3). New rows only; existing equations are never updated here (rulings live in scripts/verification/fll_gar-STAGED-plan3-rulings.sql). Regenerate, do not hand-edit.
BEGIN;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-02-D1', 'gewaesser_in_scope_code = if(gewaesser_type IN {''deponie'', ''fischerei'', ''talsperre'', ''wasserstrasse''}, 0, 1)', ARRAY['gewaesser_type']::text[], 'gewaesser_in_scope_code', NULL, '§1.1', 'Plan 3: 0 für die vier §1.1-Ausschlüsse (L509–L513 "Die Gewässerabdichtungsrichtlinien gelten nicht für: Deponien; Fischereieinrichtungen; Talsperren und Speicherbecken; Wasserstraßen." — prod-Tokens deponie / fischerei / talsperre / wasserstrasse), sonst 1; der manuelle Boolean gewaesser_in_scope (REQ-01) bleibt Produzent — Ablösung STAGED (fll_gar-D-2).', 'imported_unverified', 'Die Gewässerabdichtungsrichtlinien gelten nicht für:  
Deponien;  
Fischereieinrichtungen;  
Talsperren und Speicherbecken;  
Wasserstraßen.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-02' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-05-D1', 'w_klasse_code = if(fuellhoehe_m <= 5, 1, if(fuellhoehe_m <= 10, 2, 3))', ARRAY['fuellhoehe_m']::text[], 'w_klasse_code', NULL, '§6, Tab. 18', 'Plan 3: Wassereinwirkungsklasse aus der Füllhöhe — W1-B ≤ 5 m (L3673), W2-B ≤ 10 m (L3674), W3-B > 10 m (L3675) — als Code 1 / 2 / 3; die manuelle wassereinwirkungsklasse bleibt Produzent für -15 / -16 / -17 (fll_gar-D-1).', 'imported_unverified', 'Nr. 1 2  
1 Einwirkung Anforderung  
2 Wassereinwirkungsklasse Füllhöhe   — 3 W1-B ≤ 5 m   — 4 W2-B ≤ 10 m   — 5 W3-B \> 10 m  '
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-05' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-05-D2', 'r_klasse_code = if(neurissbildung == ''ausgeschlossen'', 0, if(rissbreite_erwartet_mm <= 0.2, 1, if(rissbreite_erwartet_mm <= 0.5, 2, if(rissbreite_erwartet_mm <= 1.0 AND rissversatz_erwartet_mm <= 0.5, 3, 9))))', ARRAY['neurissbildung','rissbreite_erwartet_mm','rissversatz_erwartet_mm']::text[], 'r_klasse_code', NULL, '§6, Tab. 18', 'Plan 3: Rissklasse aus den Tab.-18-Kriterien — R0-B "keine Rissbreitenveränderung bzw. Neurissbildung" (L3677) ⇒ 0; R1-B bis max. 0,2 mm (L3680) ⇒ 1; R2-B bis max. 0,5 mm (L3684) ⇒ 2; R3-B bis max. 1,0 mm, Rissversatz bis 0,5 mm (L3688) ⇒ 3; außerhalb der gedruckten Klassen ⇒ 9 (fll_gar-J-2); alle drei Eingaben sind erforderlich (0 eintragen, wenn keine); die manuelle rissklasse bleibt Produzent (fll_gar-D-3).', 'imported_unverified', '7 R0-B keine Rissbreitenveränderung bzw. Neurissbildung   — 8 R1-B neu entstehende Risse oder Rissbreitenveränderung bis

max. 0,2 mm — 9 R2-B neu entstehende Risse oder Rissbreitenveränderung bis

max. 0,5 mm — 10 R3-B neu entstehende Risse oder Rissbreitenveränderung bis

max. 1,0 mm, Rissversatz bis 0,5 mm'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-05' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-05-D3', 's_klasse_code = if(standort_tab18 == ''aussen_frei'', 1, 2)', ARRAY['standort_tab18']::text[], 's_klasse_code', NULL, '§6, Tab. 18', 'Plan 3: Standortklasse — S1-B "Behälter im Außenbereich, der nicht mit einem Bauwerk verbunden ist." (L3692–L3693) ⇒ 1; S2-B "Behälter im Außenbereich, der an ein Bauwerk angrenzt und mit diesem verbunden ist sowie Behälter im Innenbereich." (L3695–L3696) ⇒ 2; die manuelle standortklasse bleibt Produzent (fll_gar-D-4).', 'imported_unverified', '12 S1-B Behälter im Außenbereich, der nicht mit einem Bauwerk verbun-  
den ist. — 13 S2-B Behälter im Außenbereich, der an ein Bauwerk angrenzt und mit  
diesem verbunden ist sowie Behälter im Innenbereich.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-05' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-07-D1', 'boeschung_steilste_1m = min_rows(boeschungsabschnitte, neigung_1m)', ARRAY['boeschungsabschnitte']::text[], 'boeschung_steilste_1m', 'm (1:m)', '§4.5', 'Plan 3: die steilste Böschung über die Abschnitte = kleinstes m der Schreibweise 1:m (Zonierung Sumpf-, Flach-, Tiefwasserzone, L1415–L1418) — Text-Ableitung ohne gedruckte Formel; Vergleichswert zum Tab.-1-Fill boeschungsneigung_limit (Gate STAGED fll_gar-G-6).', 'imported_unverified', 'Wird eine naturnahe Gestaltung des Gewässers für Flora und Fauna angestrebt, ist eine ent-  
sprechende Modellierung und Profilierung des Baugrundes erforderlich (z. B. Zonierung mit

Sumpf-, Flach- und Tiefwasserzone).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-07' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-07-D2', 'boeschung_verletzungen = count_rows(boeschungsabschnitte, ok == 0)', ARRAY['boeschungsabschnitte']::text[], 'boeschung_verletzungen', NULL, '§4.5, Tab. 1', 'Plan 3: Anzahl der Abschnitte, deren Neigung steiler ist als der Tab.-1-Richtwert der Abdichtungsart (Zeilen-Grenzwert aus TAB1 über abdichtungs_art — auf -07 erst nach fll_gar-C-1 lesbar, bis dahin unentscheidbar); Richtwerte "entbinden nicht von einer rechnerischen Überprüfung" (L1383); REQ-08 STAGED (fll_gar-G-6).', 'imported_unverified', 'Nr. 1 2 3  
1 Art der Abdichtung Neigungsverhältnis Gefälle in %   — Die Angaben in der Tabelle entbinden nicht von einer rechnerischen Überprüfung der Stand-  
und Gleitsicherheit (z. B. mittels Scherversuchen).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-07' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-09-D1', 'lagen_gesamtdicke_mm = sum_rows(abdichtungslagen, if(rolle == ''abdichtung'', dicke_mm, 0))', ARRAY['abdichtungslagen']::text[], 'lagen_gesamtdicke_mm', 'mm', '§4.7', 'Plan 3: Σ Dicke der Zeilen mit Rolle Abdichtung (Schutzlagen und Auflast zählen 0) — Text-Ableitung aus L1487 "Die Art der Abdichtungsstoffe, die Anzahl der Lagen und deren Anordnung …"; Vergleichswert zu den Nenndicken-Fills der Materialblätter.', 'imported_unverified', 'Die Art der Abdichtungsstoffe, die Anzahl der Lagen und deren Anordnung sowie die Verfahren  
zur Herstellung der Abdichtungsschicht müssen in ihrem Zusammenwirken die Funktion der  
Abdichtung sicherstellen.  '
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-09' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-09-D2', 'abdichtungslagen_count = count_rows(abdichtungslagen, rolle == ''abdichtung'')', ARRAY['abdichtungslagen']::text[], 'abdichtungslagen_count', NULL, '§4.7; §6.1.1.2', 'Plan 3: Anzahl der Abdichtungslagen im Aufbau; Bitumenbahnen "i. d. R. mehrlagig" (L3765) — REQ-17 (anzahl_lagen ≥ 2) bleibt auf dem Skalar anzahl_lagen (Re-Point STAGED fll_gar-C-4).', 'imported_unverified', 'Abdichtungen aus Bitumenbahnen sind i. d. R. mehrlagig herzustellen. Die zugelassenen  
Stoffarten sind der Tab. 19 zu entnehmen. Die Bahnendicke ist abhängig von der verwendeten'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-09' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-11-D1', 'mz_dicke_min_tab5 = lookup(''TAB5'', ''verguetet'', ''abdichtung_min_cm'')', ARRAY[]::text[], 'mz_dicke_min_tab5', 'cm', '§5.2.1.2, Tab. 5', 'Plan 3: Mindestdicke der Abdichtungsschicht aus der einzigen Tab.-5-Zeile ("≥ 30 cm, in 2 Lagen von 15 bis 20 cm", L2240–L2242; Nenndicken "einzuhalten" L2222, 10 % Abweichung L2248) — Vergleichswert für mz_dicke; skalare Gleichung, nicht materialisiert (Amendment D).', 'imported_unverified', 'Beim Einbau von mineralischen Abdichtungen mit natürlichen und synthetischen Zusatzstoffen  
sind die Nenndicken der Tabelle 5 einzuhalten: — 2

natürlich vorkommende Mineral-  
böden mit Bentonit/Tonmehl bzw.

Kunststoffen

nach Eignungsprüfung  
(s. 5.2.3.1)  
≥ 30 cm,  
in 2 Lagen von  
15 bis 20 cm

nach Eignungsprüfung  
(s. 5.2.3.1)  
≥ 30 cm'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-11' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-12-D1', 'wz_max = lookup(''TAB6'', if(bauteildicke_cm <= 40, ''le40'', ''gt40''), ''wz_max'')', ARRAY['bauteildicke_cm']::text[], 'wz_max', NULL, '§5.3.1, Tab. 6', 'Plan 3: Höchstwert w/z nach Tab. 6 — d ≤ 40 cm ⇒ 0,60 (L2437), d > 40 cm ⇒ 0,70 (L2440); REQ-14 liest die Literale 0.60 / 0.70 / 280 weiter (Re-Point STAGED fll_gar-G-5); skalare Gleichung, nicht materialisiert (Amendment D).', 'imported_unverified', '2 ≤ 40 Wasserzementwert w/z ≤ 0,60  
3 ≤ 40 Zementgehalt 3 Z ≥ 280 kg/m3  
4 ≤ 40 Druckfestigkeit 4 fck ≥ C25/30   — 5 \> 40 Wasserzementwert w/z ≤ 0,70  '
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-12' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-14-D1', 'groesstkorn_max_mm = if(ungleichfoermigkeit_u >= 5, 32, 16)', ARRAY['ungleichfoermigkeit_u']::text[], 'groesstkorn_max_mm', 'mm', '§5.5.2.1', 'Plan 3: zulässiger Größtkorndurchmesser der Bodenauflast — L3438 "Der Größtkorndurchmesser darf 16 mm bzw. 32 mm bei U ≥ 5 nicht überschreiten." (Text-Ableitung, fll_gar-F-1); Vergleichswert für groesstkorn_auflast_mm (Gate STAGED fll_gar-G-1); skalare Gleichung, nicht materialisiert.', 'imported_unverified', 'innerhalb eines Arbeitstages aufzubringen (s. Abb. 15 \- 17). Die Mindestüberdeckung der Bo-  
denauflast sollte ≥ 5 kN/m2 betragen, was einer Mindestschichtdicke der Auflast von 30 cm

entspricht. Der Größtkorndurchmesser darf 16 mm bzw. 32 mm bei U ≥ 5 nicht überschreiten.  '
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-14' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-16-D1', 'naht_verletzungen = count_rows(naehte, ok == 0)', ARRAY['naehte']::text[], 'naht_verletzungen', NULL, '§6.2.2.1, Tab. 22', 'Plan 3: Anzahl der Nähte unter der Mindestfügebreite der Tab. 22 (Zeilen-Grenzwert aus TAB22 über Fügeverfahren × Stoffart; eine nicht gedruckte Kombination bleibt unentscheidbar); Gate STAGED (fll_gar-G-10).', 'imported_unverified', 'Bei Kunststoff- und Elastormerbahnen ist an den Längs- und Quernähten eine Mindestbreite  
der Überlappung von 40 mm einzuhalten. Bei Bahnen mit Polymerbitumenbeschichtung ist  
eine Mindestbreite von 60 mm einzuhalten.  
Je nach Stoffart der Kunststoff- und Elastomerbahn sind unterschiedliche Fügeverfahren und  
Mindestfügebreiten einzuhalten. — Nr. 1 2 3  
1 Fügeverfahren Stoffart Mindestfügebreite der

Nähte mm'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-16' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-16-D2', 'bahnendicke_min_mm = if(bahn_vorkonfektioniert == ''ja'', 1.0, 1.2)', ARRAY['bahn_vorkonfektioniert']::text[], 'bahnendicke_min_mm', 'mm', '§6.2.1.2', 'Plan 3: Mindestdicke der Kunststoff-/Elastomerbahn — L4064 "Die Bahnen müssen eine Mindestdicke von 1,2 mm aufweisen. Bei werkseitig vorkonfektionierten Bahnen für gering beanspruchte Nutzungen (z. B. Gartenteiche) sind Bahnendicken ≥ 1,0 mm zulässig." (Text-Ableitung, fll_gar-F-2); REQ-18 (fest 1,2) STAGED (fll_gar-G-2); skalare Gleichung, nicht materialisiert.', 'imported_unverified', 'Die Bahnen müssen eine Mindestdicke von 1,2 mm aufweisen. Bei werkseitig vorkonfektio-  
nierten Bahnen für gering beanspruchte Nutzungen (z. B. Gartenteiche) sind Bahnendicken

≥ 1,0 mm zulässig.  
Abdichtungen mit Kunststoff- und Elastomerbahnen sind i. d. R. einlagig.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-16' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-18-D1', 'pe_rhizom_nachweis_code = if(pe_werkstoff == ''PEHD'', 0, 1)', ARRAY['pe_werkstoff']::text[], 'pe_rhizom_nachweis_code', NULL, '§6.4.1.1', 'Plan 3: Nachweis der Wurzel-/Rhizomfestigkeit — PEHD "Auf eine Prüfung der Wurzel- und Rhizomfestigkeit kann verzichtet werden." (L4512) ⇒ 0; PELD "ist vom Hersteller zusätzlich ein Nachweis der Wurzel- bzw. Rhizomfestigkeit gemäß FLL zu erbringen." (L4514–L4515) ⇒ 1; der Boolean wurzel_rhizomfestigkeit_required (-09) bleibt Produzent (fll_gar-D-5); skalare Gleichung, nicht materialisiert.', 'imported_unverified', 'Kunststoffbahnen aus PEHD besitzen eine ausreichende Widerstandsfähigkeit gegenüber  
Wurzeln und Rhizomen. Auf eine Prüfung der Wurzel- und Rhizomfestigkeit kann verzichtet  
werden. Weitere stoffspezifische Anforderungen enthält Tabelle 24\.  
Bei Kunststoffbahnen aus PELD ist vom Hersteller zusätzlich ein Nachweis der Wurzel- bzw.  
Rhizomfestigkeit gemäß FLL zu erbringen.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-18-D2', 'pehd_tab24_code = if(peeh_dichte_g_cm3 > lookup(''TAB24'', ''dichte'', ''min'') AND peeh_mfr >= lookup(''TAB24'', ''mfr'', ''min'') AND peeh_mfr <= lookup(''TAB24'', ''mfr'', ''max'') AND peeh_russgehalt_pct >= lookup(''TAB24'', ''russgehalt'', ''min'') AND peeh_russgehalt_pct <= lookup(''TAB24'', ''russgehalt'', ''max''), 1, 0)', ARRAY['peeh_dichte_g_cm3','peeh_mfr','peeh_russgehalt_pct']::text[], 'pehd_tab24_code', NULL, '§6.4.1, Tab. 24', 'Plan 3: die drei Tab.-24-Anforderungen, die prod als Eingaben führt — Dichte > 0,940 g/cm3 (L4471, strikt), MFR ≥ 1,0 / ≤ 3,0 g/10 min (L4474), Rußgehalt 2-3 % (L4476) — aus TAB24 statt Literalen; REQ-20 prüft dieselben Werte als Literale (Re-Point STAGED fll_gar-G-9); skalare Gleichung, nicht materialisiert.', 'imported_unverified', 'Für PELD-Bahnen bestehen Anforderungen nur herstellerseits. Die werkstoffspezifischen An-  
forderungen für PEHD-Bahnen enthält Tabelle 24\. Insbesondere die Anforderungen hinsicht-  
lich Dichte, Schmelzrate (MFR) und Rußanteil sind zu beachten. — 3 Dichte \> 0,940 g/cm3 DIN EN ISO 1183 — 4 Schmelze-Masse-  
fließrate (MFR) ≥ 1,0 / ≤ 3,0 g/10 min. DIN EN ISO 1133 — 5 Rußgehalt 2-3 %

ASTM D 1603  
ASTM D 4218  '
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-18' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-23-D1', 'randabschnitte_sonder = count_rows(randabschnitte, zulaessig == ''sonder'')', ARRAY['randabschnitte']::text[], 'randabschnitte_sonder', NULL, '§4.8, Tab. 28', 'Plan 3: Anzahl der Randabschnitte, deren Tab.-28-Zelle "-¹" druckt (Fußnote 1 "Nur als Sonderkonstruktion, d. h. als besondere planerische und technische Lösung.", L5748); Tab. 28 druckt keine "nicht zugelassen"-Zelle; die Zeile 0 für Freifläche / Schwimmteich ist leer gedruckt (fll_gar-U-4 — unentscheidbar); REQ-23 (§4.8-Literale 5 / 30 cm) STAGED (fll_gar-G-4).', 'imported_unverified', 'Nr. 1 2 3 4 5

1  
An- /Abschlusshöhe der  
Randbefestigung  
über max. Wasserstand  
in cm

Anwendungsfälle  
X \= Ausführung zugelassen  
(X) \= nur mit geeigneter Randbefestigung und Sicherung

gegen Hinter- und Unterläufigkeit  
Bauteil/Bauwerk Freifläche Schwimmteich — 1 Nur als Sonderkonstruktion, d. h. als besondere planerische und technische Lösung.  '
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-23' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-24-D1', 'durchdringungen_count = count_rows(durchdringungen)', ARRAY['durchdringungen']::text[], 'durchdringungen_count', NULL, '§4.12', 'Plan 3: Anzahl der Durchdringungs-/Einbauten-Zeilen — ersetzt den manuellen Zähler bep_durchdringungen_anzahl nach Ratifizierung (fll_gar-D-6); Text-Ableitung ohne gedruckte Formel (L1479 "Durchdringungen und technische Einbauten").', 'imported_unverified', 'Die Art der Abdichtungsstoffe, die Anzahl der Lagen und deren Anordnung sowie die Verfahren  
zur Herstellung der Abdichtungsschicht müssen in ihrem Zusammenwirken die Funktion der  
Abdichtung sicherstellen.  '
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-24' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-24-D2', 'pflanzen_aggressiv_count = count_rows(pflanzenarten, aggressiv == true)', ARRAY['pflanzenarten']::text[], 'pflanzen_aggressiv_count', NULL, '§4.7; §10.4', 'Plan 3: Anzahl der als aggressiv wurzelnd / rhizombildend markierten Pflanzenarten (L1313 "Im Einzelfall ist der Nachweis auf Wurzel- und Rhizomfestigkeit zu führen. Bei vorgesehener Bepflanzung …"); Grundlage für REQ-11 (leere Bedingung) — Gate STAGED (fll_gar-G-13).', 'imported_unverified', 'Im Einzelfall ist der Nachweis auf Wurzel- und Rhizomfestigkeit zu führen. Bei vorgesehener

Bepflanzung ist die Eignung als Abdichtung nach dem „Verfahren zur Untersuchung der Wur-  
zelfestigkeit von Bahnen und Beschichtungen für Dachbegrünungen“ gemäß FLL durchzufüh-  
ren. Die Mindestanforderungen für Abdichtungen sind mit dem FLL-Testat „rhizomfest gegen'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-24' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-27-D1', 'sum_a_m2 = sum_rows(einzugsflaechen_not, a_m2)', ARRAY['einzugsflaechen_not']::text[], 'sum_a_m2', 'm²', 'Anhang 1, Gl. 1', 'Plan 3: Σ abflusswirksame Fläche über die Teilflächen (Beispiel L6480 "Abflusswirksame Fläche = 800 m2"); Eingang der Summenform von Gl. 1 (fll_gar-R-1) — die prod-Gleichung Gl. 1 liest den Skalar A weiter.', 'imported_unverified', '12 Beispielsberechnung für einen Notüberlauf für einen 800 m2 großen Teich in Düsseldorf  
13 nach DIN 1986-100:  
14 Für Düsseldorf gilt: r5,5 \= 316 l / (s\*ha) und r5,100 \= 607 l / (s\*ha),  
15 Abflusswirksame Fläche \= 800 m2  
16 Abflussbeiwert C \= 1  
17  
18 Berechnung:  
19 Q NOT \= \[ (r5,100 – (r5,5 \* C) \] \* (A / 10.000)  
20 \= ( (607 – 316 l/(s\*ha)) ) \* (800 m2 / 10.000) \= 23,28 l/sec  '
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-27' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLL-GAR-27-D2', 'sum_ac = sum_rows(einzugsflaechen_not, a_m2 * c)', ARRAY['einzugsflaechen_not']::text[], 'sum_ac', 'm²', 'Anhang 1, Gl. 1', 'Plan 3: Σ A · C über die Teilflächen; Gl. 1 (L6484 "Q NOT = [ (r5,100 – (r5,5 * C) ] * (A / 10.000)") in Summenform Q_NOT = (r5,100 · Σ A − r5,5 · Σ A·C) / 10.000 — die Umstellung der prod-Gleichung ist STAGED (fll_gar-R-1); keine zweite Q_NOT-Gleichung.', 'imported_unverified', '19 Q NOT \= \[ (r5,100 – (r5,5 \* C) \] \* (A / 10.000)   — 12 Beispielsberechnung für einen Notüberlauf für einen 800 m2 großen Teich in Düsseldorf  
13 nach DIN 1986-100:  
14 Für Düsseldorf gilt: r5,5 \= 316 l / (s\*ha) und r5,100 \= 607 l / (s\*ha),  
15 Abflusswirksame Fläche \= 800 m2  
16 Abflussbeiwert C \= 1  
17  
18 Berechnung:  
19 Q NOT \= \[ (r5,100 – (r5,5 \* C) \] \* (A / 10.000)  
20 \= ( (607 – 316 l/(s\*ha)) ) \* (800 m2 / 10.000) \= 23,28 l/sec  '
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLL-GAR-27' AND s.code = 'FLL-GAR-2023'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
