-- Generated by scripts/regulation-tables/emit-equations-sql.ts for m1200_3 (Plan 3). New rows only; existing equations are never updated here (rulings live in scripts/verification/m1200_3-STAGED-plan3-rulings.sql). Regenerate, do not hand-edit.
BEGIN;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M12003-06-D1', 'flaeche_gesamt_ha = sum_rows(schlaege, flaeche_ha)', ARRAY['schlaege']::text[], 'flaeche_gesamt_ha', 'ha', '§4.2, Tab. 2; §5.2.1, Tab. 5', 'Plan 3: Σ bewässerte Fläche über die Schlag-Zeilen (Tab.-2-Kopf "Bewässerte Fläche"; Basis der Tab.-5-Dimensionierung "Zu bewässernde Fläche 10 ha") — Text-Ableitung ohne gedruckte Formel; ersetzt den Skalar flaeche_groesse als Eingang von Gl-Helper-1 / -4 nach der Konsumenten-Ergänzung (m1200_3-C-7 / -R-1).', 'imported_unverified', '\hline Betrieb & Musterbetrieb & Betriebsadresse & Zum Anger 1; 12345 Neudorf & Hochwert Schlagmitte & 52,109876 ${ }^{\circ}$ & Rechtswert Schlagmitte & 12,34567 ${ }^{\circ}$ \\
\hline Bewässerte Kultur & Kartoffeln & Adresse des Schlags & Feldweg 12345 Neudorf & Feldblock Nummer & DEXXYY-2222-22244 & Schlag-Bezeichnung & Mühlenberg \\
\hline Bewässerte Fläche & 20 ha & Bewässerungstechnik & Trommel & Bewässerungsempfehlung & DWD AgroWetter & Schlagnummer & 3001-1 \\ — \hline & Zu bewässernde Fläche & 10 ha \\
\hline & Normgröße Bewässerungshöhe & 20 mm \\
\hline & Gesamtbedarf Bewässerungswasser & $2000 \mathrm{~m}^{3}$ \\
\hline \multicolumn{2}{|l|}{Minimal erforderliches Speichervolumen} & $2000 \mathrm{~m}^{3}$ \\
\hline & Installierte Pumpenleistung für die Bewässerung & $50 \mathrm{~m}^{3} / \mathrm{h}$ \\
\hline \multicolumn{2}{|l|}{Dauer eines Bewässerungsdurchgangs} & 40 h \\
\hline & entspricht & $1,7 \mathrm{~d}$ \\
\hline & Zulauf aus der Aufbereitung & $20 \mathrm{~m}^{3} / \mathrm{h}$ \\
\hline \multicolumn{2}{|l|}{Dauer einer Befüllung} & 100 h \\
\hline & entspricht & $4,2 \mathrm{~d}$ \\'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M12003-06' AND s.code = 'DWA-M-1200-3'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M12003-06-D2', 'abstand_verletzungen = count_rows(schlaege, abstand_ok == 0)', ARRAY['schlaege']::text[], 'abstand_verletzungen', NULL, '§5.2.4.2, Tab. 7, Tab. 8; §5.4.4, Tab. 9', 'Plan 3: Anzahl der Schlag-Zeilen, deren vorhandener Abstand den Mindestabstand (Faktor aus TAB789 × Wurfweite, Gl-Helper-5 je Zeile) unterschreitet; Zeilen ohne Sprinklersystem und Zeilen mit steuerbarem Zugang (L1030) zählen als eingehalten; eine Zeile mit der leer gedruckten Tab.-8-Zelle D/mit (m1200_3-U-1) macht die Zählung unentscheidbar; CR-09 auf abstand_verletzungen == 0 STAGED (m1200_3-G-3).', 'imported_unverified', 'Bei Sprinklerbewässerungssystemen werden die in Tabelle 7 sowie Tabelle 8 angegebenen Abstandsregelungen für die verschiedenen Bewässerungssysteme empfohlen. — Eine konkrete Beurteilung und Festlegung von Mindestabständen sowie eines gegebenenfalls zu steuernden Zugangs muss im RMP erfolgen.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M12003-06' AND s.code = 'DWA-M-1200-3'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M12003-08-D1', 'analysen_verletzungen = count_rows(wasseranalysen, ok == 0)', ARRAY['wasseranalysen']::text[], 'analysen_verletzungen', NULL, '§5.6.2, Tab. 11', 'Plan 3: Anzahl der Analyse-Zeilen über dem Tab.-11-Toleranzwert (die (*)-Parameter nach pflanzentyp, pH als Bereich 5,0–9,5); CR-05-Erweiterung um Chlorid / Wasserhärte / Leitfähigkeit STAGED (m1200_3-G-5).', 'imported_unverified', '7 Tabelle 11: Toleranzbereiche für chemische und sonstige Parameter im Bewässerungswasser — (*) salzempfindliche/salzunempfindliche Pflanzen.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M12003-08' AND s.code = 'DWA-M-1200-3'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M12003-10-D1', 'speichervolumen_calc = bewaesserungshoehe * flaeche_gesamt_ha * 10', ARRAY['bewaesserungshoehe','flaeche_gesamt_ha']::text[], 'speichervolumen_calc', 'm³', '§5.2.1, Tab. 5', 'Plan 3: minimal erforderliches Speichervolumen = Bewässerungshöhe × Σ Schlagfläche × 10 (die gedruckte Tab.-5-Arithmetik: 20 mm × 10 ha = 2000 m³; Faktor 10 = mm·ha → m³) — dieselbe Form wie prod Gl-Helper-1, aber über die Register-Summe statt des Skalars flaeche_groesse (m1200_3-R-1); flaeche_gesamt_ha ist auf M12003-10 erst nach der Konsumenten-Ergänzung lesbar (m1200_3-C-7); skalare Gleichung (nicht materialisiert, Amendment D).', 'imported_unverified', 'Für die Dimensionierungen von Speichern ist das Beispiel der Tabelle 5 als Orientierung dienlich. — \hline & Zu bewässernde Fläche & 10 ha \\
\hline & Normgröße Bewässerungshöhe & 20 mm \\
\hline & Gesamtbedarf Bewässerungswasser & $2000 \mathrm{~m}^{3}$ \\
\hline \multicolumn{2}{|l|}{Minimal erforderliches Speichervolumen} & $2000 \mathrm{~m}^{3}$ \\
\hline & Installierte Pumpenleistung für die Bewässerung & $50 \mathrm{~m}^{3} / \mathrm{h}$ \\
\hline \multicolumn{2}{|l|}{Dauer eines Bewässerungsdurchgangs} & 40 h \\
\hline & entspricht & $1,7 \mathrm{~d}$ \\
\hline & Zulauf aus der Aufbereitung & $20 \mathrm{~m}^{3} / \mathrm{h}$ \\
\hline \multicolumn{2}{|l|}{Dauer einer Befüllung} & 100 h \\
\hline & entspricht & $4,2 \mathrm{~d}$ \\'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M12003-10' AND s.code = 'DWA-M-1200-3'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M12003-10-D2', 'bewaesserungshoehe_tab5 = lookup(''S_TAB5_BEISPIEL'', ''normgroesse'', ''bewaesserungshoehe_mm'')', ARRAY[]::text[], 'bewaesserungshoehe_tab5', 'mm', '§5.2.1, Tab. 5', 'Plan 3: Normgröße Bewässerungshöhe des Tab.-5-Beispiels (20 mm) als Orientierungswert (L790 "als Orientierung dienlich") für das Eingabefeld bewaesserungshoehe; skalare Gleichung (nicht materialisiert, Amendment D).', 'imported_unverified', 'Für die Dimensionierungen von Speichern ist das Beispiel der Tabelle 5 als Orientierung dienlich. — \hline & Zu bewässernde Fläche & 10 ha \\
\hline & Normgröße Bewässerungshöhe & 20 mm \\
\hline & Gesamtbedarf Bewässerungswasser & $2000 \mathrm{~m}^{3}$ \\
\hline \multicolumn{2}{|l|}{Minimal erforderliches Speichervolumen} & $2000 \mathrm{~m}^{3}$ \\
\hline & Installierte Pumpenleistung für die Bewässerung & $50 \mathrm{~m}^{3} / \mathrm{h}$ \\
\hline \multicolumn{2}{|l|}{Dauer eines Bewässerungsdurchgangs} & 40 h \\
\hline & entspricht & $1,7 \mathrm{~d}$ \\
\hline & Zulauf aus der Aufbereitung & $20 \mathrm{~m}^{3} / \mathrm{h}$ \\
\hline \multicolumn{2}{|l|}{Dauer einer Befüllung} & 100 h \\
\hline & entspricht & $4,2 \mathrm{~d}$ \\'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M12003-10' AND s.code = 'DWA-M-1200-3'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M12003-10-D3', 'speichervolumen_ist_m3 = sum_rows(speicher_1200_3, volumen_m3)', ARRAY['speicher_1200_3']::text[], 'speichervolumen_ist_m3', 'm³', '§5.1.1; §5.2.1, Tab. 5', 'Plan 3: Σ vorhandenes Speichervolumen über die Speicher-Zeilen — Vergleichswert zum minimal erforderlichen Speichervolumen (Tab. 5); Text-Ableitung ohne gedruckte Formel.', 'imported_unverified', 'Für die Speicherung von Bewässerungswasser werden in Abhängigkeit von der Güteklasse des aufbereiteten Wassers Speichertypen entsprechend Tabelle 3 empfohlen. — \hline & Zu bewässernde Fläche & 10 ha \\
\hline & Normgröße Bewässerungshöhe & 20 mm \\
\hline & Gesamtbedarf Bewässerungswasser & $2000 \mathrm{~m}^{3}$ \\
\hline \multicolumn{2}{|l|}{Minimal erforderliches Speichervolumen} & $2000 \mathrm{~m}^{3}$ \\
\hline & Installierte Pumpenleistung für die Bewässerung & $50 \mathrm{~m}^{3} / \mathrm{h}$ \\
\hline \multicolumn{2}{|l|}{Dauer eines Bewässerungsdurchgangs} & 40 h \\
\hline & entspricht & $1,7 \mathrm{~d}$ \\
\hline & Zulauf aus der Aufbereitung & $20 \mathrm{~m}^{3} / \mathrm{h}$ \\
\hline \multicolumn{2}{|l|}{Dauer einer Befüllung} & 100 h \\
\hline & entspricht & $4,2 \mathrm{~d}$ \\'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M12003-10' AND s.code = 'DWA-M-1200-3'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M12003-11-D1', 'energie_kwh_a = sum_rows(druckleitungen, kwh_abschnitt)', ARRAY['druckleitungen']::text[], 'energie_kwh_a', 'kWh/a', '§5.2.2, Tab. 6', 'Plan 3: Σ Energiebedarf der Abschnitte = Tab.-6-Wert (kWh p. a. je 1.000 m beim gewählten Arbeitsdruck) × Länge / 1000 — die lineare Skalierung auf die Länge ist Text-Ableitung aus "pro 1.000 m Länge" (Caption L838) unter den Annahmen von Anm. 1 (L851) — m1200_3-F-2.', 'imported_unverified', '\caption{Tabelle 6: Schematischer Überblick zu Installations- und Energiekosten von Druckleitungen pro 1.000 m Länge (Stand Q3/2022, Beispiel ländlicher Raum Berlin-Brandenburg)} — 1) gilt für folgende Annahmen: Leitungslänge 1.000 m ohne Bögen, 0 m Höhenunterschied in der Druckleitung, $50 \mathrm{~m}^{3} / \mathrm{h}$ Fördervolumenstrom Pumpe, Saughöhe Pumpe 0 m , Gesamtwirkungsgrad Pumpe und Motor 0,75, 200 h Betriebszeit bei $5 \times 20 \mathrm{~mm}$ Bewässerungsgabe pro Jahr.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M12003-11' AND s.code = 'DWA-M-1200-3'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M12003-11-D2', 'leitungskosten_eur = sum_rows(druckleitungen, kosten_abschnitt_eur)', ARRAY['druckleitungen']::text[], 'leitungskosten_eur', '€', '§5.2.2, Tab. 6; §5.2.3', 'Plan 3: Σ (Materialkosten + Einbaukosten je 1.000 m) × Länge / 1000 über die Abschnitte (Tab. 6, Stand Q3/2022, Beispiel ländlicher Raum Berlin-Brandenburg) — m1200_3-F-2.', 'imported_unverified', '\caption{Tabelle 6: Schematischer Überblick zu Installations- und Energiekosten von Druckleitungen pro 1.000 m Länge (Stand Q3/2022, Beispiel ländlicher Raum Berlin-Brandenburg)}'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M12003-11' AND s.code = 'DWA-M-1200-3'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'M12003-18-D1', 'wasserverbrauch_ist_m3 = sum_rows(bewaesserungstagebuch, wasser_m3)', ARRAY['bewaesserungstagebuch']::text[], 'wasserverbrauch_ist_m3', 'm³', '§4.2, Tab. 2', 'Plan 3: Σ "Wasserverbrauch total (m³)" über die Tagebuch-Zeilen (Tab. 2) — Ist-Verbrauch; Text-Ableitung ohne gedruckte Formel; die Schwermetall-Fracht Σ(Menge × Konzentration) gegen 1/3 BBodSchV (L614, CR-18-2) ist nicht kodiert (m1200_3-F-1).', 'imported_unverified', '\hline Start der Bewässerung & Ende der Bewässerung & Empfehlung Bewässerungsgabe (mm) & \begin{tabular}{l}
reale Bewässerungsgabe \\
(mm)
\end{tabular} & \begin{tabular}{l}
real bewässerte Fläche \\
(ha)
\end{tabular} & \begin{tabular}{l}
Wasserverbrauch total \\
( $\mathrm{m}^{3}$ )
\end{tabular} & Davon aufbereitetes Wasser ( $\mathrm{m}^{3}$ ) & Kommentar \\ — \hline 17.06.2023 06:00 & 20.06.2023 06:00 & 20 & 15 & 20 & 300 & 300 & - \\'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'M12003-18' AND s.code = 'DWA-M-1200-3'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
