-- Generated by scripts/regulation-tables/emit-widget-configs-sql.ts from the TS fallback config (Plan 2b). Regenerate, do not hand-edit.
-- Retires: REFERENCE_CONFIGS_FALLBACK.rainfall_table_ref (src/lib/eval/reference-configs.ts) once applied. Apply AFTER 20260911100000_guideline_to_tool_schema.sql.
BEGIN;
UPDATE fields f SET widget = 'reference', ui_config = '{"title":"Regenspendentabelle (Quelle für r_D(n))","aria_label":"Regenspendentabelle wählen","carrier_symbol":"r_D_n_table","rows_path":"tables","id_key":"id","label_key":"name","badge_key":"source","badge_labels":{"KOSTRA-DWD-2020":"KOSTRA","DWA-A-531-local":"DWA-A 531","engineer":"Ingenieur"},"empty_label":"— Tabelle wählen —"}'::jsonb FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.symbol = 'rainfall_table_ref' AND s.code = 'DWA-A-138-1' AND f.worksheet_template_id = w.id AND f.widget IS NULL;
COMMIT;
