-- FLL-Naturteich · coverage wave block 3a (2026-09-29): fields the guideline prints limits for but the worksheets never asked.
-- 13 fields on FLLNT-06/-07/-11 + equation FLLNT-11-D3 (feed share of the total water volume).
-- Every verification_quote read on the rendered PDF in-session 2026-09-29 (VA); printed page in source_anchor (PDF page = printed + 3).
-- SAFETY: all new fields is_required = false; no gate, value or severity changes here — those are block 3b (sign-off).
-- STAGED — not applied. Apply: node scripts/apply-migration.mjs scripts/migrations/20260929220000_fll_naturteich_fields_coverage_block3a.sql
-- Rollback: scripts/migrations/rollback-20260929220000_fll_naturteich_fields_coverage_block3a.sql
BEGIN;
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'total_water_volume_m3', 'Gesamtwasservolumen des Naturteichs', 'Total water volume of the natural pool', 'number', 'm³', false, '§5, Tab. 4 / Tab. 5 / Tab. 6', 'Coverage block 3 (A-4/A-7): the reference quantity of the feed-rate rules ("% of the total water volume/day"); nothing in the encoding carried a volume before. Engineer input (the zones register carries areas and depths, not volumes).', 'verified_against_standard', 'Table 4 (Type III), Filter operation/warm water circulation during the swimming season: "operation of surface discharge depending on design · filter feed rate > 25% of the total water volume/day · filter operation > 12 h/day · maximum downtime 1 h" — Table 5 (Type IV): "filter feed rate > 80% of the total water volume/day · filter operation 24 h/day" — Table 6 (Type V): "filtration rate > 80% of the total water volume/day · filter operation 24 h/day"', 'FLL-Naturteich (EN 2023) printed p. 25–27 — §5, Tab. 4 / Tab. 5 / Tab. 6', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'total_water_volume_m3') AND w.code = 'FLLNT-06' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'liner_on_concrete_base', 'Folie/Bahn auf ebenem, standfestem Untergrund aus Beton verlegt (faltenfrei gefordert)', 'Liner installed on a level, stable concrete subsoil (crease-free required)', 'boolean', NULL, false, '§9.3', 'Coverage block 3 (A-38): on concrete the liner must be crease-free; without concrete the printed crease tolerances apply (REQ-38, staged).', 'verified_against_standard', 'Synthetic and elastomer liners in visible areas: are to be installed crease-free on level and stable subsoil (e.g. made of concrete); if concrete has not been applied to the subsoil, creases with a height of up to 1.0 cm and a length of up to 2.0 m with a minimum distance of 2.0 m from each other can be tolerated. Creases are not permitted to cross over each other. These specifications apply to the natural pool when it is filled. Creases cannot hinder the use of maintenance equipment;', 'FLL-Naturteich (EN 2023) printed p. 42 — §9.3', NULL, NULL, NULL, 'sealing_type IN {''EPDM'', ''PVC''}', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'liner_on_concrete_base') AND w.code = 'FLLNT-07' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'crease_height_max_cm', 'Größte Faltenhöhe (gefüllter Teich)', 'Maximum crease height (pool filled)', 'number', 'cm', false, '§9.3', 'Coverage block 3 (A-38): "height of up to 1.0 cm" — REQ-38 (staged).', 'verified_against_standard', 'Synthetic and elastomer liners in visible areas: are to be installed crease-free on level and stable subsoil (e.g. made of concrete); if concrete has not been applied to the subsoil, creases with a height of up to 1.0 cm and a length of up to 2.0 m with a minimum distance of 2.0 m from each other can be tolerated. Creases are not permitted to cross over each other. These specifications apply to the natural pool when it is filled. Creases cannot hinder the use of maintenance equipment;', 'FLL-Naturteich (EN 2023) printed p. 42 — §9.3', 'scalar', NULL, NULL, 'sealing_type IN {''EPDM'', ''PVC''} AND liner_on_concrete_base == false', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'crease_height_max_cm') AND w.code = 'FLLNT-07' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'crease_length_max_m', 'Größte Faltenlänge (gefüllter Teich)', 'Maximum crease length (pool filled)', 'number', 'm', false, '§9.3', 'Coverage block 3 (A-38): "length of up to 2.0 m" — REQ-38 (staged).', 'verified_against_standard', 'Synthetic and elastomer liners in visible areas: are to be installed crease-free on level and stable subsoil (e.g. made of concrete); if concrete has not been applied to the subsoil, creases with a height of up to 1.0 cm and a length of up to 2.0 m with a minimum distance of 2.0 m from each other can be tolerated. Creases are not permitted to cross over each other. These specifications apply to the natural pool when it is filled. Creases cannot hinder the use of maintenance equipment;', 'FLL-Naturteich (EN 2023) printed p. 42 — §9.3', 'scalar', NULL, NULL, 'sealing_type IN {''EPDM'', ''PVC''} AND liner_on_concrete_base == false', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'crease_length_max_m') AND w.code = 'FLLNT-07' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'crease_min_distance_m', 'Kleinster Abstand zwischen Falten', 'Minimum distance between creases', 'number', 'm', false, '§9.3', 'Coverage block 3 (A-38): "minimum distance of 2.0 m from each other" — REQ-38 (staged).', 'verified_against_standard', 'Synthetic and elastomer liners in visible areas: are to be installed crease-free on level and stable subsoil (e.g. made of concrete); if concrete has not been applied to the subsoil, creases with a height of up to 1.0 cm and a length of up to 2.0 m with a minimum distance of 2.0 m from each other can be tolerated. Creases are not permitted to cross over each other. These specifications apply to the natural pool when it is filled. Creases cannot hinder the use of maintenance equipment;', 'FLL-Naturteich (EN 2023) printed p. 42 — §9.3', 'scalar', NULL, NULL, 'sealing_type IN {''EPDM'', ''PVC''} AND liner_on_concrete_base == false', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'crease_min_distance_m') AND w.code = 'FLLNT-07' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'creases_crossing', 'Falten kreuzen sich', 'Creases cross over each other', 'boolean', NULL, false, '§9.3', 'Coverage block 3 (A-38): "Creases are not permitted to cross over each other" — must be false (REQ-38, staged).', 'verified_against_standard', 'Synthetic and elastomer liners in visible areas: are to be installed crease-free on level and stable subsoil (e.g. made of concrete); if concrete has not been applied to the subsoil, creases with a height of up to 1.0 cm and a length of up to 2.0 m with a minimum distance of 2.0 m from each other can be tolerated. Creases are not permitted to cross over each other. These specifications apply to the natural pool when it is filled. Creases cannot hinder the use of maintenance equipment;', 'FLL-Naturteich (EN 2023) printed p. 42 — §9.3', NULL, NULL, NULL, 'sealing_type IN {''EPDM'', ''PVC''} AND liner_on_concrete_base == false', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'creases_crossing') AND w.code = 'FLLNT-07' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'entry_exit_point_count', 'Anzahl Ein-/Ausstiegsstellen im Schwimmbereich', 'Number of entry/exit points in the swimming area', 'number', 'Stk', false, '§9.5.3', 'Coverage block 3 (A-44): "at least one" — REQ-39 (staged); the free-text entry_exit_provision stays.', 'verified_against_standard', 'They must be safe to walk on and have a non-slip finish. Routine care and maintenance must be ensured. There must be at least one entry/exit point in the swimming area.', 'FLL-Naturteich (EN 2023) printed p. 43 — §9.5.3', 'scalar', NULL, NULL, NULL, NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'entry_exit_point_count') AND w.code = 'FLLNT-07' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'surface_discharge_hours_per_day', 'Oberflächenabzug im Intervallbetrieb — Betriebsdauer', 'Surface water discharge in interval operation — hours per day', 'number', 'h/d', false, '§5, Tab. 3', 'Coverage block 3 (A-3): Type II "< 10 h/day" — REQ-34 (staged).', 'verified_against_standard', 'Table 3 (Type II), Filter operation/warm water circulation during the swimming season: "no filter available · surface water discharge in interval operation < 10 h/day"', 'FLL-Naturteich (EN 2023) printed p. 24 — §5, Tab. 3', 'scalar', NULL, NULL, 'natural_pool_type == ''type_II''', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'surface_discharge_hours_per_day') AND w.code = 'FLLNT-11' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'filter_feed_volume_per_day_m3', 'Filterbeschickung je Tag (Volumen)', 'Filter feed volume per day', 'number', 'm³/d', false, '§5, Tab. 4 / Tab. 5 / Tab. 6', 'Coverage block 3 (A-4/A-7): numerator of the feed share (FLLNT-11-D3); the per-unit register carries m³/(m²·d), not a daily volume.', 'verified_against_standard', 'Table 4 (Type III), Filter operation/warm water circulation during the swimming season: "operation of surface discharge depending on design · filter feed rate > 25% of the total water volume/day · filter operation > 12 h/day · maximum downtime 1 h" — Table 5 (Type IV): "filter feed rate > 80% of the total water volume/day · filter operation 24 h/day" — Table 6 (Type V): "filtration rate > 80% of the total water volume/day · filter operation 24 h/day"', 'FLL-Naturteich (EN 2023) printed p. 25–27 — §5, Tab. 4 / Tab. 5 / Tab. 6', 'scalar', NULL, NULL, 'natural_pool_type IN {''type_III'', ''type_IV'', ''type_V''}', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'filter_feed_volume_per_day_m3') AND w.code = 'FLLNT-11' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'feed_share_of_volume_pct', 'Filterbeschickung in % des Gesamtwasservolumens je Tag', 'Filter feed rate as % of the total water volume per day', 'number', '%', false, '§5, Tab. 4 / Tab. 5 / Tab. 6', 'Coverage block 3 (A-4/A-7): output of FLLNT-11-D3 = filter_feed_volume_per_day_m3 · 100 / total_water_volume_m3 (FLLNT-06); limits 25 % (III) / 80 % (IV, V) in REQ-35 (staged).', 'verified_against_standard', 'Table 4 (Type III), Filter operation/warm water circulation during the swimming season: "operation of surface discharge depending on design · filter feed rate > 25% of the total water volume/day · filter operation > 12 h/day · maximum downtime 1 h" — Table 5 (Type IV): "filter feed rate > 80% of the total water volume/day · filter operation 24 h/day" — Table 6 (Type V): "filtration rate > 80% of the total water volume/day · filter operation 24 h/day"', 'FLL-Naturteich (EN 2023) printed p. 25–27 — §5, Tab. 4 / Tab. 5 / Tab. 6', 'derived', NULL, NULL, 'natural_pool_type IN {''type_III'', ''type_IV'', ''type_V''}', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'feed_share_of_volume_pct') AND w.code = 'FLLNT-11' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'filter_operation_hours_per_day', 'Filterbetrieb — Stunden je Tag (Badesaison)', 'Filter operation — hours per day (swimming season)', 'number', 'h/d', false, '§5, Tab. 4 / Tab. 5 / Tab. 6', 'Coverage block 3 (A-5/A-8): "> 12 h/day" (III) · "24 h/day" (IV, V) — REQ-36 (staged).', 'verified_against_standard', 'Table 4 (Type III), Filter operation/warm water circulation during the swimming season: "operation of surface discharge depending on design · filter feed rate > 25% of the total water volume/day · filter operation > 12 h/day · maximum downtime 1 h" — Table 5 (Type IV): "filter feed rate > 80% of the total water volume/day · filter operation 24 h/day" — Table 6 (Type V): "filtration rate > 80% of the total water volume/day · filter operation 24 h/day"', 'FLL-Naturteich (EN 2023) printed p. 25–27 — §5, Tab. 4 / Tab. 5 / Tab. 6', 'scalar', NULL, NULL, 'natural_pool_type IN {''type_III'', ''type_IV'', ''type_V''}', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'filter_operation_hours_per_day') AND w.code = 'FLLNT-11' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'filter_max_downtime_h', 'Längste Filter-Stillstandszeit', 'Maximum filter downtime', 'number', 'h', false, '§5, Tab. 4', 'Coverage block 3 (A-6): "maximum downtime 1 h" — REQ-36 (staged).', 'verified_against_standard', 'Table 4 (Type III), Filter operation/warm water circulation during the swimming season: "operation of surface discharge depending on design · filter feed rate > 25% of the total water volume/day · filter operation > 12 h/day · maximum downtime 1 h"', 'FLL-Naturteich (EN 2023) printed p. 25 — §5, Tab. 4', 'scalar', NULL, NULL, 'natural_pool_type == ''type_III''', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'filter_max_downtime_h') AND w.code = 'FLLNT-11' AND s.code = 'FLL-Naturteich';
INSERT INTO fields (worksheet_template_id, section_id, symbol, label_de, label_en, data_type, unit, is_required, clause_reference, description, verification_status, verification_quote, source_anchor, widget, ui_config, lookup, visible_when, enum_values, order_index, active)
SELECT w.id, (SELECT ws.id FROM worksheet_sections ws WHERE ws.worksheet_template_id = w.id AND ws.code = 'C'), 'overflow_connected_water_surface_m2', 'Wasseroberfläche des an den Überlauf angeschlossenen Bereichs', 'Water surface of the area connected to the overflow weir', 'number', 'm²', false, '§10.3.1', 'Coverage block 3 (A-56 / B-1): the multiplier of the 150 l/m² rule is the inundated WATER SURFACE (plan area) of the connected area — single-area systems: the total water surface; multi-area: only the connected area. EQ-05 / REQ-33 currently multiply pool_underwater_surface (bottom + walls, App. 5) — wrong operand; the rewrite is 3b (staged).', 'verified_against_standard', 'A water reservoir is mandatory when using rigid overflow weirs. […] The usable volume of the splash water tank must be dimensioned so that at least 150 l per square metre can be provided to the inundated water surface. […] In the case of multi-area systems, only the water surface of the area to which the overflow weir is connected is taken into account.', 'FLL-Naturteich (EN 2023) printed p. 54–55 — §10.3.1', 'scalar', NULL, NULL, 'rigid_overflow_used == true', NULL, (SELECT COALESCE(MAX(order_index), 0) + 1 FROM fields f3 WHERE f3.worksheet_template_id = w.id), true
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE NOT EXISTS (SELECT 1 FROM fields f2 WHERE f2.worksheet_template_id = w.id AND f2.symbol = 'overflow_connected_water_surface_m2') AND w.code = 'FLLNT-11' AND s.code = 'FLL-Naturteich';
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'FLLNT-11-D3', 'feed_share_of_volume_pct = filter_feed_volume_per_day_m3 * 100 / total_water_volume_m3', ARRAY['filter_feed_volume_per_day_m3','total_water_volume_m3']::text[], 'feed_share_of_volume_pct', '%', '§5, Tab. 4 / Tab. 5 / Tab. 6', 'Coverage block 3 (A-4/A-7): feed share of the total water volume per day; total_water_volume_m3 lives on FLLNT-06 (cross-sheet input, like pool_underwater_surface in EQ-01/EQ-03).', 'verified_against_standard', 'Table 4 (Type III), Filter operation/warm water circulation during the swimming season: "operation of surface discharge depending on design · filter feed rate > 25% of the total water volume/day · filter operation > 12 h/day · maximum downtime 1 h" — Table 5 (Type IV): "filter feed rate > 80% of the total water volume/day · filter operation 24 h/day" — Table 6 (Type V): "filtration rate > 80% of the total water volume/day · filter operation 24 h/day"'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'FLLNT-11' AND s.code = 'FLL-Naturteich'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
