-- Generated by scripts/regulation-tables/emit-equations-sql.ts for iso46001 (Plan 3). New rows only; existing equations are never updated here (rulings live in scripts/verification/iso46001-STAGED-plan3-rulings.sql). Regenerate, do not hand-edit.
BEGIN;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-01-D1', 'interested_parties_count = count_rows(interested_parties_46001)', ARRAY['interested_parties_46001']::text[], 'interested_parties_count', NULL, '§4.2', 'Plan 3: Anzahl der erfassten interessierten Parteien („the interested parties that are relevant to the water efficiency management system“).', 'imported_unverified', '4.2 Understanding the needs and expectations of interested parties The organization shall determine: a) the interested parties that are relevant to the water efficiency management system; b) the relevant requirements of these interested parties.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-01' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-03-D1', 'objectives_count = count_rows(objectives)', ARRAY['objectives']::text[], 'objectives_count', NULL, '§6.2.1', 'Plan 3: Anzahl der erfassten Wassereffizienz-Ziele („establish water efficiency objectives at relevant functions and levels“); Attestierungen CR-009 / CR-010 → iso46001-G-5.', 'imported_unverified', '6.2.1 General The organization shall establish water efficiency objectives at relevant functions and levels. The water efficiency objectives shall: a) be consistent with the water efficiency policy; b) be measurable (if practicable); c) take into account applicable requirements; d) be monitored; e) be communicated; f) be updated as appropriate (for example following internal or external benchmarking). The organization shall retain documented information on the water efficiency objectives. When planning how to achieve its water efficiency objectives, the organization shall determine: 1) what will be done; 2) what resources will be required; 3) who will be responsible; 4) when it will be completed; 5) how the results will be evaluated.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-03' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-03-D2', 'legal_requirements_count = count_rows(legal_requirements)', ARRAY['legal_requirements']::text[], 'legal_requirements_count', NULL, '§6.2.3', 'Plan 3: Anzahl der erfassten rechtlichen / anderen Anforderungen („reviewed at defined intervals“).', 'imported_unverified', '6.2.3Legal requirements or other requirements
The organization shall ensure that legal requirements or other requirements are considered in establishing, implementing and maintaining the water efficiency management system and are reviewed at defined intervals.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-03' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-04-D1', 'water_efficiency_indicator_calc = past_present_water_use / business_activity_indicator_value', ARRAY['past_present_water_use','business_activity_indicator_value']::text[], 'water_efficiency_indicator_calc', NULL, '§3.33, §6.2.6', 'Plan 3: Wassereffizienz-Indikator = „amount of water used per unit of business activity indicator“ aus den vorhandenen -04-Eingaben (Wassernutzung im Datenzeitraum / Wert des Geschäftsaktivitäts-Indikators); Zwilling des Eingabefelds water_efficiency_indicator (an -05 / -09 vererbt, CR-017) — Umstellung STAGED (iso46001-D-29 / G-6); past_present_water_use ≡ Win ist iso46001-X-2. Skalar (nicht serverseitig materialisiert).', 'imported_unverified', '3.33 water efficiency indicator amount of water used per unit of business activity indicator (3.4)
Note 1 to entry: "Used" in the context of this indicator means the net amount of water used (including any water consumed) in the course of the business activity (3.3), discounting the amount of water applied that is reclaimed or recycled for further use.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-04' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-04-D2', 'seu_total = sum_rows(significant_uses, m3_per_a)', ARRAY['significant_uses']::text[], 'seu_total', 'm³/a', '§6.2.4 2)', 'Plan 3: Σ der jährlichen Wassernutzung aller erfassten signifikanten Nutzungen.', 'imported_unverified', '6.2.4 Conduct water use review
The organization shall develop, conduct and maintain a water use review to:
a) identify the activities and functions that use water;
b) record the water used for each identified activity and function;
c) determine processes and services that affect the used water quality, with the aim of segregating the used water streams with the objective of water recycling;
d) determine activities and functions with the potential for greater water efficiency.
The methodology and criteria used to develop the water use review shall be maintained as documented information.
To develop the water use review, the organization shall:
1) analyse water use based on measurement and other data as follows:
-- identify current water sources;
-- identify current water-using activities and functions;
-- evaluate past and present water use;
-- estimate future water use.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-04' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-04-D3', 'seu_share_max = max_rows(significant_uses, m3_per_a) * 100 / sum_rows(significant_uses, m3_per_a)', ARRAY['significant_uses']::text[], 'seu_share_max', '%', '§6.2.4 2), §3.28', 'Plan 3: größter Anteil einer signifikanten Nutzung an der Summe („activity accounting for a substantial portion of total water used“); ein Anteil je Zeile ist in Zeilenscope nicht darstellbar (iso46001-F-1).', 'imported_unverified', '3.28 significant water use activity accounting for a substantial portion of total water used (3.39) [including any water consumed (3.31)] and/or offering considerable potential for water efficiency performance (3.37) improvement
Note 1 to entry: Water use can include both "new" drinking water and reclaimed water (3.25) components.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-04' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-04-D4', 'seu_count = count_rows(significant_uses)', ARRAY['significant_uses']::text[], 'seu_count', NULL, '§6.2.4 2)', 'Plan 3: Anzahl der erfassten signifikanten Wassernutzungen.', 'imported_unverified', '6.2.4 Conduct water use review
The organization shall develop, conduct and maintain a water use review to:
a) identify the activities and functions that use water;
b) record the water used for each identified activity and function;
c) determine processes and services that affect the used water quality, with the aim of segregating the used water streams with the objective of water recycling;
d) determine activities and functions with the potential for greater water efficiency.
The methodology and criteria used to develop the water use review shall be maintained as documented information.
To develop the water use review, the organization shall:
1) analyse water use based on measurement and other data as follows:
-- identify current water sources;
-- identify current water-using activities and functions;
-- evaluate past and present water use;
-- estimate future water use.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-04' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-04-D5', 'water_sources_count = count_rows(water_sources_46001)', ARRAY['water_sources_46001']::text[], 'water_sources_count', NULL, '§6.2.4 1)', 'Plan 3: Anzahl der erfassten aktuellen Wasserquellen („identify current water sources“).', 'imported_unverified', '6.2.4 Conduct water use review
The organization shall develop, conduct and maintain a water use review to:
a) identify the activities and functions that use water;
b) record the water used for each identified activity and function;
c) determine processes and services that affect the used water quality, with the aim of segregating the used water streams with the objective of water recycling;
d) determine activities and functions with the potential for greater water efficiency.
The methodology and criteria used to develop the water use review shall be maintained as documented information.
To develop the water use review, the organization shall:
1) analyse water use based on measurement and other data as follows:
-- identify current water sources;
-- identify current water-using activities and functions;
-- evaluate past and present water use;
-- estimate future water use.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-04' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-04-D6', 'indicators_count = count_rows(indicators_46001)', ARRAY['indicators_46001']::text[], 'indicators_count', NULL, '§6.2.6', 'Plan 3: Anzahl der erfassten Wassereffizienz-Indikatoren.', 'imported_unverified', '6.2.6 Determine water efficiency indicator(s)
The methodology for determining and updating the water efficiency indicator(s) shall be maintained as documented information and regularly reviewed. Water efficiency indicator(s) shall be reviewed and compared with the baseline water efficiency indicator(s) as appropriate and periodically updated as appropriate.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-04' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-05-D1', 'targets_count = count_rows(targets)', ARRAY['targets']::text[], 'targets_count', NULL, '§6.3', 'Plan 3: Anzahl der erfassten Zielwerte (vollständig nur mit Zeitrahmen — „Time frames shall be established for achievement of the targets“).', 'imported_unverified', '6.3 Targets and action plans
The organization shall establish, within or supplemental to the objectives, water efficiency targets at relevant functions, levels, processes or facilities within the organization.
Time frames shall be established for achievement of the targets.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-05' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-08-D1', 'Win_calc = sum_rows(water_streams, if(role IN {''wd'', ''r_other_source''}, volume_m3, 0))', ARRAY['water_streams']::text[], 'Win_calc', 'm³', 'Annex C, Formula (C.1) / (C.2)', 'Plan 3: Win = WD + R1 + R2 + R3 als Σ der Zeilen mit Eingangsrolle (wd / r_other_source); Zwilling der geprüften Gleichung C.1 (Win, an -09 vererbt, CR-037) — Umstellung STAGED (iso46001-D-13 / R-1).', 'imported_unverified', 'Key AHU air handling unit WWTP wastewater treatment plant
Figure C.1 -- Example of a water balance chart
The water balance can be computed using Formula (C.2). Win = Wout
WD + R1 + R2 + R3 = O1 + O2 + O3 + O4'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-08' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-08-D2', 'Wout_calc = sum_rows(water_streams, if(role == ''output'', volume_m3, 0))', ARRAY['water_streams']::text[], 'Wout_calc', 'm³', 'Annex C, Formula (C.1) / (C.2)', 'Plan 3: Wout = O1 + O2 + O3 + O4 als Σ der Zeilen mit Rolle output; Zwilling der geprüften Gleichung C.2b (Wout, an -09 vererbt) — Umstellung STAGED (iso46001-D-14 / R-1).', 'imported_unverified', 'Key AHU air handling unit WWTP wastewater treatment plant
Figure C.1 -- Example of a water balance chart
The water balance can be computed using Formula (C.2). Win = Wout
WD + R1 + R2 + R3 = O1 + O2 + O3 + O4'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-08' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-08-D3', 'leak_indicator = sum_rows(water_streams, if(role IN {''wd'', ''r_other_source''}, volume_m3, 0)) - sum_rows(water_streams, if(role == ''output'', volume_m3, 0))', ARRAY['water_streams']::text[], 'leak_indicator', 'm³', 'Annex C, Formula (C.1)', 'Plan 3: Win − Wout („Should total water input exceed total water output, the difference could be due to leaks and uncontrolled losses“); inline über das Register (nie über Win_calc / Wout_calc verkettet); CR-037 → iso46001-G-4.', 'imported_unverified', 'The water balance equation can be represented by Formula (C.1):

Win = Wout

(C.1)

where

Win is total water input; Wout is total water output. Should total water input exceed total water output, the difference could be due to leaks and uncontrolled losses.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-08' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-08-D4', 'plant_recycling_rate_calc = (sum_rows(water_streams, if(role == ''rp'', volume_m3, 0)) + sum_rows(water_streams, if(role == ''rnp'', volume_m3, 0))) / (sum_rows(water_streams, if(role == ''rp'', volume_m3, 0)) + sum_rows(water_streams, if(role == ''rnp'', volume_m3, 0)) + sum_rows(water_streams, if(role == ''wd'', volume_m3, 0))) * 100', ARRAY['water_streams']::text[], 'plant_recycling_rate_calc', '%', 'Annex C, Formula (C.3)', 'Plan 3: Anlagen-/Standort-Recyclingrate (Rp + Rnp) / (Rp + Rnp + WD) × 100 % als Σ über die Rollen rp / rnp / wd („looks at all reused/reclaimed streams within the premises“); Zwilling der geprüften Gleichung C.3 — Umstellung STAGED (iso46001-D-15 / R-1 / G-4).', 'imported_unverified', 'The plant/premises recycling rate (%) calculated by Formula (C.3) looks at all reused/reclaimed streams within the premises.

Rp + Rnp ×100 % Rp + Rnp +WD where

(C.3)

Rp is total reused/recycled water from the process; Rnp is total reused/recycled water not from the process; An example of the plant/premise recycling rate, based on Figure C.2, is illustrated in Formula (C.4).'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-08' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-08-D5', 'process_recycling_rate_calc = sum_rows(water_streams, if(role == ''rp'', volume_m3, 0)) / (sum_rows(water_streams, if(role == ''wp'', volume_m3, 0)) + sum_rows(water_streams, if(role == ''rpp'', volume_m3, 0))) * 100', ARRAY['water_streams']::text[], 'process_recycling_rate_calc', '%', 'Annex C, Formula (C.5)', 'Plan 3: Prozess-Recyclingrate Rp / (Wp + Rpp) × 100 % als Σ über die Rollen rp / wp / rpp („only looks at reused/reclaimed streams within the process“); Zwilling der geprüften Gleichung C.5 — Umstellung STAGED (iso46001-D-16 / R-1 / G-4).', 'imported_unverified', 'The process recycling rate (%) shown in Formula (C.5) only looks at reused/reclaimed streams within the process.

Rp ×100 % Wp + Rpp where

(C.5)

Rp is total reused/recycled water from the process; Wp is incoming water to process; Rpp is reused/ recycled water from process back to process.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-08' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-08-D6', 'water_streams_count = count_rows(water_streams)', ARRAY['water_streams']::text[], 'water_streams_count', NULL, 'Annex C', 'Plan 3: Anzahl der erfassten Ströme / Zähler („it is desirable to measure the amount of water use“); Vorbedingung der STAGED Gates (iso46001-G-4).', 'imported_unverified', 'After carrying out a water use review, an organization should be able to develop its own water balance chart. A water balance chart compares the total water supplied to the site to the actual water use at the equipment and process level. It will allow an organization to identify activities and functions of significant water use and problem areas, including leaks and uncontrolled losses. In order to develop an accurate water balance chart, it is desirable to measure the amount of water use.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-08' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-08-D7', 'recycling_streams_count = count_rows(water_streams, role IN {''rp'', ''rnp'', ''wp'', ''rpp''})', ARRAY['water_streams']::text[], 'recycling_streams_count', NULL, 'Annex C i), Formula (C.3) / (C.5)', 'Plan 3: Anzahl der Recyclingströme (Rollen rp / rnp / wp / rpp) — „the recycling rate if recycling is carried out“; IF-Guard von CR-038 (iso46001-G-4).', 'imported_unverified', 'Besides information on these streams, the water balance chart should also indicate:

i) recycling streams from source to destination and the recycling rate if recycling is carried out;

ii) locations of water meters.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-08' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-08-D8', 'meters_unverified = count_rows(water_streams, meter_verified_on IS NULL)', ARRAY['water_streams']::text[], 'meters_unverified', NULL, 'A.12', 'Plan 3: Ströme ohne dokumentierte Zählerprüfung („verification/validation tests are carried out periodically“); CR-039 (leere Bedingung) → iso46001-G-3.', 'imported_unverified', 'For water meters, the organization should ensure that verification/validation tests are carried out periodically (e.g. once every 5 years) or per frequency recommended by the meter manufacturer or supplier, whichever is more stringent, to ensure the accuracy of water meters (e.g. within ± 3 %). Full documented information of the measurements should be maintained.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-08' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-10-D1', 'nc_count = count_rows(nonconformities)', ARRAY['nonconformities']::text[], 'nc_count', NULL, '§10.1', 'Plan 3: Anzahl der erfassten Nichtkonformitäten („the nature of the nonconformities and any subsequent actions taken“).', 'imported_unverified', 'c) implement any action needed; d) review the effectiveness of any corrective action taken; e) make changes to the water efficiency management system, if necessary. Corrective actions shall be appropriate to the effects of the nonconformities encountered. The organization shall retain documented information as evidence of: 1) the nature of the nonconformities and any subsequent actions taken; 2) the results of any corrective action. NOTE See A.15 for more information.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-10' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
INSERT INTO equations (worksheet_template_id, equation_number, formula, input_symbols, output_symbol, output_unit, clause_reference, description, verification_status, verification_quote)
SELECT w.id, 'ISO-46001-10-D2', 'nc_open = count_rows(nonconformities, closed == false)', ARRAY['nonconformities']::text[], 'nc_open', NULL, '§10.1', 'Plan 3: offene Nichtkonformitäten (closed nicht angekreuzt = offen); Attestierung CR-034 → iso46001-G-5.', 'imported_unverified', 'c) implement any action needed; d) review the effectiveness of any corrective action taken; e) make changes to the water efficiency management system, if necessary. Corrective actions shall be appropriate to the effects of the nonconformities encountered. The organization shall retain documented information as evidence of: 1) the nature of the nonconformities and any subsequent actions taken; 2) the results of any corrective action. NOTE See A.15 for more information.'
FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE w.code = 'ISO-46001-10' AND s.code = 'ISO-46001'
ON CONFLICT (worksheet_template_id, equation_number) DO NOTHING;
COMMIT;
