-- Generated by scripts/regulation-tables/emit-seed-sql.ts — do not hand-edit; regenerate.
BEGIN;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('ISO-59004', 'FDIS 2024', 'S5_2', 'Die sechs Grundsätze der Kreislaufwirtschaft (§5.2.1 – §5.2.6)', '§5.2', 'PDF p.23 (gedruckte S. 16)', ARRAY['principle']::text[], '[{"name":"clause","type":"string"},{"name":"title","type":"string"},{"name":"text","type":"string"}]'::jsonb, 'locked', 'The set of principles given in 5.2, which are interlinked and complementary, should be considered by an
organization to transition towards a circular economy.', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'systems_thinking', '{"principle":"systems_thinking"}'::jsonb, NULL, '§5.2.1 Systemdenken (Systems thinking)', 0, '{"clause":"5.2.1","title":"Systems thinking","text":"Organizations take a life cycle perspective and apply a long-term approach when considering their impacts on environmental, social and economic systems."}'::jsonb, '5.2.1   Systems thinking

Organizations take a life cycle perspective and apply a long-term approach when considering their impacts
on environmental, social and economic systems.' FROM regulation_tables WHERE standard_code = 'ISO-59004' AND edition = 'FDIS 2024' AND table_code = 'S5_2'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'value_creation', '{"principle":"value_creation"}'::jsonb, NULL, '§5.2.2 Wertschöpfung (Value creation)', 1, '{"clause":"5.2.2","title":"Value creation","text":"Organizations recover, retain or add value by providing effective solutions that contribute to socio-economic and environmental value, and use resources in an efficient way."}'::jsonb, '5.2.2   Value creation

Organizations recover, retain or add value by providing effective solutions that contribute to socio-economic
and environmental value, and use resources in an efficient way.                                 e' FROM regulation_tables WHERE standard_code = 'ISO-59004' AND edition = 'FDIS 2024' AND table_code = 'S5_2'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'value_sharing', '{"principle":"value_sharing"}'::jsonb, NULL, '§5.2.3 Wertteilung (Value sharing)', 2, '{"clause":"5.2.3","title":"Value sharing","text":"Organizations collaborate with interested parties along the value chain or value network in an inclusive and equitable way, for the benefit and well-being of society, by sharing the value created with the provision of a solution."}'::jsonb, '5.2.3   Value sharing
                                                                     ar oc
Organizations collaborate with interested parties along the value chain or value network in an inclusive and
equitable way, for the benefit and well-being of society, by sharing the value created with the provision of a


                                                                           ai
solution.' FROM regulation_tables WHERE standard_code = 'ISO-59004' AND edition = 'FDIS 2024' AND table_code = 'S5_2'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'resource_stewardship', '{"principle":"resource_stewardship"}'::jsonb, NULL, '§5.2.4 Ressourcenverantwortung (Resource stewardship)', 3, '{"clause":"5.2.4","title":"Resource stewardship","text":"Organizations manage stocks and flows in a sustainable way including by closing, slowing and narrowing resource flows to contribute to resource accessibility and continued availability for present and future generations and to reduce risks associated with dependence on virgin resources."}'::jsonb, '5.2.4   Resource stewardship

                                                                              n
Organizations manage stocks and flows in a sustainable way including by closing, slowing and narrowing
resource flows to contribute to resource accessibility and continued availability for present and future
generations and to reduce risks associated with dependence on virgin resources.' FROM regulation_tables WHERE standard_code = 'ISO-59004' AND edition = 'FDIS 2024' AND table_code = 'S5_2'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'resource_traceability', '{"principle":"resource_traceability"}'::jsonb, NULL, '§5.2.5 Ressourcenrückverfolgbarkeit (Resource traceability)', 4, '{"clause":"5.2.5","title":"Resource traceability","text":"Organizations collect and maintain data to enable tracking of resources through their value chains and are accountable for sharing relevant information with interested parties."}'::jsonb, '5.2.5   Resource traceability                               M
Organizations collect and maintain data to enable tracking of resources through their value chains and are
                                                   e
accountable for sharing relevant information with interested parties.' FROM regulation_tables WHERE standard_code = 'ISO-59004' AND edition = 'FDIS 2024' AND table_code = 'S5_2'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'ecosystem_resilience', '{"principle":"ecosystem_resilience"}'::jsonb, NULL, '§5.2.6 Ökosystem-Resilienz (Ecosystem resilience)', 5, '{"clause":"5.2.6","title":"Ecosystem resilience","text":"Organizations develop and implement practices and strategies that protect and contribute to the resilience and regeneration of ecosystems and their biodiversity, including preventing harmful losses and releases and taking into account planetary boundaries."}'::jsonb, '5.2.6   Ecosystem resilience
                                  or m
Organizations develop and implement practices and strategies that protect and contribute to the resilience
and regeneration of ecosystems and their biodiversity, including preventing harmful losses and releases and
taking into account planetary boundaries.' FROM regulation_tables WHERE standard_code = 'ISO-59004' AND edition = 'FDIS 2024' AND table_code = 'S5_2'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
COMMIT;
