-- Generated by scripts/regulation-tables/emit-seed-sql.ts — do not hand-edit; regenerate.
BEGIN;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('FLL-Naturteich', '2017', 'TABLE1', 'Naturteich-Typen I–V — Gesamtübersicht (Tab. 1: Bezeichnung, Regenerationsbereich, Durchströmung, Filterbetrieb, Mindestanteil Regenerationsfläche)', '§5, Tab. 1', '22', ARRAY['pool_type']::text[], '[{"name":"regeneration_share_min_pct","type":"number","unit":"%"},{"name":"share_comparator","type":"string"},{"name":"share_printed","type":"string"},{"name":"share_ref","type":"string"},{"name":"flow_type","type":"enum","values":["none","slow","quick","system"]},{"name":"flow_printed","type":"string"},{"name":"filter_operation","type":"string"},{"name":"p_binding_required","type":"boolean"},{"name":"substrate_filter","type":"boolean"},{"name":"hydrobotanical","type":"boolean"},{"name":"regeneration_technique","type":"string"},{"name":"technical_name","type":"string"}]'::jsonb, 'locked', 'Irrespective of the design and/or construction method, natural pool types are distinguished according to the type and scope of technical systems used to achieve a flow through the swim- ming area and regeneration area in accordance with Table 1. — Dimension of the regenera- tion area compared to the total area > 50% > 50% > 30%', 'md_verified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_I', '{"pool_type":"type_I"}'::jsonb, NULL, 'Typ I — ohne Technik zur Wasserreinigung', 0, '{"regeneration_share_min_pct":50,"share_comparator":">","share_printed":"> 50%","share_ref":null,"flow_type":"none","flow_printed":"natural circulation","filter_operation":"no filter","p_binding_required":false,"substrate_filter":false,"hydrobotanical":true,"regeneration_technique":"Hydrobotanical system","technical_name":"without technology for water purification"}'::jsonb, 'Natural pool

Features

Type I Type II Type III Type IV Type V

technical name without technology for  
water purification

with surface water purifi-  
cation

with controlled slow flow

through the substrate fil-  
ter and downstream

P-binding unit (hydrobo-  
tanical system and/or

technical filter)

with controlled quick

flow through the sub-  
strate filter

controlled flow through  
the technical unit

Regeneration area Hydrobotanical system Hydrobotanical system

Substrate filter (usually  
mineral, with or without

plants), hydrobotanical sys-  
tem, technical unit for

phosphor elimination

Substrate filter (usually  
mineral, with or without  
plants)

Carrier material, e.g. plastic  
or mineral medium in a  
technical unit

Functionality, technical features

Flow natural circulation Surface discharge and nat-  
ural circulation

Surface discharge and  
slow controlled flow  
through the regeneration  
area

Surface discharge and  
quick controlled flow  
through the regeneration  
area

Surface discharge and  
quick or slow controlled  
flow through the technical  
unit

Filter operation during  
swimming season no filter no filter, skimmer operation

intermittently intermittent/permanent permanent dependent on system

Relevant water purification  
due to

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion, mechanical filtration,

chemical-physical filter pro-  
cesses, biofilm

mechanical filtration, chem-  
ical-physical filter pro-  
cesses, biofilm

mechanical filtration, chem-  
ical-physical filter pro-  
cesses, biofilm

Dimension of the regenera-  
tion area compared to the

total area

\> 50% \> 50% \> 30%

information on construction  
based on design refer to  
Tab. 5

information on construction  
based on design refer to  
Tab. 6' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE1'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_II', '{"pool_type":"type_II"}'::jsonb, NULL, 'Typ II — mit Oberflächenwasserreinigung', 1, '{"regeneration_share_min_pct":50,"share_comparator":">","share_printed":"> 50%","share_ref":null,"flow_type":"none","flow_printed":"Surface discharge and nat- ural circulation","filter_operation":"no filter, skimmer operation intermittently","p_binding_required":false,"substrate_filter":false,"hydrobotanical":true,"regeneration_technique":"Hydrobotanical system","technical_name":"with surface water purifi- cation"}'::jsonb, 'Natural pool

Features

Type I Type II Type III Type IV Type V

technical name without technology for  
water purification

with surface water purifi-  
cation

with controlled slow flow

through the substrate fil-  
ter and downstream

P-binding unit (hydrobo-  
tanical system and/or

technical filter)

with controlled quick

flow through the sub-  
strate filter

controlled flow through  
the technical unit

Regeneration area Hydrobotanical system Hydrobotanical system

Substrate filter (usually  
mineral, with or without

plants), hydrobotanical sys-  
tem, technical unit for

phosphor elimination

Substrate filter (usually  
mineral, with or without  
plants)

Carrier material, e.g. plastic  
or mineral medium in a  
technical unit

Functionality, technical features

Flow natural circulation Surface discharge and nat-  
ural circulation

Surface discharge and  
slow controlled flow  
through the regeneration  
area

Surface discharge and  
quick controlled flow  
through the regeneration  
area

Surface discharge and  
quick or slow controlled  
flow through the technical  
unit

Filter operation during  
swimming season no filter no filter, skimmer operation

intermittently intermittent/permanent permanent dependent on system

Relevant water purification  
due to

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion, mechanical filtration,

chemical-physical filter pro-  
cesses, biofilm

mechanical filtration, chem-  
ical-physical filter pro-  
cesses, biofilm

mechanical filtration, chem-  
ical-physical filter pro-  
cesses, biofilm

Dimension of the regenera-  
tion area compared to the

total area

\> 50% \> 50% \> 30%

information on construction  
based on design refer to  
Tab. 5

information on construction  
based on design refer to  
Tab. 6' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE1'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_III', '{"pool_type":"type_III"}'::jsonb, NULL, 'Typ III — langsam durchströmter Substratfilter mit nachgeschalteter P-Bindung', 2, '{"regeneration_share_min_pct":30,"share_comparator":">","share_printed":"> 30%","share_ref":null,"flow_type":"slow","flow_printed":"Surface discharge and slow controlled flow through the regeneration area","filter_operation":"intermittent/permanent","p_binding_required":true,"substrate_filter":true,"hydrobotanical":true,"regeneration_technique":"Substrate filter (usually mineral, with or without plants), hydrobotanical sys- tem, technical unit for phosphor elimination","technical_name":"with controlled slow flow through the substrate fil- ter and downstream P-binding unit (hydrobo- tanical system and/or technical filter)"}'::jsonb, 'Natural pool

Features

Type I Type II Type III Type IV Type V

technical name without technology for  
water purification

with surface water purifi-  
cation

with controlled slow flow

through the substrate fil-  
ter and downstream

P-binding unit (hydrobo-  
tanical system and/or

technical filter)

with controlled quick

flow through the sub-  
strate filter

controlled flow through  
the technical unit

Regeneration area Hydrobotanical system Hydrobotanical system

Substrate filter (usually  
mineral, with or without

plants), hydrobotanical sys-  
tem, technical unit for

phosphor elimination

Substrate filter (usually  
mineral, with or without  
plants)

Carrier material, e.g. plastic  
or mineral medium in a  
technical unit

Functionality, technical features

Flow natural circulation Surface discharge and nat-  
ural circulation

Surface discharge and  
slow controlled flow  
through the regeneration  
area

Surface discharge and  
quick controlled flow  
through the regeneration  
area

Surface discharge and  
quick or slow controlled  
flow through the technical  
unit

Filter operation during  
swimming season no filter no filter, skimmer operation

intermittently intermittent/permanent permanent dependent on system

Relevant water purification  
due to

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion, mechanical filtration,

chemical-physical filter pro-  
cesses, biofilm

mechanical filtration, chem-  
ical-physical filter pro-  
cesses, biofilm

mechanical filtration, chem-  
ical-physical filter pro-  
cesses, biofilm

Dimension of the regenera-  
tion area compared to the

total area

\> 50% \> 50% \> 30%

information on construction  
based on design refer to  
Tab. 5

information on construction  
based on design refer to  
Tab. 6' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE1'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_IV', '{"pool_type":"type_IV"}'::jsonb, NULL, 'Typ IV — schnell durchströmter Substratfilter', 3, '{"regeneration_share_min_pct":null,"share_comparator":null,"share_printed":"information on construction based on design refer to Tab. 5","share_ref":"Tab. 5","flow_type":"quick","flow_printed":"Surface discharge and quick controlled flow through the regeneration area","filter_operation":"permanent","p_binding_required":false,"substrate_filter":true,"hydrobotanical":false,"regeneration_technique":"Substrate filter (usually mineral, with or without plants)","technical_name":"with controlled quick flow through the sub- strate filter"}'::jsonb, 'Natural pool

Features

Type I Type II Type III Type IV Type V

technical name without technology for  
water purification

with surface water purifi-  
cation

with controlled slow flow

through the substrate fil-  
ter and downstream

P-binding unit (hydrobo-  
tanical system and/or

technical filter)

with controlled quick

flow through the sub-  
strate filter

controlled flow through  
the technical unit

Regeneration area Hydrobotanical system Hydrobotanical system

Substrate filter (usually  
mineral, with or without

plants), hydrobotanical sys-  
tem, technical unit for

phosphor elimination

Substrate filter (usually  
mineral, with or without  
plants)

Carrier material, e.g. plastic  
or mineral medium in a  
technical unit

Functionality, technical features

Flow natural circulation Surface discharge and nat-  
ural circulation

Surface discharge and  
slow controlled flow  
through the regeneration  
area

Surface discharge and  
quick controlled flow  
through the regeneration  
area

Surface discharge and  
quick or slow controlled  
flow through the technical  
unit

Filter operation during  
swimming season no filter no filter, skimmer operation

intermittently intermittent/permanent permanent dependent on system

Relevant water purification  
due to

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion, mechanical filtration,

chemical-physical filter pro-  
cesses, biofilm

mechanical filtration, chem-  
ical-physical filter pro-  
cesses, biofilm

mechanical filtration, chem-  
ical-physical filter pro-  
cesses, biofilm

Dimension of the regenera-  
tion area compared to the

total area

\> 50% \> 50% \> 30%

information on construction  
based on design refer to  
Tab. 5

information on construction  
based on design refer to  
Tab. 6' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE1'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_V', '{"pool_type":"type_V"}'::jsonb, NULL, 'Typ V — durchströmte technische Einheit', 4, '{"regeneration_share_min_pct":null,"share_comparator":null,"share_printed":"information on construction based on design refer to Tab. 6","share_ref":"Tab. 6","flow_type":"system","flow_printed":"Surface discharge and quick or slow controlled flow through the technical unit","filter_operation":"dependent on system","p_binding_required":false,"substrate_filter":false,"hydrobotanical":false,"regeneration_technique":"Carrier material, e.g. plastic or mineral medium in a technical unit","technical_name":"controlled flow through the technical unit"}'::jsonb, 'Natural pool

Features

Type I Type II Type III Type IV Type V

technical name without technology for  
water purification

with surface water purifi-  
cation

with controlled slow flow

through the substrate fil-  
ter and downstream

P-binding unit (hydrobo-  
tanical system and/or

technical filter)

with controlled quick

flow through the sub-  
strate filter

controlled flow through  
the technical unit

Regeneration area Hydrobotanical system Hydrobotanical system

Substrate filter (usually  
mineral, with or without

plants), hydrobotanical sys-  
tem, technical unit for

phosphor elimination

Substrate filter (usually  
mineral, with or without  
plants)

Carrier material, e.g. plastic  
or mineral medium in a  
technical unit

Functionality, technical features

Flow natural circulation Surface discharge and nat-  
ural circulation

Surface discharge and  
slow controlled flow  
through the regeneration  
area

Surface discharge and  
quick controlled flow  
through the regeneration  
area

Surface discharge and  
quick or slow controlled  
flow through the technical  
unit

Filter operation during  
swimming season no filter no filter, skimmer operation

intermittently intermittent/permanent permanent dependent on system

Relevant water purification  
due to

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion

Macrophytes, zooplankton,

phytoplankton, sedimenta-  
tion, mechanical filtration,

chemical-physical filter pro-  
cesses, biofilm

mechanical filtration, chem-  
ical-physical filter pro-  
cesses, biofilm

mechanical filtration, chem-  
ical-physical filter pro-  
cesses, biofilm

Dimension of the regenera-  
tion area compared to the

total area

\> 50% \> 50% \> 30%

information on construction  
based on design refer to  
Tab. 5

information on construction  
based on design refer to  
Tab. 6' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE1'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
UPDATE regulation_tables SET verification_status = 'md_verified' WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE1' AND verification_status = 'imported_unverified';
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('FLL-Naturteich', '2017', 'TABLE2_SUBMERGED', 'Anteil des submersen hydrobotanischen Systems am Regenerationsbereich (Tab. 2 / Tab. 3: Typ I / II "therefrom at least half")', '§5, Tab. 2 / Tab. 3', '23–24', ARRAY['pool_type']::text[], '[{"name":"regeneration_share_min_pct","type":"number","unit":"%"},{"name":"submerged_share_of_regeneration_min_pct","type":"number","unit":"%"},{"name":"printed","type":"string"}]'::jsonb, 'locked', 'Biological characteristics Regeneration area in % of the total water area', 'md_verified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_I', '{"pool_type":"type_I"}'::jsonb, NULL, 'Typ I (Tab. 2): > 50 %, davon mindestens die Hälfte als submerses hydrobotanisches System', 0, '{"regeneration_share_min_pct":50,"submerged_share_of_regeneration_min_pct":50,"printed":"> 50% therefrom at least half as submerged hydrobotanical system"}'::jsonb, '\> 50%  
therefrom at least half as  
submerged hydrobotanical  
system' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE2_SUBMERGED'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_II', '{"pool_type":"type_II"}'::jsonb, NULL, 'Typ II (Tab. 3): > 50 %, davon mindestens die Hälfte als submerses hydrobotanisches System', 1, '{"regeneration_share_min_pct":50,"submerged_share_of_regeneration_min_pct":50,"printed":"> 50% therefrom at least half as submerged hydrobotanical system"}'::jsonb, '\> 50%  
therefrom at least half as  
submerged hydrobotanical  
system' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE2_SUBMERGED'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
UPDATE regulation_tables SET verification_status = 'md_verified' WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE2_SUBMERGED' AND verification_status = 'imported_unverified';
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('FLL-Naturteich', '2017', 'TABLE7', 'Richtwerte Füllwasser — ggf. nach Aufbereitung (Tab. 7)', '§7.1.1, Tab. 7', '33', ARRAY['source']::text[], '[{"name":"ammonium_max","type":"number","unit":"mg/l"},{"name":"iron_max","type":"number","unit":"mg/l"},{"name":"p_total_max","type":"number","unit":"mg/l"},{"name":"hardness_min","type":"number","unit":"mmol/l"},{"name":"hardness_min_dh","type":"number","unit":"°dH"},{"name":"conductivity_max","type":"number","unit":"μS/cm"},{"name":"manganese_max","type":"number","unit":"mg/l"},{"name":"nitrate_max","type":"number","unit":"mg/l"},{"name":"orthophosphate_max","type":"number","unit":"mg/l"},{"name":"ph_min","type":"number","unit":"-"},{"name":"ph_max","type":"number","unit":"-"},{"name":"acid_capacity_min","type":"number","unit":"mmol/l"},{"name":"acid_capacity_min_dh","type":"number","unit":"°dH"},{"name":"printed","type":"string"}]'::jsonb, 'anhaltswert', 'Table 7: Approximate chemical values for the fill-up water – if applicable, after purification — If the analysis results deviate from the approximate values, the biological processes must be observed and if applicable, an advanced total water analysis must be implemented and re- spective measures taken. Temporary fluctuations (e.g. due to environmental influences) can occur.', 'md_verified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'all', '{"source":"all"}'::jsonb, NULL, 'Füllwasser (Tab. 7) — alle Quellen (Leitungs-, Brunnen-, Regenwasser)', 0, '{"ammonium_max":0.5,"iron_max":0.2,"p_total_max":0.03,"hardness_min":1,"hardness_min_dh":5.6,"conductivity_max":1000,"manganese_max":0.05,"nitrate_max":50,"orthophosphate_max":0.01,"ph_min":6,"ph_max":9,"acid_capacity_min":2,"acid_capacity_min_dh":5.6,"printed":"Ammonium ≤ 0.5 mg/l · Iron ≤ 0.2 mg/l · Total phosphorus [Ptotal] ≤ 0.03 mg/l · ≥ 1.0 mmol/l ≥ 5.6 dH° · Conductivity ≤ 1000 μS/cm at 20°C · Manganese ≤ 0.05 mg/l · Nitrate ≤ 50.0 mg/l · Orthophosphate (indicated as P) ≤ 0.01 mg/l · pH value 6.0 – 9.0 · ≥ 2 mmol/l ≥ 5.6 dH°"}'::jsonb, 'No.

Parameters Values  
1 2  
1 1Ammonium ≤ 0.5 mg/l  
2 2Iron ≤ 0.2 mg/l  
3 3Total phosphorus \[Ptotal\] ≤ 0.03 mg/l  
4 4  
Hardness (total alkaline earth)  
Corresponds to total hardness

≥ 1.0 mmol/l  
≥ 5.6 dH°

5 5Conductivity ≤ 1000 μS/cm at 20°C  
6 6Manganese ≤ 0.05 mg/l  
7 7Nitrate ≤ 50.0 mg/l  
8 Orthophosphate (indicated as P) ≤ 0.01 mg/l  
9 8pH value 6.0 – 9.0  
10 9  
Acid capacity KS 4.3  
Corresponds to carbon hardness

≥ 2 mmol/l  
≥ 5.6 dH°

Reference method refer to Appendix 1\.' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE7'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
UPDATE regulation_tables SET verification_status = 'md_verified' WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE7' AND verification_status = 'imported_unverified';
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('FLL-Naturteich', '2017', 'TABLE8', 'Richtwerte Schwimmbereich — typunabhängige Parameter (Tab. 8)', '§7.1.2, Tab. 8', '33', ARRAY['source']::text[], '[{"name":"ammonium_max","type":"number","unit":"mg/l"},{"name":"hardness_min","type":"number","unit":"mmol/l"},{"name":"hardness_min_dh","type":"number","unit":"°dH"},{"name":"conductivity_max","type":"number","unit":"μS/cm"},{"name":"nitrate_max","type":"number","unit":"mg/l"},{"name":"nitrite_max","type":"number","unit":"mg/l"},{"name":"ph_min","type":"number","unit":"-"},{"name":"ph_max","type":"number","unit":"-"},{"name":"acid_capacity_min","type":"number","unit":"mmol/l"},{"name":"acid_capacity_min_dh","type":"number","unit":"°dH"},{"name":"printed","type":"string"}]'::jsonb, 'anhaltswert', 'Table 8: Approximate chemical values for the swimming area — If the analysis results deviate from the approximate values, the biological processes must be observed and if applicable, an advanced total water analysis must be implemented and re- spective measures taken. Temporary fluctuations (e.g. due to environmental influences) can occur.', 'md_verified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'all', '{"source":"all"}'::jsonb, NULL, 'Schwimmbereich (Tab. 8) — typunabhängige Parameter', 0, '{"ammonium_max":0.3,"hardness_min":1,"hardness_min_dh":5.6,"conductivity_max":1000,"nitrate_max":30,"nitrite_max":0.01,"ph_min":7,"ph_max":9,"acid_capacity_min":2,"acid_capacity_min_dh":5.6,"printed":"Ammonium ≤ 0.3 mg/l · ≥ 1.0 mmol/l ≥ 5.6 dH° · Conductivity ≤ 1000 μS/cm at 20°C · Nitrate ≤ 30.0 mg/l · Nitrite ≤ 0.01 mg/l · pH value 7.0 – 9.0 · ≥ 2 mmol/l ≥ 5.6 dH°"}'::jsonb, 'No.

Parameters Values  
1 2  
1 1Ammonium ≤ 0.3 mg/l  
2 2Total phosphorus \[Ptotal\]

≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

3 3  
Hardness (total alkaline earth)  
Corresponds to total hardness

≥ 1.0 mmol/l  
≥ 5.6 dH°

4 4Conductivity ≤ 1000 μS/cm at 20°C  
5 5Nitrate ≤ 30.0 mg/l  
6 6Nitrite ≤ 0.01 mg/l  
7 Orthophosphate (indicated as P) ≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

8 7pH value 7.0 – 9.0  
9 8  
Acid capacity KS 4.3  
Corresponds to carbon hardness

≥ 2 mmol/l  
≥ 5.6 dH°

Reference method refer to Appendix 1\.' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE8'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
UPDATE regulation_tables SET verification_status = 'md_verified' WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE8' AND verification_status = 'imported_unverified';
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('FLL-Naturteich', '2017', 'TABLE8_P', 'Richtwerte Schwimmbereich — Gesamtphosphor und Orthophosphat je Naturteich-Typ (Tab. 8)', '§7.1.2, Tab. 8', '33', ARRAY['pool_type']::text[], '[{"name":"p_total_max","type":"number","unit":"mg/l"},{"name":"orthophosphate_max","type":"number","unit":"mg/l"},{"name":"printed","type":"string"}]'::jsonb, 'anhaltswert', 'Table 8: Approximate chemical values for the swimming area — If the analysis results deviate from the approximate values, the biological processes must be observed and if applicable, an advanced total water analysis must be implemented and re- spective measures taken. Temporary fluctuations (e.g. due to environmental influences) can occur.', 'md_verified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_I', '{"pool_type":"type_I"}'::jsonb, NULL, 'Typ I — P_total / Orthophosphat ≤ 0.03 mg/l (type I-III)', 0, '{"p_total_max":0.03,"orthophosphate_max":0.03,"printed":"≤ 0.03 mg/l (type I-III)"}'::jsonb, 'No.

Parameters Values  
1 2  
1 1Ammonium ≤ 0.3 mg/l  
2 2Total phosphorus \[Ptotal\]

≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

3 3  
Hardness (total alkaline earth)  
Corresponds to total hardness

≥ 1.0 mmol/l  
≥ 5.6 dH°

4 4Conductivity ≤ 1000 μS/cm at 20°C  
5 5Nitrate ≤ 30.0 mg/l  
6 6Nitrite ≤ 0.01 mg/l  
7 Orthophosphate (indicated as P) ≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

8 7pH value 7.0 – 9.0  
9 8  
Acid capacity KS 4.3  
Corresponds to carbon hardness

≥ 2 mmol/l  
≥ 5.6 dH°

Reference method refer to Appendix 1\.' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE8_P'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_II', '{"pool_type":"type_II"}'::jsonb, NULL, 'Typ II — P_total / Orthophosphat ≤ 0.03 mg/l (type I-III)', 1, '{"p_total_max":0.03,"orthophosphate_max":0.03,"printed":"≤ 0.03 mg/l (type I-III)"}'::jsonb, 'No.

Parameters Values  
1 2  
1 1Ammonium ≤ 0.3 mg/l  
2 2Total phosphorus \[Ptotal\]

≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

3 3  
Hardness (total alkaline earth)  
Corresponds to total hardness

≥ 1.0 mmol/l  
≥ 5.6 dH°

4 4Conductivity ≤ 1000 μS/cm at 20°C  
5 5Nitrate ≤ 30.0 mg/l  
6 6Nitrite ≤ 0.01 mg/l  
7 Orthophosphate (indicated as P) ≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

8 7pH value 7.0 – 9.0  
9 8  
Acid capacity KS 4.3  
Corresponds to carbon hardness

≥ 2 mmol/l  
≥ 5.6 dH°

Reference method refer to Appendix 1\.' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE8_P'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_III', '{"pool_type":"type_III"}'::jsonb, NULL, 'Typ III — P_total / Orthophosphat ≤ 0.03 mg/l (type I-III)', 2, '{"p_total_max":0.03,"orthophosphate_max":0.03,"printed":"≤ 0.03 mg/l (type I-III)"}'::jsonb, 'No.

Parameters Values  
1 2  
1 1Ammonium ≤ 0.3 mg/l  
2 2Total phosphorus \[Ptotal\]

≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

3 3  
Hardness (total alkaline earth)  
Corresponds to total hardness

≥ 1.0 mmol/l  
≥ 5.6 dH°

4 4Conductivity ≤ 1000 μS/cm at 20°C  
5 5Nitrate ≤ 30.0 mg/l  
6 6Nitrite ≤ 0.01 mg/l  
7 Orthophosphate (indicated as P) ≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

8 7pH value 7.0 – 9.0  
9 8  
Acid capacity KS 4.3  
Corresponds to carbon hardness

≥ 2 mmol/l  
≥ 5.6 dH°

Reference method refer to Appendix 1\.' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE8_P'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_IV', '{"pool_type":"type_IV"}'::jsonb, NULL, 'Typ IV — P_total / Orthophosphat ≤ 0.01 mg/l (type IV, V)', 3, '{"p_total_max":0.01,"orthophosphate_max":0.01,"printed":"≤ 0.01 mg/l (type IV, V)"}'::jsonb, 'No.

Parameters Values  
1 2  
1 1Ammonium ≤ 0.3 mg/l  
2 2Total phosphorus \[Ptotal\]

≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

3 3  
Hardness (total alkaline earth)  
Corresponds to total hardness

≥ 1.0 mmol/l  
≥ 5.6 dH°

4 4Conductivity ≤ 1000 μS/cm at 20°C  
5 5Nitrate ≤ 30.0 mg/l  
6 6Nitrite ≤ 0.01 mg/l  
7 Orthophosphate (indicated as P) ≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

8 7pH value 7.0 – 9.0  
9 8  
Acid capacity KS 4.3  
Corresponds to carbon hardness

≥ 2 mmol/l  
≥ 5.6 dH°

Reference method refer to Appendix 1\.' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE8_P'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'type_V', '{"pool_type":"type_V"}'::jsonb, NULL, 'Typ V — P_total / Orthophosphat ≤ 0.01 mg/l (type IV, V)', 4, '{"p_total_max":0.01,"orthophosphate_max":0.01,"printed":"≤ 0.01 mg/l (type IV, V)"}'::jsonb, 'No.

Parameters Values  
1 2  
1 1Ammonium ≤ 0.3 mg/l  
2 2Total phosphorus \[Ptotal\]

≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

3 3  
Hardness (total alkaline earth)  
Corresponds to total hardness

≥ 1.0 mmol/l  
≥ 5.6 dH°

4 4Conductivity ≤ 1000 μS/cm at 20°C  
5 5Nitrate ≤ 30.0 mg/l  
6 6Nitrite ≤ 0.01 mg/l  
7 Orthophosphate (indicated as P) ≤ 0.03 mg/l (type I-III)  
≤ 0.01 mg/l (type IV, V)

8 7pH value 7.0 – 9.0  
9 8  
Acid capacity KS 4.3  
Corresponds to carbon hardness

≥ 2 mmol/l  
≥ 5.6 dH°

Reference method refer to Appendix 1\.' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE8_P'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
UPDATE regulation_tables SET verification_status = 'md_verified' WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE8_P' AND verification_status = 'imported_unverified';
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('FLL-Naturteich', '2017', 'TABLE9', 'Anforderungen an Filter- und Pflanzsubstrate (Tab. 9)', '§7.2.3, Tab. 9', '35', ARRAY['substrate_role']::text[], '[{"name":"grain_max_mm","type":"number","unit":"mm"},{"name":"oversize_max_pct","type":"number","unit":"% by weight"},{"name":"fines_max_pct","type":"number","unit":"% by weight"},{"name":"kf_min","type":"number","unit":"m/s"},{"name":"frost_resistance_required","type":"boolean"},{"name":"frost_printed","type":"string"},{"name":"elutable_p_max","type":"number","unit":"mg P/kg"},{"name":"column_head","type":"string"}]'::jsonb, 'locked', 'The percentage of oversized grain must not exceed 15% by weight. Filter substrates that are used in controlled quick flow through filter bodies (natural pool type IV) should indicate a silt and clay percentage (< 0.063 mm) of ≤ 0.5% by weight; a threshold value of ≤ 2% by weight applies here for all other filter substrates. The level of elutable phosphorus should not exceed 5 mg P/kg.', 'md_verified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'filter_iii', '{"substrate_role":"filter_iii"}'::jsonb, NULL, 'Filtersubstrat Naturteich-Typ III', 0, '{"grain_max_mm":16,"oversize_max_pct":15,"fines_max_pct":2,"kf_min":0.0001,"frost_resistance_required":true,"frost_printed":"is mandatory","elutable_p_max":5,"column_head":"Filter substrate natu- ral pool type III"}'::jsonb, 'Substrate  
type

Parameters

Filter substrate natu-  
ral pool type III

Filter substrate natu-  
ral pool type IV

Plant substrate

Recommended maxi-  
mum grain size 16 mm 32 mm 8 mm

Oversized grain per-  
centage (opening in

per cent weight per  
cent)

≤ 15% by weight ≤ 15% by weight no requirement

Percentage of elutri-  
ated parts (\< 0.063

mm)

≤ 2% by weight ≤ 0.5% by weight no requirement

Permeability coeffi-  
cient ≥ 10-4 m/s ≥ 10-3 m/s no requirement

Frost resistance is mandatory is mandatory no requirement  
Elutable phosphorus  
level ≤ 5 mg P/kg ≤ 5 mg P/kg no requirement  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE9'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'filter_iv', '{"substrate_role":"filter_iv"}'::jsonb, NULL, 'Filtersubstrat Naturteich-Typ IV', 1, '{"grain_max_mm":32,"oversize_max_pct":15,"fines_max_pct":0.5,"kf_min":0.001,"frost_resistance_required":true,"frost_printed":"is mandatory","elutable_p_max":5,"column_head":"Filter substrate natu- ral pool type IV"}'::jsonb, 'Substrate  
type

Parameters

Filter substrate natu-  
ral pool type III

Filter substrate natu-  
ral pool type IV

Plant substrate

Recommended maxi-  
mum grain size 16 mm 32 mm 8 mm

Oversized grain per-  
centage (opening in

per cent weight per  
cent)

≤ 15% by weight ≤ 15% by weight no requirement

Percentage of elutri-  
ated parts (\< 0.063

mm)

≤ 2% by weight ≤ 0.5% by weight no requirement

Permeability coeffi-  
cient ≥ 10-4 m/s ≥ 10-3 m/s no requirement

Frost resistance is mandatory is mandatory no requirement  
Elutable phosphorus  
level ≤ 5 mg P/kg ≤ 5 mg P/kg no requirement  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE9'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'plant', '{"substrate_role":"plant"}'::jsonb, NULL, 'Pflanzsubstrat', 2, '{"grain_max_mm":8,"oversize_max_pct":null,"fines_max_pct":null,"kf_min":null,"frost_resistance_required":false,"frost_printed":"no requirement","elutable_p_max":null,"column_head":"Plant substrate"}'::jsonb, 'Substrate  
type

Parameters

Filter substrate natu-  
ral pool type III

Filter substrate natu-  
ral pool type IV

Plant substrate

Recommended maxi-  
mum grain size 16 mm 32 mm 8 mm

Oversized grain per-  
centage (opening in

per cent weight per  
cent)

≤ 15% by weight ≤ 15% by weight no requirement

Percentage of elutri-  
ated parts (\< 0.063

mm)

≤ 2% by weight ≤ 0.5% by weight no requirement

Permeability coeffi-  
cient ≥ 10-4 m/s ≥ 10-3 m/s no requirement

Frost resistance is mandatory is mandatory no requirement  
Elutable phosphorus  
level ≤ 5 mg P/kg ≤ 5 mg P/kg no requirement  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE9'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
UPDATE regulation_tables SET verification_status = 'md_verified' WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE9' AND verification_status = 'imported_unverified';
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('FLL-Naturteich', '2017', 'TABLE10', 'Bauliche Anforderungen an hydrobotanische Systeme (Tab. 10)', '§10.2.1, Tab. 10', '47', ARRAY['hydrobot_type']::text[], '[{"name":"water_column_min_cm","type":"number","unit":"cm"},{"name":"water_column_max_cm","type":"number","unit":"cm"},{"name":"substrate_min_cm","type":"number","unit":"cm"},{"name":"substrate_max_cm","type":"number","unit":"cm"},{"name":"grain_max_mm","type":"number","unit":"mm"},{"name":"feed_rate_qmax","type":"number","unit":"m³/(m²·d)"},{"name":"printed","type":"string"}]'::jsonb, 'locked', 'Table 10: Structural requirements for hydrobotanical systems — There must be a flow in supplementary hydrobotanical systems in natural pool type IV; these systems are not taken into account for the dimensioning of the water purification system. Please refer to Table 10 for information on the requirements.', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'submergent', '{"hydrobot_type":"submergent"}'::jsonb, NULL, 'submergent (submerse Hydrophyten)', 0, '{"water_column_min_cm":80,"water_column_max_cm":null,"substrate_min_cm":10,"substrate_max_cm":20,"grain_max_mm":8,"feed_rate_qmax":5,"printed":"≥ 80 cm · 10 – 20 cm · ≤ 8 mm · 5 m3/(m2 x day)"}'::jsonb, 'No.

Regenera-  
tion

tech-  
nique

Parameters

Hydrobotanical systems  
submergent Emersed

1

2 3

1 Construction  
2 Water column height ≥ 80 cm 10 – 50 cm  
3 Thickness of substrate layer 10 – 20 cm 10 – 30 cm  
4 Substrate requirement

5 Grain size range1  
)  
Location  
of the  
plant

≤ 8 mm

Filters — —  
6 Oversized grain (filter) — —  
7 Percentage of elutriated parts —  
8 Frost resistance —  
9 Substrate properties unharmful  
to plants

• free of substances harmful to plants  
• no negative interaction between substrate and plant  
• easy root penetration

10 Tolerances  
11 Layer thickness tolerance — —  
12 Feed rate Qmax 5 m3/(m2 x day) 5 m3/(m2 x day)  
1\) The grain distribution curve of the substrate can deviate from the information in the table if the listed properties  
or requirements are not decisively influenced by therefrom.  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE10'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'emersed', '{"hydrobot_type":"emersed"}'::jsonb, NULL, 'Emersed (Helophyten)', 1, '{"water_column_min_cm":10,"water_column_max_cm":50,"substrate_min_cm":10,"substrate_max_cm":30,"grain_max_mm":8,"feed_rate_qmax":5,"printed":"10 – 50 cm · 10 – 30 cm · ≤ 8 mm · 5 m3/(m2 x day)"}'::jsonb, 'No.

Regenera-  
tion

tech-  
nique

Parameters

Hydrobotanical systems  
submergent Emersed

1

2 3

1 Construction  
2 Water column height ≥ 80 cm 10 – 50 cm  
3 Thickness of substrate layer 10 – 20 cm 10 – 30 cm  
4 Substrate requirement

5 Grain size range1  
)  
Location  
of the  
plant

≤ 8 mm

Filters — —  
6 Oversized grain (filter) — —  
7 Percentage of elutriated parts —  
8 Frost resistance —  
9 Substrate properties unharmful  
to plants

• free of substances harmful to plants  
• no negative interaction between substrate and plant  
• easy root penetration

10 Tolerances  
11 Layer thickness tolerance — —  
12 Feed rate Qmax 5 m3/(m2 x day) 5 m3/(m2 x day)  
1\) The grain distribution curve of the substrate can deviate from the information in the table if the listed properties  
or requirements are not decisively influenced by therefrom.  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE10'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('FLL-Naturteich', '2017', 'TABLE11', 'Bauliche Anforderungen an Substratfilter mit langsamer Durchströmung (Tab. 11)', '§10.2.2, Tab. 11', '50', ARRAY['flow_direction']::text[], '[{"name":"water_column_min_cm","type":"number","unit":"cm"},{"name":"layer_min_cm","type":"number","unit":"cm"},{"name":"grain_max_mm","type":"number","unit":"mm"},{"name":"oversize_max_pct","type":"number","unit":"% by weight"},{"name":"fines_max_pct","type":"number","unit":"% by weight"},{"name":"frost_resistance_required","type":"boolean"},{"name":"kf_min","type":"number","unit":"m/s"},{"name":"tolerance_pct","type":"number","unit":"%"},{"name":"feed_rate_qmax","type":"number","unit":"m³/(m²·d)"},{"name":"individual_verification","type":"boolean"},{"name":"printed","type":"string"}]'::jsonb, 'locked', 'Table 11: Structural requirements for substrate filters with a controlled slow flow — Substrate filters with a controlled slow flow must be equipped with a downstream phosphrous- binding purification stage (submergent hydrobotanical system or adsorbing filter material). Refer to Table 11 for information on the requirements.', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'vertical_continuous_overflow', '{"flow_direction":"vertical_continuous_overflow"}'::jsonb, NULL, 'vertikal durchströmt, kontinuierlicher ganzflächiger Überlauf', 0, '{"water_column_min_cm":10,"layer_min_cm":40,"grain_max_mm":16,"oversize_max_pct":15,"fines_max_pct":2,"frost_resistance_required":true,"kf_min":0.0001,"tolerance_pct":10,"feed_rate_qmax":5,"individual_verification":false,"printed":"≥ 10 cm · ≥ 40 cm · Filters ≤ 16 mm · ≤ 15% by weight · ≤ 2% by weight · is mandatory · 10% deviation · ≥ 10-4 m/s ≥ 10-4 m/s · 5 m3/(m2 x day)"}'::jsonb, 'No.  
Regeneration

tech-  
nique

Parameters

Substrate filter

vertical  
flow,

continuous full-  
surface over-  
flow

vertical  
flow,  
no overflow

horizontal  
flow  
1 2 3 4

1 Construction

2 Water column height ≥ 10 cm — Individual verifica-  
tion

no further  
information

3  
Thickness of the filter-effective  
layer ≥ 40 cm  
4 Substrate requirement  
5 Grain size range1  
)  
Location  
of the  
plant

— —

Individual verifica-  
tion

no further  
information

Filters ≤ 16 mm  
6 Oversized grain (filter) ≤ 15% by weight  
7 Percentage of elutriated parts ≤ 2% by weight  
8 Frost resistance is mandatory  
9  
Substrate properties unharmful  
to plants — —  
10 Tolerances  
11 Layer thickness tolerance 10% deviation

Individual verifica-  
tion

no further  
information

12 Parameters

13 Permeability coefficient ≥ 10-4 m/s ≥ 10-4 m/s Individual verifica-  
tion

no further  
information

14 Feed rate Qmax

5 m3/(m2 x  
day)

8 m3/(m2 x  
day)

1\) The grain distribution curve of the substrate must allow the specified permeability \[permeability coefficient\] to  
be achieved with the specified grain size range. If there is a deviation from the specifications regarding grain  
size range, the permeability coefficient must be maintained continuously and filter stability must be given.  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE11'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'vertical_no_overflow', '{"flow_direction":"vertical_no_overflow"}'::jsonb, NULL, 'vertikal durchströmt, ohne Überlauf', 1, '{"water_column_min_cm":null,"layer_min_cm":40,"grain_max_mm":16,"oversize_max_pct":15,"fines_max_pct":2,"frost_resistance_required":true,"kf_min":0.0001,"tolerance_pct":10,"feed_rate_qmax":8,"individual_verification":false,"printed":"— · ≥ 40 cm · Filters ≤ 16 mm · ≤ 15% by weight · ≤ 2% by weight · is mandatory · 10% deviation · ≥ 10-4 m/s ≥ 10-4 m/s · 8 m3/(m2 x day)"}'::jsonb, 'No.  
Regeneration

tech-  
nique

Parameters

Substrate filter

vertical  
flow,

continuous full-  
surface over-  
flow

vertical  
flow,  
no overflow

horizontal  
flow  
1 2 3 4

1 Construction

2 Water column height ≥ 10 cm — Individual verifica-  
tion

no further  
information

3  
Thickness of the filter-effective  
layer ≥ 40 cm  
4 Substrate requirement  
5 Grain size range1  
)  
Location  
of the  
plant

— —

Individual verifica-  
tion

no further  
information

Filters ≤ 16 mm  
6 Oversized grain (filter) ≤ 15% by weight  
7 Percentage of elutriated parts ≤ 2% by weight  
8 Frost resistance is mandatory  
9  
Substrate properties unharmful  
to plants — —  
10 Tolerances  
11 Layer thickness tolerance 10% deviation

Individual verifica-  
tion

no further  
information

12 Parameters

13 Permeability coefficient ≥ 10-4 m/s ≥ 10-4 m/s Individual verifica-  
tion

no further  
information

14 Feed rate Qmax

5 m3/(m2 x  
day)

8 m3/(m2 x  
day)

1\) The grain distribution curve of the substrate must allow the specified permeability \[permeability coefficient\] to  
be achieved with the specified grain size range. If there is a deviation from the specifications regarding grain  
size range, the permeability coefficient must be maintained continuously and filter stability must be given.  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE11'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'horizontal', '{"flow_direction":"horizontal"}'::jsonb, NULL, 'horizontal durchströmt (Einzelnachweis, keine weiteren Angaben)', 2, '{"water_column_min_cm":null,"layer_min_cm":null,"grain_max_mm":null,"oversize_max_pct":null,"fines_max_pct":null,"frost_resistance_required":null,"kf_min":null,"tolerance_pct":null,"feed_rate_qmax":null,"individual_verification":true,"printed":"Individual verifica- tion no further information"}'::jsonb, 'No.  
Regeneration

tech-  
nique

Parameters

Substrate filter

vertical  
flow,

continuous full-  
surface over-  
flow

vertical  
flow,  
no overflow

horizontal  
flow  
1 2 3 4

1 Construction

2 Water column height ≥ 10 cm — Individual verifica-  
tion

no further  
information

3  
Thickness of the filter-effective  
layer ≥ 40 cm  
4 Substrate requirement  
5 Grain size range1  
)  
Location  
of the  
plant

— —

Individual verifica-  
tion

no further  
information

Filters ≤ 16 mm  
6 Oversized grain (filter) ≤ 15% by weight  
7 Percentage of elutriated parts ≤ 2% by weight  
8 Frost resistance is mandatory  
9  
Substrate properties unharmful  
to plants — —  
10 Tolerances  
11 Layer thickness tolerance 10% deviation

Individual verifica-  
tion

no further  
information

12 Parameters

13 Permeability coefficient ≥ 10-4 m/s ≥ 10-4 m/s Individual verifica-  
tion

no further  
information

14 Feed rate Qmax

5 m3/(m2 x  
day)

8 m3/(m2 x  
day)

1\) The grain distribution curve of the substrate must allow the specified permeability \[permeability coefficient\] to  
be achieved with the specified grain size range. If there is a deviation from the specifications regarding grain  
size range, the permeability coefficient must be maintained continuously and filter stability must be given.  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE11'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('FLL-Naturteich', '2017', 'TABLE12', 'Bauliche Anforderungen an Substratfilter mit schneller Durchströmung (Tab. 12)', '§10.2.3, Tab. 12', '52', ARRAY['flow_direction']::text[], '[{"name":"water_column_min_cm","type":"number","unit":"cm"},{"name":"layer_min_cm","type":"number","unit":"cm"},{"name":"grain_max_mm","type":"number","unit":"mm"},{"name":"oversize_max_pct","type":"number","unit":"% by weight"},{"name":"fines_max_pct","type":"number","unit":"% by weight"},{"name":"frost_resistance_required","type":"boolean"},{"name":"kf_min","type":"number","unit":"m/s"},{"name":"tolerance_pct","type":"number","unit":"%"},{"name":"feed_rate_qmin","type":"number","unit":"m³/(m²·d)"},{"name":"individual_verification","type":"boolean"},{"name":"printed","type":"string"}]'::jsonb, 'locked', 'Table 12: Structural requirements for substrate filters with a controlled quick flow — According to experience, substrate filters with a controlled quick flow must be operated with a feed rate of Qmin ≥ 15 m3/(m2 x day). Smaller feed rates are permissible if the functionality of pool is ensured. Please refer to Table 12 for information on the requirements.', 'imported_unverified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'vertical_continuous_overflow', '{"flow_direction":"vertical_continuous_overflow"}'::jsonb, NULL, 'vertikal durchströmt, kontinuierlicher ganzflächiger Überlauf', 0, '{"water_column_min_cm":0,"layer_min_cm":50,"grain_max_mm":32,"oversize_max_pct":15,"fines_max_pct":0.5,"frost_resistance_required":true,"kf_min":0.001,"tolerance_pct":10,"feed_rate_qmin":15,"individual_verification":false,"printed":"≥ 0 cm · ≥ 50 cm · Filters ≤ 32 mm · ≤ 15% by weight · ≤ 0.5% by weight · is mandatory · 10% deviation · ≥ 10-3 m/s ≥ 10-3 m/s · ≥ 15 m3/(m2 x day) ≥ 15 m3/(m2 x day)"}'::jsonb, '1\) The grain distribution curve of the substrate must allow the specified permeability \[permeability coefficient\] to  
be achieved with the specified grain size range. If there is a deviation from the specifications regarding grain  
size range, the permeability coefficient must be maintained continuously and filter stability must be given.  
No.  
Regeneration  
technique

Parameters

Substrate filter

vertical  
flow,

continuous full-sur-  
face overflow

vertical  
flow,  
no overflow

horizontal  
flow  
1 2 3 4

1 Construction

2 Water column height ≥ 0 cm — Individual verifi-  
cation

no further  
information

3  
Thickness of the filter-effective  
layer ≥ 50 cm  
4 Substrate requirement  
5

Korngrößen-  
bereich1)

Location of  
the plant — —

Individual verifi-  
cation

no further  
information

Filters ≤ 32 mm  
6 Oversized grain (filter) ≤ 15% by weight  
7 Percentage of elutriated parts ≤ 0.5% by weight  
8 Frost resistance is mandatory  
9  
Substrate properties unharmful to  
plants — —  
10 Tolerances  
11 Layer thickness tolerance 10% deviation

Individual verifi-  
cation

no further  
information

12 Parameters

13 Permeability coefficient ≥ 10-3 m/s ≥ 10-3 m/s Individual verifi-  
cation no further

information 14 Feed rate Qmin ≥ 15 m3/(m2 x day) ≥ 15 m3/(m2 x day)  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE12'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'vertical_no_overflow', '{"flow_direction":"vertical_no_overflow"}'::jsonb, NULL, 'vertikal durchströmt, ohne Überlauf', 1, '{"water_column_min_cm":null,"layer_min_cm":50,"grain_max_mm":32,"oversize_max_pct":15,"fines_max_pct":0.5,"frost_resistance_required":true,"kf_min":0.001,"tolerance_pct":10,"feed_rate_qmin":15,"individual_verification":false,"printed":"— · ≥ 50 cm · Filters ≤ 32 mm · ≤ 15% by weight · ≤ 0.5% by weight · is mandatory · 10% deviation · ≥ 10-3 m/s ≥ 10-3 m/s · ≥ 15 m3/(m2 x day) ≥ 15 m3/(m2 x day)"}'::jsonb, '1\) The grain distribution curve of the substrate must allow the specified permeability \[permeability coefficient\] to  
be achieved with the specified grain size range. If there is a deviation from the specifications regarding grain  
size range, the permeability coefficient must be maintained continuously and filter stability must be given.  
No.  
Regeneration  
technique

Parameters

Substrate filter

vertical  
flow,

continuous full-sur-  
face overflow

vertical  
flow,  
no overflow

horizontal  
flow  
1 2 3 4

1 Construction

2 Water column height ≥ 0 cm — Individual verifi-  
cation

no further  
information

3  
Thickness of the filter-effective  
layer ≥ 50 cm  
4 Substrate requirement  
5

Korngrößen-  
bereich1)

Location of  
the plant — —

Individual verifi-  
cation

no further  
information

Filters ≤ 32 mm  
6 Oversized grain (filter) ≤ 15% by weight  
7 Percentage of elutriated parts ≤ 0.5% by weight  
8 Frost resistance is mandatory  
9  
Substrate properties unharmful to  
plants — —  
10 Tolerances  
11 Layer thickness tolerance 10% deviation

Individual verifi-  
cation

no further  
information

12 Parameters

13 Permeability coefficient ≥ 10-3 m/s ≥ 10-3 m/s Individual verifi-  
cation no further

information 14 Feed rate Qmin ≥ 15 m3/(m2 x day) ≥ 15 m3/(m2 x day)  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE12'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'horizontal', '{"flow_direction":"horizontal"}'::jsonb, NULL, 'horizontal durchströmt (Einzelnachweis, keine weiteren Angaben)', 2, '{"water_column_min_cm":null,"layer_min_cm":null,"grain_max_mm":null,"oversize_max_pct":null,"fines_max_pct":null,"frost_resistance_required":null,"kf_min":null,"tolerance_pct":null,"feed_rate_qmin":null,"individual_verification":true,"printed":"Individual verifi- cation no further information"}'::jsonb, '1\) The grain distribution curve of the substrate must allow the specified permeability \[permeability coefficient\] to  
be achieved with the specified grain size range. If there is a deviation from the specifications regarding grain  
size range, the permeability coefficient must be maintained continuously and filter stability must be given.  
No.  
Regeneration  
technique

Parameters

Substrate filter

vertical  
flow,

continuous full-sur-  
face overflow

vertical  
flow,  
no overflow

horizontal  
flow  
1 2 3 4

1 Construction

2 Water column height ≥ 0 cm — Individual verifi-  
cation

no further  
information

3  
Thickness of the filter-effective  
layer ≥ 50 cm  
4 Substrate requirement  
5

Korngrößen-  
bereich1)

Location of  
the plant — —

Individual verifi-  
cation

no further  
information

Filters ≤ 32 mm  
6 Oversized grain (filter) ≤ 15% by weight  
7 Percentage of elutriated parts ≤ 0.5% by weight  
8 Frost resistance is mandatory  
9  
Substrate properties unharmful to  
plants — —  
10 Tolerances  
11 Layer thickness tolerance 10% deviation

Individual verifi-  
cation

no further  
information

12 Parameters

13 Permeability coefficient ≥ 10-3 m/s ≥ 10-3 m/s Individual verifi-  
cation no further

information 14 Feed rate Qmin ≥ 15 m3/(m2 x day) ≥ 15 m3/(m2 x day)  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE12'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('FLL-Naturteich', '2017', 'TABLE15', 'Korngrößen – Oberflächen (Tab. 15, Dolomitkies): Porenwasser und besiedelbare Oberfläche je Kornklasse', 'Appendix 5, Tab. 15', '83', ARRAY['grain_class']::text[], '[{"name":"pore_water_pct","type":"number","unit":"%"},{"name":"surface_m2_m3","type":"number","unit":"m²/m³"},{"name":"grain_printed","type":"string"}]'::jsonb, 'anhaltswert', 'The values were determined using dolomite gravel — Size of the grain surface depends on its composition of grain sizes', 'md_verified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, '4_6', '{"grain_class":"4_6"}'::jsonb, NULL, 'Korn 4/6 mm', 0, '{"pore_water_pct":43,"surface_m2_m3":1400,"grain_printed":"4/6"}'::jsonb, 'Grain 4/6 43 1400  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE15'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, '4_8', '{"grain_class":"4_8"}'::jsonb, NULL, 'Korn 4/8 mm', 1, '{"pore_water_pct":43,"surface_m2_m3":1200,"grain_printed":"4/8"}'::jsonb, 'Grain 4/8 43 1200  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE15'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, '6_8', '{"grain_class":"6_8"}'::jsonb, NULL, 'Korn 6/8 mm', 2, '{"pore_water_pct":43,"surface_m2_m3":1000,"grain_printed":"6/8"}'::jsonb, 'Grain 6/8 43 1000  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE15'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, '8_12', '{"grain_class":"8_12"}'::jsonb, NULL, 'Korn 8/12 mm', 3, '{"pore_water_pct":44,"surface_m2_m3":700,"grain_printed":"8/12"}'::jsonb, 'Grain 8/12 44 700  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE15'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, '8_16', '{"grain_class":"8_16"}'::jsonb, NULL, 'Korn 8/16 mm', 4, '{"pore_water_pct":44,"surface_m2_m3":600,"grain_printed":"8/16"}'::jsonb, 'Grain 8/16 44 600  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE15'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, '12_16', '{"grain_class":"12_16"}'::jsonb, NULL, 'Korn 12/16 mm', 5, '{"pore_water_pct":47,"surface_m2_m3":500,"grain_printed":"12/16"}'::jsonb, 'Grain 12/16 47 500  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE15'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, '16_22', '{"grain_class":"16_22"}'::jsonb, NULL, 'Korn 16/22 mm', 6, '{"pore_water_pct":48,"surface_m2_m3":350,"grain_printed":"16/22"}'::jsonb, 'Grain 16/22 48 350  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE15'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, '16_32', '{"grain_class":"16_32"}'::jsonb, NULL, 'Korn 16/32 mm', 7, '{"pore_water_pct":47,"surface_m2_m3":300,"grain_printed":"16/32"}'::jsonb, 'Grain 16/32 47 300  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE15'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, '22_32', '{"grain_class":"22_32"}'::jsonb, NULL, 'Korn 22/32 mm', 8, '{"pore_water_pct":47,"surface_m2_m3":250,"grain_printed":"22/32"}'::jsonb, 'Grain 22/32 47 250  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE15'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
UPDATE regulation_tables SET verification_status = 'md_verified' WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'TABLE15' AND verification_status = 'imported_unverified';
INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES ('FLL-Naturteich', '2017', 'S10_4_3', 'Pflanzdichte je Pflanzengruppe — Richtwert je m² Pflanzfläche, Topfware P 0.5 (§10.4.3)', '§10.4.3', '57', ARRAY['plant_group']::text[], '[{"name":"density_min","type":"number","unit":"1/m²"},{"name":"density_max","type":"number","unit":"1/m²"},{"name":"pot_size","type":"string"},{"name":"printed","type":"string"}]'::jsonb, 'anhaltswert', 'For plant density, the following number of plants applies as an approximate value per m2 of planting surface area: — The aforementioned number of plants applies to pot plants P 0.5 (500 cm3).', 'md_verified')
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'submerged', '{"plant_group":"submerged"}'::jsonb, NULL, 'Unterwasserpflanzen (submerged plants)', 0, '{"density_min":6,"density_max":10,"pot_size":"P 0.5 (500 cm3)","printed":"• submerged plants 6 – 10 plants;"}'::jsonb, '• submerged plants 6 – 10 plants;  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'S10_4_3'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'marsh_small', '{"plant_group":"marsh_small"}'::jsonb, NULL, 'halbhohe bis hohe Sumpf- und Wasserpflanzen (half-height to tall marsh and aquatic plants)', 1, '{"density_min":3,"density_max":5,"pot_size":"P 0.5 (500 cm3)","printed":"• half-height to tall marsh and aquatic plants 3 – 5 plants;"}'::jsonb, '• half-height to tall marsh and aquatic plants 3 – 5 plants;  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'S10_4_3'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'marsh_medium', '{"plant_group":"marsh_medium"}'::jsonb, NULL, 'mittelhohe bis hohe Sumpf- und Wasserpflanzen (medium height to tall marsh and aquatic plants)', 2, '{"density_min":5,"density_max":7,"pot_size":"P 0.5 (500 cm3)","printed":"• medium height to tall marsh and aquatic plants 5 – 7 plants;"}'::jsonb, '• medium height to tall marsh and aquatic plants 5 – 7 plants;  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'S10_4_3'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, 'lilies', '{"plant_group":"lilies"}'::jsonb, NULL, 'Seerosen (lilies and lily pads — depending on type)', 3, '{"density_min":null,"density_max":null,"pot_size":"P 0.5 (500 cm3)","printed":"• lilies and lily pads depending on type."}'::jsonb, '• lilies and lily pads depending on type.  ' FROM regulation_tables WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'S10_4_3'
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;
UPDATE regulation_tables SET verification_status = 'md_verified' WHERE standard_code = 'FLL-Naturteich' AND edition = '2017' AND table_code = 'S10_4_3' AND verification_status = 'imported_unverified';
COMMIT;
