-- ROLLBACK for 20261005173200_fll_gar_followup_hints.sql — restores the pre-block descriptions (inventory snapshot 20261005).
BEGIN;
UPDATE fields x SET description = 'Ergebnis der baurechtlichen Prüfung: Ist für Herstellung, Inbetriebnahme, Nutzung und Instandhaltung des Gewässers eine Genehmigung nach Landesbauordnung erforderlich? Zu prüfen sind u. a. Bauordnung und Abgrabungsgesetze, Genehmigungsverfahren der Länder und Kommunen je nach Größe und Nutzung, Nachbarrecht, Natur-/Umweltschutzrecht, Tierschutz, Hygiene (§ 4.2; § 4.1 „baurechtliche Genehmigungen gemäß LBO“). Tor REQ-02 besteht nur bei Ja.
[EN] Result of the building-law check: does construction, commissioning, use and maintenance of the water body need a permit under the state building code (LBO)? Check e.g. building code and excavation acts, approval procedures of states and municipalities depending on size and use, neighbour law, nature/environmental law, animal welfare, hygiene (§ 4.2; § 4.1 ''building permits per LBO''). Gate REQ-02 passes only with yes.' FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE x.worksheet_template_id = w.id AND s.code = 'FLL-GAR-2023' AND w.code = 'FLL-GAR-03' AND x.symbol = 'lbo_genehmigung_erforderlich';
UPDATE fields x SET description = 'Ergebnis der wasserrechtlichen Prüfung: Ist für die Einleitung von Überschusswasser in natürliche Gewässer, in das angrenzende Gelände oder in das öffentliche Kanalnetz eine Genehmigung nach WHG erforderlich bzw. erteilt? Die Richtlinien nennen die Einleitung „gemäß WHG“ (§ 4.1) und weisen darauf hin, dass Einleitungen genehmigungspflichtig sein können (§ 4.10). Tor REQ-03 besteht nur bei Ja.
[EN] Result of the water-law check: does the discharge of surplus water into natural waters, adjacent ground or the public sewer require or hold a permit under the Federal Water Act (WHG)? The guideline names discharge ''per WHG'' (§ 4.1) and notes that discharges can be subject to approval (§ 4.10). Gate REQ-03 passes only with yes.' FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE x.worksheet_template_id = w.id AND s.code = 'FLL-GAR-2023' AND w.code = 'FLL-GAR-03' AND x.symbol = 'whg_einleitung_genehmigung';
UPDATE compliance_requirements x SET description = 'Besteht, wenn „LBO-Genehmigung erforderlich“ auf Ja steht – d. h. die bauaufsichtlichen Anforderungen sind geprüft und die erforderlichen Genehmigungen beantragt. Die Richtlinien verlangen, im Planungsverlauf zu klären, welche bauaufsichtlichen Anforderungen Herstellung, Inbetriebnahme, Nutzung und Instandhaltung bestimmen (§ 4.2; § 4.1). Sperrtor: Feld belegen, sonst keine Freigabe. Hinweis: Das Tor liest nur den Ja-Wert; ein begründetes „nicht erforderlich“ ist hier nicht abbildbar.
[EN] Passes when ''LBO permit required'' is set to yes – i.e. the building-supervision requirements have been checked and the required permits applied for. The guideline requires clarifying during design which building-law requirements govern construction, commissioning, use and maintenance (§ 4.2; § 4.1). Blocking gate: fill the field, otherwise no approval. Note: the gate reads only the yes value; a justified ''not required'' cannot be recorded here.' FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE x.worksheet_template_id = w.id AND s.code = 'FLL-GAR-2023' AND w.code = 'FLL-GAR-03' AND x.code = 'REQ-02';
UPDATE compliance_requirements x SET description = 'Besteht, wenn „WHG-Einleitungsgenehmigung“ auf Ja steht – die Genehmigungsfrage für die Ableitung des Überschusswassers ist geklärt. Grundlage: Einleitung in natürliche Gewässer gemäß WHG (§ 4.1); Einleitung in das angrenzende Gelände oder das öffentliche Kanalnetz kann genehmigungspflichtig sein (§ 4.10). Sperrtor: Feld belegen; das Tor liest nur Ja.
[EN] Passes when ''WHG discharge permit'' is set to yes – the permit question for the surplus-water discharge is settled. Basis: discharge into natural waters per WHG (§ 4.1); discharge into adjacent ground or the public sewer can be subject to approval (§ 4.10). Blocking gate: fill the field; the gate reads only yes.' FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE x.worksheet_template_id = w.id AND s.code = 'FLL-GAR-2023' AND w.code = 'FLL-GAR-03' AND x.code = 'REQ-03';
COMMIT;
