-- Read-back after block 4a (+ 4b). Run: node scripts/verification/prod-query.mjs scripts/verification/apply/readback-fll-tp-rhizom-coverage-block4.sql
-- Expected after 4a: 17 fields (active, not required, verified_against_standard), 3 equations, vts_gesamt_dicke_mm widget derived.
select w.code ws, f.symbol, f.data_type, f.unit, f.widget, f.visible_when, f.is_required, f.verification_status, f.order_index
  from fields f join worksheet_templates w on w.id = f.worksheet_template_id join standards s on s.id = w.standard_id
 where s.code = 'FLL-TP-RHIZOM-2023' and f.symbol in ('widerlager_eingebaut', 'widerlager_verzicht_begruendung', 'kontrollgefaesse_wasserdicht', 'gefaess_flaeche_m2', 'gefaess_skalierungsfaktor', 'standrohr_anzahl', 'standrohr_laenge_mm', 'rueckstellprobe_vor_pruefung_datum', 'rueckstellprobe_nach_pruefung_datum', 'rueckstellprobe_flaeche_m2', 'rueckstellprobe_enthaelt_naht_je_fuegetechnik', 'rueckstellprobe_lager_temp_min_C', 'rueckstellprobe_lager_temp_max_C', 'rueckstellprobe_trocken_dunkel', 'rueckstellprobe_lagerung_bis', 'lagerung_unvertraeglichkeiten_beachtet', 'verlaengerung_beantragt', 'vts_gesamt_dicke_mm') order by w.code, f.order_index;
select w.code ws, e.equation_number, e.formula from equations e join worksheet_templates w on w.id = e.worksheet_template_id join standards s on s.id = w.standard_id where s.code = 'FLL-TP-RHIZOM-2023' and e.equation_number in ('FLLTP-RHZ-05-D1','FLLTP-RHZ-05-D2','FLLTP-RHZ-06-D1') order by 2;
-- Expected after 4b: REQ-06/-10/-14/-22 updated, REQ-23…REQ-26 present; widerlager_* and the RHZ-20 extension fields optional with visible_when.
select w.code ws, cr.code, cr.severity, cr.condition from compliance_requirements cr join worksheet_templates w on w.id = cr.worksheet_template_id join standards s on s.id = w.standard_id
 where s.code = 'FLL-TP-RHIZOM-2023' and cr.code in ('REQ-06','REQ-10','REQ-14','REQ-22','REQ-23','REQ-24','REQ-25','REQ-26') order by cr.code;
select w.code ws, f.symbol, f.is_required, f.visible_when from fields f join worksheet_templates w on w.id = f.worksheet_template_id join standards s on s.id = w.standard_id
 where s.code = 'FLL-TP-RHIZOM-2023' and f.symbol in ('widerlager_dicke_mm', 'widerlager_material', 'pruefgrundlagen_unveraendert', 'produkt_aktuell_im_lieferprogramm', 'rueckstellmuster_erneut_hinterlegt', 'eidesstattliche_erklaerung_vorhanden', 'verlangerung_zeitabschnitt_jahre') order by 1, 2;
