import { writeFileSync } from 'node:fs';
import { SEED_BUILDERS } from '../../src/lib/eval/regulation-tables-seed-index';
import type { RegulationTable } from '../../src/lib/eval/regulation-tables';

/**
 * Slug → seed builder + migration file stamp (Plan 3 Task 0). The map itself
 * lives in the pure module `src/lib/eval/regulation-tables-seed-index.ts` so
 * the deploy-before-seed fallback (`regulation-tables-fallback.ts`) reads the
 * same set; it is re-exported here for the emitter's callers. Each Plan-3
 * standard task appends one line THERE, never here.
 */
export { SEED_BUILDERS };

const q = (s: string | null) => (s == null ? 'NULL' : `'${s.replace(/'/g, "''")}'`);
const j = (v: unknown) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const arr = (a: string[]) => `ARRAY[${a.map((x) => q(x)).join(',')}]::text[]`;

export function emitSeedSql(tables: RegulationTable[]): { up: string; down: string } {
  const up: string[] = ['-- Generated by scripts/regulation-tables/emit-seed-sql.ts — do not hand-edit; regenerate.', 'BEGIN;'];
  const down: string[] = ['BEGIN;'];
  for (const t of tables) {
    up.push(`INSERT INTO regulation_tables (standard_code, edition, table_code, title_de, clause_reference, page_ref, key_columns, value_columns, override_policy, override_quote, verification_status)
VALUES (${q(t.standard_code)}, ${q(t.edition)}, ${q(t.table_code)}, ${q(t.title_de)}, ${q(t.clause_reference)}, ${q(t.page_ref)}, ${arr(t.key_columns)}, ${j(t.value_columns)}, ${q(t.override_policy)}, ${q(t.override_quote)}, ${q(t.verification_status)})
ON CONFLICT (standard_code, edition, table_code) DO UPDATE SET title_de = EXCLUDED.title_de, clause_reference = EXCLUDED.clause_reference, page_ref = EXCLUDED.page_ref, key_columns = EXCLUDED.key_columns, value_columns = EXCLUDED.value_columns, override_policy = EXCLUDED.override_policy, override_quote = EXCLUDED.override_quote;`);
    for (const r of t.rows) {
      up.push(`INSERT INTO regulation_table_rows (table_id, row_key, keys, group_label, label_de, order_index, row_values, verbatim_quote)
SELECT id, ${q(r.row_key)}, ${j(r.keys)}, ${q(r.group_label)}, ${q(r.label_de)}, ${r.order_index}, ${j(r.values)}, ${q(r.verbatim_quote)} FROM regulation_tables WHERE standard_code = ${q(t.standard_code)} AND edition = ${q(t.edition)} AND table_code = ${q(t.table_code)}
ON CONFLICT (table_id, row_key) DO UPDATE SET keys = EXCLUDED.keys, group_label = EXCLUDED.group_label, label_de = EXCLUDED.label_de, order_index = EXCLUDED.order_index, row_values = EXCLUDED.row_values, verbatim_quote = EXCLUDED.verbatim_quote;`);
    }
    down.push(`DELETE FROM regulation_tables WHERE standard_code = ${q(t.standard_code)} AND edition = ${q(t.edition)} AND table_code = ${q(t.table_code)};`);
  }
  up.push('COMMIT;'); down.push('COMMIT;');
  return { up: up.join('\n') + '\n', down: down.join('\n') + '\n' };
}

/** Migration + rollback file paths for a seed slug (relative to the repo root). */
export function seedFilesFor(slug: string): { migration: string; rollback: string } {
  const b = SEED_BUILDERS[slug];
  if (!b) throw new Error(`unknown seed slug ${JSON.stringify(slug)} — known: ${Object.keys(SEED_BUILDERS).join(', ')}`);
  return {
    migration: `scripts/migrations/${b.ts}_regulation_tables_seed_${b.slugFile}.sql`,
    rollback: `scripts/rollback-${b.ts}-regulation-tables-seed-${b.slugFile.replace(/_/g, '-')}.sql`,
  };
}

if (process.argv[1]?.endsWith('emit-seed-sql.ts')) {
  // CLI: tsx scripts/regulation-tables/emit-seed-sql.ts <slug>
  const slug = process.argv[2] ?? '';
  const files = seedFilesFor(slug);
  const { up, down } = emitSeedSql(SEED_BUILDERS[slug].build());
  writeFileSync(files.migration, up);
  writeFileSync(files.rollback, down);
  console.log('wrote seed + rollback for', slug, '->', files.migration, files.rollback);
}
