import { readFileSync, writeFileSync } from 'node:fs';
import { SELECTION_CONFIGS, toDbShape } from '../../src/lib/eval/selection-fields';

type EnumValue = { value: string; label_de: string; label_en?: string | null; order_index?: number };

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const j = (v: unknown) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

export function emitSelectionConfigSql(
  entries: Array<{ standard: string; symbol: string; keepProdEnum?: EnumValue[] }>
): Map<string, string> {
  const out = new Map<string, string[]>();
  for (const e of entries) {
    const config = SELECTION_CONFIGS[e.symbol];
    if (!config) throw new Error(`no SELECTION_CONFIGS entry for ${e.symbol}`);
    const db = toDbShape(e.symbol, config, { keepProdEnum: e.keepProdEnum });
    const sets = [`widget = ${q(db.widget)}`, `ui_config = ${j(db.ui_config)}`];
    if (db.widget === 'select_many' && !e.keepProdEnum) sets.push(`enum_values = ${j(db.enum_values)}`);
    const stmt = `UPDATE fields f SET ${sets.join(', ')} FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.symbol = ${q(e.symbol)} AND s.code = ${q(e.standard)} AND f.worksheet_template_id = w.id;`;
    if (!out.has(e.standard)) {
      out.set(e.standard, [
        '-- Generated by scripts/regulation-tables/emit-selection-configs-sql.ts from SELECTION_CONFIGS (phase 2). Regenerate, do not hand-edit.',
        'BEGIN;',
      ]);
    }
    out.get(e.standard)!.push(stmt);
  }
  return new Map([...out].map(([k, v]) => [k, [...v, 'COMMIT;'].join('\n') + '\n']));
}

if (process.argv[1]?.endsWith('emit-selection-configs-sql.ts')) {
  const entries = JSON.parse(readFileSync(process.argv[2], 'utf8')) as Array<{
    standard: string;
    symbol: string;
    keepProdEnum?: EnumValue[];
  }>;
  for (const [std, sql] of emitSelectionConfigSql(entries)) {
    writeFileSync(`scripts/migrations/20260911120000_selection_configs_${std.replace(/[^A-Za-z0-9]/g, '_')}.sql`, sql);
  }
  const rollback: string[] = ['BEGIN;'];
  for (const e of entries) {
    rollback.push(
      `UPDATE fields f SET widget = NULL, ui_config = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.symbol = ${q(e.symbol)} AND s.code = ${q(e.standard)} AND f.worksheet_template_id = w.id;`
    );
  }
  rollback.push('COMMIT;');
  writeFileSync('scripts/rollback-20260911120000-selection-configs.sql', rollback.join('\n') + '\n');
  console.log('wrote', entries.length, 'entries');
}
