/**
 * KOSTRA-DWD-2020 grid coverage bitmap (BELEG = 1 cells).
 *
 * Encodes which of the 300×300 grid cells contain actual KOSTRA-DWD-2020
 * data — there are 15,989 such cells (covering Germany incl. a few-km
 * buffer beyond the political border). Cells outside this mask are
 * outside Germany or otherwise uncovered, and `latLonToKostraCell` must
 * return null for them so the engineer enters a value manually instead.
 *
 * Source: `GIS_KOSTRA-DWD-2020_Param.zip` from DWD CDC Open Data,
 *   https://opendata.dwd.de/climate_environment/CDC/grids_germany/return_periods/precipitation/KOSTRA/KOSTRA_DWD_2020/gis/
 *   field `BELEG` of the parameter shapefile (1 = covered, 0 = no data).
 *
 * Bit layout: 90 000 bits = 11 250 bytes, packed LSB-first into bytes by
 * the linear index `row * 300 + col` (row, col ∈ {0..299}). Bit set ⇒
 * cell has KOSTRA data. Base64-encoded, decoded once at module load.
 *
 * Regenerate: `pnpm tsx scripts/build-kostra-bitmap.ts` (see that script).
 */

const BITMAP_B64 =
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOB/AAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/n8cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAPD//wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AQAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD//z8AAAAAgAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAA////AwAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD//38AAAAA8A8AAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////BwAAAID/AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAOD//38AAAAA/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v//B/ABAMP/AwAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAID///8APwD4/z8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAA+P//f/gHwP//AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///+ffwD8/38AAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAA8P////8H4P//BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAD/////fwD///8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P////8A+P//HwAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAgAP+////D8D///8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8' +
  'wP/////g////DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAf4////j/////8DAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAA4wP/////4////fwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+' +
  '////3/////8PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P///////////wEAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAMD///////////8/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v//' +
  '/////////wMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD///////////8fAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAIB/+P///////////wMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA/5//////' +
  '//////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P//+////////////wcAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAID///////////////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P//////////' +
  '/////wcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD///////////////9/AAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAA/P///////////////w8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAID/////////////' +
  '////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP///////////////w8AAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAD4////////////////AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwP//////////////' +
  '/x8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4////////////////AQAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAgP///////////////x8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg////////////////' +
  'AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7//////////////x8AAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAADg////////////////AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7//////////////x8A' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAP7//////////////wcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg//////////////9/AAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////wMAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAD4//////////////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP///////////////x8AAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAD4////////////////AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'gP///////////////38AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD/////////////////DwAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAA/P////////////////8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD/' +
  '////////////////HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v////////////////8BAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAMD/////////////////HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P//' +
  '//////////////8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD/////////////////DwAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAA+P////////////////8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8////' +
  '////////////PwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwP////////////////8DAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAD+////////////////PwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//////' +
  '//////////8DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD/////////////////fwAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAA/v////////////////8HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOD/////////' +
  '////////fwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v////////////////8HAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAA4PH/////////////////fwAAAAAAAAAAAAAAAAAAAAAAAAAAAID/////////////' +
  '//////8HAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P//////////////////PwAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAMD///////////////////8DAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P//////////////' +
  '////fwAAAAAAAAAAAAAAAAAAAAAAAAAAAMD///////////////////8PAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAA+P///////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////' +
  '//8PAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P///////////////////wEAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAD+//////////////////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAA4P//////////////////' +
  '/wcAAAAAAAAAAAAAAAAAAAAAAAAAAAD8//////////////////9/AAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAwP///////////////////wcAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////////////////////' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAA8P///////////////////w8AAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAD/////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAA+P///////////////////w8A' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAID/////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  '/P///////////////////w8AAAAAAAAAAAAAAAAAAAAAAAAAAOD/////////////////////AAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAA/////////////////////w8AAAAAAAAAAAAAAAAAAAAAAAAAAOD/' +
  '//////////////////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAA/v///////////////////wcAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAOD///////////////////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAA/P//' +
  '/////////////////wMAAAAAAAAAAAAAAAAAAAAAAAAAAMD//////////////////z8/AAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAA/P//////////////////4AEAAAAAAAAAAAAAAAAAAAAAAAAAAMD/////' +
  '/////////////wMAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/P////////////////8fAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAID//////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//////' +
  '//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////BwAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAA8P///////////////38AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////////' +
  '//////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwP///////////////wcAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAD8//////////////8fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwP//////////' +
  '/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////8EAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAA8P//////////////AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAID/////////////' +
  '/w8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P//////////////AAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAID//////////////wcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P////////////9/' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAID//////////////x8AAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAA+P//////////////AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAID//////////////z8A' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//////////////BwAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAD+/////////////38AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwP//////////////AwAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4/////////////z8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAgP//////////////AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4/////////////38AAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAwP//////////////BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAD8/////////////38AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwP//////////////DwAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAD8//////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'wP//////////////HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8//////////////8PAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAP///////////////wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg' +
  '//////////////8/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7//////////////wcAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAADA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPz/' +
  '/////////////x8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA////////////////AwAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAPj///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P//' +
  '////////////PwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA//////////////8HAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAPD//////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwP//' +
  '//////////8fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4/////////////wMAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAwP////////////8/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////' +
  '/////////wcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P////////////9/AAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAID//////////////wMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P//////' +
  '//////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD//////////////wMAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAA/P////////////8/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD/////////' +
  '/////wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v////////////8NAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAOD/////////////HwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v//////////' +
  '//8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD/////////////DwAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAA//////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPD/////////////' +
  'AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA/////////////w8AAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAPj///////////8/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA/////////////wAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPz///////////8PAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAADA/////////////wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPz///////////8/AAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA/////////////wMAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAPz///////////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA/////////////wcAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7///////////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AADg/////////////w8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7/////////////AAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAADg/////////////x8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AP7/////////////AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA//////////9//w8AAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAPz/H4D//////2f/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA' +
  '//0A8P////8B4A8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACACAAD8////AQB4AAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPif/w8AAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AACA/+F/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAP/gEAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AOAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAA';

/** 300×300 grid cell count. */
export const KOSTRA_GRID_SIZE = 300;

/** Lazily-decoded bitmap. 11 250 bytes; one bit per cell. */
let bitmap: Uint8Array | null = null;

function getBitmap(): Uint8Array {
  if (bitmap) return bitmap;
  // Decode base64 portably (works in browser + Node + edge).
  const binary =
    typeof atob === 'function' ? atob(BITMAP_B64) : Buffer.from(BITMAP_B64, 'base64').toString('binary');
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  bitmap = out;
  return out;
}

/**
 * Whether grid cell (row, col) is one of the 15 989 KOSTRA-DWD-2020 cells
 * with actual data. Returns false for out-of-range row/col too.
 */
export function isKostraCellCovered(row: number, col: number): boolean {
  if (!Number.isInteger(row) || !Number.isInteger(col)) return false;
  if (row < 0 || row >= KOSTRA_GRID_SIZE) return false;
  if (col < 0 || col >= KOSTRA_GRID_SIZE) return false;
  const idx = row * KOSTRA_GRID_SIZE + col;
  const byte = getBitmap()[idx >> 3];
  return (byte & (1 << (idx & 7))) !== 0;
}
