import { describe, it, expect } from 'vitest';
import { emitWidgetConfigSql, emitWidgetRollbackSql, type WidgetEntry } from '../regulation-tables/emit-widget-configs-sql';

const reg: WidgetEntry = {
  file: '20990101000000_x_reg', standard: 'DWA-X', symbol: 'reg_sym', widget: 'register',
  ui_config: { title: "O'Brien", columns: [{ key: 'a', type: 'text', label: 'A' }] },
  retires: 'X_FALLBACK.reg_sym (src/lib/eval/x.ts)',
};
const lf: WidgetEntry = {
  file: '20990101000001_x_lf', standard: 'DWA-X', symbol: 'lf_sym', widget: 'lookup_fill',
  ui_config: null, lookup: { table_code: 'TAB1', role: 'value', keys: [{ column: 'k', from_symbol: 'k' }], value: 'v' },
  retires: 'X_FALLBACK.lf_sym (src/lib/eval/x.ts)', gated: 'D-9', gated_note: 'Why gated: reason.\n\n  (a) option a\n  (b) option b',
};

describe('emitWidgetConfigSql', () => {
  it('one file per entry, keyed by entry.file, one transactional UPDATE scoped by symbol + standard code + widget IS NULL', () => {
    const m = emitWidgetConfigSql([reg]);
    expect([...m.keys()]).toEqual(['20990101000000_x_reg']);
    const sql = m.get('20990101000000_x_reg')!;
    expect(sql.split('\n')[0]).toBe('-- Generated by scripts/regulation-tables/emit-widget-configs-sql.ts from the TS fallback config (Plan 2b). Regenerate, do not hand-edit.');
    expect(sql).toContain('-- Retires: X_FALLBACK.reg_sym (src/lib/eval/x.ts) once applied. Apply AFTER 20260911100000_guideline_to_tool_schema.sql.');
    expect(sql).toMatch(/^BEGIN;$/m);
    expect(sql).toMatch(/^COMMIT;$/m);
    expect(sql).toContain("UPDATE fields f SET widget = 'register', ui_config = '");
    expect(sql).toContain("FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.symbol = 'reg_sym' AND s.code = 'DWA-X' AND f.worksheet_template_id = w.id AND f.widget IS NULL;");
    expect((sql.match(/UPDATE fields/g) ?? []).length).toBe(1);
    expect(sql.endsWith('\n')).toBe(true);
  });

  it('JSON is embedded with SQL single-quote doubling and no lookup column for a non-lookup_fill entry', () => {
    const sql = emitWidgetConfigSql([reg]).get('20990101000000_x_reg')!;
    expect(sql).toContain(`ui_config = '{"title":"O''Brien","columns":[{"key":"a","type":"text","label":"A"}]}'::jsonb`);
    expect(sql).not.toContain('lookup =');
    expect(sql).not.toMatch(/^-- GATED/m);
  });

  it('lookup_fill: ui_config NULL when null, lookup column emitted, GATED line + gated_note lines prefixed as SQL comments', () => {
    const sql = emitWidgetConfigSql([lf]).get('20990101000001_x_lf')!;
    expect(sql).toContain(`SET widget = 'lookup_fill', ui_config = NULL, lookup = '{"table_code":"TAB1","role":"value","keys":[{"column":"k","from_symbol":"k"}],"value":"v"}'::jsonb FROM`);
    const lines = sql.split('\n');
    const gatedIdx = lines.findIndex((l) => l.startsWith('-- GATED: do not apply before sign-off D-9 is RATIFIED'));
    expect(gatedIdx).toBe(2);
    expect(lines.slice(gatedIdx + 1, gatedIdx + 5)).toEqual(['-- Why gated: reason.', '--', '--   (a) option a', '--   (b) option b']);
    expect(lines[gatedIdx + 5]).toBe('BEGIN;');
  });

  it('gated without gated_note: GATED line directly followed by BEGIN', () => {
    const { gated_note: _n, ...bare } = lf;
    void _n;
    const lines = emitWidgetConfigSql([bare]).get('20990101000001_x_lf')!.split('\n');
    expect(lines[2]).toMatch(/^-- GATED:/);
    expect(lines[3]).toBe('BEGIN;');
  });

  it('template_code scopes UP and rollback to the home worksheet template; provenance replaces line 1', () => {
    const scoped: WidgetEntry = { ...lf, template_code: 'X-12', provenance: '-- Hand-authored (Task 7); regenerated by the Task-5 emitter.' };
    const sql = emitWidgetConfigSql([scoped]).get(scoped.file)!;
    expect(sql.split('\n')[0]).toBe('-- Hand-authored (Task 7); regenerated by the Task-5 emitter.');
    expect(sql).toContain("WHERE f.symbol = 'lf_sym' AND s.code = 'DWA-X' AND w.code = 'X-12' AND f.worksheet_template_id = w.id AND f.widget IS NULL;");
    expect(emitWidgetRollbackSql([scoped])).toContain("WHERE f.symbol = 'lf_sym' AND s.code = 'DWA-X' AND w.code = 'X-12' AND f.worksheet_template_id = w.id AND f.widget = 'lookup_fill';");
    // Without template_code no w.code clause at all.
    expect(emitWidgetConfigSql([lf]).get(lf.file)!).not.toContain('w.code');
  });

  it('never emits data_type or enum_values (controller pin)', () => {
    for (const sql of emitWidgetConfigSql([reg, lf]).values()) {
      expect(sql).not.toMatch(/data_type|enum_values/);
    }
    expect(emitWidgetRollbackSql([reg, lf])).not.toMatch(/data_type|enum_values/);
  });

  it('rejects an entry with a duplicate file name', () => {
    expect(() => emitWidgetConfigSql([reg, { ...lf, file: reg.file }])).toThrow(/duplicate migration file/);
  });
});

describe('emitWidgetRollbackSql', () => {
  it('one guarded NULL-restore per entry in reverse order, inside one transaction', () => {
    const sql = emitWidgetRollbackSql([reg, lf]);
    const lines = sql.split('\n');
    expect(lines[0]).toMatch(/^-- Generated rollback for the Plan 2b widget migrations/);
    const upd = lines.filter((l) => l.startsWith('UPDATE fields'));
    expect(upd).toHaveLength(2);
    expect(upd[0]).toBe("UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.symbol = 'lf_sym' AND s.code = 'DWA-X' AND f.worksheet_template_id = w.id AND f.widget = 'lookup_fill';");
    expect(upd[1]).toBe("UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.symbol = 'reg_sym' AND s.code = 'DWA-X' AND f.worksheet_template_id = w.id AND f.widget = 'register';");
    expect(lines.indexOf('BEGIN;')).toBeLessThan(lines.indexOf(upd[0]));
    expect(lines[lines.length - 2]).toBe('COMMIT;');
    expect(sql.endsWith('\n')).toBe(true);
  });
});
