-- Generated rollback for m205 equations (scripts/regulation-tables/emit-equations-sql.ts). Deletes only the 'Plan 3:' rows this migration inserted. Regenerate, do not hand-edit.
BEGIN;
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-10' AND e.equation_number = 'M205-10-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-10' AND e.equation_number = 'M205-10-D2' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-11' AND e.equation_number = 'M205-11-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-11' AND e.equation_number = 'M205-11-D2' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-11' AND e.equation_number = 'M205-11-D3' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-14' AND e.equation_number = 'M205-14-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-14' AND e.equation_number = 'M205-14-D2' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND e.equation_number = 'M205-17-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND e.equation_number = 'M205-17-D2' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND e.equation_number = 'M205-17-D3' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND e.equation_number = 'M205-17-D4' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND e.equation_number = 'M205-17-D5' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-21' AND e.equation_number = 'M205-21-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-24' AND e.equation_number = 'M205-24-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-24' AND e.equation_number = 'M205-24-D2' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-24' AND e.equation_number = 'M205-24-D3' AND e.description LIKE 'Plan 3:%';
COMMIT;
