-- Generated rollback for m205 field configs (scripts/regulation-tables/emit-field-configs-sql.ts). Restores the captured prior; deletes only 'Plan 3:' rows. Regenerate, do not hand-edit.
BEGIN;
-- M205-04 gesamtcoliforme: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'gesamtcoliforme' AND w.code = 'M205-04' AND s.code = 'DWA-M-205' AND f.active;
-- M205-04 faekalcoliforme: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'faekalcoliforme' AND w.code = 'M205-04' AND s.code = 'DWA-M-205' AND f.active;
-- M205-04 strep_faecalis: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'strep_faecalis' AND w.code = 'M205-04' AND s.code = 'DWA-M-205' AND f.active;
-- M205-04 gewaessertyp: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'gewaessertyp' AND w.code = 'M205-04' AND s.code = 'DWA-M-205' AND f.active;
-- M205-04 guetekategorie: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'guetekategorie' AND w.code = 'M205-04' AND s.code = 'DWA-M-205' AND f.active;
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-05' AND f.symbol = 'bewirtschaftung' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-05' AND f.symbol = 'log_reduktion_empfehlung' AND f.description LIKE 'Plan 3:%';
-- M205-05 fkstrep: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'fkstrep' AND w.code = 'M205-05' AND s.code = 'DWA-M-205' AND f.active;
-- M205-05 toc: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'toc' AND w.code = 'M205-05' AND s.code = 'DWA-M-205' AND f.active;
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-05' AND f.symbol = 'strahler_quecksilberdampfdruck_tab4' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-05' AND f.symbol = 'strahler_wellenlaenge_tab4' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-05' AND f.symbol = 'strahler_leistungsdichte_tab4' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-05' AND f.symbol = 'uvc_anteil_tab4' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-05' AND f.symbol = 'strahler_oberflaechentemperatur_tab4' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-05' AND f.symbol = 'strahler_nutzungsdauer_tab4' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-10' AND f.symbol = 'leitorganismen' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-10' AND f.symbol = 'leitorganismen_count' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-10' AND f.symbol = 'leitorganismen_verletzungen' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-10' AND f.symbol = 'uv_dosis_min' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-10' AND f.symbol = 'uv_dosis_max' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-11' AND f.symbol = 'bestrahlungsgerinne' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-11' AND f.symbol = 'durchfluss_gerinne_sum' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-11' AND f.symbol = 'gerinne_count' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-11' AND f.symbol = 'gerinne_sensor_verletzungen' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-14' AND f.symbol = 'membranmodule' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-14' AND f.symbol = 'membranflaeche_sum' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-14' AND f.symbol = 'permeat_design' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND f.symbol = 'ozongeneratoren' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND f.symbol = 'ozon_kapazitaet_sum' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND f.symbol = 'ozon_pro_doc_calc' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND f.symbol = 'ozonbedarf_kg_h' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND f.symbol = 'o2_bedarf_kg_h' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND f.symbol = 'ct_ecoli_basis' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND f.symbol = 'ct_ziel' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-17' AND f.symbol = 'spez_energie_ozon_tab' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-18' AND f.symbol = 'temperatur_ozonentfernung_min' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-18' AND f.symbol = 'temperatur_ozonentfernung_max' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-18' AND f.symbol = 'verbrennung_haltezeit_min' AND f.description LIKE 'Plan 3:%';
-- M205-18 verbrennung_haltezeit_s: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'verbrennung_haltezeit_s' AND w.code = 'M205-18' AND s.code = 'DWA-M-205' AND f.active;
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-21' AND f.symbol = 'chlorungsmittel' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-21' AND f.symbol = 'chlordosis_verletzungen' AND f.description LIKE 'Plan 3:%';
-- M205-21 clo2_konzentration: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'clo2_konzentration' AND w.code = 'M205-21' AND s.code = 'DWA-M-205' AND f.active;
-- M205-21 chlor_kontaktzeit: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'chlor_kontaktzeit' AND w.code = 'M205-21' AND s.code = 'DWA-M-205' AND f.active;
-- M205-21 chlor_ph: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'chlor_ph' AND w.code = 'M205-21' AND s.code = 'DWA-M-205' AND f.active;
-- M205-21 restchlor_betrieb: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'restchlor_betrieb' AND w.code = 'M205-21' AND s.code = 'DWA-M-205' AND f.active;
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-24' AND f.symbol = 'proben_desinfektion' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-24' AND f.symbol = 'proben_count' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-24' AND f.symbol = 'log_reduktion_mean' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-205' AND w.code = 'M205-24' AND f.symbol = 'log_reduktion_min' AND f.description LIKE 'Plan 3:%';
COMMIT;
