-- Generated rollback for m820_2 equations (scripts/regulation-tables/emit-equations-sql.ts). Deletes only the 'Plan 3:' rows this migration inserted. Regenerate, do not hand-edit.
BEGIN;
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-06' AND e.equation_number = '820-2-06-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-06' AND e.equation_number = '820-2-06-D2' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-12' AND e.equation_number = '820-2-12-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-12' AND e.equation_number = '820-2-12-D2' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-13' AND e.equation_number = '820-2-13-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-16' AND e.equation_number = '820-2-16-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-16' AND e.equation_number = '820-2-16-D2' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-19' AND e.equation_number = '820-2-19-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-19' AND e.equation_number = '820-2-19-D2' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-21' AND e.equation_number = '820-2-21-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-21' AND e.equation_number = '820-2-21-D2' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-21' AND e.equation_number = '820-2-21-D3' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-24' AND e.equation_number = '820-2-24-D1' AND e.description LIKE 'Plan 3:%';
DELETE FROM equations e USING worksheet_templates w, standards s WHERE e.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-820-2' AND w.code = '820-2-24' AND e.equation_number = '820-2-24-D2' AND e.description LIKE 'Plan 3:%';
COMMIT;
