-- Generated rollback for m277e field configs (scripts/regulation-tables/emit-field-configs-sql.ts). Restores the captured prior; deletes only 'Plan 3:' rows. Regenerate, do not hand-edit.
BEGIN;
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-06' AND f.symbol = 'grauwasserquellen' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-06' AND f.symbol = 'greywater_type_code' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-06' AND f.symbol = 'Q_GW_rows' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-06' AND f.symbol = 'total_coliforms_untreated_range' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-06' AND f.symbol = 'faecal_coliforms_untreated_range' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-08' AND f.symbol = 'sievers_statistic' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-08' AND f.symbol = 'Q_GW_P_sievers' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-08' AND f.symbol = 'COD_sievers' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-08' AND f.symbol = 'BOD5_sievers' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-08' AND f.symbol = 'TN_sievers' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-08' AND f.symbol = 'TP_sievers' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-08' AND f.symbol = 'TS_sievers' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-10' AND f.symbol = 'nutzungsarten' AND f.description LIKE 'Plan 3:%';
-- M277E-10 turbidity_NTU: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'turbidity_NTU' AND w.code = 'M277E-10' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-10 BOD5: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'BOD5' AND w.code = 'M277E-10' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-10 total_coliforms_treated: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'total_coliforms_treated' AND w.code = 'M277E-10' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-10 e_coli: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'e_coli' AND w.code = 'M277E-10' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-10 p_aeruginosa: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'p_aeruginosa' AND w.code = 'M277E-10' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-10 sampling_location: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'sampling_location' AND w.code = 'M277E-10' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-12 drinking_water_option_available: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'drinking_water_option_available' AND w.code = 'M277E-12' AND s.code = 'DWA-M-277E' AND f.active;
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-16' AND f.symbol = 'verbraucher_sw' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-16' AND f.symbol = 'bewaesserung_sw' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-16' AND f.symbol = 'Q_SW_rows' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-16' AND f.symbol = 'quality_category_code_rows' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-05' AND f.symbol = 'mbo_authorisation_code' AND f.description LIKE 'Plan 3:%';
-- M277E-19 selected_hygienisation: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'selected_hygienisation' AND w.code = 'M277E-19' AND s.code = 'DWA-M-277E' AND f.active;
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-19' AND f.symbol = 'treatment_method_allowed' AND f.description LIKE 'Plan 3:%';
-- M277E-20 membrane_process_selected: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'membrane_process_selected' AND w.code = 'M277E-20' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-20 uv_disinfection_used: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'uv_disinfection_used' AND w.code = 'M277E-20' AND s.code = 'DWA-M-277E' AND f.active;
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-21' AND f.symbol = 'speicher_277' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-21' AND f.symbol = 'storage_capacity_calc_m3' AND f.description LIKE 'Plan 3:%';
-- M277E-21 pump_station_capacity: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'pump_station_capacity' AND w.code = 'M277E-21' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-09 pump_station_capacity: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'pump_station_capacity' AND w.code = 'M277E-09' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-11 WHG_permit_present: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'WHG_permit_present' AND w.code = 'M277E-11' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-24 WHG_permit_present: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'WHG_permit_present' AND w.code = 'M277E-24' AND s.code = 'DWA-M-277E' AND f.active;
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-24' AND f.symbol = 'turbidity_limit' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-24' AND f.symbol = 'bod5_limit' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-24' AND f.symbol = 'o2_sat_min' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-24' AND f.symbol = 'ph_min_limit' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-24' AND f.symbol = 'ph_max_limit' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-24' AND f.symbol = 'total_coliforms_limit' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-24' AND f.symbol = 'e_coli_limit' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-24' AND f.symbol = 'p_aeruginosa_limit' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-24' AND f.symbol = 'ablaufproben_treated' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-24' AND f.symbol = 'treated_samples_count' AND f.description LIKE 'Plan 3:%';
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-24' AND f.symbol = 'treated_samples_fail' AND f.description LIKE 'Plan 3:%';
-- M277E-24 turbidity_NTU: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'turbidity_NTU' AND w.code = 'M277E-24' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-24 total_coliforms_treated: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'total_coliforms_treated' AND w.code = 'M277E-24' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-24 e_coli: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'e_coli' AND w.code = 'M277E-24' AND s.code = 'DWA-M-277E' AND f.active;
-- M277E-24 p_aeruginosa: the UP writes visible_when under an IS NULL guard; this restore is unguarded — re-capture before applying the rollback (a rule set after the migration is overwritten here).
UPDATE fields f SET widget = NULL, ui_config = NULL, lookup = NULL, visible_when = NULL FROM worksheet_templates w JOIN standards s ON s.id = w.standard_id WHERE f.worksheet_template_id = w.id AND f.symbol = 'p_aeruginosa' AND w.code = 'M277E-24' AND s.code = 'DWA-M-277E' AND f.active;
DELETE FROM fields f USING worksheet_templates w, standards s WHERE f.worksheet_template_id = w.id AND w.standard_id = s.id AND s.code = 'DWA-M-277E' AND w.code = 'M277E-18' AND f.symbol = 'bilanzperioden' AND f.description LIKE 'Plan 3:%';
COMMIT;
