-- ============================================================================
-- SR-1 field-verification pack — DIN-1989-2 (DIN 1989-2:2004 Regenwassernutzungsanlagen — Teil 2: Filter; the
-- rainwater-filter standard of the Blumen Forscheln deliverable V1.4)
-- Generated: 2026-09-05 — md-verified pass (owner ruling 2026-09-05: the markdown transcript is the verification
--   source; PDF only where no markdown exists). Grade: VC (SR-3), labelled as such on every row.
-- Source md: C:\Users\Ekowai\Desktop\Guidelines\DWA DIN Scribd\DIN-1989-2\DIN-1989-2.md (927 lines, German,
--   mathpix LaTeX transcript of the DIN PDF). Read completely (lines 1–734 + 735–928).
--   Page convention: the md carries ONE standalone page-number line ("8" at md line 305, after Bild 1). "printed p.N"
--   is DERIVED from the Inhalt (md lines 16–64: §1/§2 p.3 · §3 p.4 · §4 p.6 · §5.1–5.2.3 p.7 · §5.3–5.3.2 p.8 · §5.3.3 p.9 ·
--   §5.3.4–5.5 p.10 · §5.6/5.7/§6.1–6.4.1 p.11 · §6.4.2–6.4.5 p.13 · §6.4.6 p.14 · §6.5/6.5.1 p.15 · §6.5.2/6.5.3 p.16 ·
--   §7/§8 p.18 · §9 p.19 · Anhang A p.20 · B p.21 · C p.22 · D p.23 · E p.25) and cross-checked against the mathpix
--   figure page indices embedded in the md (…-08.jpg = Tab. 1/Bild 1 in §5.3, -09 = Bild 2 §5.3.3, -10 = Bild 3 §5.3.4,
--   -12 = Bild 4 §6.4.1, -20/-21/-22 = Anhang A/B/C, -23/-24 = Anhang D, -26 = Bild E.1), which coincide with the printed
--   pages and with the one printed "8". Where a clause runs onto the next page a range is given (p.4–5 for the §3
--   definitions, p.11–12 for §6.4.1, p.16–17 for §6.5.3.2, p.18–19 for §8.3). PDF confirmation would lift every row to VA.
--   LaTeX: the md writes symbols/units/formulas in LaTeX ("$\leq$ DN 200", "$V_{\text {Rück }}$", "\tag{1}"); these are
--   quoted VERBATIM (the equations already store LaTeX source_quotes). Table rows: "\hline" and the trailing "\\"
--   row terminators dropped, cells kept with "&", the table title prefixed. OCR quirks are quoted as printed and named
--   in the note ("( z . B. Speicher)", "Sp. veruur" = Sp.verunr, "DIN ISO 3301-1" = 3310-1).
--   "[...]" = omitted run inside one clause/cell; " | " joins two clauses or rows; one page ref at the end of each quote.
-- Scope A (default job): 42 fields, ALL imported_unverified → 41 quoted → verified_against_standard /
--   1 app-metadata → inferred_from_worksheet (filter_id) / 0 residue.
-- Scope B (quote backfill): 9 equations already verified_against_standard with verification_quote NULL →
--   9 quoted, STATUS UNCHANGED (guard "verification_quote is null"; rollback nulls the quote and strips the tag).
-- Equations with status ≠ verified: none. Residue equations: none.
-- Gates: 17 read, none edited here (structure/enforcement → din-1989-2-STAGED-rulings.sql).
-- Rollback: scripts/verification/rollback-din-1989-2-md-verification-pack.sql
-- ============================================================================

-- ######################## SECTION A — default job (status changes) ########################

-- App/project metadata (exempt class): DIN-1989-2-01.filter_id — a product/record identifier the standard never
-- defines as a data item (closest anchor is the informative Anhang E form line "Typenbezeichnung:", p.25).
update public.fields set verification_status='inferred_from_worksheet', verification_note='md-pass 2026-09-05: app/project metadata — the guideline does not define this field; exempt per the 2026-08-01 metadata ruling', verified_at=now() where id in ('ef8eb4a1-9b51-40d1-9388-4e311750261d') and verification_status not in ('verified_against_standard','corrected');

-- ---------- DIN-1989-2-01 Registrierung, Anwendungsbereich und Begriffe ----------

-- hersteller
update public.fields set verification_status='verified_against_standard', verification_quote='Regenwasserfilter nach dieser Norm sind deutlich sichtbar und dauerhaft wie folgt zu kennzeichnen mit: a) Nummer dieser Norm; b) Name und/oder Zeichen des Herstellers; c) Typ; — printed p.18', verification_note='md-verified 2026-09-05 (§7 b), printed p.18 derived) [VC]', verified_at=now() where id='097ec461-e2c5-4f11-a4ea-1d42e06723e9' and verification_status not in ('verified_against_standard','corrected');

-- filtertyp
update public.fields set verification_status='verified_against_standard', verification_quote='Aufgrund der unterschiedlichen Funktionsprinzipien sind Filter den in Tabelle 1 aufgeführten Typen zuzuordnen. | Tabelle 1 - Filtertypen | mit Fremdstoffrückhalt & TYP A & TYP B & - | mit Fremdstoffableitung & TYP A & TYP B & TYP C | Alle Filter mit Fremdstoffableitung ohne planmäßige Sedimentations- und Rückhaltewirkung (siehe Bild 3) sind in Typ C einzustufen. — printed p.8, p.10', verification_note='md-verified 2026-09-05 (§5.3.1 Tab. 1 + §5.3.4, printed p.8, p.10 derived); enum tokens = the three printed types; NOTE the Tab. 1 column-group header (Sedimentationsvolumen classes) is an IMAGE in the md — only the row labels are transcribed; Tab. 1 lists Typ A/B under BOTH Filterarten while §3.8/§3.9 bind A/B to Rückhalt and C to Ableitung — see STAGED S-2 [VC]', verified_at=now() where id='debeabeb-5274-4d4f-9d25-57ba49204f90' and verification_status not in ('verified_against_standard','corrected');

-- funktionsprinzip
update public.fields set verification_status='verified_against_standard', verification_quote='Hinsichtlich Bauart, Einbauort und Funktionsprinzip sind sie zu unterscheiden in: - Systeme mit separater Ableitung von Fremdstoffen; - Systeme mit Rückhaltung von Fremdstoffen innerhalb des Filters in definierten Rückhalteräumen. | Filter, mit dem auf mechanischem Wege mittels eines Filterelements vor dem Zulauf in den Speicher ungelöste Stoffe aus dem Regenwasser entfernt, aus dem Filtergehäuse herausgeführt und einer Versickerungsanlage, einem Vorfluter oder einem Kanal zugeleitet werden | Filter, mit dem auf mechanischem Wege mittels eines Filterelements vor dem Zulauf in den Speicher ungelöste Stoffe aus dem Regenwasser entfernt und vor dem Filter in einem definierten Rückhalteraum zurückgehalten werden — printed p.7, p.4–5', verification_note='md-verified 2026-09-05 (§5.1 + §3.8 Typ C + §3.9 Typ A/B, printed p.7, p.4–5 derived); the two tokens are the two printed system classes; per §3.8/§3.9 the value follows from filtertyp (A/B → Rückhalt, C → Ableitung) — duplicate candidate, STAGED S-2 [VC]', verified_at=now() where id='69513474-19e9-4966-81c4-0735f6b72eb8' and verification_status not in ('verified_against_standard','corrected');

-- einbausystem
update public.fields set verification_status='verified_against_standard', verification_quote='System, dessen Filtereinheit in einem Filtergehäuse so verankert ist, dass keine äußeren Beanspruchungen (Temperatur, Wasser- und Erddruck usw.) auf die Filtereinheit wirken | in ein gesondertes Filtergehäuse eingebaute Filtereinheit, die nicht mit anderen Funktionen einer Regenwassernutzungsanlage ( z . B. Speicher) kombiniert wird | Filtersystem, dessen Filtereinheit und -gehäuse sich oberhalb der Geländeoberkante bzw. der Rückstauebene befinden, die nicht mit anderen Funktionen einer Regenwassernutzungsanlage (z. B. Speicher) kombiniert werden — printed p.4–5', verification_note='md-verified 2026-09-05 (§3.10 integriert + §3.11 separat Erdeinbau + §3.12 separat oberirdisch, printed p.4–5 derived); "( z . B. Speicher)" is an OCR spacing quirk quoted as printed; the §5.2.3 Fallrohr case has no token (STAGED S-7c) [VC]', verified_at=now() where id='f4fc9848-9bbb-4f6b-b571-58c02c81fa3f' and verification_status not in ('verified_against_standard','corrected');

-- DN
update public.fields set verification_status='verified_against_standard', verification_quote='Filter mit Zulaufnennweiten $\leq$ DN 200 müssen allen Anforderungen dieser Norm entsprechen. Für Filter mit Zulaufnennweite > DN 200 gibt es für die Anforderung Filtertrennwirkung und hydraulischer Wirkungsgrad des dauerbelasteten Systems zur Zeit kein genormtes Prüfverfahren. Der Hersteller muss diese Werte angeben und nachvollziehbar dokumentieren, wie er diese Werte ermittelt hat. | d) Nenngröße des Zu- und Ablaufs; — printed p.7, p.18', verification_note='md-verified 2026-09-05 (§5.1 + §7 d), printed p.7, p.18 derived); DN 200 is the printed applicability threshold for §5.4.3/§5.5/§6.4.6/§6.5 — gates CR-08/CR-11 do not condition on it (STAGED S-5) [VC]', verified_at=now() where id='3d471a30-71c4-498e-8e89-01a8c5110a14' and verification_status not in ('verified_against_standard','corrected');

-- ---------- DIN-1989-2-02 Anforderungen an Filter (Werkstoffe, Typen, Hydraulik, Trennwirkung) ----------

-- Q
update public.fields set verification_status='verified_against_standard', verification_quote='$Q$ Volumenstrom in der planmäßigen Zulaufleitung | Q der Volumenstrom in der planmäßigen Zulaufleitung zum Filter bei einem Füllungsgrad von $70 \%$ und einem Gefälle von 1 \% nach DIN EN 12056-3:2001-01, Tabelle C.1, in Liter je Sekunde — printed p.6, p.8', verification_note='md-verified 2026-09-05 (§4 + §5.3.2 legend, printed p.6, p.8 derived); the VALUE comes from DIN EN 12056-3:2001-01 Tab. C.1 by DN (not in library → NR), so Q is a hand-entered lookup, not engineer data; Q, Q_max and Q_Zu_max name the same Tab. C.1 quantity — STAGED S-2 [VC]', verified_at=now() where id='575f24b4-cad1-4be3-ad90-5afca26ee3b3' and verification_status not in ('verified_against_standard','corrected');

-- Q_max
update public.fields set verification_status='verified_against_standard', verification_quote='$Q_{\text {max }} \quad$ maximal zufließender Volumenstrom in Liter je Sekunde | Bezugsgröße ist der maximal zufließende Volumenstrom $Q_{\text {max }}$, nach DIN EN 12056-3:2001-01, Tabelle C. 1 in Abhängigkeit von der Nennweite DN der Zulaufleitung bei $1 \%$ Gefälle (70 \% Füllungsgrad). — printed p.6, p.10', verification_note='md-verified 2026-09-05 (§4 + §5.4.2, printed p.6, p.10 derived); value from DIN EN 12056-3 Tab. C.1 (NR); same quantity as Q (§5.3.2) and Q_Zu_max (§6.4.6) — STAGED S-2 [VC]', verified_at=now() where id='809aa64b-3d3d-4f8e-b5c5-a9f2f406a4bb' and verification_status not in ('verified_against_standard','corrected');

-- werkstoff_filterelement
update public.fields set verification_status='verified_against_standard', verification_quote='Vorzugsweise sind Werkstoffe wie Kunststoffe, Metalle (korrosionsbeständig oder beschichtet), textile Stoffe oder Porenbeton unter Beachtung der im Abschnitt 5.2.1 genannten Kriterien zu verwenden. — printed p.7', verification_note='md-verified 2026-09-05 (§5.2.2, printed p.7 derived); "Vorzugsweise [...] wie" = preferred, exemplary list → the token "sonstige" is legitimate; the material itself must be stated (§6.2 Herstellerangaben, §7 g) so required=true stands [VC]', verified_at=now() where id='d516ce4f-ff7a-4231-a35e-ffd122d8f2bf' and verification_status not in ('verified_against_standard','corrected');

-- werkstoff_gehaeuse
update public.fields set verification_status='verified_against_standard', verification_quote='Zusätzlich zu 5.2.2 sind für separate Filtersysteme für den Erdeinbau die Anforderungen nach DIN 1989-3:2003-08, 4.2 einzuhalten. [...] Vorzugsweise sollten Werkstoffe wie Kunststoffe, Metalle (korrosionsbeständig oder beschichtet) oder Beton verwendet werden. — printed p.7', verification_note='md-verified 2026-09-05 (§5.2.3, printed p.7 derived); "sollten [...] wie" = recommendation, exemplary → "sonstige" legitimate; Erdeinbau housings additionally follow DIN 1989-3:2003-08 4.2 (NR) [VC]', verified_at=now() where id='62bbc378-2fee-435e-ac3b-b983bfc8ecfd' and verification_status not in ('verified_against_standard','corrected');

-- werkstoff_eignung_nachgewiesen
update public.fields set verification_status='verified_against_standard', verification_quote='Werkstoffe für alle Bauteile müssen für die zu erwartenden Belastungen aus den hydraulischen Kräften, wie Strömungsdruck, Sog, Rückstau, Aufstau und Wassereigengewicht geeignet sein und dabei auftretende Kräfte sicher auf das Filtergehäuse übertragen. | Die verwendeten Werkstoffe und Schutzüberzüge müssen gegen alle bei sachgemäßem Einsatz zu erwartenden physikalischen (u.a. Temperatur), chemischen und korrosiven Beanspruchungen ausreichend beständig sein. Eine Beeinträchtigung der Funktion muss ausgeschlossen sein. | Sie dürfen keine zusätzlichen Stoffe abgeben, die die Qualität des Regenwassers nachteilig beeinflussen könnten. — printed p.7', verification_note='md-verified 2026-09-05 (§5.2.1, printed p.7 derived); gate CR-02 anchors on the middle sentence [VC]', verified_at=now() where id='40084568-421e-4324-8d4b-72e5a4774f4a' and verification_status not in ('verified_against_standard','corrected');

-- temperaturbestaendig_fallrohr
update public.fields set verification_status='verified_against_standard', verification_quote='Für den Einbau in Fallrohre muss der Werkstoff zwischen $-20^{\circ} \mathrm{C}$ und $+80^{\circ} \mathrm{C}$ temperaturbeständig sein. — printed p.7', verification_note='md-verified 2026-09-05 (§5.2.3, printed p.7 derived); printed hard requirement ("muss") conditional on Fallrohr installation — no gate and no field marks the Fallrohr case (STAGED S-7c) [VC]', verified_at=now() where id='8efc35b5-fadf-44a3-93f5-34c364955928' and verification_status not in ('verified_against_standard','corrected');

-- V_Rueck_A
update public.fields set verification_status='verified_against_standard', verification_quote='Die Filtereinheiten müssen vor den Trennflächen (bei senkrechter Anordnung) oder über den Trennflächen (bei waagrechter Anordnung) ein Einstauvolumen $V_{\text {Rück }}$ nach Gleichung 1 sicherstellen. | V_{\text {Rück }}=Q \times 25 \tag{1} | $V_{\text {Rück }}$ das Einstauvolumen in Liter; [...] 25 Dauer in Sekunden. — printed p.8', verification_note='md-verified 2026-09-05 (§5.3.2 Gl.(1), printed p.8 derived); Anhang A/B print the same criterion as "$V_{\text {Rück }} \geq Q_{\text {Zu, max }} \times 25 s$" (p.20–21), i.e. Gl.(1) is a minimum — gate CR-03 ">=" is consistent; applies to Typ A only (gate not scoped, STAGED S-5) [VC]', verified_at=now() where id='e0a55dcc-b834-4f1b-9f4e-86c9bd9381ee' and verification_status not in ('verified_against_standard','corrected');

-- V_Rueck_B
update public.fields set verification_status='verified_against_standard', verification_quote='Das Volumen der herausnehmbaren Behältnisse $V_{\text {Rück }}$ muss mindestens betragen: | V_{\text {Rück }}=Q \times 2 \tag{2} | $V_{\text {Rück }}$ das Einstauvolumen in Liter; [...] 2 Dauer in Sekunden. — printed p.9', verification_note='md-verified 2026-09-05 (§5.3.3 Gl.(2), printed p.9 derived); "muss mindestens betragen" → minimum, gate CR-04 ">=" consistent; FINDING: the informative Anhang B Einstufungskriterien print "$-V_{\text {Rück }} \geq Q_{\text {zu, } \max } \times 25 \mathrm{~s}$" for Typ B (p.21) — contradicts the normative Gl.(2) factor 2; normative text wins, PDF check advised (STAGED S-9) [VC]', verified_at=now() where id='5ca57046-b54b-43f2-9c64-b257c028c5ea' and verification_status not in ('verified_against_standard','corrected');

-- behaeltnis_masse
update public.fields set verification_status='verified_against_standard', verification_quote='Die Masse eines planmäßig herausnehmbaren Behältnisses darf im gefüllten Zustand 20 kg nicht überschreiten. — printed p.9', verification_note='md-verified 2026-09-05 (§5.3.3, printed p.9 derived); printed hard limit 20 kg, gate CR-05 "<= 20" consistent; Typ B only [VC]', verified_at=now() where id='7e796266-a08b-4be3-9e57-200b78c4e609' and verification_status not in ('verified_against_standard','corrected');

-- tiefe_gok_griff
update public.fields set verification_status='verified_against_standard', verification_quote='Bei Erdeinbau darf zwischen Geländeoberkante (Schachtabdeckung) und Entnahmeelement (z. B. Haltegriff) eine Tiefe von 60 cm nicht überschritten werden. — printed p.9', verification_note='md-verified 2026-09-05 (§5.3.3, printed p.9 derived); printed hard limit 60 cm, gate CR-06 "<= 60" consistent; Typ B + Erdeinbau only [VC]', verified_at=now() where id='db627bab-b152-430b-a0d6-22ddea203df1' and verification_status not in ('verified_against_standard','corrected');

-- rueckhalteraum_zugaenglich
update public.fields set verification_status='verified_against_standard', verification_quote='Das Einstauvolumen muss für Reinigungszwecke zugänglich sein. | Diese Behältnisse müssen ohne Verwendung von Werkzeugen leicht herausnehmbar und übersichtlich angeordnet sein. — printed p.8, p.9', verification_note='md-verified 2026-09-05 (§5.3.2 + §5.3.3 (same sentence printed in both) + §5.3.3 Behältnisse, printed p.8, p.9 derived); "muss" obligation with NO gate (STAGED S-7d); the tool-free removal rule has no field [VC]', verified_at=now() where id='a83d0fc0-856c-49ed-982a-c404e30d878c' and verification_status not in ('verified_against_standard','corrected');

-- querschnitt_nicht_eingeengt
update public.fields set verification_status='verified_against_standard', verification_quote='Der Filter darf als Bestandteil der Entwässerungsanlage den Querschnitt der Zulaufleitung zum Regenwasserspeicher nicht einengen. | Die Dachentwässerung muss sowohl bei unbelastetem als auch bei belastetem Filter bei maximalem Volumenstrom ohne Rückstau sichergestellt sein (siehe DIN EN 12056-3). — printed p.10', verification_note='md-verified 2026-09-05 (§5.4.1, printed p.10 derived); gate CR-07 anchors on the first sentence; the Rückstau-free proof is §6.4.4 ("über eine Dauer von 5 min ohne Rückstau") — test-protocol parameter without field (STAGED S-7h) [VC]', verified_at=now() where id='39e8c65b-085f-44fd-991d-08d3927e54b4' and verification_status not in ('verified_against_standard','corrected');

-- eta_hydr_unbel_doku
update public.fields set verification_status='verified_against_standard', verification_quote='Der hydraulische Wirkungsgrad am unbelasteten System ist nach 6.4.5 zu ermitteln und in der Produktdokumentation anzugeben. | Bezugsgröße ist der maximal zufließende Volumenstrom $Q_{\text {max }}$, nach DIN EN 12056-3:2001-01, Tabelle C. 1 in Abhängigkeit von der Nennweite DN der Zulaufleitung bei $1 \%$ Gefälle (70 \% Füllungsgrad). — printed p.10', verification_note='md-verified 2026-09-05 (§5.4.2, printed p.10 derived); documented (manufacturer) value; the computed twin is DIN-1989-2-03.eta_hydr (Gl.(3)) — STAGED S-2 [VC]', verified_at=now() where id='c0e86394-530e-4b7f-94ff-558279f55bd4' and verification_status not in ('verified_against_standard','corrected');

-- eta_hydr_bel_doku
update public.fields set verification_status='verified_against_standard', verification_quote='Um Rückschlüsse auf die Dauerhaftigkeit und die Betriebssicherheit des Filtersystems zu ermöglichen, ist für Filter mit Zulaufnennweiten $\leq$ DN 200 der hydraulische Wirkungsgrad des belasteten Filters nach 6.4.6 zu ermitteln und in der Produktdokumentation anzugeben. — printed p.10', verification_note='md-verified 2026-09-05 (§5.4.3, printed p.10 derived); obligation for DN ≤ 200 — gate CR-11 cites §5.4.3 but its condition covers only the unbelastet value (STAGED S-3/S-7b); required=false is right because conditional on DN [VC]', verified_at=now() where id='f6c8533d-b805-4e32-a28f-43e165e0552e' and verification_status not in ('verified_against_standard','corrected');

-- dichtheit_eingehalten
update public.fields set verification_status='verified_against_standard', verification_quote='Verfügen Filter planmäßig über einen Wasserinhalt und werden diese in Böden mit Schicht- oder Grundwasser eingebaut, gelten die Anforderungen nach DIN 1989-3:2003-08, 4.4.3. | Bei allen anderen Filtern darf im Betrieb Wasser nicht unplanmäßig austreten. — printed p.11', verification_note='md-verified 2026-09-05 (§5.6, printed p.11 derived); the groundwater case defers to DIN 1989-3:2003-08 4.4.3 (NR) [VC]', verified_at=now() where id='d399fd43-aa40-400a-a8cb-af7f52640f88' and verification_status not in ('verified_against_standard','corrected');

-- standsicherheit_eingehalten
update public.fields set verification_status='verified_against_standard', verification_quote='Separate Filtersysteme für den Erdeinbau müssen den Anforderungen an die Standsicherheit für Behälter nach DIN 1989-3:2003-08, 4.4.4 entsprechen. — printed p.11', verification_note='md-verified 2026-09-05 (§5.7, printed p.11 derived); applies ONLY to separate Erdeinbau systems — gate CR-10 "== true" is unscoped (STAGED S-5); values per DIN 1989-3 (NR) [VC]', verified_at=now() where id='ccbb44f6-76bb-4363-8098-3367f76187e2' and verification_status not in ('verified_against_standard','corrected');

-- ---------- DIN-1989-2-03 Pruefungen (hydraulischer Wirkungsgrad und Filtertrennwirkung) ----------

-- Q_Zu
update public.fields set verification_status='verified_against_standard', verification_quote='$Q_{\mathrm{Zu}} \quad$ dem Filter zufließender Volumenstrom | $Q_{\mathrm{Zu}} \quad$ der dem Filtersystem zugeführte Volumenstrom in Liter je Sekunde; — printed p.6, p.13', verification_note='md-verified 2026-09-05 (§4 + §6.4.5 legend, printed p.6, p.13 derived); NOTE the §6.4.6 Gl.(5) legend prints Q_Zu as "dem Speicher zufließender Volumenstrom" — inconsistent with §4/§6.4.5; the encoding follows §4/§6.4.5 (STAGED S-9) [VC]', verified_at=now() where id='a475b605-1c9c-4593-946d-cf29f7514fab' and verification_status not in ('verified_against_standard','corrected');

-- Q_Ab
update public.fields set verification_status='verified_against_standard', verification_quote='$Q_{\mathrm{Ab}} \quad$ der vom Filtersystem in den Ablauf (z. B. Kanal, Versickerungsanlage) abgeführte Volumenstrom in Liter je Sekunde. — printed p.13', verification_note='md-verified 2026-09-05 (§6.4.5 legend, printed p.13 derived); §4 prints Q_Ab as "vom Filter abfließender und in die Speicherzulaufleitung fließender Volumenstrom" (to storage) — contradicts §6.4.5; the §3.15 ANMERKUNG (ratio of the flow forwarded INTO the storage to the DN flow) confirms the §6.4.5 reading used by Gl.(3)/(5), so the encoding is right (STAGED S-9) [VC]', verified_at=now() where id='7f250107-a6c7-4ec8-ad37-1bf467c5b731' and verification_status not in ('verified_against_standard','corrected');

-- Q_Zu_max
update public.fields set verification_status='verified_against_standard', verification_quote='Der Vorlagebehälter muss mindestens einem Volumen $V_{\text {Prüf }}$ entsprechen, das dem maximalen Volumenstrom $Q_{\mathrm{Zu}, \max }$ der jeweils vorgegebenen Nennweite des Querschnittes der Zulaufleitung bei $1 \%$ Gefälle, multipliziert mit 90 s entspricht. | $Q_{\text {Zu,max }} \quad$ maximaler Volumenstrom in Liter je Sekunde; — printed p.14', verification_note='md-verified 2026-09-05 (§6.4.6, printed p.14 derived); same Tab. C.1 quantity as Q / Q_max (STAGED S-2) [VC]', verified_at=now() where id='7a7defcc-f8ad-4e68-8a0f-5e577dba3b90' and verification_status not in ('verified_against_standard','corrected');

-- V_Pruef_leist
update public.fields set verification_status='verified_against_standard', verification_quote='V_{\text {Prüf }} \geq Q_{\mathrm{Zu}, \max } \times 90 \tag{4} | $V_{\text {Prüf }} \quad$ Volumen des Vorlagebehälters in Liter; $Q_{\text {Zu,max }} \quad$ maximaler Volumenstrom in Liter je Sekunde; 90 Dauer in Sekunden. — printed p.14', verification_note='md-verified 2026-09-05 (§6.4.6 Gl.(4), printed p.14 derived); the printed relation is "≥" — the encoded equation computes the MINIMUM (label says Mindest-), consistent [VC]', verified_at=now() where id='aaae66e8-605a-4829-a4ad-cbb88329c5e6' and verification_status not in ('verified_against_standard','corrected');

-- V_Pruef_trenn
update public.fields set verification_status='verified_against_standard', verification_quote='Der Vorlagebehälter muss mindestens einem Volumen $V_{\text {Prüf }}$ entsprechen, das dem maximalen Volumenstrom $Q_{\text {Zu, max }}$ der jeweils vorgegebenen Nennweite des Querschnittes der Zulaufleitung bei $1 \%$ Gefälle, multipliziert mit 180 s entspricht (Gleichung (6)). | V_{\text {Prüf }} \geq Q_{\text {Zu,max }} \times 180 \tag{6} — printed p.15', verification_note='md-verified 2026-09-05 (§6.5.1 Gl.(6), printed p.15 derived); "≥" minimum, equation computes the minimum — consistent [VC]', verified_at=now() where id='614270fb-7831-4e83-8973-a2c899813e9c' and verification_status not in ('verified_against_standard','corrected');

-- m_ges_festst
update public.fields set verification_status='verified_against_standard', verification_quote='$\Sigma_{\text {ges.Festst }} \quad$ Summe der zugegebenen Prüfstoffe; | Tabelle 3 - Prüfstoffe je 1000 Liter Prüfmedium | LDPE-Folie, $15 \mu \mathrm{~m}$ dick & 15 & $150{ }^{\text {a }}$ & $0,15 \mathrm{~g} / \mathrm{l}$ | Quarzsand HFs $250 \mu \mathrm{~m}$ bis $1250 \mu \mathrm{~m}$ & - & 200 & $0,20 \mathrm{~g} / \mathrm{l}$ | ${ }^{\mathrm{a}}$ Die LDPE-Folie geht fiktiv mit $10 \mathrm{~g} /$ Stück in die Massenbilanz ein. — printed p.16, p.15', verification_note='md-verified 2026-09-05 (§6.5.3.1 legend + §6.5.1 Tab. 3, printed p.16, p.15 derived); Tab. 3 fixes 150 g + 150 g (PP-Kugeln, row split across md lines) + 200 g = 500 g per 1000 l → m_ges_festst is derivable from the test-medium volume (hand-enterable derived, STAGED S-8) [VC]', verified_at=now() where id='7340f3b7-b991-41bc-a7b5-0b3440ce6a2b' and verification_status not in ('verified_against_standard','corrected');

-- m_sp_verunr
update public.fields set verification_status='verified_against_standard', verification_quote='$\Sigma_{\text {Sp.verunr }} \quad$ Summe der ermittelten Masseanteile, die in den Speicher eindringt. | Nicht abgetrennte Prüfstoffe sind am Filterablauf mit einem Drahtsieb mit einer Nennmaschenweite von $250 \mu \mathrm{~m}$ nach DIN ISO 3310-1, das zur Nasssiebung geeignet ist, aufzufangen, zu trocknen und zu wägen. — printed p.16', verification_note='md-verified 2026-09-05 (§6.5.3.1 legend + §6.5.2, printed p.16 derived); §6.4.1 prints a 125 µm sieve "nach DIN ISO 3301-1" (typo) for the wet sieving vs 250 µm here — PDF check (STAGED S-9) [VC]', verified_at=now() where id='1d8ce3d4-0bf6-469e-9e68-7ae02c7173f9' and verification_status not in ('verified_against_standard','corrected');

-- m_verw
update public.fields set verification_status='verified_against_standard', verification_quote='Verwurf abgetrennte Feststoffe, die in den Schmutzwasserabfluss geleitet werden | Bei Filtern Typ C ist der Verwurf (siehe 3.17) in gleicher Weise zu ermitteln. | $\Sigma_{\text {Verw }}$ & Summe der in die Abflussleitung eingedrungenen festen Stoffe. — printed p.5, p.16, p.16–17', verification_note='md-verified 2026-09-05 (§3.17 + §6.5.2 + §6.5.3.2 legend, printed p.5, p.16, p.16–17 derived); Typ C only — clause retag to include §3.17/§6.5.2 proposed (STAGED S-4) [VC]', verified_at=now() where id='9e519854-b82e-4a69-b187-a8202e8959c9' and verification_status not in ('verified_against_standard','corrected');

-- eta_hydr
update public.fields set verification_status='verified_against_standard', verification_quote='Der hydraulische Wirkungsgrad des unbelasteten Filtersystems ist nach Gleichung (3) zu ermitteln: | \eta_{\mathrm{hydr}}=\frac{Q_{\mathrm{Zu}}-Q_{\mathrm{Ab}}}{Q_{\mathrm{Zu}}} \tag{3} | Tabelle 2 - Prüfzeiten für Volumenströme | 100 & 2 | 50 & 2 | 20 & 3 | 10 & 4 | 5 & 8 | 2,5 & 8 | 1 & 8 — printed p.13', verification_note='md-verified 2026-09-05 (§6.4.5 Gl.(3) + Tab. 2, printed p.13 derived); derived field (equation 3); Tab. 2 prescribes seven Q_Zu/Q_Zu,max steps, the encoding holds ONE Q_Zu/Q_Ab pair — the standard reports η as a curve (Bild E.1), single-point simplification noted (STAGED S-8) [VC]', verified_at=now() where id='a539fd83-9eef-4f8a-a1d3-efb97b27f34b' and verification_status not in ('verified_against_standard','corrected');

-- eta_hyd_bel
update public.fields set verification_status='verified_against_standard', verification_quote='Das zunächst unverschmutzte Filtersystem ist mit einem konstant eingestellten Volumenstrom des mit Prüfstoffen versehenen Klarwassers von $30 \%$ des maximalen Volumenstroms $Q_{\mathrm{Zu}, \max }$ über eine Dauer von 4 min zu beaufschlagen. | Anschließend folgen mindestens 10 min Pause. Dieser intermittierende Betrieb erfolgt über 100 Zyklen. | Der hydraulische Wirkungsgrad des dauerbelasteten Filtersystems ist zu ermitteln nach: | \eta_{\text {hyd,bel }}=\frac{Q_{\mathrm{Zu}}-Q_{\mathrm{Ab}}}{Q_{\mathrm{Zu}}} \tag{5} — printed p.14', verification_note='md-verified 2026-09-05 (§6.4.6 Gl.(5), printed p.14 derived); derived field (equation 5); the 30 % / 4 min / ≥10 min / 100 Zyklen protocol has no fields (STAGED S-7h); Gl.(5) legend swaps Q_Zu/Q_Ab wording vs §6.4.5 (STAGED S-9) [VC]', verified_at=now() where id='81e181b8-5ee3-47ea-9545-cfdc6e60ffde' and verification_status not in ('verified_against_standard','corrected');

-- eta_Rueck_AB
update public.fields set verification_status='verified_against_standard', verification_quote='Für die Filter Typ A und Typ B ist die Filtertrennwirkung $\eta_{\text {Rück, } \mathrm{A}, \mathrm{B}}$ zu ermitteln aus: | \eta_{\text {Rück,A,B }}=\frac{\sum_{\text {ges.Festst }}-\sum_{\text {Sp.verunr }}}{\sum_{\text {ges.Festst }}} \tag{7} — printed p.16', verification_note='md-verified 2026-09-05 (§6.5.3.1 Gl.(7), printed p.16 derived); derived field (equation 7); Typ A/B only, yet required=true (STAGED S-6) [VC]', verified_at=now() where id='a07d8f93-3fa5-455e-a05a-26e4d3a3c3dd' and verification_status not in ('verified_against_standard','corrected');

-- eta_Verw
update public.fields set verification_status='verified_against_standard', verification_quote='Hierfür ist analog zur Ermittlung der Speicherverunreinigung in einer parallelen Messung der Quotient aus den in der Abflussleitung gefundenen Fremdstoffmassen (Verwurf) mit der Gesamtmasse an zugegebenen Fremdstoffen zu ermitteln. | \eta_{\text {Verw }}=\frac{\sum_{\text {Verw }}}{\sum_{\text {ges.Festst }}} \tag{8} — printed p.16–17', verification_note='md-verified 2026-09-05 (§6.5.3.2 Gl.(8), printed p.16–17 derived); derived field (equation 8); Typ C only [VC]', verified_at=now() where id='1b4fcd17-2321-4723-baed-111e0de5f498' and verification_status not in ('verified_against_standard','corrected');

-- eta_C
update public.fields set verification_status='verified_against_standard', verification_quote='Es wird das arithmetische Mittel aus ( $\eta_{\text {Rück }}+\eta_{\text {Verw }}$ ) gebildet, folglich gilt: | \eta_{\mathrm{C}}=0,5\left(\eta_{\text {Rück }}+\eta_{\text {Verw }}\right)=0,5 \frac{\Sigma_{\text {ges.Festst }}-\Sigma_{\text {Sp. veruur }}+\Sigma_{\text {Verw }}}{\Sigma_{\text {ges.Festst }}} \tag{9} — printed p.16–17', verification_note='md-verified 2026-09-05 (§6.5.3.2 Gl.(9), printed p.16–17 derived); derived field (equation 9); "Sp. veruur" is an OCR quirk (= Sp.verunr) quoted as printed; Anhang C worked example 0,5·(10−2+7)/10 = 0,75 confirms the composition [VC]', verified_at=now() where id='11fc2f69-0dd0-415c-af4a-2eb1571fe0dd' and verification_status not in ('verified_against_standard','corrected');

-- filtertrennwirkung_nachgewiesen
update public.fields set verification_status='verified_against_standard', verification_quote='Die Filtertrennwirkung ist für Filter mit Zulaufnennweiten $\leq$ DN 200 nachzuweisen. [...] Hinsichtlich der Abtrennung von Fremdstoffen müssen diese Filter einen Wirkungsgrad von mindestens 0,7 erreichen (siehe 6.5.3). — printed p.10', verification_note='md-verified 2026-09-05 (§5.5, printed p.10 derived); the 0,7 limit is §5.5, not §6.5.3 (clause retag STAGED S-4); boolean attestation shadows the computed eta_Rueck_AB / eta_C — numeric gate proposed (STAGED S-7a); the standard defines NO efficiency classes, only this one threshold [VC]', verified_at=now() where id='590083e0-23a5-42bd-9feb-59ed5eeff427' and verification_status not in ('verified_against_standard','corrected');

-- ---------- DIN-1989-2-04 Kennzeichnung, Konformitaetsbewertung und Einbau/Betrieb/Wartung ----------

-- kennzeichnung_vollstaendig
update public.fields set verification_status='verified_against_standard', verification_quote='Regenwasserfilter nach dieser Norm sind deutlich sichtbar und dauerhaft wie folgt zu kennzeichnen mit: a) Nummer dieser Norm; b) Name und/oder Zeichen des Herstellers; c) Typ; d) Nenngröße des Zu- und Ablaufs; e) Fließrichtung; f) Filtertrennwirkung nach 6.5.3; g) Werkstoffbezeichnung (nur bei Kunststoff nach DIN EN ISO 1043-1); h) Herstelldatum; i) Zeichen der überwachenden Stelle. — printed p.18', verification_note='md-verified 2026-09-05 (§7 a)–i), printed p.18 derived); gate CR-14 anchors on the lead sentence [VC]', verified_at=now() where id='6d1d99ed-7401-46b6-8a17-005ca4b6cb45' and verification_status not in ('verified_against_standard','corrected');

-- werkstoffbezeichnung
update public.fields set verification_status='verified_against_standard', verification_quote='g) Werkstoffbezeichnung (nur bei Kunststoff nach DIN EN ISO 1043-1); — printed p.18', verification_note='md-verified 2026-09-05 (§7 g), printed p.18 derived); designation per DIN EN ISO 1043-1 (NR); required=false is right (Kunststoff only) [VC]', verified_at=now() where id='d829f7eb-727a-4c54-b7cb-0e04f30bff60' and verification_status not in ('verified_against_standard','corrected');

-- erstpruefung_bestanden
update public.fields set verification_status='verified_against_standard', verification_quote='Vor Produktionsbeginn ist von jedem Filtersystem mindestens ein Prüfstück auf Übereinstimmung mit allen Anforderungen dieser Norm nach Abschnitt 6 zu prüfen. [...] Die Erstprüfung ist vom Hersteller durchzuführen und zu dokumentieren. Die Übereinstimmung der Produkte mit den Anforderungen dieser Norm ist durch eine akkreditierte Zertifizierungsstelle zu bestätigen. — printed p.18', verification_note='md-verified 2026-09-05 (§8.2, printed p.18 derived) [VC]', verified_at=now() where id='036aaef7-2b25-4bea-9ed2-2bfd115a2147' and verification_status not in ('verified_against_standard','corrected');

-- wpk_eingerichtet
update public.fields set verification_status='verified_against_standard', verification_quote='Der Hersteller muss entsprechend der Art des Produktes und der Art der Produktion ein geeignetes System zur Produktionskontrolle durchführen. [...] Die werkseigene Produktionskontrolle ist vom Hersteller zu dokumentieren. Der Mindestumfang der durchzuführenden Prüfungen und Kontrollen muss Tabelle 5 entsprechen. | Tabelle 5 - Werkseigene Produktionskontrolle | Werkstoff & Abschnitt 5 & Inaugenscheinnahme des Lieferscheines & Jede Anlieferung | Maße & Herstellerunterlagen & Vergleich mit Erstprüfstück & Halbjährlich an einem Prüfstück — printed p.18–19', verification_note='md-verified 2026-09-05 (§8.3 + Tab. 5, printed p.18–19 derived); the md transcribes only two Tab. 5 rows (Werkstoff, Maße) — PDF check whether more rows exist (STAGED S-9); "kann auf der Grundlage von DIN EN ISO 9001" is optional basis, the "muss ... durchführen" is hard [VC]', verified_at=now() where id='5d5591fe-54bc-45fc-b8fe-61d04f2299ad' and verification_status not in ('verified_against_standard','corrected');

-- pruefberichte_aufbewahrung_jahre
update public.fields set verification_status='verified_against_standard', verification_quote='Die Prüfungsunterlagen sind vom Hersteller solange aufzubewahren, wie das betreffende Produkt am Markt angeboten und in Verkehr gebracht wird, jedoch mindestens 10 Jahre. | Die vollständigen Prüfberichte sind vom Hersteller mindestens 10 Jahre aufzubewahren. — printed p.18, p.19', verification_note='md-verified 2026-09-05 (§8.2 + §8.3, printed p.18, p.19 derived); printed fixed minimum (10 a) held in a hand-enterable number with NO gate — standard_fixed-editable finding, gate ">= 10" proposed (STAGED S-7e) [VC]', verified_at=now() where id='394e7b5c-d99d-4cb3-8687-c7487710bc06' and verification_status not in ('verified_against_standard','corrected');

-- anleitung_vorhanden
update public.fields set verification_status='verified_against_standard', verification_quote='Alle Filter sind vom Hersteller mit einer ausreichenden Produktbeschreibung, insbesondere der Funktionsweise, sowie einer Einbau-, Betriebs- und Wartungsanleitung zu versehen und nach diesen zu installieren, zu betreiben und zu warten. | Die Einbauanweisung muss eine Beschreibung und eine Zeichnung mit Darstellung der erforderlichen Randbedingungen (z. B. Beschaffenheit der Baugrube, Verfüllung usw.) und der Montage des Filters (ggf. aller beweglichen Teile) enthalten. — printed p.19', verification_note='md-verified 2026-09-05 (§9, printed p.19 derived); the Betriebsanleitung content is "sollte" (recommendation) — the existence obligation and the Einbauanweisung content are hard, so block gate CR-15 stands [VC]', verified_at=now() where id='e609bed5-343f-468f-9885-4a08ecb89e0c' and verification_status not in ('verified_against_standard','corrected');

-- ######################## SECTION B — equation quote backfill, STATUS UNCHANGED ########################
-- All 9 equations are already verified_against_standard (encode-time, source_quote stored) but verification_quote is
-- NULL. Only verification_quote is filled and a " | md-quote 2026-09-05 (…) [VC]" tag appended to verification_note;
-- the guard "verification_quote is null" makes every statement idempotent. Rollback: null the quote where the note
-- carries the tag.

-- Gl.(1) V_Rueck_A = Q * 25
update public.equations set verification_quote='Die Filtereinheiten müssen vor den Trennflächen (bei senkrechter Anordnung) oder über den Trennflächen (bei waagrechter Anordnung) ein Einstauvolumen $V_{\text {Rück }}$ nach Gleichung 1 sicherstellen. | V_{\text {Rück }}=Q \times 25 \tag{1} | Dabei ist $V_{\text {Rück }}$ das Einstauvolumen in Liter; Q der Volumenstrom in der planmäßigen Zulaufleitung zum Filter bei einem Füllungsgrad von $70 \%$ und einem Gefälle von 1 \% nach DIN EN 12056-3:2001-01, Tabelle C.1, in Liter je Sekunde 25 Dauer in Sekunden. — printed p.8', verification_note=coalesce(verification_note,'')||' | md-quote 2026-09-05 (§5.3.2 Gl.(1), printed p.8 derived; formula matches the encoded V_Rueck_A = Q * 25; Anhang A prints the criterion as "≥" (minimum); status unchanged — quote backfill only) [VC]' where id='46fb74c9-af5e-4705-8b7e-7c56e595240e' and verification_quote is null;

-- Gl.(2) V_Rueck_B = Q * 2
update public.equations set verification_quote='Das Volumen der herausnehmbaren Behältnisse $V_{\text {Rück }}$ muss mindestens betragen: | V_{\text {Rück }}=Q \times 2 \tag{2} | Dabei ist $V_{\text {Rück }}$ das Einstauvolumen in Liter; $Q$ der Volumenstrom in der planmäßigen Zulaufleitung zum Filter bei einem Füllungsgrad von $70 \%$ und einem Gefälle von 1 \% nach DIN EN 12056-3:2001-01, Tabelle C.1, in Liter je Sekunde; 2 Dauer in Sekunden. — printed p.9', verification_note=coalesce(verification_note,'')||' | md-quote 2026-09-05 (§5.3.3 Gl.(2), printed p.9 derived; formula matches the encoded V_Rueck_B = Q * 2 ("muss mindestens betragen" → minimum); informative Anhang B prints "× 25 s" for Typ B — normative Gl.(2) wins, PDF check advised; status unchanged — quote backfill only) [VC]' where id='f1ac6dff-12fa-43f4-af5b-2b0796ed349b' and verification_quote is null;

-- Gl.(3) eta_hydr = (Q_Zu - Q_Ab) / Q_Zu
update public.equations set verification_quote='Der hydraulische Wirkungsgrad des unbelasteten Filtersystems ist nach Gleichung (3) zu ermitteln: | \eta_{\mathrm{hydr}}=\frac{Q_{\mathrm{Zu}}-Q_{\mathrm{Ab}}}{Q_{\mathrm{Zu}}} \tag{3} | Dabei ist $Q_{\mathrm{Zu}} \quad$ der dem Filtersystem zugeführte Volumenstrom in Liter je Sekunde; $Q_{\mathrm{Ab}} \quad$ der vom Filtersystem in den Ablauf (z. B. Kanal, Versickerungsanlage) abgeführte Volumenstrom in Liter je Sekunde. — printed p.13', verification_note=coalesce(verification_note,'')||' | md-quote 2026-09-05 (§6.4.5 Gl.(3), printed p.13 derived; formula matches the encoded eta_hydr = (Q_Zu - Q_Ab) / Q_Zu; status unchanged — quote backfill only) [VC]' where id='c44be6b5-448a-43f8-9755-ff041c659246' and verification_quote is null;

-- Gl.(4) V_Pruef_leist = Q_Zu_max * 90
update public.equations set verification_quote='Der Vorlagebehälter muss mindestens einem Volumen $V_{\text {Prüf }}$ entsprechen, das dem maximalen Volumenstrom $Q_{\mathrm{Zu}, \max }$ der jeweils vorgegebenen Nennweite des Querschnittes der Zulaufleitung bei $1 \%$ Gefälle, multipliziert mit 90 s entspricht. | V_{\text {Prüf }} \geq Q_{\mathrm{Zu}, \max } \times 90 \tag{4} | Dabei ist $V_{\text {Prüf }} \quad$ Volumen des Vorlagebehälters in Liter; $Q_{\text {Zu,max }} \quad$ maximaler Volumenstrom in Liter je Sekunde; 90 Dauer in Sekunden. — printed p.14', verification_note=coalesce(verification_note,'')||' | md-quote 2026-09-05 (§6.4.6 Gl.(4), printed p.14 derived; printed "≥" — the encoded V_Pruef_leist = Q_Zu_max * 90 computes the minimum; status unchanged — quote backfill only) [VC]' where id='41935d13-1d60-49f6-8308-25d0203c44f0' and verification_quote is null;

-- Gl.(5) eta_hyd_bel = (Q_Zu - Q_Ab) / Q_Zu
update public.equations set verification_quote='Der hydraulische Wirkungsgrad des dauerbelasteten Filtersystems ist zu ermitteln nach: | \eta_{\text {hyd,bel }}=\frac{Q_{\mathrm{Zu}}-Q_{\mathrm{Ab}}}{Q_{\mathrm{Zu}}} \tag{5} | Dabei ist $\eta_{\text {hyd,bel }} \quad$ der hydraulische Wirkungsgrad des dauerbelasteten Systems; $Q_{\mathrm{Ab}} \quad$ der Kanalisation oder der Versickerungsanlage zufließende Volumenstrom; $Q_{\mathrm{Zu}} \quad$ dem Speicher zufließender Volumenstrom. — printed p.14', verification_note=coalesce(verification_note,'')||' | md-quote 2026-09-05 (§6.4.6 Gl.(5), printed p.14 derived; formula matches the encoded eta_hyd_bel = (Q_Zu - Q_Ab) / Q_Zu; the printed legend calls Q_Zu "dem Speicher zufließender Volumenstrom" — inconsistent with §4/§6.4.5 (Q_Zu = to the filter), encoding follows §6.4.5; status unchanged — quote backfill only) [VC]' where id='b6241c7a-4a65-4052-9ea9-9b7704e5d0e1' and verification_quote is null;

-- Gl.(6) V_Pruef_trenn = Q_Zu_max * 180
update public.equations set verification_quote='Der Vorlagebehälter muss mindestens einem Volumen $V_{\text {Prüf }}$ entsprechen, das dem maximalen Volumenstrom $Q_{\text {Zu, max }}$ der jeweils vorgegebenen Nennweite des Querschnittes der Zulaufleitung bei $1 \%$ Gefälle, multipliziert mit 180 s entspricht (Gleichung (6)). | V_{\text {Prüf }} \geq Q_{\text {Zu,max }} \times 180 \tag{6} | Dabei ist $V_{\text {Prüf }} \quad$ Volumen des Vorlagebehälters in Liter; $Q_{\mathrm{Zu} \text { max }} \quad$ maximaler Volumenstrom in Liter je Sekunde; 180 Dauer in Sekunden. — printed p.15', verification_note=coalesce(verification_note,'')||' | md-quote 2026-09-05 (§6.5.1 Gl.(6), printed p.15 derived; printed "≥" — the encoded V_Pruef_trenn = Q_Zu_max * 180 computes the minimum; status unchanged — quote backfill only) [VC]' where id='fd3184a2-6cdb-4498-b78a-083033d12978' and verification_quote is null;

-- Gl.(7) eta_Rueck_AB = (m_ges_festst - m_sp_verunr) / m_ges_festst
update public.equations set verification_quote='Für die Filter Typ A und Typ B ist die Filtertrennwirkung $\eta_{\text {Rück, } \mathrm{A}, \mathrm{B}}$ zu ermitteln aus: | \eta_{\text {Rück,A,B }}=\frac{\sum_{\text {ges.Festst }}-\sum_{\text {Sp.verunr }}}{\sum_{\text {ges.Festst }}} \tag{7} | $\Sigma_{\text {ges.Festst }} \quad$ Summe der zugegebenen Prüfstoffe; $\Sigma_{\text {Sp.verunr }} \quad$ Summe der ermittelten Masseanteile, die in den Speicher eindringt. — printed p.16', verification_note=coalesce(verification_note,'')||' | md-quote 2026-09-05 (§6.5.3.1 Gl.(7), printed p.16 derived; formula matches the encoded eta_Rueck_AB = (m_ges_festst - m_sp_verunr) / m_ges_festst; Anhang A/B worked example (10−3)/10 = 0,7; status unchanged — quote backfill only) [VC]' where id='20c140c2-3bdb-4ed4-937f-b0bded5cd925' and verification_quote is null;

-- Gl.(8) eta_Verw = m_verw / m_ges_festst
update public.equations set verification_quote='Hierfür ist analog zur Ermittlung der Speicherverunreinigung in einer parallelen Messung der Quotient aus den in der Abflussleitung gefundenen Fremdstoffmassen (Verwurf) mit der Gesamtmasse an zugegebenen Fremdstoffen zu ermitteln. | \eta_{\text {Verw }}=\frac{\sum_{\text {Verw }}}{\sum_{\text {ges.Festst }}} \tag{8} — printed p.16–17', verification_note=coalesce(verification_note,'')||' | md-quote 2026-09-05 (§6.5.3.2 Gl.(8), printed p.16–17 derived; formula matches the encoded eta_Verw = m_verw / m_ges_festst; Anhang C worked example 7/10 = 0,7; status unchanged — quote backfill only) [VC]' where id='64f61270-2f75-4f4b-8e5d-25893c023e93' and verification_quote is null;

-- Gl.(9) eta_C = 0.5 * (m_ges_festst - m_sp_verunr + m_verw) / m_ges_festst
update public.equations set verification_quote='Es wird das arithmetische Mittel aus ( $\eta_{\text {Rück }}+\eta_{\text {Verw }}$ ) gebildet, folglich gilt: | \eta_{\mathrm{C}}=0,5\left(\eta_{\text {Rück }}+\eta_{\text {Verw }}\right)=0,5 \frac{\Sigma_{\text {ges.Festst }}-\Sigma_{\text {Sp. veruur }}+\Sigma_{\text {Verw }}}{\Sigma_{\text {ges.Festst }}} \tag{9} — printed p.16–17', verification_note=coalesce(verification_note,'')||' | md-quote 2026-09-05 (§6.5.3.2 Gl.(9), printed p.16–17 derived; formula matches the encoded eta_C = 0.5 * (m_ges_festst - m_sp_verunr + m_verw) / m_ges_festst; "Sp. veruur" = OCR of Sp.verunr; Anhang C worked example 0,5·(10−2+7)/10 = 0,75; status unchanged — quote backfill only) [VC]' where id='8c7c52f1-9976-452c-a3c1-cf00131697e6' and verification_quote is null;
