-- HOAI-2021 — md verification pack (2026-09-05 pass, run 2026-09-07)
-- Source md : C:\Users\Ekowai\Desktop\Guidelines\DWA DIN Scribd\bayika-hoai-2021\bayika_hoai_2021.md
-- PROVENANCE: CLEAN — PRIMARY TEXT, not a chamber commentary. The file is a Textausgabe: its own title
--             block reads "Honorarordnung für Architekten und Ingenieure – HOAI / Textausgabe mit
--             amtlicher Begründung" (printed p.2) and it reproduces the Verordnung's own §§ 1-57 verbatim
--             ("Verordnung über die Honorare für Architekten- und Ingenieurleistungen (Honorarordnung für
--             Architekten und Ingenieure - HOAI)", Eingangsformel, Inhaltsübersicht, printed p.3), in the
--             2021 version (§ 57 Abs. 2 references the Erste Verordnung zur Änderung der HOAI vom
--             2. Dezember 2020, BGBl. I S. 2636). The Bayerische Ingenieurekammer-Bau appears ONLY as the
--             imprint on the last page ("© 2021 Bayerische Ingenieurekammer-Bau ... Quellen: Bundesamt für
--             Justiz | Bundesministerium der Justiz und für Verbraucherschutz | ... | www.gesetze-im-internet.de",
--             printed p.135). It contributes no commentary and no fee tables of its own: the non-Verordnung
--             content is the amtliche Begründung (Bundesrat-Drucksache 539/20, printed p.115 ff.) and the
--             ArchLG (printed p.126 ff.) — both primary federal documents. Every quote below is from the
--             Verordnung text itself, so nothing rests on a secondary source. Machine-translation markers
--             ("Traducido", "Translated from", "onlinedoctranslator") are ABSENT — the transcript is German original.
-- Language  : German (Verordnung original).
-- Pages     : the transcript carries 135 "===== PAGE N =====" markers, each immediately followed by the
--             page's own running head "- Seite N -"; a programmatic check found 135/135 markers with a
--             matching head and 0 mismatches, so marker N = the Textausgabe's printed page N. The
--             Inhaltsverzeichnis (printed p.2) confirms the mapping (Verordnung p.3, Begründung p.115,
--             ArchLG p.126). Every quote carries its page ONCE at the end; a quote joined from two
--             different pages carries both, in quote order.
-- Artefacts : this pdftotext transcript splits words at the justification break ("w eisen", "allgeme in",
--             "st ets", "Honorarrege lungen", "Leistungsphas e 6", "Hon orartafel", "Anrechen bar").
--             Those are quoted AS THEY STAND rather than silently repaired, so every quote stays
--             byte-verifiable against the transcript.
-- Lists     : numbered Absatz items are joined to their lead-in with " | " (house style); an omitted run
--             inside one clause is [...].
-- Grade     : [VC] markdown-verified (SR-3: the rendered PDF was not read this session).
-- SCOPE     : the HOAI is a Verordnung, so its "ist zu"/"sind zu" is genuinely binding — BUT since the
--             2021 amendment the Honorartafeln are explicitly ORIENTATION values, not binding min/max
--             rates: § 2a Abs. 1 "Die Honorartafeln dieser Verordnung w eisen Orientierungswerte aus"
--             (printed p.6) and every Honorartafel headline reads "sind die in der nachstehenden
--             Honorartafel aufgeführten Honorarspannen Orientierungswerte" (§§ 20, 21, 35, 40, 44, 48,
--             52, 56). § 7 Abs. 2 confirms a higher OR lower fee may be agreed. Findings on gates that
--             would enforce more than this are in hoai-2021-STAGED-rulings.sql.
-- Counts    : 94 fields examined / 92 quoted / 2 exempt / 0 residue /
--             6 equations (all 6 already verified_against_standard with a NULL verification_quote —
--             this pack BACKFILLS the quote only, guard "verification_quote is null", status untouched).
-- Rollback  : rollback-hoai-2021-md-verification-pack.sql
-- No transaction control in this file: apply-pack.mjs supplies BEGIN/COMMIT and implements --dry-run by
-- rolling back; an inline commit would end that transaction early and turn a dry run into a real apply.


-- ================= HOAI-2021-01 =================
-- HOAI-2021-01 · hoai_anwendbar
update public.fields set verification_status='verified_against_standard', verification_quote='§ 1 Anwendungsbereich Diese Verordnung gilt für Honorare für Ingenieur- und Architektenleistungen, soweit diese Leistungen durch diese Verordnung erfasst sind. Die Regelungen dieser Verordnung können zum Zwecke der Honorarberechnung einer Honorarvereinbarung zugrunde gelegt werden. — printed p.6', verification_note='md-verified 2026-09-05 (§1, printed p.6) [VC]', verified_at=now() where id='fe5e9e54-872b-4669-84b5-8d8be8c64c9a' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-01 · objektart
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Objekte sind Gebäude, Innenräume, Freianlagen, Ingenieurbauwerke, Verkehrsanlagen. Objekte sind auch Tragwerke und Anlagen der Technischen Ausrüstung. — printed p.6', verification_note='md-verified 2026-09-05 (§2 Abs.1, printed p.6) [VC]', verified_at=now() where id='468f5751-d537-45f4-969a-3b5479095b6e' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-01 · massnahmenart
update public.fields set verification_status='verified_against_standard', verification_quote='(2) Neubauten und Neuanlagen sind Objekte, die neu errichtet oder neu hergestellt werden. | (3) Wiederaufbauten sind Objekte, bei denen die zerstörten Teile auf noch vorhandenen Bau- oder Anlagenteilen | (4) Erweiterungsbauten sind Ergänzungen eines vorhandenen Objekts. | (5) Umbauten sind Umgestaltungen eines vorhandenen Objekts mit wesentlichen Eingriffen in Konstruktion oder | (6) Modernisierungen sind bauliche Maßnahmen zur nachhaltigen Erhöhung des Gebrauchswertes eines Objekts, | (8) Instandsetzungen sind Maßnahmen zur Wiederherstellung des zum bestimmungsgemäßen Gebrauch | (9) Instandhaltungen sind Maßnahmen zur Erhaltung des Soll-Zustandes eines Objekts. — printed p.6', verification_note='md-verified 2026-09-05 (§2 Abs.2-9, printed p.6) [VC] — the seven enum values map 1:1 onto § 2 Abs. 2 (Neubau/Neuanlage), 3 (Wiederaufbau), 4 (Erweiterungsbau), 5 (Umbau), 6 (Modernisierung), 8 (Instandsetzung), 9 (Instandhaltung); only the defining first line of each Absatz is quoted', verified_at=now() where id='42beb5b4-823c-4727-a43a-6394b101c026' and verification_status not in ('verified_against_standard','corrected');

-- ================= HOAI-2021-02 =================
-- HOAI-2021-02 · K
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Anrechenbare Kosten sind Teil der Kosten für die Herstellung, den Umbau, die Modernisierung, Instandhaltung oder Instandsetzung von Objekten sowie für die damit zusammenhängenden Aufwendungen. Sie | bei der Ermittlung der anrechenbaren Kosten zugrunde zu legen. Umsatzsteuer, die auf die Kosten von Objekten entfällt, ist nicht Bestandteil der anrechenbaren Kosten. | 2. für die Leistungsbilder der Teile 3 und 4 und der Anlage 1 Nummer 1.2, 1.3 und 1.4.5 nach den anrechenbaren Kosten des Objekts auf der Grundlage der Kostenberechnung oder, sofern keine Kostenberechnung vorliegt, auf der Grundlage der Kostenschätzung, — printed p.7', verification_note='md-verified 2026-09-05 (§4 Abs.1; §6 Abs.1, printed p.7) [VC]', verified_at=now() where id='05195481-5ae0-4b14-9c15-86aef0d578f7' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-02 · honorarzone
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Die Grundleistungen der Flächen-, Objekt- oder Fachplanungen werden zur Berechnung der Honorare nach den jeweiligen Planungsanforderungen Honorarzonen zugeordnet, die von der Honorarzone I aus ansteigend den Schwierigkeitsgrad der Planung einstufen. — printed p.7', verification_note='md-verified 2026-09-05 (§5 Abs.1, printed p.7) [VC] — the Verordnung fixes zones I-V only for the Teil-3/Teil-4 Leistungsbilder; Bauleitplanung (§20 Abs.5, §21) and Technische Ausruestung (§56) print only I-III — see the STAGED file', verified_at=now() where id='2d594be3-d0b7-407d-826b-4a1e07063157' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-02 · bewertungspunkte
update public.fields set verification_status='verified_against_standard', verification_quote='(2) Die Honorarzonen sind anhand der Bewertungsmerkmale in den Honorarrege lungen der jeweiligen Leistungsbilder der Teile 2 bis 4 und der Anlage 1 zu ermitteln. Die Zurechnung zu den einzelnen Honorarzonen ist nach Maßgabe der Bewertungsmerkmale und gegebenenfalls der Bewertungspunkte sowie unter Berücksichtigung der Regelbeispiele in den Objektlisten der Anlagen dieser Verordnung vorzunehmen. — printed p.7', verification_note='md-verified 2026-09-05 (§5 Abs.2, printed p.7) [VC] — the point thresholds themselves are per-Leistungsbild, e.g. § 35 Abs. 6 (printed p.24): Honorarzone I bis zu 10 Punkte, II 11 bis 18, III 19 bis 26, IV 27 bis 34, V 35 bis 42', verified_at=now() where id='e1e766c6-201d-4632-8328-dabdbfd5b0d1' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-02 · leistungsbild
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Bei der Ermittlung des Honorars für Grundleistungen im Sinne des § 3 Absatz 1 sind zugrunde zu legen 1. das Leistungsbild, 2. die Honorarzone und 3. die dazugehörige Hon orartafel zur Honorarorientierung. | (1) Grundleistungen sind Leistungen, die regelmäßig im Rahmen von Flächen-, Objekt- oder Fachplanungen auszuführen sind. Sie sind zur ordnungsgemäßen Erfüllung eines Auftrags im Allgemeinen erforderlich und in Leistungsbildern erfasst. Die Leistungsbilder gliedern sich in Leistungsphasen nach den Regelungen in den Teilen 2 bis 4 und der Anlage 1. — printed p.7', verification_note='md-verified 2026-09-05 (§6 Abs.1; §3 Abs.1, printed p.7) [VC]', verified_at=now() where id='94ac694b-88ea-437c-bf2d-a49b248c3fd6' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-02 · flaeche
update public.fields set verification_status='verified_against_standard', verification_quote='1. für die Leistungsbilder des Teils 2 und der Anlage 1 Nummer 1.1 nach der Größe der Fläche, | (2) Das Honorar für die Aufstellung von Flächennutzungsplänen ist nach der Fläche des Plangebiets in Hektar und nach der Honorarzone zu berechnen. — printed p.7, p.12', verification_note='md-verified 2026-09-05 (§6 Abs.1; §20 Abs.2, printed p.7, p.12) [VC]', verified_at=now() where id='a5c95c50-197c-434e-93f2-5f64126ff12a' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-02 · K_u
update public.fields set verification_status='verified_against_standard', verification_quote='§ 13 Interpolation Zwischenstufen der in den Honorartafeln angegebenen anrechenbaren Kosten und Flächen oder Verrechnungseinheiten sind durch lineare Interpolation zu ermitteln. — printed p.9', verification_note='md-verified 2026-09-05 (§13, printed p.9) [VC]', verified_at=now() where id='be5abcd5-425f-45e2-9109-3c2ac7d07645' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-02 · K_o
update public.fields set verification_status='verified_against_standard', verification_quote='§ 13 Interpolation Zwischenstufen der in den Honorartafeln angegebenen anrechenbaren Kosten und Flächen oder Verrechnungseinheiten sind durch lineare Interpolation zu ermitteln. — printed p.9', verification_note='md-verified 2026-09-05 (§13, printed p.9) [VC]', verified_at=now() where id='9c1c4df6-acb1-44f4-857b-3ab9699a201c' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-02 · H_u_unten
update public.fields set verification_status='verified_against_standard', verification_quote='(2) Basishonorarsatz ist der jeweils untere in den Honorartafeln dieser Verordnung enthaltene Honorarsatz. | § 13 Interpolation Zwischenstufen der in den Honorartafeln angegebenen anrechenbaren Kosten und Flächen oder Verrechnungseinheiten sind durch lineare Interpolation zu ermitteln. — printed p.7, p.9', verification_note='md-verified 2026-09-05 (§2a Abs.2; §13, printed p.7, p.9) [VC]', verified_at=now() where id='bd898cd2-bcf5-4e34-9259-aef8c86d3666' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-02 · H_o_unten
update public.fields set verification_status='verified_against_standard', verification_quote='(2) Basishonorarsatz ist der jeweils untere in den Honorartafeln dieser Verordnung enthaltene Honorarsatz. | § 13 Interpolation Zwischenstufen der in den Honorartafeln angegebenen anrechenbaren Kosten und Flächen oder Verrechnungseinheiten sind durch lineare Interpolation zu ermitteln. — printed p.7, p.9', verification_note='md-verified 2026-09-05 (§2a Abs.2; §13, printed p.7, p.9) [VC]', verified_at=now() where id='77b5ad87-d6da-4edb-928c-5a50cdb8c418' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-02 · H_u_oben
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Die Honorartafeln dieser Verordnung w eisen Orientierungswerte aus, die an der Art und dem Umfang der Aufgabe sowie an der Leistung ausgerichtet sind. Die Honorartafeln enthalten für jeden Leistungsbereich Honorarspannen vom Basishonorarsatz bis zum oberen Honorarsatz, gegliedert nach den einzelnen Honorarzonen und den zugrunde liegenden Ansätzen für Flächen, anrechenbare Kosten oder Verrechnungseinheiten. | § 13 Interpolation Zwischenstufen der in den Honorartafeln angegebenen anrechenbaren Kosten und Flächen oder Verrechnungseinheiten sind durch lineare Interpolation zu ermitteln. — printed p.6, p.9', verification_note='md-verified 2026-09-05 (§2a Abs.1; §13, printed p.6, p.9) [VC]', verified_at=now() where id='b82967e0-9c78-42eb-8d01-2fab1cc82e06' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-02 · H_o_oben
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Die Honorartafeln dieser Verordnung w eisen Orientierungswerte aus, die an der Art und dem Umfang der Aufgabe sowie an der Leistung ausgerichtet sind. Die Honorartafeln enthalten für jeden Leistungsbereich Honorarspannen vom Basishonorarsatz bis zum oberen Honorarsatz, gegliedert nach den einzelnen Honorarzonen und den zugrunde liegenden Ansätzen für Flächen, anrechenbare Kosten oder Verrechnungseinheiten. | § 13 Interpolation Zwischenstufen der in den Honorartafeln angegebenen anrechenbaren Kosten und Flächen oder Verrechnungseinheiten sind durch lineare Interpolation zu ermitteln. — printed p.6, p.9', verification_note='md-verified 2026-09-05 (§2a Abs.1; §13, printed p.6, p.9) [VC]', verified_at=now() where id='87f54e2e-c357-4be4-b769-966637b02a4a' and verification_status not in ('verified_against_standard','corrected');

-- ================= HOAI-2021-03 =================
-- HOAI-2021-03 · H_basis
update public.fields set verification_status='verified_against_standard', verification_quote='§ 13 Interpolation Zwischenstufen der in den Honorartafeln angegebenen anrechenbaren Kosten und Flächen oder Verrechnungseinheiten sind durch lineare Interpolation zu ermitteln. | (2) Basishonorarsatz ist der jeweils untere in den Honorartafeln dieser Verordnung enthaltene Honorarsatz. — printed p.9, p.7', verification_note='md-verified 2026-09-05 (§13; §2a Abs.2, printed p.9, p.7) [VC] — the Verordnung prescribes "lineare Interpolation" in words; the algebraic form in the encoding is EKOWAI’s rendering of that instruction, not a printed formula', verified_at=now() where id='446690b8-71d7-411d-be1f-630e4769d515' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-03 · H_oben
update public.fields set verification_status='verified_against_standard', verification_quote='§ 13 Interpolation Zwischenstufen der in den Honorartafeln angegebenen anrechenbaren Kosten und Flächen oder Verrechnungseinheiten sind durch lineare Interpolation zu ermitteln. | (1) Die Honorartafeln dieser Verordnung w eisen Orientierungswerte aus, die an der Art und dem Umfang der Aufgabe sowie an der Leistung ausgerichtet sind. Die Honorartafeln enthalten für jeden Leistungsbereich Honorarspannen vom Basishonorarsatz bis zum oberen Honorarsatz, gegliedert nach den — printed p.9, p.6', verification_note='md-verified 2026-09-05 (§13; §2a Abs.1, printed p.9, p.6) [VC] — the Verordnung prescribes "lineare Interpolation" in words; the algebraic form in the encoding is EKOWAI’s rendering of that instruction, not a printed formula', verified_at=now() where id='48b63524-cced-493c-9b80-e15e1fc4f3de' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-03 · H_tafel
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Die Honorartafeln dieser Verordnung w eisen Orientierungswerte aus, die an der Art und dem Umfang der Aufgabe sowie an der Leistung ausgerichtet sind. Die Honorartafeln enthalten für jeden Leistungsbereich Honorarspannen vom Basishonorarsatz bis zum oberen Honorarsatz, gegliedert nach den einzelnen Honorarzonen und den zugrunde liegenden Ansätzen für Flächen, anrechenbare Kosten oder Verrechnungseinheiten. — printed p.6', verification_note='md-verified 2026-09-05 (§2a Abs.1, printed p.6) [VC] — the Honorartafel values are ORIENTIERUNGSWERTE, not binding minimum/maximum rates — a value outside the printed Spanne is lawful (§7 Abs.1/Abs.2)', verified_at=now() where id='3ad67ddc-c6cb-41c9-95fe-80167dad43af' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-03 · s_satz
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Die Honorartafeln dieser Verordnung w eisen Orientierungswerte aus, die an der Art und dem Umfang der Aufgabe sowie an der Leistung ausgerichtet sind. Die Honorartafeln enthalten für jeden Leistungsbereich Honorarspannen vom Basishonorarsatz bis zum oberen Honorarsatz, gegliedert nach den | (1) Das Honorar richtet sich nach der Vereinbarung, die die Vertragsparteien in Textform treffen. Sofern keine Vereinbarung über die Höhe des Honorars in Textform getroffen wurde, gilt für Grundleistungen der jeweilige Basishonorarsatz als vereinbart, der sich bei der Anwendung der Honorargrundlagen des § 6 ergibt. — printed p.6, p.8', verification_note='md-verified 2026-09-05 (§2a Abs.1; §7 Abs.1, printed p.6, p.8) [VC] — the 0..1 parametrisation of the position inside the Honorarspanne is EKOWAI’s; the Verordnung names only the two ends (Basishonorarsatz / oberer Honorarsatz) and leaves the point free (SR-2 selection)', verified_at=now() where id='9e34a771-a839-4b11-a33c-07445d3ac733' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-03 · p_sum
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Werden dem Auftragnehmer nicht alle Leistungsphasen eines Leistungsbildes übertragen, so dürfen nur die für die übertragenen Phasen vorgesehenen Prozentsätze berechnet und vereinbart werden. Die Vereinbarung hat in Textform zu erfolgen. — printed p.8', verification_note='md-verified 2026-09-05 (§8 Abs.1, printed p.8) [VC]', verified_at=now() where id='d84ab438-5f31-4d28-9af5-868af1bd45ae' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-03 · H_phasen
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Werden dem Auftragnehmer nicht alle Leistungsphasen eines Leistungsbildes übertragen, so dürfen nur die für die übertragenen Phasen vorgesehenen Prozentsätze berechnet und vereinbart werden. Die Vereinbarung hat in Textform zu erfolgen. — printed p.8', verification_note='md-verified 2026-09-05 (§8 Abs.1, printed p.8) [VC]', verified_at=now() where id='cf28339b-74c1-4122-a4d7-62c80f24f91c' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-03 · z_umbau
update public.fields set verification_status='verified_against_standard', verification_quote='Der Umbau- oder Modernisierungszuschlag ist unter Berücksichtigung des Schwierigkeitsgrads der Leistungen in Textform zu vereinbaren. Die Höhe des Zuschlags auf das Honorar ist in den jeweiligen Honorarregelungen der Leistungsbilder der Teile 3 und 4 und in Anlage 1 Nummer 1.2 geregelt. Sofern keine Vereinbarung in Textform getroffen wurde, gilt ein Zuschlag von 20 Prozent ab einem durchschnittlichen Schwierigkeitsgrad als vereinbart. — printed p.8', verification_note='md-verified 2026-09-05 (§6 Abs.2, printed p.8) [VC] — the 20 % default applies only in the absence of a Textform agreement; the per-Leistungsbild ceilings are §36 Abs.1 (33 %), §36 Abs.2 (50 %), §52 Abs.4 (50 %), §56 Abs.5 (50 %)', verified_at=now() where id='5ffb4d68-e05f-404e-9a21-f75665895133' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-03 · H_zuschlag
update public.fields set verification_status='verified_against_standard', verification_quote='(2) Honorare für Grundleistungen bei Umbauten und Modernisierungen gemäß § 2 Absatz 5 und 6 sind zu ermitteln nach 1. den anrechenbaren Kosten, 2. der Honorarzone, welcher der Umbau oder die Modernisierung in sinngemäßer Anwendung der Bewertungsmerkmale zuzuordnen ist, 3. den Leistungsphasen, 4. der Honorartafel zur Honorarorientierung und 5. dem Umbau- oder Modernisierungszuschlag auf das Honorar. — printed p.8', verification_note='md-verified 2026-09-05 (§6 Abs.2, printed p.8) [VC]', verified_at=now() where id='4c0b4b5b-0baa-4e6c-b511-ee72551d059c' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-03 · NK
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Der Auftragnehmer kann neben den Honoraren dieser Verordnung auch die für die Ausführung des Auftrags erforderlichen Nebenkosten in Rechnung stellen; ausgenommen sind die abziehbaren Vorsteuern gemäß § 15 Absatz 1 des Umsatzsteuergesetzes in der jeweils geltenden Fassung. Die Vertragsparteien können in Textform vereinbaren, dass abweichend von Satz 1 eine Erstattung ganz oder teilweise ausgeschlossen ist. | (3) Nebenkosten können pauschal oder nach Einzelnachweis abgerechnet werden. Sie sind nach Einzelnachweis abzurechnen, sofern keine pauschale Abrechnung in Textform vereinbart worden ist. — printed p.9, p.10', verification_note='md-verified 2026-09-05 (§14 Abs.1; §14 Abs.3, printed p.9, p.10) [VC]', verified_at=now() where id='8c6fb0c5-c9ba-4cb7-b202-e1e280a2c212' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-03 · ust
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Der Auftragnehmer hat Anspruch auf Ersatz der gesetzlich geschuldeten Umsatzsteuer für nach dieser Verordnung abrechenbare Leistungen, sofern nicht die Kleinunternehmerregelung nach § 19 des Umsatzsteuergesetzes angewendet wird. Satz 1 ist auch hinsichtlich der um die nach § 15 des Umsatzsteuergeset zes abziehbaren Vorsteuer gekürzten Nebenkosten anzuwenden, die nach § 14 dieser Verordnung weiterberechenbar sind. — printed p.10', verification_note='md-verified 2026-09-05 (§16 Abs.1, printed p.10) [VC]', verified_at=now() where id='34c71855-e33b-4302-8245-634dcf86c98c' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-03 · H_gesamt
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Der Auftragnehmer kann neben den Honoraren dieser Verordnung auch die für die Ausführung des Auftrags erforderlichen Nebenkosten in Rechnung stellen; ausgenommen sind die abziehbaren Vorsteuern gemäß § 15 | (1) Der Auftragnehmer hat Anspruch auf Ersatz der gesetzlich geschuldeten Umsatzsteuer für nach dieser Verordnung abrechenbare Leistungen, sofern nicht die Kleinunternehmerregelung nach § 19 des — printed p.9, p.10', verification_note='md-verified 2026-09-05 (§14 Abs.1; §16 Abs.1, printed p.9, p.10) [VC]', verified_at=now() where id='ff65e0dc-efec-4956-89fa-8a23bb62079f' and verification_status not in ('verified_against_standard','corrected');

-- ================= HOAI-2021-04 =================
-- HOAI-2021-04 · p_geb_lph1
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 1. für die Leistungsphase 1 (Grundlagenermittlung) mit je 2 Prozent für Gebäude und Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC]', verified_at=now() where id='e73c9e4d-70b2-4667-9b23-5bba7836499c' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_inn_lph1
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 1. für die Leistungsphase 1 (Grundlagenermittlung) mit je 2 Prozent für Gebäude und Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC] — the same numbered item carries the Gebaeude and the Innenraeume percentage; the Innenraeume value is the second one where the two differ (LPH 4, 5, 6, 7)', verified_at=now() where id='a4abee1d-2635-4b28-b031-94132f61f57f' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_geb_lph2
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 2. für die Leistungsphase 2 (Vorplanung) mit je 7 Prozent für Gebäude und Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC]', verified_at=now() where id='b0f6956a-1377-44ae-af4d-fc402c69e336' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_inn_lph2
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 2. für die Leistungsphase 2 (Vorplanung) mit je 7 Prozent für Gebäude und Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC] — the same numbered item carries the Gebaeude and the Innenraeume percentage; the Innenraeume value is the second one where the two differ (LPH 4, 5, 6, 7)', verified_at=now() where id='7fc3011e-5772-4d4a-b157-fc4d2da4a3bc' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_geb_lph3
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 3. für die Leistungsphase 3 (Entwurfsplanung) mit 15 Prozent für Gebäude und Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC]', verified_at=now() where id='4d3f1dc1-af40-4d81-a2b4-5e358e004ef8' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_inn_lph3
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 3. für die Leistungsphase 3 (Entwurfsplanung) mit 15 Prozent für Gebäude und Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC] — the same numbered item carries the Gebaeude and the Innenraeume percentage; the Innenraeume value is the second one where the two differ (LPH 4, 5, 6, 7)', verified_at=now() where id='3b693928-21f9-431f-9e08-bf9891466e49' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_geb_lph4
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 4. für die Leistungsphase 4 (Genehmigungsplanung) mit 3 Prozent für Gebäude und 2 Prozent für Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC]', verified_at=now() where id='9e80ebfd-a5ac-4baf-9ce2-5ca65f3e4be9' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_inn_lph4
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 4. für die Leistungsphase 4 (Genehmigungsplanung) mit 3 Prozent für Gebäude und 2 Prozent für Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC] — the same numbered item carries the Gebaeude and the Innenraeume percentage; the Innenraeume value is the second one where the two differ (LPH 4, 5, 6, 7)', verified_at=now() where id='701a9c37-7e4b-4ff0-98dc-eb9c5506c411' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_geb_lph5
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 5. für die Leistungsphase 5 (Ausführungsplanung) mit 25 Prozent für Gebäude und 30 Prozent für Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC]', verified_at=now() where id='24c103e4-2c30-4f79-adef-724266e81ee4' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_inn_lph5
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 5. für die Leistungsphase 5 (Ausführungsplanung) mit 25 Prozent für Gebäude und 30 Prozent für Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC] — the same numbered item carries the Gebaeude and the Innenraeume percentage; the Innenraeume value is the second one where the two differ (LPH 4, 5, 6, 7)', verified_at=now() where id='bc494beb-889b-4274-b892-7729994d712a' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_geb_lph6
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 6. für die Leistungsphase 6 (Vorbereitung der Vergabe) mit 10 Prozent für Gebäude und 7 Prozent für Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC]', verified_at=now() where id='222d60ea-3f1c-4445-b3f9-70f8fac994bd' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_inn_lph6
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 6. für die Leistungsphase 6 (Vorbereitung der Vergabe) mit 10 Prozent für Gebäude und 7 Prozent für Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC] — the same numbered item carries the Gebaeude and the Innenraeume percentage; the Innenraeume value is the second one where the two differ (LPH 4, 5, 6, 7)', verified_at=now() where id='bfeaac52-7cde-45da-b2cd-0f921184060b' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_geb_lph7
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 7. für die Leistungsphase 7 (Mitwirkung bei der Vergabe) mit 4 Prozent für Gebäude und 3 Prozent für Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC]', verified_at=now() where id='d0688876-d20d-45e3-a970-2c68801aea3d' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_inn_lph7
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 7. für die Leistungsphase 7 (Mitwirkung bei der Vergabe) mit 4 Prozent für Gebäude und 3 Prozent für Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC] — the same numbered item carries the Gebaeude and the Innenraeume percentage; the Innenraeume value is the second one where the two differ (LPH 4, 5, 6, 7)', verified_at=now() where id='9b10f768-6a84-4ebd-8698-f79f474b683c' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_geb_lph8
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 8. für die Leistungsphase 8 (Objektüberwachung – Bauüberwachung und Dokumentation) mit 32 Prozent für Gebäude und Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC]', verified_at=now() where id='bc93dba1-fa53-4b78-a92f-fabbbeaa82b0' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_inn_lph8
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 8. für die Leistungsphase 8 (Objektüberwachung – Bauüberwachung und Dokumentation) mit 32 Prozent für Gebäude und Innenräume, — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC] — the same numbered item carries the Gebaeude and the Innenraeume percentage; the Innenraeume value is the second one where the two differ (LPH 4, 5, 6, 7)', verified_at=now() where id='849c2633-3d16-40e8-8134-28820c946dd3' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_geb_lph9
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 9. für die Leistungsphase 9 (Objektbetreuung) mit je 2 Prozent für Gebäude und Innenräume. — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC]', verified_at=now() where id='a054ea3e-7d50-421b-8dbd-97a46852eb8c' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_inn_lph9
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 35 bewertet: | 9. für die Leistungsphase 9 (Objektbetreuung) mit je 2 Prozent für Gebäude und Innenräume. — printed p.22', verification_note='md-verified 2026-09-05 (§34 Abs.3, printed p.22) [VC] — the same numbered item carries the Gebaeude and the Innenraeume percentage; the Innenraeume value is the second one where the two differ (LPH 4, 5, 6, 7)', verified_at=now() where id='63dc12f6-f768-43af-a389-0752bb387f3d' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_fre_lph1
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen bei Freianlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 40 bewertet: | 1. für die Leistungsphase 1 (Grundlagenermittlung) mit 3 Prozent, — printed p.25', verification_note='md-verified 2026-09-05 (§39 Abs.3, printed p.25) [VC]', verified_at=now() where id='4fc490cc-9697-4c78-913e-7871ab879e91' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_fre_lph2
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen bei Freianlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 40 bewertet: | 2. für die Leistungsphase 2 (Vorplanung) mit 10 Prozent, — printed p.25', verification_note='md-verified 2026-09-05 (§39 Abs.3, printed p.25) [VC]', verified_at=now() where id='fe847c74-7a2a-43d3-a2de-baa2108dc74b' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_fre_lph3
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen bei Freianlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 40 bewertet: | 3. für die Leistungsphase 3 (Entwurfsplanung) mit 16 Prozent, — printed p.25', verification_note='md-verified 2026-09-05 (§39 Abs.3, printed p.25) [VC]', verified_at=now() where id='8fc3d16c-8698-41db-9398-6d642e0e9328' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_fre_lph4
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen bei Freianlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 40 bewertet: | 4. für die Leistungsphase 4 (Genehmigungsplanung) mit 4 Prozent, — printed p.25', verification_note='md-verified 2026-09-05 (§39 Abs.3, printed p.25) [VC]', verified_at=now() where id='86ca71a3-3c4b-4974-ad1e-287dd2df92e6' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_fre_lph5
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen bei Freianlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 40 bewertet: | 5. für die Leistungsphase 5 (Ausführungsplanung) mit 25 Prozent, — printed p.25, p.26', verification_note='md-verified 2026-09-05 (§39 Abs.3, printed p.25, p.26) [VC]', verified_at=now() where id='a6f40104-485f-4cf3-a4ce-ca21a42974e2' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_fre_lph6
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen bei Freianlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 40 bewertet: | 6. für die Leistungsphas e 6 (Vorbereitung der Vergabe) mit 7 Prozent, — printed p.25, p.26', verification_note='md-verified 2026-09-05 (§39 Abs.3, printed p.25, p.26) [VC]', verified_at=now() where id='df2357ef-e9ae-4241-9d20-35959ecd4395' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_fre_lph7
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen bei Freianlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 40 bewertet: | 7. für die Leistungsphase 7 (Mitwirkung bei der Vergabe) mit 3 Prozent, — printed p.25, p.26', verification_note='md-verified 2026-09-05 (§39 Abs.3, printed p.25, p.26) [VC]', verified_at=now() where id='1496da0b-50ca-4c85-8b62-2d8b1c6594cb' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_fre_lph8
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen bei Freianlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 40 bewertet: | 8. für die Leistungsphase 8 (Objektüberwachung – Bauüberwachung und Dokumentation) mit 30 Prozent und — printed p.25, p.26', verification_note='md-verified 2026-09-05 (§39 Abs.3, printed p.25, p.26) [VC]', verified_at=now() where id='b0ee525a-0542-45df-b23a-b0b6eb98236b' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · p_fre_lph9
update public.fields set verification_status='verified_against_standard', verification_quote='(3) Die Grundleistungen bei Freianlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 40 bewertet: | 9. für die Leistungsphase 9 (Objektbetreuung) mit 2 Prozent. — printed p.25, p.26', verification_note='md-verified 2026-09-05 (§39 Abs.3, printed p.25, p.26) [VC]', verified_at=now() where id='63728b9a-c36c-4529-ab73-5c2c17a47eb2' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · z_umbau_gebaeude_max
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Für Umbauten und Modernisierungen von Gebäuden kann bei einem durchschnittlichen Schwierigkeitsgrad ein Zuschlag gemäß § 6 Absatz 2 Satz 3 bis 33 Prozent auf das ermittelte Honorar in Textform vereinbart werden. — printed p.24', verification_note='md-verified 2026-09-05 (§36 Abs.1, printed p.24) [VC] — "kann ... bis 33 Prozent ... in Textform vereinbart werden" — a ceiling on an agreed surcharge, not a mandatory value (SR-2)', verified_at=now() where id='9e640882-1178-4681-81ce-67ea4adfcc27' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-04 · z_umbau_innenraum_max
update public.fields set verification_status='verified_against_standard', verification_quote='(2) Für Umbauten und Modernisierungen von Innenräumen in Gebäuden kann bei einem durchschnittlichen Schwierigkeitsgrad ein Zuschlag gemäß § 6 Absatz 2 Satz 3 bis 50 Prozent auf das ermittelte Honorar in Textform vereinbart werden. — printed p.25', verification_note='md-verified 2026-09-05 (§36 Abs.2, printed p.25) [VC] — "kann ... bis 50 Prozent ... in Textform vereinbart werden" — a ceiling on an agreed surcharge, not a mandatory value (SR-2)', verified_at=now() where id='6c752264-7cc3-4409-9e93-0725871fa868' and verification_status not in ('verified_against_standard','corrected');

-- ================= HOAI-2021-05 =================
-- HOAI-2021-05 · p_ing_lph1
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Ingenieurbauwerke sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 44 bewertet: | 1. für die Leistungsphase 1 (Grundlagenermittlung) mit 2 Prozent, — printed p.28', verification_note='md-verified 2026-09-05 (§43 Abs.1, printed p.28) [VC]', verified_at=now() where id='d4580ca0-ebe1-46da-aa5f-4d0906f6b784' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ing_lph2
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Ingenieurbauwerke sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 44 bewertet: | 2. für die Leistungsphase 2 (Vorplanung) mit 20 Prozent, — printed p.28', verification_note='md-verified 2026-09-05 (§43 Abs.1, printed p.28) [VC] — Abs. 2 derogates: "die Leistungsphase 2 bei Objekten nach § 41 Nummer 6 und 7, die eine Tragwerksplanung erfordern, mit 10 Prozent bewertet" (printed p.28)', verified_at=now() where id='457e8efb-d235-4b5a-a50a-bb4f92820709' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ing_lph3
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Ingenieurbauwerke sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 44 bewertet: | 3. für die Leistungsphase 3 (Entwurfsplanung) mit 25 Prozent, — printed p.28', verification_note='md-verified 2026-09-05 (§43 Abs.1, printed p.28) [VC]', verified_at=now() where id='615758b9-ce14-4d27-8e59-4ac32644e717' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ing_lph4
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Ingenieurbauwerke sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 44 bewertet: | 4. für die Leistungsphase 4 (Genehmigungsplanung) mit 5 Prozent, — printed p.28', verification_note='md-verified 2026-09-05 (§43 Abs.1, printed p.28) [VC] — Abs. 3 Nr. 1 allows 5 bis 8 Prozent by Textform agreement where a separate Planfeststellungsverfahren is required (printed p.28) — SR-2 range', verified_at=now() where id='5a053d61-70a1-4b02-b000-7575b27572f7' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ing_lph5
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Ingenieurbauwerke sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 44 bewertet: | 5. für die Leistungsphase 5 (Ausführungsplanung) mit 15 Prozent, — printed p.28', verification_note='md-verified 2026-09-05 (§43 Abs.1, printed p.28) [VC] — Abs. 3 Nr. 2 allows 15 bis 35 Prozent by Textform agreement at above-average Ausfuehrungszeichnungen effort (printed p.28) — SR-2 range', verified_at=now() where id='90e5d3ca-8328-4105-bf5e-152c782b5139' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ing_lph6
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Ingenieurbauwerke sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 44 bewertet: | 6. für die Leistungsphase 6 (Vorbereitung der Vergabe) mit 13 Prozent, — printed p.28', verification_note='md-verified 2026-09-05 (§43 Abs.1, printed p.28) [VC]', verified_at=now() where id='c5644ea6-f26e-46f8-b114-179c5025ee1c' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ing_lph7
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Ingenieurbauwerke sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 44 bewertet: | 7. für die Leistungsphase 7 (Mitwirkung bei der Vergabe) mit 4 Prozent, — printed p.28', verification_note='md-verified 2026-09-05 (§43 Abs.1, printed p.28) [VC]', verified_at=now() where id='232ffbb0-f6a6-4990-977e-2ef09686f0ab' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ing_lph8
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Ingenieurbauwerke sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 44 bewertet: | 8. für die Leistungsphase 8 (Bauoberleitung) mit 15 Prozent, — printed p.28', verification_note='md-verified 2026-09-05 (§43 Abs.1, printed p.28) [VC]', verified_at=now() where id='72c05214-7998-4fec-b97d-4cd0c786f3b6' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ing_lph9
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Ingenieurbauwerke sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 44 bewertet: | 9. für die Leistungsphase 9 (Objektbetreuung) mit 1 Prozent. — printed p.28', verification_note='md-verified 2026-09-05 (§43 Abs.1, printed p.28) [VC]', verified_at=now() where id='811ab1a7-0d04-4e8c-b395-c6648ab5b281' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ver_lph1
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Verkehrsanlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 48 bewertet: | 1. für die Leistungsphase 1 (Grundlagenermittlung) mit 2 Prozent, — printed p.31', verification_note='md-verified 2026-09-05 (§47 Abs.1, printed p.31) [VC]', verified_at=now() where id='9cb87fbb-6ba8-46f3-a9aa-38b1b801e7ed' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ver_lph2
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Verkehrsanlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 48 bewertet: | 2. für die Leistungsphase 2 (Vorplanung) mit 20 Prozent, — printed p.31', verification_note='md-verified 2026-09-05 (§47 Abs.1, printed p.31) [VC]', verified_at=now() where id='52e73e6a-c5a6-449c-b38a-e6baab1f4b42' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ver_lph3
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Verkehrsanlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 48 bewertet: | 3. für die Leistungsphase 3 (Entwurfsplanung) mit 25 Prozent, — printed p.31', verification_note='md-verified 2026-09-05 (§47 Abs.1, printed p.31) [VC]', verified_at=now() where id='ef1f383e-e52d-4387-a472-97f41774d4c0' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ver_lph4
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Verkehrsanlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 48 bewertet: | 4. für die Leistungsphase 4 (Genehmigungsplanung) mit 8 Prozent, — printed p.31', verification_note='md-verified 2026-09-05 (§47 Abs.1, printed p.31) [VC]', verified_at=now() where id='124dfeba-5f58-46c8-a952-a1d7833e3ffd' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ver_lph5
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Verkehrsanlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 48 bewertet: | 5. für die Leistungsphase 5 (Ausführungsplanung) mit 15 Prozent, — printed p.31', verification_note='md-verified 2026-09-05 (§47 Abs.1, printed p.31) [VC]', verified_at=now() where id='706b5e05-7a6f-4d39-946a-67f66232febb' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ver_lph6
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Verkehrsanlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 48 bewertet: | 6. für die Leistungsphase 6 (Vorbereitung der Vergabe) mit 10 Prozent, — printed p.31', verification_note='md-verified 2026-09-05 (§47 Abs.1, printed p.31) [VC]', verified_at=now() where id='6ab8da59-80e9-4318-96c1-d7ca5ee3240a' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ver_lph7
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Verkehrsanlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 48 bewertet: | 7. für die Leistungsphase 7 (Mitwirkung bei der Vergabe) mit 4 Prozent, — printed p.31', verification_note='md-verified 2026-09-05 (§47 Abs.1, printed p.31) [VC]', verified_at=now() where id='7aa5bff0-2542-4e34-b2b6-b6285d330b17' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ver_lph8
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Verkehrsanlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 48 bewertet: | 8. für die Leistungsphase 8 (Bauoberleitung) mit 15 Prozent, — printed p.31', verification_note='md-verified 2026-09-05 (§47 Abs.1, printed p.31) [VC]', verified_at=now() where id='9a9bfcae-3a97-4e4d-af41-8e00c848f6f6' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-05 · p_ver_lph9
update public.fields set verification_status='verified_against_standard', verification_quote='(1) § 34 Absatz 1 gilt entsprechend. Die Grundleistungen für Verkehrsanlagen sind in neun Leistungsphasen unterteilt und werden wie folgt in Prozentsätzen der Honorare des § 48 bewertet: | 9. für die Leistungsphase 9 (Objektbetreuung) mit 1 Prozent. — printed p.31', verification_note='md-verified 2026-09-05 (§47 Abs.1, printed p.31) [VC]', verified_at=now() where id='21487a44-b7b9-41ba-b693-7848d808f719' and verification_status not in ('verified_against_standard','corrected');

-- ================= HOAI-2021-06 =================
-- HOAI-2021-06 · anlagengruppe_tga
update public.fields set verification_status='verified_against_standard', verification_quote='(2) Zur Technischen Ausrüstung gehören folgende Anlagengruppen: 1. Abwasser-, Wasser- und Gasanlagen, 2. Wärmeversorgungsanlagen, 3. Lufttechnische Anlagen, 4. Starkstromanlagen, 5. Fernmelde- und informationstechnische Anlagen, 6. Förderanlagen, 7. nutzungsspezifische Anlagen und verfahrenstechnische Anlagen, 8. Gebäudeautomation und Automation von Ingenieurbauwerken. — printed p.35', verification_note='md-verified 2026-09-05 (§53 Abs.2, printed p.35) [VC]', verified_at=now() where id='2bb83f5d-192f-4668-98c8-30bfa67f4c85' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tra_lph1
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Die Grundleistungen der Tragwerksplanung sind für Gebäude und zugehörige bauliche Anlagen sowie für Ingenieurbauwerke nach § 41 Nummer 1 bis 5 in den Leistungsphasen 1 bis 6 sowie für Ingenieurbauwerke nach § 41 Nummer 6 und 7 in den Leistungsphasen 2 bis 6 zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 52 bewertet: | 1. für die Leistungsphase 1 (Grundlagenermittlung) mit 3 Prozent, — printed p.34', verification_note='md-verified 2026-09-05 (§51 Abs.1, printed p.34) [VC]', verified_at=now() where id='f4acce7e-c4ee-4ac3-b249-b00e58957b54' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tra_lph2
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Die Grundleistungen der Tragwerksplanung sind für Gebäude und zugehörige bauliche Anlagen sowie für Ingenieurbauwerke nach § 41 Nummer 1 bis 5 in den Leistungsphasen 1 bis 6 sowie für Ingenieurbauwerke nach § 41 Nummer 6 und 7 in den Leistungsphasen 2 bis 6 zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 52 bewertet: | 2. für die Leistungsphase 2 (Vorplanung) mit 10 Prozent, — printed p.34', verification_note='md-verified 2026-09-05 (§51 Abs.1, printed p.34) [VC]', verified_at=now() where id='ee3e33d4-300c-40d0-ac69-35f964b58628' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tra_lph3
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Die Grundleistungen der Tragwerksplanung sind für Gebäude und zugehörige bauliche Anlagen sowie für Ingenieurbauwerke nach § 41 Nummer 1 bis 5 in den Leistungsphasen 1 bis 6 sowie für Ingenieurbauwerke nach § 41 Nummer 6 und 7 in den Leistungsphasen 2 bis 6 zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 52 bewertet: | 3. für die Leistungsphase 3 (Entwurfsplanung) mit 15 Prozent, — printed p.34', verification_note='md-verified 2026-09-05 (§51 Abs.1, printed p.34) [VC]', verified_at=now() where id='74dfdb61-70f6-48c1-b5ec-83878c9ddd42' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tra_lph4
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Die Grundleistungen der Tragwerksplanung sind für Gebäude und zugehörige bauliche Anlagen sowie für Ingenieurbauwerke nach § 41 Nummer 1 bis 5 in den Leistungsphasen 1 bis 6 sowie für Ingenieurbauwerke nach § 41 Nummer 6 und 7 in den Leistungsphasen 2 bis 6 zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 52 bewertet: | 4. für die Leistungsphase 4 (Genehmigungsplanung) mit 30 Prozent, — printed p.34', verification_note='md-verified 2026-09-05 (§51 Abs.1, printed p.34) [VC]', verified_at=now() where id='cfe0b0cc-4caf-4cd8-b53c-8faea79a4dd3' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tra_lph5
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Die Grundleistungen der Tragwerksplanung sind für Gebäude und zugehörige bauliche Anlagen sowie für Ingenieurbauwerke nach § 41 Nummer 1 bis 5 in den Leistungsphasen 1 bis 6 sowie für Ingenieurbauwerke nach § 41 Nummer 6 und 7 in den Leistungsphasen 2 bis 6 zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 52 bewertet: | 5. für die Leistungsphase 5 (Ausführungsplanung) mit 40 Prozent, — printed p.34', verification_note='md-verified 2026-09-05 (§51 Abs.1, printed p.34) [VC] — Abs. 2 sets 30 Prozent im Stahlbetonbau ohne Schalplaene / im Holzbau mit unterdurchschnittlichem Schwierigkeitsgrad, Abs. 3 sets 20 Prozent wenn nur Schalplaene beauftragt, Abs. 4 allows +bis zu 4 Prozent bei sehr enger Bewehrung (printed p.34)', verified_at=now() where id='312f0f4a-641a-4c69-bfa4-0cbd5676607a' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tra_lph6
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Die Grundleistungen der Tragwerksplanung sind für Gebäude und zugehörige bauliche Anlagen sowie für Ingenieurbauwerke nach § 41 Nummer 1 bis 5 in den Leistungsphasen 1 bis 6 sowie für Ingenieurbauwerke nach § 41 Nummer 6 und 7 in den Leistungsphasen 2 bis 6 zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 52 bewertet: | 6. für die Leistungsphase 6 (Vorbereitung der Vergabe) mit 2 Prozent. — printed p.34', verification_note='md-verified 2026-09-05 (§51 Abs.1, printed p.34) [VC]', verified_at=now() where id='f03f62a7-6c61-4340-aeb0-d3e572bb09e4' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tga_lph1
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Das Leistungsbild Technische Ausrüstung umfasst Grundleistungen für Neuanlagen, Wiederaufbauten, Erweiterungsbauten, Umbauten, Modernisierungen, Instandhaltungen und Instandsetzungen. Die Grundleistungen bei der Technischen Ausrüstung sind in neun Leistungsphasen zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 56 bewertet: | 1. für die Leistungsphase 1 (Grundlagenermittlung) mit 2 Prozent, — printed p.36', verification_note='md-verified 2026-09-05 (§55 Abs.1, printed p.36) [VC]', verified_at=now() where id='2a3890eb-9e69-4a42-ba29-c61c5f701e7c' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tga_lph2
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Das Leistungsbild Technische Ausrüstung umfasst Grundleistungen für Neuanlagen, Wiederaufbauten, Erweiterungsbauten, Umbauten, Modernisierungen, Instandhaltungen und Instandsetzungen. Die Grundleistungen bei der Technischen Ausrüstung sind in neun Leistungsphasen zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 56 bewertet: | 2. für die Leistungsphase 2 (Vorplanung) mit 9 Prozent, — printed p.36', verification_note='md-verified 2026-09-05 (§55 Abs.1, printed p.36) [VC]', verified_at=now() where id='318f433a-4f75-470e-92d3-086feec315b2' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tga_lph3
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Das Leistungsbild Technische Ausrüstung umfasst Grundleistungen für Neuanlagen, Wiederaufbauten, Erweiterungsbauten, Umbauten, Modernisierungen, Instandhaltungen und Instandsetzungen. Die Grundleistungen bei der Technischen Ausrüstung sind in neun Leistungsphasen zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 56 bewertet: | 3. für die Leistungsphase 3 (Entwurfsplanung) mit 17 Prozent, — printed p.36', verification_note='md-verified 2026-09-05 (§55 Abs.1, printed p.36) [VC]', verified_at=now() where id='16c8bb02-632a-467f-bda5-e24ce4f31b3e' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tga_lph4
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Das Leistungsbild Technische Ausrüstung umfasst Grundleistungen für Neuanlagen, Wiederaufbauten, Erweiterungsbauten, Umbauten, Modernisierungen, Instandhaltungen und Instandsetzungen. Die Grundleistungen bei der Technischen Ausrüstung sind in neun Leistungsphasen zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 56 bewertet: | 4. für die Leistungsphase 4 (Genehmigungsplanung) mit 2 Prozent, — printed p.36', verification_note='md-verified 2026-09-05 (§55 Abs.1, printed p.36) [VC]', verified_at=now() where id='3ea83d6c-c1de-4848-b270-76ff5f796953' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tga_lph5
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Das Leistungsbild Technische Ausrüstung umfasst Grundleistungen für Neuanlagen, Wiederaufbauten, Erweiterungsbauten, Umbauten, Modernisierungen, Instandhaltungen und Instandsetzungen. Die Grundleistungen bei der Technischen Ausrüstung sind in neun Leistungsphasen zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 56 bewertet: | 5. für die Leistungsphase 5 (Ausführungsplanung) mit 22 Prozent, — printed p.36', verification_note='md-verified 2026-09-05 (§55 Abs.1, printed p.36) [VC] — Abs. 2 prescribes a 4-Prozent Abschlag where Schlitz- und Durchbruchsplaene or the Pruefen der Montage- und Werkstattplaene are not commissioned (printed p.36)', verified_at=now() where id='d61f0f28-1953-45e4-821d-9f0592295f46' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tga_lph6
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Das Leistungsbild Technische Ausrüstung umfasst Grundleistungen für Neuanlagen, Wiederaufbauten, Erweiterungsbauten, Umbauten, Modernisierungen, Instandhaltungen und Instandsetzungen. Die Grundleistungen bei der Technischen Ausrüstung sind in neun Leistungsphasen zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 56 bewertet: | 6. für die Leistungsphase 6 (Vorbereitung der Vergabe) mit 7 Prozent, — printed p.36', verification_note='md-verified 2026-09-05 (§55 Abs.1, printed p.36) [VC]', verified_at=now() where id='6f9cc0c6-bde9-4114-bcac-147d6aaa9cec' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tga_lph7
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Das Leistungsbild Technische Ausrüstung umfasst Grundleistungen für Neuanlagen, Wiederaufbauten, Erweiterungsbauten, Umbauten, Modernisierungen, Instandhaltungen und Instandsetzungen. Die Grundleistungen bei der Technischen Ausrüstung sind in neun Leistungsphasen zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 56 bewertet: | 7. für die Leistungsphase 7 (Mitwirkung bei der Vergabe) mit 5 Prozent, — printed p.36', verification_note='md-verified 2026-09-05 (§55 Abs.1, printed p.36) [VC]', verified_at=now() where id='41ec50d9-d871-43a4-a734-87812e9b30e5' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tga_lph8
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Das Leistungsbild Technische Ausrüstung umfasst Grundleistungen für Neuanlagen, Wiederaufbauten, Erweiterungsbauten, Umbauten, Modernisierungen, Instandhaltungen und Instandsetzungen. Die Grundleistungen bei der Technischen Ausrüstung sind in neun Leistungsphasen zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 56 bewertet: | 8. für die Leistungsphase 8 (Objektüberwachung – Bauüberwachung) mit 35 Prozent, — printed p.36', verification_note='md-verified 2026-09-05 (§55 Abs.1, printed p.36) [VC]', verified_at=now() where id='be6c25a3-a7f7-4a55-bdfd-54e4835800ae' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · p_tga_lph9
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Das Leistungsbild Technische Ausrüstung umfasst Grundleistungen für Neuanlagen, Wiederaufbauten, Erweiterungsbauten, Umbauten, Modernisierungen, Instandhaltungen und Instandsetzungen. Die Grundleistungen bei der Technischen Ausrüstung sind in neun Leistungsphasen zusammengefasst und werden wie folgt in Prozentsätzen der Honorare des § 56 bewertet: | 9. für die Leistungsphase 9 (Objektbetreuung) mit 1 Prozent. — printed p.36', verification_note='md-verified 2026-09-05 (§55 Abs.1, printed p.36) [VC]', verified_at=now() where id='8173c10e-3841-4f00-b9f5-697791900fd8' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-06 · z_umbau_tragwerk_max
update public.fields set verification_status='verified_against_standard', verification_quote='(4) Für Umbauten und Modernisierungen kann bei einem durchschnittlichen Schwierigkeitsgrad ein Zuschlag gemäß § 6 Absatz 2 Satz 3 bis 50 Prozent in Textform vereinbart werden. — printed p.35', verification_note='md-verified 2026-09-05 (§52 Abs.4, printed p.35) [VC] — "kann ... bis 50 Prozent in Textform vereinbart werden" — a ceiling on an agreed surcharge, not a mandatory value (SR-2)', verified_at=now() where id='ce0fda76-e349-405f-831d-e1ebe18bcf4f' and verification_status not in ('verified_against_standard','corrected');

-- ================= HOAI-2021-07 =================
-- HOAI-2021-07 · vereinbarung_textform
update public.fields set verification_status='verified_against_standard', verification_quote='(1) Das Honorar richtet sich nach der Vereinbarung, die die Vertragsparteien in Textform treffen. Sofern keine Vereinbarung über die Höhe des Honorars in Textform getroffen wurde, gilt für Grundleistungen der jeweilige Basishonorarsatz als vereinbart, der sich bei der Anwendung der Honorargrundlagen des § 6 ergibt. — printed p.8', verification_note='md-verified 2026-09-05 (§7 Abs.1, printed p.8) [VC]', verified_at=now() where id='4230b3a1-ff19-4db2-870e-1a0a49e7edd6' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-07 · auftraggeber_verbraucher
update public.fields set verification_status='verified_against_standard', verification_quote='(2) Der Auftragnehmer hat den Auftraggeber, sofern dieser Verbraucher ist, vor Abgabe von dessen verbindlicher Vertragserklärung zur Honorarvereinbarung in Textform darauf hinzuweisen, dass ein höheres oder niedrigeres Honorar als die in den Honorartafeln dieser Verordnung enthaltenen Werte vereinbart werden kann. Erfolgt der Hinweis nach Satz 1 nicht oder nicht rechtzeitig, gilt für die zwischen den Vertragsparteien vereinbarten Grundleistungen anstelle eines höheren Honorars ein Honorar in Höhe des jeweiligen Basishonorarsatzes als vereinbart. — printed p.8', verification_note='md-verified 2026-09-05 (§7 Abs.2, printed p.8) [VC]', verified_at=now() where id='20ce7622-385d-4d31-8695-edf1d33c8f10' and verification_status not in ('verified_against_standard','corrected');
-- HOAI-2021-07 · hinweis_erteilt
update public.fields set verification_status='verified_against_standard', verification_quote='(2) Der Auftragnehmer hat den Auftraggeber, sofern dieser Verbraucher ist, vor Abgabe von dessen verbindlicher Vertragserklärung zur Honorarvereinbarung in Textform darauf hinzuweisen, dass ein höheres oder niedrigeres Honorar als die in den Honorartafeln dieser Verordnung enthaltenen Werte vereinbart werden kann. Erfolgt der Hinweis nach Satz 1 nicht oder nicht rechtzeitig, gilt für die zwischen den Vertragsparteien vereinbarten Grundleistungen anstelle eines höheren Honorars ein Honorar in Höhe des jeweiligen Basishonorarsatzes als vereinbart. — printed p.8', verification_note='md-verified 2026-09-05 (§7 Abs.2, printed p.8) [VC]', verified_at=now() where id='824e8dc6-323b-4cad-90ed-29bac9175eb5' and verification_status not in ('verified_against_standard','corrected');

-- ================= app/project metadata (exempt class, 2026-08-01 ruling) =================
-- HOAI-2021-01.projekt_bezeichnung, HOAI-2021-07.honorar_freigegeben
update public.fields set verification_status='inferred_from_worksheet', verification_note='md-pass 2026-09-05: app/project metadata — the guideline does not define this field; exempt per the 2026-08-01 metadata ruling', verified_at=now() where id in ('98bb9afb-ebe1-451b-90af-a31ecf91ee77','aee2d473-b107-44e8-874d-75160839d777') and verification_status not in ('verified_against_standard','corrected');

-- ================= equations — QUOTE BACKFILL ONLY (status untouched) =================
-- HOAI-EQ-01 · H_basis
update public.equations set verification_quote='§ 13 Interpolation Zwischenstufen der in den Honorartafeln angegebenen anrechenbaren Kosten und Flächen oder Verrechnungseinheiten sind durch lineare Interpolation zu ermitteln. | (2) Basishonorarsatz ist der jeweils untere in den Honorartafeln dieser Verordnung enthaltene Honorarsatz. — printed p.9, p.7', verification_note='md-verified 2026-09-05 (§13; §2a Abs.2, printed p.9, p.7) [VC] — the HOAI prints no algebraic formula; it states the rule in words and the encoded expression is EKOWAI’s rendering of it', verified_at=now() where id='2c177fbd-dc96-4ffd-9bb3-e79fc13d70d5' and verification_quote is null;
-- HOAI-EQ-02 · H_oben
update public.equations set verification_quote='§ 13 Interpolation Zwischenstufen der in den Honorartafeln angegebenen anrechenbaren Kosten und Flächen oder Verrechnungseinheiten sind durch lineare Interpolation zu ermitteln. | (1) Die Honorartafeln dieser Verordnung w eisen Orientierungswerte aus, die an der Art und dem Umfang der Aufgabe sowie an der Leistung ausgerichtet sind. Die Honorartafeln enthalten für jeden Leistungsbereich Honorarspannen vom Basishonorarsatz bis zum oberen Honorarsatz, gegliedert nach den — printed p.9, p.6', verification_note='md-verified 2026-09-05 (§13; §2a Abs.1, printed p.9, p.6) [VC] — the HOAI prints no algebraic formula; it states the rule in words and the encoded expression is EKOWAI’s rendering of it', verified_at=now() where id='86a93a1d-a7bf-4ef9-8ebc-584e3f3049cf' and verification_quote is null;
-- HOAI-EQ-03 · H_tafel
update public.equations set verification_quote='(1) Die Honorartafeln dieser Verordnung w eisen Orientierungswerte aus, die an der Art und dem Umfang der Aufgabe sowie an der Leistung ausgerichtet sind. Die Honorartafeln enthalten für jeden Leistungsbereich Honorarspannen vom Basishonorarsatz bis zum oberen Honorarsatz, gegliedert nach den | (1) Das Honorar richtet sich nach der Vereinbarung, die die Vertragsparteien in Textform treffen. Sofern keine Vereinbarung über die Höhe des Honorars in Textform getroffen wurde, gilt für Grundleistungen der jeweilige Basishonorarsatz als vereinbart, der sich bei der Anwendung der Honorargrundlagen des § 6 ergibt. — printed p.6, p.8', verification_note='md-verified 2026-09-05 (§2a Abs.1; §7 Abs.1, printed p.6, p.8) [VC] — the HOAI prints no algebraic formula; it states the rule in words and the encoded expression is EKOWAI’s rendering of it; the Honorartafel values are Orientierungswerte, so s_satz may lawfully leave [0,1]', verified_at=now() where id='e29beb8e-62b0-4422-8035-5e46f28ed598' and verification_quote is null;
-- HOAI-EQ-04 · H_phasen
update public.equations set verification_quote='(1) Werden dem Auftragnehmer nicht alle Leistungsphasen eines Leistungsbildes übertragen, so dürfen nur die für die übertragenen Phasen vorgesehenen Prozentsätze berechnet und vereinbart werden. Die Vereinbarung hat in Textform zu erfolgen. — printed p.8', verification_note='md-verified 2026-09-05 (§8 Abs.1, printed p.8) [VC] — the HOAI prints no algebraic formula; it states the rule in words and the encoded expression is EKOWAI’s rendering of it', verified_at=now() where id='21fd5fb6-c76a-4afa-98d9-31a8d1c190d0' and verification_quote is null;
-- HOAI-EQ-05 · H_zuschlag
update public.equations set verification_quote='5. dem Umbau- oder Modernisierungszuschlag auf das Honorar. Der Umbau- oder Modernisierungszuschlag ist unter Berücksichtigung des Schwierigkeitsgrads der Leistungen in Textform zu vereinbaren. Die Höhe des Zuschlags auf das Honorar ist in den jeweiligen Honorarregelungen der Leistungsbilder der Teile 3 und 4 und in Anlage 1 Nummer 1.2 geregelt. Sofern keine Vereinbarung in Textform getroffen wurde, gilt ein Zuschlag von 20 Prozent ab einem durchschnittlichen Schwierigkeitsgrad als vereinbart. — printed p.8', verification_note='md-verified 2026-09-05 (§6 Abs.2, printed p.8) [VC] — the HOAI prints no algebraic formula; it states the rule in words and the encoded expression is EKOWAI’s rendering of it', verified_at=now() where id='42c36e85-fbee-4876-82ff-191503e660dc' and verification_quote is null;
-- HOAI-EQ-06 · H_gesamt
update public.equations set verification_quote='(1) Der Auftragnehmer kann neben den Honoraren dieser Verordnung auch die für die Ausführung des Auftrags erforderlichen Nebenkosten in Rechnung stellen; ausgenommen sind die abziehbaren Vorsteuern gemäß § 15 | (1) Der Auftragnehmer hat Anspruch auf Ersatz der gesetzlich geschuldeten Umsatzsteuer für nach dieser Verordnung abrechenbare Leistungen, sofern nicht die Kleinunternehmerregelung nach § 19 des — printed p.9, p.10', verification_note='md-verified 2026-09-05 (§14 Abs.1; §16 Abs.1, printed p.9, p.10) [VC] — the HOAI prints no algebraic formula; it states the rule in words and the encoded expression is EKOWAI’s rendering of it', verified_at=now() where id='b3637322-8489-4492-9fb2-0bdb89cdcfa4' and verification_quote is null;
