-- ============================================================================
-- SR-1 field-verification pack — ISO-14004 (DIN EN ISO 14004:2016, "Umweltmanagementsysteme — Allgemeine
--   Leitlinien zur Verwirklichung (ISO 14004:2016)"; Ref. Nr. EN ISO 14004:2016 D/E, vom CEN am 1. März 2016
--   angenommen. Prod standards.version = "2016 (EN ISO 14004:2016 D/E)" — matches. standard id
--   d52ffd83-a016-4591-a1ee-fe44f347e9f7.)
-- Generated: 2026-09-05 — md-verified pass (owner ruling 2026-09-05: the markdown transcript is the verification
--   source; PDF only where no markdown exists). Grade: VC (SR-3), labelled on every row. Records EVIDENCE only
--   (verification_status / _quote / _note / verified_at); changes NO structure, enforcement or required-ness —
--   all of that is in iso-14004-STAGED-rulings.sql.
--
-- Source md: C:\Users\Ekowai\Desktop\Guidelines\DWA DIN Scribd\ISO-14004\ISO-14004.md (4199 lines, mathpix
--   LaTeX transcript of the DIN EN ISO 14004:2016 D/E bilingual print; read completely in chunks).
--   LANGUAGE: the document is the official CEN German+English parallel edition; German is an official version
--   ("Diese Europäische Norm besteht in drei offiziellen Fassungen (Deutsch, Englisch, Französisch)"), so every
--   quote below is GERMAN, verbatim from that official text — not a back-translation.
--
--   SCOPE NOTE (governs how these rows may be used): ISO 14004 is GUIDANCE, not a requirements standard. §1
--   prints "Diese Internationale Norm enthält Leitlinien für den Aufbau, die Verwirklichung, die Aufrechterhaltung
--   und die Verbesserung eines widerstandsfähigen, glaubwürdigen und zuverlässigen Umweltmanagementsystems."
--   and "Die Anleitung in dieser Internationalen Norm kann im Ganzen oder in Teilen für die systematische
--   Verbesserung des Umweltmanagements genutzt werden. Sie dient der Bereitstellung zusätzlicher Erläuterungen
--   zu den Konzepten und Anforderungen." and "Die Leitlinien in der vorliegenden Internationalen Norm stimmen
--   zwar mit dem Modell eines Umweltmanagementsystems nach ISO 14001 überein, sind jedoch nicht dafür vorgesehen,
--   die Anforderungen von ISO 14001 zu interpretieren." (printed p.14–15). The 2016 edition's §1 carries NO
--   sentence of the form "contains no requirements / not intended for certification" — that wording is NOT in
--   this document and is not quoted here. The modal verb throughout the body is "sollte"/"kann"; the "muss"
--   forms appear only inside the definition of bindende Verpflichtungen (3.2.9) and in the front matter.
--   CONSEQUENCE: no quote in this pack is a hard limit, and none of them can carry a block gate. Prod agrees:
--   all 38 compliance_requirements are severity='warn'; there is not one block gate on this standard.
--
--   Page convention: the mathpix transcript carries NO standalone page-number lines. "printed p.N" is DERIVED
--   from the standard's own Inhalt/Contents index (md lines 112–277), which prints a page for every clause down
--   to the 4th level: §1 p.14 · §2/§3 p.15 (3.1 p.15 · 3.2 p.16 · 3.3 p.19 · 3.4 p.20) · 4.1 p.23 · 4.2.1 p.29 ·
--   4.2.2 p.30 · 4.2.3 p.31 · 4.2.4 p.32 · 4.2.5/4.3 p.33 · 4.4.1 p.35 · 4.4.2/§5/5.1 p.37 · 5.2 p.40 · 5.3 p.44 ·
--   6.1.1 p.46 · 6.1.2.1 p.52 · 6.1.2.2/6.1.2.3 p.54 · 6.1.2.4 p.56 · 6.1.2.5 p.58 · 6.1.3.1 p.60 · 6.1.3.2 p.62 ·
--   6.1.3.3/6.1.3.4/6.1.4 p.63 · 6.2.1/6.2.2 p.65 · 6.2.3 p.67 · 6.2.4 p.68 · 7.1 p.69 · 7.2 p.71 · 7.3 p.75 ·
--   7.4.1 p.76 · 7.4.2 p.79 · 7.4.3 p.80 · 7.5.1 p.81 · 7.5.2/7.5.3 p.84 · 8.1.1 p.85 · 8.1.2 p.86 · 8.1.3 p.89 ·
--   8.2 p.90 · 9.1.1 p.92 · 9.1.2 p.94 · 9.2 p.97 · 9.3 p.99 · 10.1 p.101 · 10.2 p.102 · 10.3.1 p.104 ·
--   10.3.2 p.105 · Anhang A p.106 · Anhang B p.125 · Literaturhinweise p.130.
--   Because a clause usually spans several printed pages, text taken from inside a clause is cited as the page
--   RANGE from that clause's index page up to the page before the next indexed clause (e.g. §4.1 -> p.23–28),
--   never as an invented single page. "Kasten zur praktischen Hilfe" boxes have no index entry and are cited
--   inside their parent clause's range (Kasten 1–3 in §4.1, Kasten 7/8 in §5.2, Kasten 12 in §6.1.2.1, Kasten 13
--   in §6.1.2.4, Kasten 15 in §6.2.4, Kasten 17 in §7.2, Kasten 19 in §7.5.1). Cross-check: the German and
--   English Contents give IDENTICAL pages for §1–§10 (both print 5.1 p.37, 9.3 p.99), i.e. clauses 1–10 are set
--   as parallel columns on one page; they diverge only for the annexes (Anhang A p.106 vs Annex A p.115), where
--   the German annex is printed before the English one. Nothing in this pack is quoted from an annex.
--
--   Transcript quirks, handled and disclosed: (a) mathpix interleaves the German and English columns at
--   irregular boundaries, so a German sentence can be SPLIT by an intervening English block (§5.2 "... das
--   Verhindern von" / "Umweltbelastungen und die fortlaufende Verbesserung ...", md lines 1455 vs 1462).
--   Such a split is marked "[...]" inside the quote — it is a transcript column break, not an omission of
--   normative text. (b) "[...]" also marks an omitted run inside ONE clause; " | " joins separate clauses;
--   the page ref appears ONCE, at the END of each quote (multi-clause quotes list their pages once, in quote
--   order). (c) list items are quoted with their printed "-" / "a)" markers. (d) OCR artefacts are quoted AS
--   PRINTED where they fall inside a quote and flagged in the note.
--
-- Scope (default job): 65 fields (export 2026-09-05: ALL 65 imported_unverified; NONE already
--   verified_against_standard/corrected) -> 64 quoted -> verified_against_standard / 1 app-project-metadata
--   -> inferred_from_worksheet (organisation_name) / 0 residue. Partly-supported fields carry the caveat in
--   verification_note (lebensweg_betrachtung_angewendet clause home; notfallsituation clause home;
--   bedeutung_stufe as an SR-2 example scale; verpflichtung_verzeichnis "könnten";
--   einhaltungsbewertung_haeufigkeit per-obligation variation). Every verification_quote was written from the
--   md in this session.
-- Equations: prod holds 0 equations for ISO-14004 (export 2026-09-05) and the md prints no formula anywhere —
--   the standard is narrative guidance. Nothing to lift or backfill; no equation section in this pack.
-- Gates: 38 read, ALL severity='warn', 0 block. Every source_quote was re-checked word by word against the md;
--   the mismatches (7 non-verbatim quotes, 2 condition='TRUE' no-ops, 3 duplicate/subset pairs, 1 mis-homed
--   gate, 3 quotes that carry no obligation) are catalogued in iso-14004-STAGED-rulings.sql. Nothing about
--   gates is changed here.
-- Rollback: scripts/verification/rollback-iso-14004-md-verification-pack.sql
-- ============================================================================

-- ISO-14004-01 · kontext_externe_themen — Relevante externe Themen
update public.fields set verification_status='verified_against_standard', verification_quote='Damit eine Organisation ein Umweltmanagementsystem aufbauen, verwirklichen, aufrechterhalten und fortlaufend verbessern kann, sollte sie den Kontext bestimmen, in dem sie handelt. Der Kontext umfasst die externen und internen Themen, einschließlich der Umweltzustände, die für ihren Zweck relevant sind und sich auf ihre Fähigkeit auswirken, die beabsichtigten Ergebnisse des Umweltmanagementsystems zu erreichen. | a) Kennzeichnung der relevanten externen und internen Themen, einschließlich der Umweltzustände und Ereignisse, die Einfluss auf die Tätigkeiten, Produkte und Dienstleistungen der Organisation besitzen; — printed p.23–28', verification_note='md-verified 2026-09-05 (§4.1, printed p.23–28) [VC]', verified_at=now() where id='a0dd857f-f32b-45eb-b40a-e004e66d7f7c' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-01 · kontext_interne_themen — Relevante interne Themen
update public.fields set verification_status='verified_against_standard', verification_quote='Das Verstehen des Kontextes ist wichtig, da Organisationen nicht alleinstehend funktionieren, sondern von externen und internen Themen, wie z. B. der Verfügbarkeit von Ressourcen und der Beteiligung ihrer Beschäftigten, beeinflusst werden. Der Kontext der Organisation kann außerdem deren Komplexität, Struktur, Tätigkeiten und die geographische Lage ihrer Funktionseinheiten umfassen, sowohl im gesamten Unternehmen als auch auf lokaler Ebene. | Zu den Methoden, die angewendet werden können, um relevante interne Faktoren zu untersuchen, zählen das Erfassen von Informationen über das aktuelle Managementsystem, wie vorstehend betrachtet — printed p.23–28', verification_note='md-verified 2026-09-05 (§4.1 mit Kasten zur praktischen Hilfe 3, printed p.23–28) [VC]', verified_at=now() where id='cf17e7e9-e76a-4c05-bd4b-d854b6636b54' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-01 · umweltzustaende — Umweltzustaende einschliesslich Ereignisse
update public.fields set verification_status='verified_against_standard', verification_quote='Zum Kontext der Organisation zählt die natürliche Umwelt, in der sie tätig wird. Die natürliche Umwelt kann Zustände und Ereignisse schaffen, die die Tätigkeiten, Produkte und Dienstleistungen der Organisation beeinflussen. Zustände können vorhanden sein oder sich allmählich ändern, wohingegen ein Ereignis eine plötzliche Änderung beinhalten kann, die sich typischerweise durch eine Extremsituation erklären lässt. | Ein Umweltzustand, der die Tätigkeiten, Produkte und Dienstleistungen der Organisation beeinflussen kann, kann beispielsweise eine klimabedingte Temperaturänderung sein — printed p.23–28', verification_note='md-verified 2026-09-05 (§4.1 mit Kasten zur praktischen Hilfe 2, printed p.23–28) [VC]', verified_at=now() where id='8994ce84-8979-4493-b546-61a0a11a429e' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-01 · interessierte_parteien — Relevante interessierte Parteien
update public.fields set verification_status='verified_against_standard', verification_quote='Interessierte Parteien einer Organisation können sowohl intern als auch extern sein. Die Organisation sollte bestimmen, welche interessierten Parteien für das Umweltmanagementsystem der Organisation relevant sind. Interessierte Parteien können im Verlauf der Zeit je nach Branche oder Industriezweig oder geographischer Lage, in der die Organisation tätig ist, wechseln. — printed p.30', verification_note='md-verified 2026-09-05 (§4.2.2, printed p.30) [VC]', verified_at=now() where id='6c6aa0b5-98b4-455b-b7ba-6a15c251b351' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-01 · erfordernisse_erwartungen — Erfordernisse und Erwartungen relevanter interessierter Parteien
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation sollte die relevanten Erfordernisse und Erwartungen ihrer betreffenden interessierten Parteien bestimmen, die als Eingabe bei der Gestaltung des Umweltmanagementsystems verwendet werden können. [...] Es ist wichtig, nicht nur diejenigen zu ermitteln, die verbindlich und festgelegt sind, sondern auch diejenigen, die üblicherweise vorausgesetzt werden (d.h. standardmäßig vorausgesetzt). — printed p.31', verification_note='md-verified 2026-09-05 (§4.2.3, printed p.31) [VC]', verified_at=now() where id='18b4026b-c481-4860-b3d5-371a203dda65' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-01 · anwendungsbereich — Anwendungsbereich des Umweltmanagementsystems
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation sollte die Grenzen und die Anwendbarkeit des Umweltmanagementsystems bestimmen, um dessen Anwendungsbereich festzulegen. Der Anwendungsbereich ist für jede Organisation einzigartig. [...] Die Bestimmung des Anwendungsbereichs schließt auch die physischen, funktionalen und organisatorischen Grenzen ein. | Die Organisation sollte den Anwendungsbereich als dokumentierte Information aufrechterhalten und sie den interessierten Parteien zur Verfügung stellen. — printed p.33–34', verification_note='md-verified 2026-09-05 (§4.3, printed p.33–34) [VC]', verified_at=now() where id='cdd55dc6-2798-409a-bb37-47a60e6767b8' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-01 · lebensweg_betrachtung_angewendet — Lebenswegbetrachtung angewendet
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Betrachtung des Lebenswegs umfasst die Berücksichtigung der Steuerung und Einflussnahme der Organisation im Hinblick auf die Phasen des Lebenswegs ihrer Produkte und Dienstleistungen. Diese Vorgehensweise ermöglicht es der Organisation, diejenigen Bereiche zu ermitteln, in denen sie unter Berücksichtigung ihres Anwendungsbereichs ihren Einfluss auf die Umwelt minimieren kann, während ein Mehrwert für die Organisation geschaffen wird. — printed p.23–28', verification_note='md-verified 2026-09-05 (§4.1, printed p.23–28; CAVEAT: the field is filed under §4.3, but the md defines the Lebenswegbetrachtung in §4.1 (and applies it in §6.1.2.3); §4.3 only mentions it in passing — clause retag proposed in the STAGED file) [VC]', verified_at=now() where id='d03d5cfe-565e-4ce4-a289-b76633cb7f27' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-02 · politik_verpflichtung_schutz_umwelt — Verpflichtung zum Schutz der Umwelt in der Politik
update public.fields set verification_status='verified_against_standard', verification_quote='Die Umweltpolitik sollte die Verpflichtung der Organisation umfassen, ihre bindenden Verpflichtungen und ihre Verpflichtungen in Bezug auf den Schutz der Umwelt, das Verhindern von [...] Umweltbelastungen und die fortlaufende Verbesserung zu erfüllen. Die Kästen zur praktischen Hilfe 7 und 8 bieten zusätzliche Informationen im Hinblick auf die Verpflichtungen der Umweltpolitik. — printed p.40–43', verification_note='md-verified 2026-09-05 (§5.2, printed p.40–43; the [...] marks a mathpix column break (md 1455 / 1462), not omitted normative text) [VC]', verified_at=now() where id='078239ff-92ee-4fd0-9afb-2ef042bd0e05' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-02 · verpflichtung_oberste_leitung — Nachweis der Verpflichtung der obersten Leitung
update public.fields set verification_status='verified_against_standard', verification_quote='Die Verpflichtung, Rechenschaftspflicht und Führungsfunktion der obersten Leitung sind für die erfolgreiche Umsetzung eines Umweltmanagementsystems unerlässlich, einschließlich der Fähigkeit, die beabsichtigten Ergebnisse zu erreichen. Die oberste Leitung sollte daher Verantwortung für die Wirksamkeit des Umweltmanagementsystems der Organisation übernehmen und sicherstellen, dass ihre beabsichtigten Ergebnisse erreicht werden. Die Verpflichtung der obersten Leitung bedeutet, dass sie physische und finanzielle Ressourcen bereitstellt und eine Ausrichtung vorgibt. — printed p.37–39', verification_note='md-verified 2026-09-05 (§5.1, printed p.37–39) [VC]', verified_at=now() where id='606659dd-03b2-45ec-9a85-7233d721d8ff' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-02 · umweltpolitik — Umweltpolitik (dokumentierte Information)
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Umweltpolitik legt die strategische Ausrichtung einer Organisation im Hinblick auf die Umwelt innerhalb des festgelegten Anwendungsbereichs des Umweltmanagementsystems fest. Die Umweltpolitik sollte einen Rahmen für die Festlegung von Umweltzielen bieten und den Grad der Umweltverantwortung und -leistung festlegen, der von der Organisation gefordert wird und anhand dessen alle nachfolgenden Tätigkeiten beurteilt werden können. | Die Umweltpolitik sollte als dokumentierte Information aufrechterhalten werden — printed p.40–43', verification_note='md-verified 2026-09-05 (§5.2, printed p.40–43) [VC]', verified_at=now() where id='02f007fa-bc6d-47f5-be8c-6aa3e12c23e0' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-02 · politik_kommuniziert — Umweltpolitik kommuniziert und verfuegbar
update public.fields set verification_status='verified_against_standard', verification_quote='Die Umweltpolitik sollte allen Personen mitgeteilt werden, die im Auftrag der Organisation tätig sind, und sollte den interessierten Parteien zur Verfügung gestellt werden. Die Organisation kann entscheiden, die Umweltpolitik uneingeschränkt zur Verfügung zu stellen, wie z. B. durch Veröffentlichung auf einer Website, oder, soweit erforderlich, kann sie diese, wenn Informationen über die Identität, Erfordernisse und Erwartungen der interessierten Parteien bekannt sind, oder auf Anfrage zur Verfügung stellen. — printed p.40–43', verification_note='md-verified 2026-09-05 (§5.2, printed p.40–43) [VC]', verified_at=now() where id='0ce9fef2-5190-40f0-bfbd-86368e552d21' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-02 · rollen_verantwortlichkeiten — Zugewiesene Rollen, Verantwortlichkeiten und Befugnisse
update public.fields set verification_status='verified_against_standard', verification_quote='Die oberste Leitung sollte (einen) Verantwortliche(n) ernennen oder (eine) Funktion(en) mit ausreichender Befugnis, ausreichendem Bewusstsein, ausreichender Kompetenz und Ressourcen zuteilen, um a) den Aufbau, die Verwirklichung und die Aufrechterhaltung des Umweltmanagementsystems auf allen zutreffenden Ebenen der Organisation sicherzustellen, b) der obersten Leitung eine Rückmeldung über das Umweltmanagementsystem zu liefern, einschließlich über die Umweltleistung und deren Chancen zur Verbesserung. — printed p.44–45', verification_note='md-verified 2026-09-05 (§5.3, printed p.44–45) [VC]', verified_at=now() where id='9dd1f896-7c5e-4458-a848-13439467fe5b' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-03 · taetigkeiten_produkte_dienstleistungen — Taetigkeiten, Produkte und Dienstleistungen
update public.fields set verification_status='verified_against_standard', verification_quote='Alle Tätigkeiten, Produkte und Dienstleistungen haben in gewisser Weise Auswirkungen auf die Umwelt, die in einer oder in allen Lebenswegphasen auftreten können, d.h. von der Beschaffung und Verteilung der Rohstoffe bis zur Nutzung und Entsorgung. Eine Organisation sollte ihre Tätigkeiten, Produkte und Dienstleistungen, die innerhalb des Anwendungsbereichs ihres Umweltmanagementsystems liegen, verstehen, um die damit verbundenen Umweltaspekte und -auswirkungen ermitteln zu können. — printed p.54', verification_note='md-verified 2026-09-05 (§6.1.2.2, printed p.54) [VC]', verified_at=now() where id='5c1184cc-1fad-42dc-a030-df86e61a0379' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-03 · umweltaspekt — Umweltaspekt
update public.fields set verification_status='verified_against_standard', verification_quote='Bei der Bestimmung von Umweltaspekten einer Organisation innerhalb des Anwendungsbereichs ihres Umweltmanagementsystems sollte die Organisation den Lebensweg in Betracht ziehen und diejenigen Aspekte berücksichtigen, die in Verbindung mit früheren, derzeitigen und zukünftigen Tätigkeiten, Produkten und Dienstleistungen stehen. In allen Fällen sollte die Organisation normale und abweichende Betriebsbedingungen, einschließlich Einschalt- und Ausschaltbedingungen, Wartungsbedingungen sowie vernünftigerweise vorhersehbare Notfallsituationen berücksichtigen. — printed p.54–55', verification_note='md-verified 2026-09-05 (§6.1.2.3, printed p.54–55) [VC]', verified_at=now() where id='ba925543-39bf-4e54-86da-1d38bce17111' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-03 · aspekt_lenkbarkeit — Lenkbarkeit des Umweltaspekts
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation, die ein Umweltmanagementsystem verwirklicht, sollte die Umweltaspekte bestimmen, die sie lenken kann und diejenigen Umweltaspekte, die sie unter Berücksichtigung des Lebenswegs beeinflussen kann (siehe 6.1.2.3). | Zusätzlich zu diesen Umweltaspekten, die von der Organisation direkt gelenkt werden können, sollte sie auch Aspekte betrachten, auf die sie lediglich Einfluss nehmen kann, z. B. solche, die sich auf von der Organisation eingesetzte Produkte und Dienstleistungen beziehen, und solche, die mit von ihr angebotenen Produkten und Dienstleistungen zusammenhängen. — printed p.52–53 und p.54–55', verification_note='md-verified 2026-09-05 (§6.1.2.1 printed p.52–53 und §6.1.2.3 printed p.54–55) [VC]', verified_at=now() where id='81f9761a-6079-4e60-ae82-4f398c9da5ce' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-03 · umweltauswirkung — Umweltauswirkung
update public.fields set verification_status='verified_against_standard', verification_quote='Veränderungen in Bezug auf die Umwelt, schädlich oder nützlich, die ganz oder teilweise von Umweltaspekten herrühren, werden Umweltauswirkungen genannt. Zu den Beispielen für schädliche Umweltauswirkungen zählen Luftverschmutzung und der Abbau natürlicher Rohstoffe. Beispiele für nützliche Umweltauswirkungen sind eine verbesserte Wasserqualität oder Bodenbeschaffenheit. Der Zusammenhang zwischen Umweltaspekten und damit verbundenen Umweltauswirkungen beruht auf einem Ursache-Wirkungs-Prinzip. — printed p.52–53', verification_note='md-verified 2026-09-05 (§6.1.2.1, printed p.52–53) [VC]', verified_at=now() where id='cda0efe8-5432-458d-a4b9-111cf67bbf80' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-03 · auswirkung_art — Art der Umweltauswirkung
update public.fields set verification_status='verified_against_standard', verification_quote='Mit dem ausgewählten Ansatz sollte es möglich sein, Folgendes zu erkennen: - positive (nützliche) Umweltauswirkungen sowie negative (schädliche) Umweltauswirkungen; [...] - tatsächliche und potenzielle Umweltauswirkungen; — printed p.56–57', verification_note='md-verified 2026-09-05 (§6.1.2.4, printed p.56–57) [VC]', verified_at=now() where id='84a68468-9dfd-4a1c-9ece-0220dafd8dcf' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-03 · bedeutungskriterien — Kriterien zur Bestimmung bedeutender Umweltaspekte
update public.fields set verification_status='verified_against_standard', verification_quote='Da die Organisation eine Vielzahl von Umweltaspekten und damit verbundenen Umweltauswirkungen haben kann, sollte sie Kriterien festlegen und eine Methode einführen, um diejenigen Aspekte zu bestimmen, die für sie bedeutend sind. Kriterien können den Umweltaspekt betreffen (z. B. Typ, Größe, Häufigkeit) oder die Umweltauswirkung (z. B. Ausmaß, Schwere, Dauer, Exposition). [...] Die Festlegung und Anwendung derartiger Kriterien sollten Kontinuität bei der Beurteilung der Bedeutung sicherstellen. — printed p.58–59', verification_note='md-verified 2026-09-05 (§6.1.2.5, printed p.58–59) [VC]', verified_at=now() where id='49d485f9-2601-447b-aec3-c761165b6d37' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-03 · bedeutung_stufe — Bedeutungsstufe
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation kann Ebenen (oder Werte) der Bedeutung festlegen, die mit den einzelnen Kriterien in Zusammenhang gebracht werden. [...] Eine Art Maßstab oder Rangfolge kann hilfreich für die Einstufung der Bedeutung sein, zum Beispiel quantitativ in Form eines Zahlenwertes oder qualitativ in Form von Stufen, wie z. B. hoch, mittel, niedrig oder vernachlässigbar. — printed p.58–59', verification_note='md-verified 2026-09-05 (§6.1.2.5, printed p.58–59; CAVEAT (SR-2): the md prints the four levels as an EXAMPLE ("zum Beispiel ... wie z. B.") of one possible scale, next to the quantitative alternative "in Form eines Zahlenwertes" — the encoded 4-value enum is therefore a closed list where the source leaves the scale to the organization; enum review staged) [VC]', verified_at=now() where id='27f1029f-2067-4667-8e58-1a8d77e05693' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-03 · bedeutender_umweltaspekt — Bedeutender Umweltaspekt
update public.fields set verification_status='verified_against_standard', verification_quote='Für die Organisation kann es hilfreich sein, die Bedeutung eines Umweltaspektes und die damit verbundenen Umweltauswirkungen zu bewerten, indem sie die Ergebnisse dieser Kriterien kombiniert. Sie sollte entscheiden, welche Umweltaspekte bedeutend sind, z. B. durch die Anwendung eines Schwellenwertes. Wenn eine solche Vorgehensweise angewendet wird, sollte die Organisation jedoch den Schwellenwert begründen können. — printed p.58–59', verification_note='md-verified 2026-09-05 (§6.1.2.5, printed p.58–59) [VC]', verified_at=now() where id='944b30dc-2862-45c3-9c9d-1ac4caa882ee' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-03 · risiko_chance — Risiko bzw. Chance, die zu beruecksichtigen ist
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation sollte über (einen) Prozess(e) zur Bestimmung von Risiken und Chancen verfügen, die zu berücksichtigen sind. [...] Bindenden Verpflichtungen, Ansichten von interessierten Parteien sowie sonstigen Quellen für Risiken und Chancen, die zu berücksichtigen sind, beispielsweise Umweltzustände, einschließlich Umweltereignisse, sollte Rechnung getragen werden. | potenziell ungünstige Auswirkungen (Bedrohungen) und potenziell günstige Auswirkungen (Chancen) — printed p.46–51 und p.16–18', verification_note='md-verified 2026-09-05 (§6.1.1 printed p.46–51 und Begriff 3.2.11 printed p.16–18) [VC]', verified_at=now() where id='f797db8c-b84e-4742-a094-8d614893e5aa' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-03 · notfallsituation — Moegliche Notfallsituation
update public.fields set verification_status='verified_against_standard', verification_quote='In allen Fällen sollte die Organisation normale und abweichende Betriebsbedingungen, einschließlich Einschalt- und Ausschaltbedingungen, Wartungsbedingungen sowie vernünftigerweise vorhersehbare Notfallsituationen berücksichtigen. | Bei der Vorbereitung einer Gefahrenabwehr in vernünftigerweise vorhersehbaren Notfallsituationen sollte insbesondere auf die Einschalt- und Ausschaltbedingungen sowie auf abweichende Betriebsbedingungen geachtet werden. Siehe 6.1.1 für die Bestimmung von Notfallsituationen. — printed p.54–55 und p.90–91', verification_note='md-verified 2026-09-05 (§6.1.2.3 printed p.54–55 und §8.2 printed p.90–91; CAVEAT: the field is filed under §6.1.1, but §6.1.1''s own text in the md never names Notfallsituationen — the §6.1.1 home rests only on the §8.2 back-reference "Siehe 6.1.1 für die Bestimmung von Notfallsituationen"; clause note staged) [VC]', verified_at=now() where id='3c6972d0-8a91-42da-bd32-7e770f193c26' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-04 · bindende_verpflichtung — Bindende Verpflichtung
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation sollte anhand des in 4.2.4 erlangten Wissens einen Prozess festlegen, verwirklichen und aufrechterhalten, mit dem bindende Verpflichtungen, die auf die Umweltaspekte ihrer Tätigkeiten, Produkte und Dienstleistungen zutreffen, ermittelt werden und Zugang zu ihnen hergestellt wird. | rechtliche Verpflichtungen, die eine Organisation (3.1.4) erfüllen muss und andere Anforderungen (3.2.8), die eine Organisation erfüllen muss oder zu deren Erfüllung sich eine Organisation entschließt — printed p.60–61 und p.16–18', verification_note='md-verified 2026-09-05 (§6.1.3.1 printed p.60–61 und Begriff 3.2.9 printed p.16–18) [VC]', verified_at=now() where id='b7a65fc3-ef3b-478d-ad10-b0fa1ec286d8' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-04 · verpflichtung_art — Art der bindenden Verpflichtung
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation kann Zugriff auf eine oder mehrere Informationsquellen haben, um rechtliche Verpflichtungen in Bezug auf ihre Umweltaspekte zu ermitteln. | Eine Organisation sollte außerdem bestimmen, wie weitere bindende Verpflichtungen, die sie angenommen hat und die von anderen interessierten Parteien stammen (wie in 4.2 ermittelt), im Zusammenhang mit den Umweltaspekten der Organisation stehen. — printed p.62 und p.63', verification_note='md-verified 2026-09-05 (§6.1.3.2 printed p.62 (rechtliche Verpflichtung) und §6.1.3.3 printed p.63 (weitere Anforderung) — the two enum values are exactly these two sub-clauses) [VC]', verified_at=now() where id='4b9984ee-abee-424e-a274-87fc8dce0035' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-04 · verpflichtung_ursprung — Ursprung der bindenden Verpflichtung (interessierte Partei)
update public.fields set verification_status='verified_against_standard', verification_quote='Dieses Verzeichnis bzw. diese Liste könnte Folgendes enthalten: - den Ursprung der bindenden Verpflichtung, einschließlich der relevanten interessierten Partei; — printed p.63', verification_note='md-verified 2026-09-05 (§6.1.3.4, printed p.63) [VC]', verified_at=now() where id='024cf673-6e2e-483e-ba61-e3b915ccc890' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-04 · verpflichtung_bezug_aspekt — Bezug der Verpflichtung zu Umweltaspekten / Anforderungen
update public.fields set verification_status='verified_against_standard', verification_quote='Dieses Verzeichnis bzw. diese Liste könnte Folgendes enthalten: [...] - in welchem Zusammenhang die bindenden Verpflichtungen zu den Aspekten der Organisation und/oder zu den relevanten Anforderungen der interessierten Parteien stehen. — printed p.63', verification_note='md-verified 2026-09-05 (§6.1.3.4, printed p.63) [VC]', verified_at=now() where id='18394965-10cc-488a-abb3-e19c4ac5124f' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-04 · verpflichtung_verzeichnis — Verzeichnis bindender Verpflichtungen (dokumentierte Information)
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation sollte dokumentierte Informationen über ihre bindenden Verpflichtungen aufrechterhalten, die in Form eines Verzeichnisses oder einer Liste gestaltet werden könnten. Dies kann dabei helfen, das Bewusstsein und die Transparenz im Hinblick auf geltende Anforderungen aufrechtzuerhalten. Dieses Verzeichnis sollte regelmäßig überprüft werden, um sicherzustellen, dass es aktuell bleibt. — printed p.63', verification_note='md-verified 2026-09-05 (§6.1.3.4, printed p.63; CAVEAT: the source obliges dokumentierte Information ("sollte ... aufrechterhalten") but leaves the VERZEICHNIS/LISTE form optional ("gestaltet werden könnten") — the boolean is_required=true over-reads that; review staged) [VC]', verified_at=now() where id='efe4fa8d-920f-4a34-bedb-a9a374334e26' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-05 · geplante_massnahme — Geplante Massnahme
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation sollte überlegen und planen, wie sie Maßnahmen ergreifen kann, um bedeutende Umweltaspekte, bindende Verpflichtungen sowie Risiken und Chancen zu behandeln, die zu berücksichtigen sind, wie in 6.1.1 festgelegt. [...] Bei der Planung von Maßnahmen sollte die Organisation ihre technologischen Möglichkeiten und die Durchführbarkeit und ihre finanziellen, betrieblichen und geschäftlichen Anforderungen berücksichtigen. — printed p.63–64', verification_note='md-verified 2026-09-05 (§6.1.4, printed p.63–64) [VC]', verified_at=now() where id='175a8ed3-2e2e-4b43-b083-e06fa1b376e7' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-05 · massnahme_wirksamkeit — Bewertung der Wirksamkeit der Massnahme
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation sollte außerdem die Wirksamkeit der ergriffenen Maßnahmen bestimmen. | Organisationen können eine Vielzahl an Methoden und Techniken zur Bewertung der Wirksamkeit der ergriffenen Maßnahmen übernehmen, die von statistischen Techniken bis hin zu Vergleichen von Überwachungs- und Messergebnissen mit den erwarteten Leistungswerten reichen (siehe 9.1). — printed p.63–64', verification_note='md-verified 2026-09-05 (§6.1.4, printed p.63–64) [VC]', verified_at=now() where id='433c5589-549b-4a13-b5f6-4abb897f6a44' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-05 · umweltziel — Umweltziel
update public.fields set verification_status='verified_against_standard', verification_quote='Umweltziele sollten auf der obersten Ebene der Organisation und auf anderen Ebenen und Funktionsbereichen, in denen Tätigkeiten durchgeführt werden, die für die Erfüllung der Verpflichtungen aus der Umweltpolitik und der übergreifenden Ziele der Organisation von Bedeutung sind, festgelegt werden. Die Umweltziele sollten mit der Umweltpolitik und der Verpflichtung zum Schutz der Umwelt übereinstimmen, einschließlich des Verhinderns von Umweltbelastungen, der Erfüllung bindender Verpflichtungen und der fortlaufenden Verbesserung. — printed p.65–66', verification_note='md-verified 2026-09-05 (§6.2.2, printed p.65–66) [VC]', verified_at=now() where id='ddf46d98-48cd-44f1-a6af-bf5c278aa304' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-05 · einzelziel — Einzelziel (messbare Leistungsanforderung)
update public.fields set verification_status='verified_against_standard', verification_quote='Ein Umweltziel kann entweder direkt als spezifisches Leistungsniveau oder auf allgemeine Weise ausgedrückt und durch ein oder mehrere Einzelziele näher bestimmt werden, d.h. durch eine detaillierte Leistungsanforderung, die erfüllt werden sollte, um das Umweltziel zu erreichen. Wenn Einzelziele festgelegt werden, sollten sie messbar sein. Einzelziele müssen möglicherweise mit einem festgelegten Zeitrahmen versehen sein. — printed p.65–66', verification_note='md-verified 2026-09-05 (§6.2.2, printed p.65–66) [VC]', verified_at=now() where id='1da7f164-0fc5-4cf5-8519-bef8b7af1da3' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-05 · ziel_messbar — Umweltziel/Einzelziel messbar
update public.fields set verification_status='verified_against_standard', verification_quote='Wenn Einzelziele festgelegt werden, sollten sie messbar sein. Einzelziele müssen möglicherweise mit einem festgelegten Zeitrahmen versehen sein. — printed p.65–66', verification_note='md-verified 2026-09-05 (§6.2.2, printed p.65–66; CAVEAT: the measurability duty is CONDITIONAL on Einzelziele having been set ("Wenn Einzelziele festgelegt werden") — it is not an unconditional duty on every Umweltziel) [VC]', verified_at=now() where id='ebdfd5c1-15f6-4efd-aa16-d086de06b459' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-05 · ziel_programm — Programm zum Erreichen der Umweltziele
update public.fields set verification_status='verified_against_standard', verification_quote='Ein Teil des Planungsprozesses kann ein Programm (Programme) zum Erreichen der Umweltziele einer Organisation umfassen. Das Programm sollte Rollen, Verantwortlichkeiten, Prozesse, Ressourcen, Zeitrahmen, Prioritäten und Maßnahmen, die zum Erreichen der Umweltziele notwendig sind, zuweisen. — printed p.67', verification_note='md-verified 2026-09-05 (§6.2.3, printed p.67; the programme itself is optional ("kann ... umfassen"), only its CONTENT is a "sollte") [VC]', verified_at=now() where id='9b6f85f2-38e3-48cf-8d54-53bfb0a926d0' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-05 · leistungskennzahl — Umweltleistungskennzahl
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation sollte Umweltleistungskennzahlen festlegen, die objektive, nachweisbare und reproduzierbare Ergebnisse hervorbringen können. Die Kennzahlen sollten für die Tätigkeiten, Produkte und Dienstleistungen der Organisation geeignet sein, im Einklang mit deren Umweltpolitik stehen, praktisch, kostensparend und technisch durchführbar sein. — printed p.68', verification_note='md-verified 2026-09-05 (§6.2.4, printed p.68) [VC]', verified_at=now() where id='d5207cb4-e756-446f-881e-82a9f16c732b' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-05 · leistungskennzahl_typ — Typ der Leistungskennzahl
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation kann die Verwendung von Umweltzustandskennzahlen (ECIs), Managementleistungskennzahlen (MPIs) und Betriebsleistungskennzahlen (OPIs) in Betracht ziehen, die für ihre bedeutenden Umweltaspekte geeignet sind. — printed p.68', verification_note='md-verified 2026-09-05 (§6.2.4, printed p.68; the three enum values are exactly the three printed indicator types) [VC]', verified_at=now() where id='1e3f1361-913b-4304-bfe9-808fd500b9a8' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-06 · ressourcenbedarf — Bestimmter Ressourcenbedarf
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation sollte die Ressourcen bestimmen, die notwendig sind, um das Umweltmanagementsystem aufzubauen, zu verwirklichen, aufrechtzuerhalten und zu verbessern. Beim Bestimmen der benötigten Ressourcen sollte die Organisation Folgendes berücksichtigen: - Infrastruktur; - extern bereitgestellte Ressourcen; - Informationssysteme; - Kompetenz; - Technik; - finanzielle, personelle und andere Ressourcen, die spezifisch für ihre Tätigkeiten, Produkte und Dienstleistungen sind. — printed p.69–70', verification_note='md-verified 2026-09-05 (§7.1, printed p.69–70) [VC]', verified_at=now() where id='e7cc8022-de37-4ab3-8f1b-428381468e2a' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-06 · kompetenzbedarf — Ermittelter Kompetenzbedarf
update public.fields set verification_status='verified_against_standard', verification_quote='Alle Personen, die unter Aufsicht einer Organisation Tätigkeiten verrichten und durch ihre Arbeit die Umweltleistung der Organisation, einschließlich ihrer Fähigkeit zur Erfüllung der bindenden Verpflichtungen, beeinflussen oder beeinflussen können, sollten durch Schulungen, Ausbildung, Erfahrung oder eine Kombination daraus, wie von der Organisation festgelegt, kompetent sein. | Die Organisation sollte die notwendigen Kompetenzen ermitteln, die erforderlich sind, um die beabsichtigten Ergebnisse des Umweltmanagementsystems zu erreichen und Lücken zu schließen — printed p.71–74', verification_note='md-verified 2026-09-05 (§7.2, printed p.71–74) [VC]', verified_at=now() where id='73d5f262-dcb9-4ac5-9209-bd7d9f0c95a8' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-06 · kompetenznachweis — Nachweis der Kompetenz (dokumentierte Information)
update public.fields set verification_status='verified_against_standard', verification_quote='Es sollten zumindest geeignete dokumentierte Informationen als Nachweis für die Kompetenzen aufrechterhalten werden. | Die Organisation sollte dokumentierte Informationen als Nachweis (Aufzeichnungen) für Folgendes aufbewahren: - Kompetenzen, soweit erforderlich (siehe 7.2); — printed p.71–74 und p.81–83', verification_note='md-verified 2026-09-05 (§7.2 printed p.71–74 und Kasten zur praktischen Hilfe 19 in §7.5.1 printed p.81–83) [VC]', verified_at=now() where id='040aebbb-1b81-4221-958b-87b77d185729' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-06 · schulungsplan — Schulungsplan / -programm
update public.fields set verification_status='verified_against_standard', verification_quote='Wenn Kompetenzen durch Schulung erworben werden, kann (können) der Schulungsprozess (die Schulungsprozesse) der Organisation Folgendes umfassen: - Kennzeichnung des Schulungsbedarfs; - Entwicklung eines Schulungsplans oder -programms, der/das sich auf den ermittelten Schulungsbedarf bezieht; - Durchführung von Schulungen; - Bewertung der Schulungsergebnisse; - Dokumentation und Überwachung der durchgeführten Schulungen. — printed p.71–74', verification_note='md-verified 2026-09-05 (§7.2, printed p.71–74) [VC]', verified_at=now() where id='6305e1d5-4c69-470e-8d8e-67b54c2940b7' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-06 · bewusstsein_gefoerdert — Bewusstsein der Personen gefoerdert
update public.fields set verification_status='verified_against_standard', verification_quote='Die oberste Leitung sollte außerdem sicherstellen, dass das Bewusstsein aller Personen, die unter Aufsicht der Organisation Tätigkeiten verrichten, hinsichtlich Folgendem gefördert wird: - der Umweltpolitik der Organisation und ihre Verpflichtung zur Umweltpolitik, - der Bedeutung der Erfüllung von Anforderungen des Umweltmanagementsystems, - deren Beitrag zur Wirksamkeit des Umweltmanagementsystems, - dem Nutzen einer verbesserten Umweltleistung, - deren Verantwortlichkeiten und Befugnisse innerhalb des Umweltmanagementsystems, — printed p.75', verification_note='md-verified 2026-09-05 (§7.3, printed p.75) [VC]', verified_at=now() where id='fd28ba28-9c31-40b3-9752-166f343ffb44' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-06 · kommunikationsprozess — Kommunikationsprozess (was/wann/an wen/wie)
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation sollte Prozesse für die für das Umweltmanagementsystem relevante Kommunikation unter Berücksichtigung der bindenden Verpflichtungen der Organisation festlegen. Diese Prozesse sollten ermitteln: - welche Informationen kommuniziert werden müssen; - wann oder unter welchen Umständen sie kommuniziert werden müssen; - an wen sie kommuniziert werden müssen; - wie sie kommuniziert werden. — printed p.76–78', verification_note='md-verified 2026-09-05 (§7.4.1, printed p.76–78) [VC]', verified_at=now() where id='4d445cf0-36c4-4ccd-9b80-86015fabca46' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-06 · kommunikation_richtung — Richtung der Kommunikation
update public.fields set verification_status='verified_against_standard', verification_quote='Die Kommunikation zwischen den und innerhalb der Ebenen und Funktionsbereiche einer Organisation ist entscheidend für die Wirksamkeit des Umweltmanagementsystems. | Die Kommunikation mit externen interessierten Parteien kann ein wichtiges und wirksames Instrument für das Umweltmanagement sein. Eine Organisation sollte die Kommunikationsanforderungen im Hinblick auf ihre bindenden Verpflichtungen und ihre Kommunikationsprozesse (siehe 7.4.1) berücksichtigen und relevante Informationen zum Umweltmanagementsystem, bei Bedarf, extern kommunizieren. — printed p.79 und p.80', verification_note='md-verified 2026-09-05 (§7.4.2 printed p.79 (intern) und §7.4.3 printed p.80 (extern) — the two enum values are exactly these two sub-clauses) [VC]', verified_at=now() where id='c3c6c711-0ba9-4b2d-9bac-c03476eeb2ef' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-06 · dokumentierte_information — Dokumentierte Information des UMS
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation sollte angemessene dokumentierte Informationen erfassen und aufbewahren, um sicherzustellen, dass ihr Umweltmanagementsystem wirksam arbeitet, von den Personen, die unter Aufsicht der Organisation Tätigkeiten verrichten sowie von anderen relevanten interessierten Parteien verstanden wird, und dass Prozesse im Zusammenhang mit dem Umweltmanagementsystem planmäßig durchgeführt werden. | Die Organisation sollte folgende dokumentierte Informationen aufrechterhalten: - der Anwendungsbereich des Umweltmanagementsystems (siehe 4.3); - die Umweltpolitik (siehe 5.2); — printed p.81–83', verification_note='md-verified 2026-09-05 (§7.5.1 mit Kasten zur praktischen Hilfe 19, printed p.81–83) [VC]', verified_at=now() where id='3992bad1-c597-4adc-9b0a-8a508876f206' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-06 · dokument_lenkung — Lenkung dokumentierter Information
update public.fields set verification_status='verified_against_standard', verification_quote='Die Lenkung dokumentierter Information des Umweltmanagementsystems ist wichtig, um sicherzustellen, dass - die Informationen der entsprechenden Organisation, Abteilung, Funktion, Tätigkeit oder Kontaktperson zugeordnet werden können; - die Informationen, die von der Organisation aufbewahrt werden, regelmäßig überprüft, nach Bedarf überarbeitet und von befugten Personen vor der Herausgabe genehmigt werden; — printed p.84', verification_note='md-verified 2026-09-05 (§7.5.3, printed p.84) [VC]', verified_at=now() where id='715ec806-b140-413c-a7d8-c1f10e38b371' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-07 · betriebliche_steuerung — Festgelegte betriebliche Steuerung
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation sollte sicherstellen, dass ihre Betriebsabläufe und zugehörigen Prozesse gesteuert werden, um den Verpflichtungen ihrer Umweltpolitik nachzugehen, ihre Umweltziele zu erreichen und ihre bedeutenden Umweltaspekte, bindenden Verpflichtungen sowie ihre Risiken und Chancen, die zu berücksichtigen sind, zu steuern. | Betriebliche Steuerungen können in verschiedenster Weise erfolgen, wie z. B. als Verfahren, Arbeitsanweisungen, technische Überwachungen, Einsatz von kompetentem Personal oder eine Kombination dieser Formen. — printed p.85 und p.89', verification_note='md-verified 2026-09-05 (§8.1.1 printed p.85 und §8.1.3 printed p.89) [VC]', verified_at=now() where id='cf7ffe9e-3bef-499a-b119-2cc9c835094c' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-07 · steuerungshierarchie — Stufe der Steuerungshierarchie
update public.fields set verification_status='verified_against_standard', verification_quote='Bei der Betrachtung von Steuerungen für schädliche Umweltauswirkungen kann sich die Organisation auf die folgende Hierarchie beziehen: - Beseitigung, wie z. B. Verbot des Einsatzes von PCB, FCKW usw.; - Ersatz, wie z. B. Wechsel von Farben auf Lösemittelbasis zu Farben auf Wasserbasis; - technische Überwachung, wie z. B. Schadstoffbegrenzung, emissionsmindernde Technologie usw.; - verwaltungstechnische Überwachung, wie z. B. Verfahren, Sichtkontrollen, Arbeitsanweisungen, Sicherheitsdatenblätter (SDS/MSDS/CSDS) usw. — printed p.85', verification_note='md-verified 2026-09-05 (§8.1.1, printed p.85; the four enum values are exactly the four printed hierarchy steps, but the hierarchy itself is offered as "kann sich die Organisation ... beziehen") [VC]', verified_at=now() where id='75e50077-241e-4241-a7ee-42b082e9fa34' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-07 · ablaufkriterien — Akzeptable Ablaufkriterien
update public.fields set verification_status='verified_against_standard', verification_quote='Ein gebräuchlicher Ansatz zur Einführung von betrieblichen Steuerungen kann aus Folgendem bestehen: a) Auswahl eines Steuerungsverfahrens; b) Auswahl akzeptabler Ablaufkriterien, z. B. Bedienungseigenschaften von Maschinen und Messungen des Gewichts oder der Temperatur; — printed p.89', verification_note='md-verified 2026-09-05 (§8.1.3, printed p.89) [VC]', verified_at=now() where id='aec10c1f-5d86-4dab-b5b8-ea370fc18bc4' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-07 · notfallplan — Notfallvorsorge- und Gefahrenabwehrplan
update public.fields set verification_status='verified_against_standard', verification_quote='Es liegt in der Verantwortung jeder Organisation, Pläne zur Notfallvorsorge und Gefahrenabwehr festzulegen, die ihren eigenen individuellen Erfordernissen entsprechen. Bei der Festlegung ihrer Pläne sollte die Organisation Folgendes berücksichtigen: - tatsächliche und mögliche externe Umweltbedingungen, einschließlich Naturkatastrophen; - die Art der Gefährdungen vor Ort, z. B. brennbare Flüssigkeiten, Speichertanks, komprimierte Gase sowie Maßnahmen, die bei Austreten oder unbeabsichtigter Freisetzung von Stoffen einzuleiten sind; — printed p.90–91', verification_note='md-verified 2026-09-05 (§8.2, printed p.90–91) [VC]', verified_at=now() where id='7b1e9650-70d8-4806-9e91-85cea0a0786f' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-07 · notfalluebung_durchgefuehrt — Regelmaessige Notfalluebung durchgefuehrt
update public.fields set verification_status='verified_against_standard', verification_quote='Bei der Festlegung ihrer Pläne sollte die Organisation Folgendes berücksichtigen: [...] - Prozess(e) zur Auswertung von Notfällen, einschließlich der Bewertung der geplanten Gefahrenabwehr, um Korrektur- und Vorbeugungsmaßnahmen festzulegen und zu verwirklichen; - regelmäßige Durchführung von Notfallübungen; — printed p.90–91', verification_note='md-verified 2026-09-05 (§8.2, printed p.90–91) [VC]', verified_at=now() where id='c07e1fbc-0407-4c49-a00a-35e9d5eedd50' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-07 · gefahrstoff_liste — Liste gefaehrlicher Stoffe mit moeglichen Umweltauswirkungen
update public.fields set verification_status='verified_against_standard', verification_quote='Bei der Festlegung ihrer Pläne sollte die Organisation Folgendes berücksichtigen: [...] - Angaben zu gefährlichen Stoffen, einschließlich aller möglichen Umweltauswirkungen dieser Stoffe und der Maßnahmen, die bei unfallbedingtem Freisetzen zu ergreifen sind; — printed p.90–91', verification_note='md-verified 2026-09-05 (§8.2, printed p.90–91) [VC]', verified_at=now() where id='9b3d7940-f952-4667-ac9f-f72fb85fe072' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-08 · ueberwachung_messung_ergebnis — Ergebnisse von Ueberwachung, Messung, Analyse und Bewertung
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation sollte über einen systematischen Ansatz für die regelmäßige Überwachung, Messung, Analyse und Bewertung ihrer Umweltleistung verfügen. [...] Eine Organisation sollte bestimmen, was überwacht und gemessen werden muss, wobei ihre Umweltziele, bedeutenden Umweltaspekte, bindenden Verpflichtungen und betrieblichen Steuerungen zu berücksichtigen sind. Dazu sollte die Bestimmung der Häufigkeit und der zur Erfassung der Daten genutzten Methoden gehören. — printed p.92–93', verification_note='md-verified 2026-09-05 (§9.1.1, printed p.92–93) [VC]', verified_at=now() where id='206e7ca1-d9b2-4147-8754-2f41f5f1e385' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-08 · einhaltungsbewertung_ergebnis — Ergebnis der Bewertung der Einhaltung bindender Verpflichtungen
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Organisation sollte einen Prozess festlegen, um das Ausmaß der Erfüllung ihrer bindenden Verpflichtungen durch Überwachung, Messung, Analyse und Überprüfung ihrer Leistung hinsichtlich ihrer bindenden Verpflichtungen zu bewerten, wie in 4.2 und 6.1.3 bestimmt. | Die Organisation sollte dokumentierte Informationen als Nachweis für ihre Bewertung der Einhaltung von Verpflichtungen aufbewahren. — printed p.94–96', verification_note='md-verified 2026-09-05 (§9.1.2, printed p.94–96) [VC]', verified_at=now() where id='9ad75752-ab07-4090-80cf-35a6b901076f' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-08 · einhaltungsbewertung_haeufigkeit — Haeufigkeit der Einhaltungsbewertung
update public.fields set verification_status='verified_against_standard', verification_quote='Durch die Bewertung der Einhaltung von Verpflichtungen erlangt die Organisation das Wissen und Verständnis über ihren Einhaltungsstatus. Die Häufigkeit von Bewertungen der Einhaltung von Verpflichtungen sollte geeignet sein, um dieses Wissen und Verständnis auf dem neuesten Stand zu halten. Bewertungen sollten auf eine Weise durchgeführt werden, dass sie einen zeitnahen Input für die Managementbewertung (siehe 9.3) zur Verfügung stellen. — printed p.94–96', verification_note='md-verified 2026-09-05 (§9.1.2, printed p.94–96; CAVEAT: the encoded description says the frequency may vary PER bindender Verpflichtung — the 2016 md carries no such per-obligation sentence; description review staged) [VC]', verified_at=now() where id='c389dc74-505f-4c6b-a909-8d256f18e312' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-08 · auditprogramm — Internes Auditprogramm
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation sollte ein internes Auditprogramm einführen, um die Planung und Durchführung von internen Audits zu leiten und die Audits ausfindig zu machen, die benötigt werden, um die Ziele des Auditprogramms zu erreichen. | Nicht jedes interne Audit braucht das gesamte System abzudecken, solange durch das Auditprogramm sichergestellt ist, dass alle organisationsbezogenen Einheiten und Funktionen, Systemelemente und der vollständige Anwendungsbereich des Umweltmanagementsystems regelmäßig auditiert werden. — printed p.97–98', verification_note='md-verified 2026-09-05 (§9.2, printed p.97–98) [VC]', verified_at=now() where id='684df4cd-1796-48a9-88c3-57dce953e2ac' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-08 · auditergebnis — Auditergebnis (dokumentierte Information)
update public.fields set verification_status='verified_against_standard', verification_quote='Die Ergebnisse eines internen Audits können in Form eines Berichts als Grundlage für die Verifizierung bereitgestellt werden und zur Korrektur oder zum Vermeiden von spezifischen Nichtkonformitäten oder zum Erreichen eines oder mehrerer Ziele des Auditprogramms verwendet werden und eine Eingabe für die Managementbewertung liefern. | Die Organisation sollte dokumentierte Information als Nachweis der Verwirklichung des Auditprogramms und der Ergebnisse des Audits aufbewahren. — printed p.97–98', verification_note='md-verified 2026-09-05 (§9.2, printed p.97–98) [VC]', verified_at=now() where id='16dd8430-36c6-4966-9bf9-9c2d868c636f' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-08 · managementbewertung_eingaben — Eingaben fuer die Managementbewertung
update public.fields set verification_status='verified_against_standard', verification_quote='Eingaben für die Managementbewertung können Folgendes umfassen: - die Ergebnisse von den Audits und Bewertungen der Erfüllung von bindenden Verpflichtungen; - Aussagen externer interessierter Parteien, einschließlich Beschwerden; - die Umweltleistung der Organisation; - den erreichten Erfüllungsgrad der Umweltziele der Organisation; - den Status von Korrekturmaßnahmen; - die Folgemaßnahmen aus früheren Managementbewertungen; — printed p.99–100', verification_note='md-verified 2026-09-05 (§9.3, printed p.99–100) [VC]', verified_at=now() where id='d7362f77-c413-4f1b-ac7e-1d40815817ee' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-08 · managementbewertung_ergebnisse — Ergebnisse der Managementbewertung
update public.fields set verification_status='verified_against_standard', verification_quote='Ergebnisse aus der Überprüfung des Umweltmanagementsystems sollten Entscheidungen hinsichtlich Folgendem umfassen: - der Eignung, Angemessenheit und Wirksamkeit des Systems; - Möglichkeiten zur fortlaufenden Verbesserung; - der Notwendigkeit von Änderungen von physischen, personellen und finanziellen Ressourcen; - Maßnahmen bei Nichterreichen der Umweltziele, sofern erforderlich; — printed p.99–100', verification_note='md-verified 2026-09-05 (§9.3, printed p.99–100) [VC]', verified_at=now() where id='979b59ae-f815-48e2-b990-bf6490685ca5' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-09 · verbesserungsmoeglichkeit — Ermittelte Verbesserungsmoeglichkeit
update public.fields set verification_status='verified_against_standard', verification_quote='Verbesserung ist wesentlich für ein wirksames Umweltmanagementsystem. Die Organisation sollte Möglichkeiten zur Verbesserung anhand folgender Maßnahmen ermitteln: - Überwachung, Messung, Analyse und Bewertung in Bezug auf die Umweltleistung und die Erfüllung der bindenden Verpflichtungen (siehe 9.1); - Audits zu ihrem Umweltmanagementsystem (siehe 9.2); - Managementbewertung (siehe 9.3). — printed p.101', verification_note='md-verified 2026-09-05 (§10.1, printed p.101) [VC]', verified_at=now() where id='0fb98d89-3080-4e49-b0e8-73e7332152f0' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-09 · nichtkonformitaet — Ermittelte Nichtkonformitaet
update public.fields set verification_status='verified_against_standard', verification_quote='Nichtkonformität ist die Nichterfüllung einer Anforderung, die in Bezug auf das Umweltmanagementsystem oder die Umweltleistung festgelegt werden kann. Es können Situationen auftreten, in denen ein Teil des Umweltmanagementsystems nicht wie vorgesehen funktioniert oder die Anforderungen an die Umweltleistung nicht erfüllt werden. — printed p.102–103', verification_note='md-verified 2026-09-05 (§10.2, printed p.102–103) [VC]', verified_at=now() where id='103f8de9-1885-4cde-8647-0ba277f8ba5a' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-09 · konformitaet_status — Konformitaetsstatus (Audit-/Bewertungsfeststellung)
update public.fields set verification_status='verified_against_standard', verification_quote='Konformität: Erfüllung einer Anforderung | Nichtkonformität: Nichterfüllung einer Anforderung | Nichtkonformität ist die Nichterfüllung einer Anforderung, die in Bezug auf das Umweltmanagementsystem oder die Umweltleistung festgelegt werden kann. — printed p.20–22 und p.102–103', verification_note='md-verified 2026-09-05 (Begriffe 3.4.2/3.4.3 printed p.20–22 und §10.2 printed p.102–103; the mathpix transcript renders both definitions inside their heading line, so the term and its definition are quoted as one run) [VC]', verified_at=now() where id='78edd962-aa84-4da1-864a-05e7f660a9a7' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-09 · nichtkonformitaet_art — Art der Nichtkonformitaet
update public.fields set verification_status='verified_against_standard', verification_quote='Zu den Beispielen für derartige Situationen zählen: - Nichtkonformität der Leistungen des Umweltmanagementsystems, wie z. B.: - die Umweltaspekte von Produkten werden nicht im Hinblick auf ihre Bedeutung bewertet; [...] - Nichtkonformität der Umweltleistung, wie z. B.: - Ziele hinsichtlich der Energieeinsparung wurden nicht erreicht; — printed p.102–103', verification_note='md-verified 2026-09-05 (§10.2, printed p.102–103; the two enum values are exactly the two printed example classes) [VC]', verified_at=now() where id='24e8ec21-5e20-4aaf-bcd1-58f4d229ea42' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-09 · ursachenanalyse — Ursachenanalyse der Nichtkonformitaet
update public.fields set verification_status='verified_against_standard', verification_quote='Nachdem eine Nichtkonformität ermittelt wurde, sollte sie untersucht werden, um deren Ursache(n) zu bestimmen, damit Korrekturmaßnahmen auf den entsprechenden Teil des Umweltmanagementsystems konzentriert werden können. — printed p.102–103', verification_note='md-verified 2026-09-05 (§10.2, printed p.102–103) [VC]', verified_at=now() where id='cef105b9-b7e6-4bf3-9f13-6a0a2066d7f6' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-09 · korrekturmassnahme — Korrekturmassnahme und Ergebnis
update public.fields set verification_status='verified_against_standard', verification_quote='Bei der Entwicklung eines Plans zur Behebung einer Nichtkonformität sollte die Organisation berücksichtigen, welche Maßnahmen eingeleitet werden sollten, um das Problem zu lösen, welche Änderungen erfolgen sollten, um die Situation zu korrigieren und den normalen Betrieb wiederherzustellen, und was getan werden sollte, um die Ursache(n) zu beseitigen und ein Wiederauftreten oder Auftreten des Problems an anderer Stelle zu vermeiden. | Die Organisation sollte dokumentierte Informationen als Nachweis über die Art der Nichtkonformitäten und anschließend durchgeführten Maßnahmen und die Ergebnisse von durchgeführten Korrekturmaßnahmen aufbewahren. — printed p.102–103', verification_note='md-verified 2026-09-05 (§10.2, printed p.102–103) [VC]', verified_at=now() where id='4435f8a3-68df-46f7-b96c-50f7a6f54c4a' and verification_status not in ('verified_against_standard','corrected');

-- ISO-14004-09 · fortlaufende_verbesserung_massnahme — Umgesetzte Massnahme zur fortlaufenden Verbesserung
update public.fields set verification_status='verified_against_standard', verification_quote='Wenn die Möglichkeiten zur Verbesserung ermittelt sind, sollten diese bewertet werden, um festzulegen, welche Maßnahmen eingeleitet werden sollten. Diese Verbesserungsmaßnahmen sollten geplant und entsprechende Veränderungen im Umweltmanagementsystem vorgenommen werden. — printed p.105', verification_note='md-verified 2026-09-05 (§10.3.2, printed p.105) [VC]', verified_at=now() where id='6035a6f4-7b73-4015-8de1-9a98a1b1a0db' and verification_status not in ('verified_against_standard','corrected');

-- app/project metadata (exempt class, ruling 2026-08-01): organisation_name
update public.fields set verification_status='inferred_from_worksheet', verification_note='md-pass 2026-09-05: app/project metadata — the guideline does not define this field; exempt per the 2026-08-01 metadata ruling', verified_at=now() where id in ('c4fb6971-8dc4-472f-88ef-fdcdd5de49f6') and verification_status not in ('verified_against_standard','corrected');
