-- ============================================================================================================
-- SR-1 field-verification pack - ISO-59010   ***  SOURCE IS OCR OF A SCAN - READ THE GRADE NOTE  ***
-- ***  THE SOURCE IS A BALLOT DRAFT (ISO/FDIS), NOT A PUBLISHED STANDARD - READ THE IDENTITY NOTE  ***
--
-- DOCUMENT IDENTITY (established 2026-09-09 from the RENDERED cover, PDF p.1, and the title page, PDF p.9):
--   The cover prints:  FINAL DRAFT
--                      International
--                      Standard
--                                                        ISO/FDIS 59010
--                      Circular economy - Guidance on    ISO/TC 323
--                      the transition of business        Secretariat: AFNOR
--                      models and value networks         Voting begins on: 2024-02-20
--                      Economie circulaire - Recomman-   Voting terminates on: 2024-04-16
--                      dations relatives a la transition
--                      des modeles d'affaires et des
--                      reseaux de valeur
--                      Reference number ISO/FDIS 59010:2024(en)          (c) ISO 2024
--   The cover further prints, verbatim: "RECIPIENTS OF THIS DRAFT ARE INVITED TO SUBMIT, WITH THEIR COMMENTS,
--     NOTIFICATION OF ANY RELEVANT PATENT RIGHTS OF WHICH THEY ARE AWARE AND TO PROVIDE SUPPORTING
--     DOCUMENTATION. IN ADDITION TO THEIR EVALUATION AS BEING ACCEPTABLE FOR INDUSTRIAL, TECHNOLOGICAL,
--     COMMERCIAL AND USER PURPOSES, DRAFT INTERNATIONAL STANDARDS MAY ON OCCASION HAVE TO BE CONSIDERED IN
--     THE LIGHT OF THEIR POTENTIAL TO BECOME STANDARDS TO WHICH REFERENCE MAY BE MADE IN NATIONAL
--     REGULATIONS."
--   Every body page carries the running head "ISO/FDIS 59010:2024(en)"; the title page (PDF p.9) repeats
--     "FINAL DRAFT International Standard   ISO/FDIS 59010:2024(en)".
--   Kind:          an ISO FINAL DRAFT INTERNATIONAL STANDARD (FDIS) - a BALLOT DRAFT, not a published IS,
--                  not a TR/TS, not a national adoption.
--   Issuing body:  ISO, Technical Committee ISO/TC 323 Circular economy, Secretariat AFNOR.
--   Language:      English ("(en)"); the French title appears on the cover only.
--   Edition/date:  2024; ballot 2024-02-20 to 2024-04-16. Descriptor page (PDF p.45): ICS 03.100.01;
--                  13.020.20, "Price based on 36 pages".
--   Normative reference: ISO 59004, Circular economy - Vocabulary, principles and guidance for
--                  implementation - itself marked "Under preparation" in this draft (footnote 4, PDF p.9).
--
--   *** CITABILITY WARNING - BINDING ON EVERY ROW BELOW ***
--   This is an FDIS. It MAY NOT be cited as the published ISO 59010:2024, and its clause numbering, its
--   normative references and its wording can differ from the published edition. Every verification_note in
--   this pack therefore NAMES the draft explicitly ("ISO/FDIS 59010:2024(en), FINAL DRAFT International
--   Standard") rather than saying only "verified"; do not restamp them to a generic wording.
--
--   PROD VERSION MATCH: prod standards.version = "2024 (Final Draft International Standard,
--     ISO/FDIS 59010:2024)". Prod ALREADY records the draft status, and records it correctly. What prod does
--     NOT record is the code: standards.code is "ISO-59010", which reads as the published standard. See
--     iso-59010-STAGED-rulings.sql block R-0 (owner action: re-source against the published ISO 59010:2024,
--     or make the draft visible in the picker label).
--
-- GRADE: **[VA-OCR]** on every row. This PDF is a SCAN WITH NO TEXT LAYER; the transcript was produced by
--   tesseract (eng, 300 dpi, one pass per page, 45 pages, ~16 509 words, 0 undecodable) at
--   ...\scratchpad\pdftext\ISO-59010-OCR.txt. A quote taken from that transcript evidences WHAT THE OCR READ,
--   not what the page prints. Accordingly EVERY quote in this pack was RE-READ ON THE RENDERED PAGE IMAGE
--   before it was written, and each verification_note names the printed page AND the PDF page it was
--   confirmed on.
--   Rendered pages read for confirmation: PDF 1, 2, 9, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
--     25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36.
--   NOT image-read (and no quoted row rests on any of them): PDF 3-8 (Contents, Foreword, Introduction),
--     PDF 10, 11 (§3.2-§3.13 definitions), PDF 31 (§6.2.4-§6.2.9), PDF 37-45 (Annex A.2-A.6, Bibliography,
--     descriptor page).
--   OCR damage actually observed on pages this pack quotes (examples, all corrected from the image):
--     Table 2 / printed p.19 - OCR "radically different solutions." vs printed "radically different
--       solution."; OCR "stilin working condition" vs printed "still in working condition"; OCR "Adapta
--       product orits parts ... maior modifications" vs printed "Adapt a product or its parts ... major
--       modifications"; OCR "Recyele" vs printed "Recycle".
--     §4.5 / printed p.8 - OCR "eyele" vs printed "cycle"; §7.3 / printed p.26 - OCR "cdlesr roles" vs
--       printed "clear roles"; §5.2 / printed p.20 - OCR "availabilipy" vs printed "availability".
--     The printed page ALWAYS wins; no quote below was adjusted to match the OCR.
--
-- PAGE-NUMBER CONVENTION: the printed folio is the arabic body number. PRINTED p.N = PDF p.(N+8)
--   (confirmed on the rendered pages: PDF 9 = printed 1, PDF 27 = printed 19, PDF 33 = printed 25,
--   PDF 34 = printed 26). Front matter (cover, copyright, Contents, Foreword, Introduction) is PDF 1-8 and
--   carries no arabic folio; the cover row below is cited as "printed cover (PDF p.1)".
--
-- TYPOGRAPHIC CONVENTION: the printed em dash is written "-", curly quotes/apostrophes are written straight,
--   and SQL single quotes are doubled. Where a quote joins two separate printed passages the join is " | ";
--   "[...]" marks an omitted run inside ONE passage. No word, number or unit was altered anywhere.
--
-- MODALITY CENSUS (mechanical, whole OCR transcript, word-bounded, case-insensitive):
--   shall = 1, should = 96, must = 0, may = 6, can = 211.
--   The single "shall" is ISO Foreword boilerplate ("ISO shall not be held responsible for identifying any
--   or all such patent rights", PDF p.4) - i.e. the NORMATIVE BODY OF THIS DOCUMENT CONTAINS ZERO "shall".
--   That is exactly what the title promises ("Guidance on the transition of business models and value
--   networks") and what Clause 1 says ("This document gives guidance for an organization seeking to
--   transition its value creation models and value networks from linear to circular").
--   WHAT THE ENCODING DID WITH THAT: all 23 compliance_requirements rows are severity='warn'; NOT ONE is a
--   block gate. On that axis the encoding MATCHES the source. What does NOT match is is_required: 36 of the
--   51 fields carry is_required=true, and every one of them rests on a "should", a "can" or on nothing at
--   all. See iso-59010-STAGED-rulings.sql, block R-5.
--
-- COUNTS
--   fields examined ........ 51   (9 worksheets; prod export 2026-09-09, 0 already verified)
--   verified with a quote .. 50
--   exempt (app metadata) ... 1   (ISO-59010-01.organization_name)
--   residue ................. 0
--   equations ............... 0   (prod holds none, and the document prints no formula - see R-9)
--   gates ................... 23  (not touched by this pack; findings staged)
--
-- ROLLBACK: rollback-iso-59010-md-verification-pack.sql
-- NO transaction-control statements in this file by design; apply-pack.mjs supplies the transaction.
-- ============================================================================================================


-- ============================ WORKSHEET ISO-59010-01 - Registrierung & Anwendungsbereich ====================

-- standard_edition
update public.fields set verification_status='verified_against_standard', verification_quote='FINAL DRAFT International Standard | ISO/FDIS 59010 | Circular economy - Guidance on the transition of business models and value networks | ISO/TC 323 | Secretariat: AFNOR | Voting begins on: 2024-02-20 | Voting terminates on: 2024-04-16 | Reference number ISO/FDIS 59010:2024(en) - (c) ISO 2024 — printed cover (PDF p.1)', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - cover block, printed cover = PDF p.1, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='b76337ef-8cf6-442f-ab1e-dde451e3e3ef' and verification_status not in ('verified_against_standard','corrected');

-- current_value_creation_model
update public.fields set verification_status='verified_against_standard', verification_quote='3.1 value creation model / business model / organization''s chosen system of interconnected and interdependent decisions and activities that determines how it creates, delivers and captures value (3.16) | Note 2 to entry: The value creation model can have a focus on the short, medium or long term, or some combination thereof. — printed p.1', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §3.1, printed p.1 = PDF p.9, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='10fae041-ef5e-4f62-857c-90c7b5f6953d' and verification_status not in ('verified_against_standard','corrected');

-- position_in_value_chain
update public.fields set verification_status='verified_against_standard', verification_quote='3.17 value chain / set of organizations that provide a solution (3.14) that results in value (3.16) for them | The subject organization can be located anywhere in Figure A.1, depending on the organization''s role in the value chain. For example, if the organization is a manufacturer, it is typically positioned upstream in the value chain. If the subject organization provides services, it is typically positioned downstream in the value chain. — printed p.4 (§3.17) and printed p.28 (§A.1)', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §3.17 printed p.4 = PDF p.12 and §A.1 printed p.28 = PDF p.36, both confirmed on the rendered pages. CAVEAT: §A.1 is Annex A (informative), so the upstream/downstream positioning is an example, not a requirement [VA-OCR]', verified_at=now() where id='1157f2e4-2109-4990-a4c7-c6296a9bb0d8' and verification_status not in ('verified_against_standard','corrected');


-- ============================ WORKSHEET ISO-59010-02 - Zieldefinition & aktuelles Modell ====================

-- transition_goal
update public.fields set verification_status='verified_against_standard', verification_quote='The organization should initially define its goals, i.e. what it seeks to achieve by transitioning to a circular economy value creation model. This goal definition process can include considerations on reductions in resource inflows and outflows, energy consumption and water consumption, as well as other approaches to improve the efficient use of resources. — printed p.5', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.1, printed p.5 = PDF p.13, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='1d797b75-4fc8-4a1b-8a06-68e8b7c4ddf3' and verification_status not in ('verified_against_standard','corrected');

-- goal_measurable
update public.fields set verification_status='verified_against_standard', verification_quote='To help set measurable goals, an organization can conduct an assessment by reviewing and mapping all its activities and interactions within and between its value chains and broader value network. — printed p.5', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.1, printed p.5 = PDF p.13, confirmed on the rendered page. CAVEAT: the printed modality is "can", not "shall"/"should"; the field is nevertheless is_required=true and gate CR-002 tests it == true - see STAGED R-5 [VA-OCR]', verified_at=now() where id='c23ee82a-861e-427b-92a9-2cc8efcfb6b9' and verification_status not in ('verified_against_standard','corrected');

-- goal_defined_early
update public.fields set verification_status='verified_against_standard', verification_quote='Defining the goals early in the solution development process enables circularity aspects to be incorporated in the design of the solution. — printed p.5', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.1, printed p.5 = PDF p.13, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='649c532d-7694-4094-820e-11881fafa31c' and verification_status not in ('verified_against_standard','corrected');

-- enablers_identified
update public.fields set verification_status='verified_against_standard', verification_quote='In addition to the above business elements, relevant enablers should be identified and understood for how their availability influences business elements. — printed p.7', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.2 (last paragraph), printed p.7 = PDF p.15, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='006399e7-4029-46fa-a823-2bdf9bb0fc3a' and verification_status not in ('verified_against_standard','corrected');

-- business_element
update public.fields set verification_status='verified_against_standard', verification_quote='Typical business elements and examples are listed below. However, each organization can have unique value creation models and associated elements. | a) Value proposition: | b) Key activities: | c) Key business resources: | d) Customer segment: | e) Customer relationships: | f) Channels: | g) Costs: | h) Revenue streams: | i) Key partners: | j) Other elements: — printed p.5 to p.7', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.2 items a) to j), printed p.5-p.7 = PDF p.13-15, confirmed on the rendered pages. CAVEAT: the printed lead-in calls the list "typical" and says each organization "can have unique ... associated elements", so the 10-value enum closes a list the source leaves open, and the source treats a) to j) as a conjunction to be assessed, not a single pick - see STAGED R-6 [VA-OCR]', verified_at=now() where id='8e62c6da-5ec1-460e-b48e-eabe014e1fa8' and verification_status not in ('verified_against_standard','corrected');


-- ============================ WORKSHEET ISO-59010-03 - Kette/Netzwerk abbilden & Grenze ====================

-- value_chain_mapped
update public.fields set verification_status='verified_against_standard', verification_quote='Taking into account the defined goals, the organization should map its existing relationships with other organizations and interested parties up and down the value chain along with associated resource flows. — printed p.7', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.3, printed p.7 = PDF p.15, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='934e36a6-cba4-45e7-b290-309289dc5945' and verification_status not in ('verified_against_standard','corrected');

-- stakeholder_analysis_type
update public.fields set verification_status='verified_against_standard', verification_quote='Mapping the organization in its value chain or value network represents an important starting point for exploring collaboration opportunities across the value chain and value network. This activity can be applied through qualitative or quantitative stakeholder analysis with the participation of interested parties. — printed p.7', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.3, printed p.7 = PDF p.15, confirmed on the rendered page. The two enum values (qualitative / quantitative) reproduce the printed pair exactly [VA-OCR]', verified_at=now() where id='c5fd5a85-b256-43f4-b2da-5e8f9d431265' and verification_status not in ('verified_against_standard','corrected');

-- sufficient_enablers
update public.fields set verification_status='verified_against_standard', verification_quote='These enablers provide the necessary infrastructure and support to foster circular initiatives. They can include shared infrastructure, circular suppliers, academic partnerships, research and development, etc. Therefore, when conducting this mapping activity, organizations should focus on their relationships and assess whether there are sufficient enablers or if others need to be developed. — printed p.7', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.3, printed p.7 = PDF p.15, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='a67c8c64-2592-4678-91e7-351e6497b9cb' and verification_status not in ('verified_against_standard','corrected');

-- boundary_defined
update public.fields set verification_status='verified_against_standard', verification_quote='Setting the boundary (e.g. a company or group of companies within the value network) will help clarify the scope of actions necessary to achieve an organization''s goals. This boundary applies to all of the following clauses and subclauses. — printed p.7', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.4 (opening), printed p.7 = PDF p.15, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='243dda47-b882-4e47-8261-345e407ad633' and verification_status not in ('verified_against_standard','corrected');

-- boundary_scope
update public.fields set verification_status='verified_against_standard', verification_quote='The organization should define a boundary and scope of actions after gaining a clear initial picture of its operational context. The boundary should include all relevant activities, locations, types of solutions and value networks. It should include the portion of the economic system within which the organization operates, collaborates or exercises influence (e.g. supply chain, supply partners), and within which it can drive the circular flow of resources, sustainable development and assess performance. — printed p.7', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.4, printed p.7 = PDF p.15, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='5cab4447-5814-4731-a715-fe42e81eeba4' and verification_status not in ('verified_against_standard','corrected');

-- boundary_aligned_with_influence
update public.fields set verification_status='verified_against_standard', verification_quote='Theoretically, a value chain and value network can be extensive. However, when setting the boundary, it should align with the boundary of the organization''s ambition. | To set an appropriate boundary, an organization should consider its sphere of influence. Each organization can have different capacities to influence different aspects of circularity within its value network. — printed p.7 and p.8', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.4, printed p.7 = PDF p.15 (first passage) and printed p.8 = PDF p.16 (second passage), both confirmed on the rendered pages. "sphere of influence" is defined at §3.15, printed p.4 = PDF p.12 [VA-OCR]', verified_at=now() where id='e56affce-2a53-4368-8cae-3e3686eda121' and verification_status not in ('verified_against_standard','corrected');


-- ============================ WORKSHEET ISO-59010-04 - Aktuelle Zirkularitaetsleistung ======================

-- circularity_kpi_selected
update public.fields set verification_status='verified_against_standard', verification_quote='Understanding the current circularity performance by selecting circularity key performance indicators (KPIs) and using those indicators to assess the state of the current value creation model and value network within the boundary are essential to ensure that the defined goals are appropriate. — printed p.8', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.5 (opening), printed p.8 = PDF p.16, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='a2408657-84cb-49b1-99e7-6164b9d09cae' and verification_status not in ('verified_against_standard','corrected');

-- circularity_performance_assessed
update public.fields set verification_status='verified_against_standard', verification_quote='To measure and assess the circular performance, ISO 59020 provides a taxonomy of circularity indicators to measure resource flows and their impacts within a system under study (described as the "system in focus"). | Once the current performance is evaluated, the next step is to determine a strategy of improvement as described in Clause 5. The selected KPIs should be continually monitored and evaluated as described in Clause 8. — printed p.8 and p.9', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.5, printed p.8 = PDF p.16 (first passage) and printed p.9 = PDF p.17 (second passage), both confirmed on the rendered pages. NR CAVEAT: the indicator taxonomy itself lives in ISO 59020, which is a separate document [VA-OCR]', verified_at=now() where id='bfc64e0c-c18d-43e1-8484-783bee8d0aa0' and verification_status not in ('verified_against_standard','corrected');

-- indicator_category
update public.fields set verification_status='verified_against_standard', verification_quote='ISO 59020 categorizes these indicators as follows: | Resource inflows: The resource inflow circularity indicators represent the circularity performance of resources that flow through the system boundary into the system in focus. | Resource outflows: The resource outflow circularity indicators represent the circularity performance of resources that flow out of the boundary of the system in focus. | Energy: The energy circularity indicators represent the fraction of energy used by the system in focus that is renewable energy. | Water: This is an important resource and a focus of a circular economy. | Economic: The application of economic-related circularity indicators is of high importance for an organization. — printed p.8', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.5, printed p.8 = PDF p.16, confirmed on the rendered page; the 5 enum values reproduce the 5 printed dashes exactly. CAVEAT: Figure 4 (printed p.20 = PDF p.28) shows a DIFFERENT category set for the same purpose - "Resource (inflows/outflows), Waste and emissions, Energy, Water, Economic and other indicators" - see STAGED R-8 [VA-OCR]', verified_at=now() where id='79ed1c19-22d5-4209-9463-500d8c7657a1' and verification_status not in ('verified_against_standard','corrected');

-- assessment_method
update public.fields set verification_status='verified_against_standard', verification_quote='NOTE 2 The methodology for assessing circular performance can be realized by applying a typical life cycle assessment (LCA), either a full or streamlined LCA, an eco-efficiency assessment, a water footprint assessment or others as referenced in ISO 59020. — printed p.9', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.5 NOTE 2, printed p.9 = PDF p.17, confirmed on the rendered page. A NOTE is informative; the field is correctly is_required=false [VA-OCR]', verified_at=now() where id='c313e635-6cb2-459a-b735-4bdf4937355b' and verification_status not in ('verified_against_standard','corrected');


-- ============================ WORKSHEET ISO-59010-05 - Massnahmenkatalog ====================================

-- preliminary_action_considered
update public.fields set verification_status='verified_against_standard', verification_quote='Organizations should consider refuse and rethink as preliminary actions. | Refusing refers to re-evaluating resource use patterns to ensure that organizations pursue sufficiency and are set up to prevent overusing resources. | Rethinking refers to a reconsideration of design and manufacturing decisions with a different mindset (e.g. making service use more intensive, sharing or by putting multi-functional products on the market). — printed p.9', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.6.1, printed p.9 = PDF p.17, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='23051059-67fb-4f4a-8a4c-cb08c803a2de' and verification_status not in ('verified_against_standard','corrected');

-- added_value_action
update public.fields set verification_status='verified_against_standard', verification_quote='4.6.2 Actions that create added value | 4.6.2.2 Design for circularity | 4.6.2.3 Circular sourcing | 4.6.2.4 Circular procurement | 4.6.2.5 Process optimization | 4.6.2.6 Industrial, regional or urban symbiosis — printed p.9 to p.11', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.6.2 subclause headings, printed p.9-p.11 = PDF p.17-19, confirmed on the rendered pages; the 5 enum values reproduce the 5 printed headings exactly. CAVEAT: §4.6.1 (printed p.9) states "The actions are not exhaustive", so a closed enum narrows an explicitly open list - see STAGED R-7 [VA-OCR]', verified_at=now() where id='9613a0f5-67ee-48b6-8bc4-2204c0b5bef7' and verification_status not in ('verified_against_standard','corrected');

-- value_retention_action
update public.fields set verification_status='verified_against_standard', verification_quote='4.6.3 Actions that contribute to value retention | 4.6.3.2 Reduce, reuse and repurpose | 4.6.3.3 Maintenance and repair | 4.6.3.4 Performance-based approaches | 4.6.3.5 Sharing to intensify use | 4.6.3.6 Refurbishing | 4.6.3.7 Remanufacturing — printed p.12 and p.13', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.6.3 subclause headings, printed p.12-p.13 = PDF p.20-21, confirmed on the rendered pages; the 6 enum values reproduce the 6 printed headings exactly. CAVEAT: §4.6.1 "The actions are not exhaustive" - see STAGED R-7 [VA-OCR]', verified_at=now() where id='591f547a-52db-4962-b09c-20b977c44242' and verification_status not in ('verified_against_standard','corrected');

-- value_recovery_action
update public.fields set verification_status='verified_against_standard', verification_quote='4.6.4 Actions that contribute to value recovery | 4.6.4.2 Reverse logistics | 4.6.4.3 Cascading of resources | 4.6.4.3.2 Cascading in technical cycles | 4.6.4.3.3 Cascading of biobased resources | 4.6.4.4 Recycling | 4.6.4.5 Waste management | 4.6.4.6 Material recovery | 4.6.4.7 Energy recovery — printed p.13 to p.16', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.6.4 subclause headings, printed p.13-p.16 = PDF p.21-24, confirmed on the rendered pages; the 7 enum values reproduce the printed headings (the two cascading values reproduce §4.6.4.3.2 and §4.6.4.3.3). CAVEAT: §4.6.1 "The actions are not exhaustive" - see STAGED R-7 [VA-OCR]', verified_at=now() where id='45d1cb97-ee2a-4f26-9347-97e772a863c6' and verification_status not in ('verified_against_standard','corrected');

-- ecosystem_regeneration_action
update public.fields set verification_status='verified_against_standard', verification_quote='To align with the principle of ecosystem resilience, regeneration of degraded ecosystems can encompass removal of harmful substances and remediation of soil and water bodies, mitigation and adaptation to climate change impacts, and protection of biodiversity. These actions should ultimately lead to the conservation and continuous renewal of natural resources, improvements in water, soil and air quality, and prevention of land degradation. — printed p.16', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.6.5, printed p.16 = PDF p.24, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='d4a83518-0065-4050-9ff9-be135d32b831' and verification_status not in ('verified_against_standard','corrected');

-- transition_support_action
update public.fields set verification_status='verified_against_standard', verification_quote='4.6.6 Actions to support a circular economy transition | 4.6.6.2 Education and research | 4.6.6.3 Innovation | 4.6.6.4 Collaboration and networks | 4.6.6.5 Helping users change their behaviour | 4.6.6.6 Policy and legal system | 4.6.6.7 Financial services | 4.6.6.8 Digitalization — printed p.16 to p.18', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.6.6 subclause headings, printed p.16-p.18 = PDF p.24-26, confirmed on the rendered pages; the 7 enum values reproduce the 7 printed headings exactly. §4.6.6.1 (printed p.16) adds: "Depending on the type of organizations, these actions can be considered as enablers." [VA-OCR]', verified_at=now() where id='22ff0fea-6e41-4f7d-9117-115143e29ad1' and verification_status not in ('verified_against_standard','corrected');

-- resource_management_action
update public.fields set verification_status='verified_against_standard', verification_quote='Table 2 - Guidance for resource management actions | Action / Description | Refuse: Make solutions redundant by abandoning its function or by offering the same function with a radically different solution. | Rethink | Source | Reduce | Repair | Re-use | Refurbish | Remanufacture | Repurpose | Cascade | Recycle | Recover energy | Re-mine: Mining or extraction from landfills and waste plants can be possible in some cases if mining or extraction activities are sustainably managed. — printed p.19', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - Table 2 (§4.6.7), printed p.19 = PDF p.27, table read off the rendered page; the 13 enum values reproduce the 13 printed Action rows in printed order exactly. OCR of this table was damaged ("radically different solutions", "stilin", "Adapta ... maior", "Recyele"); the printed page was used [VA-OCR]', verified_at=now() where id='895cb205-e9cd-498f-a264-7dfedda53705' and verification_status not in ('verified_against_standard','corrected');

-- life_cycle_perspective_applied
update public.fields set verification_status='verified_against_standard', verification_quote='This resource management guidance is intended to help organizations prioritize actions to increase circularity performance. A life cycle perspective should guide the organization in the identification of the best action for their value creation model and to avoid unwanted trade-offs. | In general, products should be repaired before they are remanufactured, and remanufactured before they are recycled. However, in cases where applying this guidance does not lead to the best outcome, organizations should consider applying a life cycle perspective to determine the best action. — printed p.18 and p.19', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §4.6.7, printed p.18 = PDF p.26 (first passage) and printed p.19 = PDF p.27 (second passage), both confirmed on the rendered pages [VA-OCR]', verified_at=now() where id='1abc8c85-69b4-482b-9248-d05baf6b73d3' and verification_status not in ('verified_against_standard','corrected');


-- ============================ WORKSHEET ISO-59010-06 - Strategie bestimmen ==================================

-- gaps_opportunities_identified
update public.fields set verification_status='verified_against_standard', verification_quote='Having assessed its current circularity performance or the value network within the defined boundary, as described in Clause 4, the organization should next identify the gaps and opportunities to transition its value creation model towards circularity. For this purpose, the elements of the value creation model (shown in the middle-left box of Figure 4) should be evaluated based on the circular economy principles defined in ISO 59004 (in the top box) to determine a circular economy strategy. — printed p.19', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §5.1, printed p.19 = PDF p.27, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='647b0e21-aa3c-44ab-b1b5-944b2c0403a4' and verification_status not in ('verified_against_standard','corrected');

-- circular_economy_principle
update public.fields set verification_status='verified_against_standard', verification_quote='The six circular economy principles (system thinking, value creation, value sharing, resource stewardship, resource traceability and ecosystem resilience) and their interconnection provide the basis for this strategy. | Figure 4 - Framework to determine a circular economy strategy, top box "Determining a strategy based on circular economy principles": Systems thinking / Value creation / Value sharing / Resource stewardship / Resource traceability / Ecosystem resilience — printed p.20', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §5.2 and Figure 4, printed p.20 = PDF p.28, both confirmed on the rendered page; the 6 enum values reproduce the 6 printed principles exactly. Two CAVEATS: (a) the body prints "system thinking" where Figure 4 prints "Systems thinking" - the encoding follows the figure; (b) the printed statement is a CONJUNCTION ("The six ... and their interconnection provide the basis"), while the field is a single-select - see STAGED R-6 [VA-OCR]', verified_at=now() where id='d50cae27-bbe3-4a97-a697-ddb0cee6644d' and verification_status not in ('verified_against_standard','corrected');

-- circular_economy_strategy
update public.fields set verification_status='verified_against_standard', verification_quote='A strategy for the transition of an organization''s value creation model and value network to achieve the goals, i.e. a circular economy strategy, should be determined by considering the organization''s purpose, vision, mission, identified gaps and opportunities, its need to reposition within the value chain or the value network, its need to expand its sphere of influence and its desire to achieve a transition towards a more circular value creation model. — printed p.20', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §5.2, printed p.20 = PDF p.28, confirmed on the rendered page. §5.2 also prints: "The resulting circular economy strategy is on a case-by-case basis." (printed p.21) [VA-OCR]', verified_at=now() where id='0e84e7dc-be78-4fba-97c4-100766eaadc6' and verification_status not in ('verified_against_standard','corrected');

-- materiality_assessment_done
update public.fields set verification_status='verified_against_standard', verification_quote='Materiality is also a key consideration when developing a circular economy strategy. For example, many organizations conduct materiality assessments to assist in making decisions, especially when considering how to make their operations more sustainable. A common analysis method is to create a matrix with the vertical axis representing interested parties'' expectations for the organization and the horizontal axis representing the organization''s business priorities. — printed p.21', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §5.2, printed p.21 = PDF p.29, confirmed on the rendered page. "materiality" and "materiality assessment" are defined at §3.8 and §3.9. Correctly is_required=false: the printed modality is "many organizations conduct" [VA-OCR]', verified_at=now() where id='c9f3e72b-fba4-44fd-9cae-7ab726bf6af8' and verification_status not in ('verified_against_standard','corrected');

-- economic_rationalization_done
update public.fields set verification_status='verified_against_standard', verification_quote='Irrespective of the interested parties'' expectations or the organization''s desire to shift to a circular value creation model, the actual transition cannot successfully be conducted without economic rationalization. All value creation models presume an ability to realize a profit while taking into account the associated risks. — printed p.21', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §5.3, printed p.21 = PDF p.29, confirmed on the rendered page. This is the strongest statement in the document; it is still not a "shall" [VA-OCR]', verified_at=now() where id='6cff7fff-6586-42e8-b6ae-5fc1b47d9ef9' and verification_status not in ('verified_against_standard','corrected');


-- ============================ WORKSHEET ISO-59010-07 - Wertschoepfungsmodell umstellen ======================

-- transition_plan
update public.fields set verification_status='verified_against_standard', verification_quote='After a circular economy strategy is set, the next step is to develop a transition plan to shift from the current to the desired future. | An organization''s transition plan should include objectives, timelines, actions and anticipated interim results. — printed p.22', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §6.1, printed p.22 = PDF p.30, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='5982a448-d791-452b-8458-3517a20e35d1' and verification_status not in ('verified_against_standard','corrected');

-- plan_objectives_in_kpis
update public.fields set verification_status='verified_against_standard', verification_quote='The objectives and interim results should be expressed in KPIs used to assess the status of circularity as described in 4.6. The plan should be in line with the circular economy strategy as described in 5.2. — printed p.22', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §6.1, printed p.22 = PDF p.30, confirmed on the rendered page. SOURCE INCONSISTENCY (the document''s own, not the encoding''s): §6.1 and §7.2 point to 4.6 for these KPIs while §8.1 points to 4.5; the KPI selection clause is 4.5 - see STAGED R-11 [VA-OCR]', verified_at=now() where id='20698e1e-344b-4aa7-b45d-52606d8ce566' and verification_status not in ('verified_against_standard','corrected');

-- value_model_element_reviewed
update public.fields set verification_status='verified_against_standard', verification_quote='The organization should consider changes to its value creation model that are consistent with the developed plan. Examples of such considerations are given in 6.2.2 to 6.2.11. — printed p.22', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §6.2.1, printed p.22 = PDF p.30, confirmed on the rendered page. CAVEAT: the printed text calls 6.2.2-6.2.11 "Examples of such considerations" [VA-OCR]', verified_at=now() where id='3abade2e-151b-4498-bda3-cc326195479b' and verification_status not in ('verified_against_standard','corrected');

-- value_proposition_reviewed
update public.fields set verification_status='verified_against_standard', verification_quote='A value proposition for circularity includes how the target group''s needs can be fulfilled while keeping resources at their highest value for as long as possible. This can be done by considering a product''s lifetime over several use cycles in which the maximum value is created by cascading materials through circular actions such as reuse, repair, remanufacturing and recycling. — printed p.22', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §6.2.2, printed p.22 = PDF p.30, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='1fbd291b-f5b3-48fb-89bf-566a93122e88' and verification_status not in ('verified_against_standard','corrected');

-- recovered_resources_prioritized
update public.fields set verification_status='verified_against_standard', verification_quote='As a key business resource in a circular value creation model, recovered resources obtained via, for example, reusing or recycling products, parts or materials take precedence over virgin resources extracted from the earth. — printed p.22', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §6.2.4, printed p.22 = PDF p.30, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='18f18c4b-b38c-45c8-a5ab-be63eb7954b3' and verification_status not in ('verified_against_standard','corrected');

-- other_consideration
update public.fields set verification_status='verified_against_standard', verification_quote='In addition to the considerations listed in 6.2.2 to 6.2.11, an organization can identify potential risks and opportunities by exploring: | current/future compliance obligations; | current solutions that are related to end-to-end processes (life cycle perspective); | market and societal perspectives of linear value networks; | potential unintended consequences from implementing circular economy solutions; | use of renewable energy; | education and awareness of circular economy objectives. — printed p.24', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §6.2.12, printed p.24 = PDF p.32, confirmed on the rendered page; the 6 enum values reproduce the 6 printed dashes exactly [VA-OCR]', verified_at=now() where id='d2181237-daf4-4b9f-89b8-0d4e69a2dd31' and verification_status not in ('verified_against_standard','corrected');


-- ============================ WORKSHEET ISO-59010-08 - Wertschoepfungsnetzwerk umstellen ====================

-- boundary_expanded
update public.fields set verification_status='verified_against_standard', verification_quote='In many cases, during the transition to circularity, it is necessary to expand the project''s boundary to include a broader perspective beyond the organization''s immediate value chain. Expanding the boundary of the existing value chain beyond solely commercial relationships can create opportunities to develop circular flows of resources by regenerating ecosystems, and retaining or adding to their value. — printed p.24', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §7.1, printed p.24 = PDF p.32, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='73111e4c-2c5f-4c5a-b6c5-b7eee158db1c' and verification_status not in ('verified_against_standard','corrected');

-- shared_objectives_defined
update public.fields set verification_status='verified_against_standard', verification_quote='Value network members should determine their shared objectives by considering potential symbiotic opportunities and members'' individual circular objectives. — printed p.25', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §7.2 (opening), printed p.25 = PDF p.33, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='b407c511-02fa-4a6d-930f-9b47c3fabc61' and verification_status not in ('verified_against_standard','corrected');

-- shared_strategy_plan
update public.fields set verification_status='verified_against_standard', verification_quote='The members can decide to create a shared circular economy strategy based on those shared objectives in addition to each member''s circular economy strategy. | Value network members should break down the shared objectives into actions and create a shared plan with timelines with expected interim results and associated actions to shift their value networks towards circularity. — printed p.25', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §7.2, printed p.25 = PDF p.33, confirmed on the rendered page. CAVEAT: the SHARED STRATEGY half is printed as "can decide", only the SHARED PLAN half is a "should"; the field is is_required=true for both - see STAGED R-5 [VA-OCR]', verified_at=now() where id='808e1c49-47af-4262-aebb-8e3ddd910810' and verification_status not in ('verified_against_standard','corrected');

-- consistency_verification_done
update public.fields set verification_status='verified_against_standard', verification_quote='Participating members of the value network should engage in consistency verification to ensure alignment in objectives, values, governance and decision-making throughout the network. Open communication between the members can be instrumental in resolving any potential misalignments. — printed p.26', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §7.2, printed p.26 = PDF p.34, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='13e3aca8-f702-43ce-997a-0baee44ff383' and verification_status not in ('verified_against_standard','corrected');

-- governance_structure
update public.fields set verification_status='verified_against_standard', verification_quote='A governance structure should be implemented in a value network. Depending on the network objectives and strategy, the governance structures can take diverse forms. | EXAMPLE A forum, an alliance, pacts, a consortium, members networks, public-private partnerships. — printed p.26', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §7.3, printed p.26 = PDF p.34, confirmed on the rendered page. "governance" is defined at §3.5 (printed p.2) as "principles, policies and framework by which an organization is directed and controlled" [VA-OCR]', verified_at=now() where id='8a776108-7358-492c-a2f5-ca979b3886a5' and verification_status not in ('verified_against_standard','corrected');

-- governance_element
update public.fields set verification_status='verified_against_standard', verification_quote='The following elements should be considered for governance: | clear roles and responsibilities of members; | principle of respect for the liberty and free will of each member; | establishing an advisory group, steering committee or governing board; | shared by-laws that provide the principles and rules by which shared objectives and strategies are to be achieved; | clear and active communication channels and protocols between members and external interested parties; | risk management (member impartiality and inclusivity); | fostering of trust-building and engagement; | transparent decision-making processes; | traceability mechanisms; | reporting processes to interested parties, community and key partners, especially non-financial disclosure. — printed p.26', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §7.3, printed p.26 = PDF p.34, confirmed on the rendered page; the 10 enum values reproduce the 10 printed dashes exactly. CAVEAT: the printed lead-in is a conjunction ("The following elements should be considered"), while the field is a single-select - see STAGED R-6 [VA-OCR]', verified_at=now() where id='fbbf9b4e-f676-44df-aa65-7f4ccdac416a' and verification_status not in ('verified_against_standard','corrected');

-- shared_infrastructure
update public.fields set verification_status='verified_against_standard', verification_quote='Collaboration between members in a circular value network often requires shared infrastructure, sometimes provided by value network members. Example components of such an infrastructure include: | an information exchange platform for participating parties and their external interested parties (e.g. block-chain, digital material, product passports); | shared facilities and assets that achieve shared objectives such as (reverse) logistics, warehouses, treatment of PCM, land and energy recovery; | leveraged knowledge and skills to deploy relevant technologies and social and capital innovations. — printed p.26', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §7.4, printed p.26 = PDF p.34, confirmed on the rendered page; the 3 enum values reproduce the 3 printed dashes exactly. CAVEAT: the printed lead-in says "Example components ... include", so the enum closes an explicitly exemplary list; gate CR-019 nevertheless tests it IS NOT NULL - see STAGED R-7 [VA-OCR]', verified_at=now() where id='4b9a482c-14c3-476c-ac4f-0ad6eb227862' and verification_status not in ('verified_against_standard','corrected');


-- ============================ WORKSHEET ISO-59010-09 - Pruefung & Ueberwachung ==============================

-- performance_measured
update public.fields set verification_status='verified_against_standard', verification_quote='After selecting actions to improve circularity, an organization should measure and assess the results of those actions as its circularity performance, which aligns with the KPIs described in 4.5. — printed p.26', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §8.1 (opening), printed p.26 = PDF p.34, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='88291662-09d2-46ad-92e3-dc2105cead90' and verification_status not in ('verified_against_standard','corrected');

-- measurement_meaningful
update public.fields set verification_status='verified_against_standard', verification_quote='Measurement and assessment of circularity performance should be meaningful, i.e. the data needs to be relevant and precise enough for the intended application. Data acquisition should be organized across value chains or value networks, with regard to the amount of data and its quality. | The measurement should include all resource inflows and outflows (including emissions and losses) by applying the core circularity indicators of ISO 59020. — printed p.27', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §8.1, printed p.27 = PDF p.35, confirmed on the rendered page. NR CAVEAT: the core circularity indicators live in ISO 59020, a separate document [VA-OCR]', verified_at=now() where id='e0ec4881-5da4-4601-b192-68c59fd656e1' and verification_status not in ('verified_against_standard','corrected');

-- complementary_method
update public.fields set verification_status='verified_against_standard', verification_quote='The assessment of impacts on social, environmental and economic aspects is part of the assessment step as explained in ISO 59020. It can be made by applying complementary methods (e.g. ISO 14044 for LCA, ISO 26000 for social responsibility). — printed p.27', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §8.1, printed p.27 = PDF p.35, confirmed on the rendered page. Correctly is_required=false: the printed modality is "can be made" and the two standards are "e.g." [VA-OCR]', verified_at=now() where id='58994603-9d3a-4521-818c-d8db8973a983' and verification_status not in ('verified_against_standard','corrected');

-- periodic_assessment
update public.fields set verification_status='verified_against_standard', verification_quote='The outcome of the measurement and assessment process is specific to a defined time period for which the measurement and assessment are conducted. To monitor progress over time, the organization can choose to carry out periodic assessments. — printed p.27', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §8.1, printed p.27 = PDF p.35, confirmed on the rendered page. The document names NO interval, frequency or period length anywhere - correctly is_required=false and correctly unquantified in prod [VA-OCR]', verified_at=now() where id='6767b276-55be-4cc2-87b7-220333ad23c4' and verification_status not in ('verified_against_standard','corrected');

-- value_model_improvement_reviewed
update public.fields set verification_status='verified_against_standard', verification_quote='At an appropriate interval, such as when interim results are achieved, the plan as described in 6.1 should be reviewed from, but not limited to, the following perspectives: | a) Achieved performance: the interim results described in 6.1 should be checked, and improvement opportunities identified if results are not on target to achieve goals. | b) Value creation model elements: The value creation model elements investigated in 4.2 and 6.2 should be reviewed for further continuous improvement opportunities. | c) Access to finance and funding — printed p.27', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §8.2, printed p.27 = PDF p.35, confirmed on the rendered page. The printed interval is "At an appropriate interval, such as when interim results are achieved" - no number is printed and none is encoded [VA-OCR]', verified_at=now() where id='4232be61-4324-4ad6-aef2-a822c6025473' and verification_status not in ('verified_against_standard','corrected');

-- value_network_improvement_reviewed
update public.fields set verification_status='verified_against_standard', verification_quote='At an appropriate interval, such as when reviewing interim results, the shared strategic plan described in 7.2 should be reviewed by value network members in a transparent, inclusive and impartial manner from, but not limited to, the following perspectives: | a) The performance achieved | b) The boundary | c) The diversity of members | d) Achieving good relationships between members | e) The governance performance and structure — printed p.27', verification_note='md-verified 2026-09-09 - source: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard (a ballot draft, NOT the published ISO 59010) - §8.3, printed p.27 = PDF p.35, confirmed on the rendered page [VA-OCR]', verified_at=now() where id='b02ae10a-c7d3-455a-95bb-5152a3d660aa' and verification_status not in ('verified_against_standard','corrected');


-- ============================ EXEMPT - app/project metadata (2026-08-01 ruling) =============================
-- ISO-59010-01.organization_name ("Name der Organisation"). Clause 1 (printed p.1) says only "This document
-- is applicable to any organization regardless of size, sector or region." - it scopes WHO may use the
-- document, it does not define a name field. The identity of the client organization is project data the
-- guideline never states. No quote is fabricated for it.
update public.fields set verification_status='inferred_from_worksheet', verification_note='md-pass 2026-09-09: app/project metadata - the guideline does not define this field; exempt per the 2026-08-01 metadata ruling. Source checked and found silent: ISO/FDIS 59010:2024(en), FINAL DRAFT International Standard, Clause 1, printed p.1 = PDF p.9 [VA-OCR]', verified_at=now() where id='cde447ec-f534-4a60-922b-87897731de00' and verification_status not in ('verified_against_standard','corrected');
