-- ============================================================================
-- SR-1 field-verification pack — ISO-14064-1 (DIN EN ISO 14064-1:2019-06, "DEUTSCHE NORM Juni 2019";
--   "Treibhausgase - Teil 1: Spezifikation mit Anleitung zur quantitativen Bestimmung und Berichterstattung
--   von Treibhausgasemissionen und Entzug von Treibhausgasen auf Organisationsebene (ISO 14064-1:2018);
--   Deutsche und Englische Fassung EN ISO 14064-1:2018"; prod standards.version = "EN ISO 14064-1:2018
--   (DIN EN ISO 14064-1:2019)"; standard id 3487e7cf-6e44-46c6-8eab-fc257d66f143).
--   This is a REQUIREMENTS standard ("muss"/"shall"), not a guidance document — block gates are defensible
--   here, but ONLY where the sentence they cite actually says "muss"/"muessen". Every gate was checked; the
--   ones that are not so anchored are listed in iso-14064-1-STAGED-rulings.sql.
-- Generated: 2026-09-05 — md-verified pass (owner ruling 2026-09-05: the markdown transcript is the
--   verification source; the PDF only where no markdown exists). Grade: VC (SR-3), labelled on every row.
--   Records EVIDENCE only (verification_status / verification_quote / verification_note / verified_at);
--   changes NO structure, no enforcement, no required-ness — all of that sits in the STAGED file, unapplied.
--
-- Source md: C:\Users\Ekowai\Desktop\Guidelines\DWA DIN Scribd\ISO-14064-1\ISO-14064-1-Deutsch.md
--   (3280 lines, mathpix LaTeX transcript, read completely). The document is a CEN PARALLEL D+E edition:
--   German and English run as ALTERNATING BLOCKS. LANGUAGE CONVENTION: every quote below is the GERMAN
--   column, verbatim, because the German text is the normative German-language text of this DIN edition and
--   it is the one that carries the "muss" vs "sollte" vs "darf" distinction the gates depend on. Runs joined
--   inside one clause are marked " | "; an omitted run inside one clause would be marked "[...]" (none used).
--   Quotes were extracted BY LINE from the md, never retyped, so mathpix LaTeX ($\mathrm{CO}_{2}$) and the
--   transcript's own OCR artefacts ("THGEmissionen" for "THG-Emissionen", "\mathrm{AIq}" for "CO2 Aeq",
--   "KohlendioxidAequivalent") are reproduced exactly as the md reads them. Those artefacts are named in the
--   affected rows' verification_note.
--
--   Page convention: "printed p.N" is stated ONCE at the END of each quote (pp.A, B = the two clauses joined
--   by " | " sit on different pages; pp.A-B = one quote spans a page break). The md carries NO page markers
--   at all (no standalone number lines, no running headers), so pages were DERIVED, not guessed, in two steps:
--     (1) the standard's own Inhalt index (md lines 85-190) gives a printed page for every 1st/2nd-level
--         clause: §1 p.14 · §3.1 p.14 · §3.2 p.17 · §3.3 p.20 · §3.4 p.21 · §4 p.23 · §5 p.24 · §5.1 p.24 ·
--         §5.2 p.25 · §6 p.27 · §6.1 p.27 · §6.2 p.27 · §6.3 p.29 · §6.4 p.30 · §7 p.31 · §7.2 p.33 ·
--         §7.3 p.33 · §8 p.33 · §8.2 p.35 · §8.3 p.35 · §9 p.35 · §9.2 p.36 · §9.3 p.36 · §10 p.40 ·
--         Anhang A p.41 · B p.44 · C p.57 · D p.71 · E p.72 · F p.75 · G p.86 · H p.99.
--     (2) for 3rd-level sub-clauses and for every individual list item the index has no entry, so the exact
--         printed page of each quoted sentence was read off the rendered PDF's own page footers
--         (scoop pdftotext, raw reading order, ISO-14064-1-Deutsch.pdf, 110 PDF pages): the footer on PDF
--         page 26 reads "22", i.e. printed page = PDF page - 4, constant over the whole document. All 70
--         quoted German anchors resolve to exactly ONE PDF page each under that mapping, and every one of
--         them agrees with the Inhalt index of step (1). The PDF was used ONLY to number pages, never to
--         verify text — the text is the md — so the grade stays VC, not VA.
--
-- Counts: 49 fields examined · 49 quoted now · 0 app-metadata exempt · 0 residue (every field is carried by
--   at least one "muss"/"sollte"/"darf" sentence or one definition of clause 3) · 4 equations, all 4 already
--   verification_status='verified_against_standard' with an EMPTY verification_quote -> QUOTE BACKFILL only,
--   guarded on "verification_quote is null", verification_status NOT touched.
-- Rollback: rollback-iso-14064-1-md-verification-pack.sql
-- ============================================================================
-- grundsaetze_eingehalten
update public.fields set verification_status='verified_against_standard', verification_quote='Die Anwendung von Grundsätzen ist wesentlich, um sicherzustellen, dass treibhausgasbezogene Angaben den tatsächlichen Verhältnissen entsprechend berücksichtigt werden. Die Grundsätze bilden die Grundlage für die Anforderungen im vorliegenden Dokument und stellen eine Anleitung für die Anwendung dieser Anforderungen dar. | Alle relevanten Treibhausgasemissionen und entzogenen Mengen von Treibhausgasen sind einzubeziehen. — printed p.23', verification_note='md-verified 2026-09-05 (§4.1/§4.3, printed p.23) [VC]', verified_at=now() where id='a1c93e53-e398-45db-bc15-970f7c5bc014' and verification_status not in ('verified_against_standard','corrected');
-- organisation_name
update public.fields set verification_status='verified_against_standard', verification_quote='Der Treibhausgasbericht muss Folgendes umfassen: | a) eine Beschreibung der berichterstattenden Organisation; | Person oder Personengruppe, die eigene Funktionen mit Verantwortlichkeiten, Befugnissen und Beziehungen hat, um ihre Ziele zu erreichen — printed pp.37, 21', verification_note='md-verified 2026-09-05 (§9.3.1 a)/§3.4.2, printed pp.37, 21) [VC]', verified_at=now() where id='66bec742-fd02-4824-ac73-c37824e2bcb6' and verification_status not in ('verified_against_standard','corrected');
-- berichtszeitraum
update public.fields set verification_status='verified_against_standard', verification_quote='Der Zeitraum, für den THG-Emissionen oder der Entzug von Treibhausgasen berechnet wurden, muss angegeben werden. | c) den erfassten Berichtszeitraum; — printed pp.29, 37', verification_note='md-verified 2026-09-05 (§6.3/§9.3.1 c), printed pp.29, 37) [VC]', verified_at=now() where id='8ed5c75e-1a4e-41de-a650-f496dfcb5937' and verification_status not in ('verified_against_standard','corrected');
-- vorgesehene_nutzung
update public.fields set verification_status='verified_against_standard', verification_quote='von der Organisation (3.4.2) festgelegter Hauptzweck oder ein Programm zur Quantifizierung ihrer THG-Emissionen (3.1.5) und des Entzugs von THG (3.1.6) entsprechend den Bedürfnissen des vorgesehenen Anwenders (3.4.4) — printed p.22', verification_note='md-verified 2026-09-05 (§3.4.6, printed p.22) [VC]', verified_at=now() where id='296dd97b-2fe2-43fa-b94b-7879cf9f58e8' and verification_status not in ('verified_against_standard','corrected');
-- vorgesehene_anwender
update public.fields set verification_status='verified_against_standard', verification_quote='Einzelperson oder Organisation (3.4.2), die von der Seite, die die THG-bezogenen Angaben bei der Berichterstattung anführt, als diejenige Seite identifiziert wird, die für die Entscheidungsfindung auf diese Angaben angewiesen ist — printed p.21', verification_note='md-verified 2026-09-05 (§3.4.4, printed p.21) [VC]', verified_at=now() where id='8eae7927-b5f6-4332-885b-d68953348079' and verification_status not in ('verified_against_standard','corrected');
-- thg_programm_anwendbar
update public.fields set verification_status='verified_against_standard', verification_quote='Die Normenreihe ISO 14064 ist gegenüber Klimaschutzprogrammen neutral. Wenn ein Klimaschutzprogramm anwendbar ist, gelten die Anforderungen dieses Klimaschutzprogramms ergänzend zu den Anforderungen der Normenreihe ISO 14064. — printed p.14', verification_note='md-verified 2026-09-05 (§1, printed p.14) [VC]', verified_at=now() where id='788b3338-c12c-422e-91ed-83b542e9c056' and verification_status not in ('verified_against_standard','corrected');
-- einrichtung_liste
update public.fields set verification_status='verified_against_standard', verification_quote='einzelne Einrichtung oder eine Reihe von Einrichtungen oder Herstellungsprozessen (stationär oder mobil), die innerhalb einer einzelnen geografischen Grenze, Organisationseinheit oder eines Herstellungsprozesses definiert werden kann | Die Organisation kann eine oder mehrere Einrichtungen umfassen. THG-Emissionen oder Entzug von THG auf Ebene der Einrichtung können durch eine oder mehrere THG-Quellen oder -Senken produziert werden. — printed pp.21, 24', verification_note='md-verified 2026-09-05 (§3.4.1/§5.1, printed pp.21, 24) [VC]', verified_at=now() where id='26c53278-c96f-47c6-a4a8-c1164c9d82a3' and verification_status not in ('verified_against_standard','corrected');
-- organisationsgrenze_def
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss ihre Organisationsgrenzen definieren. | Gruppierung von Tätigkeiten oder Einrichtungen, in denen eine Organisation (3.4.2) operativ oder finanzielle Kontrolle ausübt oder an denen sie einen Kapitalanteil hält — printed pp.24, 22', verification_note='md-verified 2026-09-05 (§5.1/§3.4.7, printed pp.24, 22) [VC]', verified_at=now() where id='8d97d79b-1142-4318-a864-44e3cbedbc8a' and verification_status not in ('verified_against_standard','corrected');
-- zusammenfuehrungsansatz
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss die Treibhausgasemissionen und den Entzug von Treibhausgasen auf Ebene der Einrichtung nach einem der folgenden Ansätze zusammenführen: | a) Kontrolle: Die Organisation legt über alle Treibhausgasemissionen und/oder entzogenen Mengen von Treibhausgasen von Einrichtungen, über die sie die Finanzkontrolle hat oder deren Betriebsabläufe sie kontrolliert, Rechenschaft ab; | b) Beteiligung: Die Organisation legt über ihren Anteil an Treibhausgasemissionen und/oder den Entzug von Treibhausgasen von den betreffenden Einrichtungen Rechenschaft ab. | Die Organisation muss den verwendeten Ansatz zur Zusammenführung dokumentieren und darüber Bericht erstatten. — printed pp.24-25', verification_note='md-verified 2026-09-05 (§5.1 a)/b), printed pp.24-25) [VC]', verified_at=now() where id='447d8489-dc4d-4a44-ba13-0518e2354600' and verification_status not in ('verified_against_standard','corrected');
-- beteiligungsanteil
update public.fields set verification_status='verified_against_standard', verification_quote='Beteiligung ist der prozentuale Anteil wirtschaftlicher Interessen an einer Einrichtung oder des aus dieser Einrichtung gezogenen Nutzens. | Die Zusammenführung auf Organisationsebene auf der Grundlage von Beteiligungen erfordert die Ermittlung des prozentualen Miteigentumsanteils von jeder Einrichtung und die Berücksichtigung dieses prozentualen Anteils von Treibhausgasemissionen oder entzogenen Mengen der entsprechenden Einrichtungen, einschließlich der Nutzung von Vereinbarungen zu Produktionsanteilen. — printed p.43', verification_note='md-verified 2026-09-05 (§A.3, printed p.43) [VC] — Anhang A is INFORMATIV; the standard fixes no numeric value for this field, only the requirement to establish the ownership percentage', verified_at=now() where id='d05158a2-a346-442d-a3bb-e79560926a63' and verification_status not in ('verified_against_standard','corrected');
-- wesentlichkeitskriterien
update public.fields set verification_status='verified_against_standard', verification_quote='Als Teil dieses Prozesses muss die Organisation, unter Berücksichtigung der vorgesehenen Nutzung der Treibhausgasbilanz, ihre eigenen vorgegebenen Wesentlichkeitskriterien für indirekte Emissionen definieren und erläutern. | Die Organisation muss diese Kriterien nutzen, um ihre indirekten THG-Emissionen zu identifizieren, zu beurteilen und die wesentlichen Emissionen auszuwählen. — printed p.25', verification_note='md-verified 2026-09-05 (§5.2.3, printed p.25) [VC]', verified_at=now() where id='cdd4a4e6-8f11-48a5-a267-32b1f9ebbb0e' and verification_status not in ('verified_against_standard','corrected');
-- berichtsgrenze_def
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss ihre Berichtsgrenzen festlegen und dokumentieren. Dies umfasst die Identifizierung direkter und indirekter THG-Emissionen und entzogener THG-Emissionen in Verbindung mit den Betriebsabläufen der Organisation. — printed p.25', verification_note='md-verified 2026-09-05 (§5.2.1, printed p.25) [VC]', verified_at=now() where id='d6a698f3-19a6-40d5-929e-793967122763' and verification_status not in ('verified_against_standard','corrected');
-- kategorie_auswahl
update public.fields set verification_status='verified_against_standard', verification_quote='Treibhausgasemissionen sind in den folgenden Kategorien auf der Organisationsebene zusammenzufassen: | a) direkte THG-Emissionen und Entzug direkter THG; | b) indirekte THG-Emissionen aus importierter Energie; | c) indirekte THG-Emissionen aus Transport; | d) indirekte THG-Emissionen aus von der Organisation genutzten Produkten; | e) indirekte THG-Emissionen in Verbindung mit der Nutzung von Produkten der Organisation; | f) indirekte THG-Emissionen aus anderen Quellen. — printed p.26', verification_note='md-verified 2026-09-05 (§5.2.4 a)-f), printed p.26) [VC]', verified_at=now() where id='c379e991-c167-400b-a298-759678ad23c2' and verification_status not in ('verified_against_standard','corrected');
-- biogen_klasse
update public.fields set verification_status='verified_against_standard', verification_quote='In jeder Kategorie müssen nicht-biogene Emissionen, biogene anthropogene Emissionen und, sofern quantifiziert und berichtet, biogene nicht-anthropogene Emissionen getrennt werden (siehe Anhang D). — printed p.26', verification_note='md-verified 2026-09-05 (§5.2.4, printed p.26) [VC]', verified_at=now() where id='3c1fab4a-9ae2-4f35-bc3a-63aae0ab7016' and verification_status not in ('verified_against_standard','corrected');
-- ausschluss_begruendung
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss diese wesentlichen Emissionen quantifizieren und dokumentieren. Ausschlüsse wesentlicher indirekter Emissionen müssen begründet werden. — printed p.25', verification_note='md-verified 2026-09-05 (§5.2.3, printed p.25) [VC]', verified_at=now() where id='6901ba56-e130-4c17-817c-fad3217886f3' and verification_status not in ('verified_against_standard','corrected');
-- quelle_senke_id
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss alle relevanten THG-Quellen und -Senken innerhalb ihrer Berichtsgrenzen identifizieren und dokumentieren. Die Organisation muss alle relevanten THG einbinden. | THG-Quellen und -Senken müssen in Übereinstimmung mit den in 5.2.4 festgelegten Kategorien identifiziert werden. — printed p.27', verification_note='md-verified 2026-09-05 (§6.1, printed p.27) [VC]', verified_at=now() where id='444e5818-a1a5-4dfa-8ce2-61d07cbfd96c' and verification_status not in ('verified_against_standard','corrected');
-- emissionsart
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss ihre Daten für jede als direkte oder indirekte Emission oder direkter oder indirekter Entzug klassifizierte Quelle oder Senke identifizieren und dokumentieren. | THG-Emission (3.1.5) aus THG-Quellen (3.1.2) im Besitz oder unter Kontrolle einer Organisation (3.4.2) — printed pp.28, 16', verification_note='md-verified 2026-09-05 (§6.2.2/§3.1.9, printed pp.28, 16) [VC]', verified_at=now() where id='4847222f-3112-4aa8-a4d6-bc1451a9711e' and verification_status not in ('verified_against_standard','corrected');
-- quantifizierungsansatz
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss Quantifizierungsmethodiken auswählen und anwenden, die Unsicherheiten minimieren und genaue, einheitliche und reproduzierbare Ergebnisse erzielen. | Die Organisation muss ihren Quantifizierungsansatz und alle Änderungen desselben erläutern und dokumentieren. — printed p.27', verification_note='md-verified 2026-09-05 (§6.2.1, printed p.27) [VC]', verified_at=now() where id='ff10861d-7cb4-4492-bf1a-59ada289b807' and verification_status not in ('verified_against_standard','corrected');
-- modell_begruendung
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss die Begründung für die Auswahl oder Entwicklung des Modells unter Berücksichtigung der folgenden Modelleigenschaften erläutern und dokumentieren: | a) wie genau das Modell die Emissionen und den Entzug wiedergibt; | b) seine Anwendungsgrenzen; | c) seine Unsicherheiten und seine Genauigkeit; | d) die Reproduzierbarkeit der Ergebnisse; | e) die Angemessenheit des Modells; | f) die Herkunft und das Maß der Anerkennung des Modells; | g) die Eignung für die vorgesehene Nutzung. — printed pp.28-29', verification_note='md-verified 2026-09-05 (§6.2.3 a)-g), printed pp.28-29) [VC]', verified_at=now() where id='45c320c5-0591-4227-8696-0d9639e1a53d' and verification_status not in ('verified_against_standard','corrected');
-- datenart
update public.fields set verification_status='verified_against_standard', verification_quote='ANMERKUNG 1 Die für die Quantifizierung verwendeten Daten umfassen Primärdaten (einschließlich standortspezifischer Daten) und Sekundärdaten. | Daten, die aus anderen Quellen als Primärdaten (3.2.2) erhalten werden — printed pp.28, 17', verification_note='md-verified 2026-09-05 (§6.2.2/§3.2.4, printed pp.28, 17) [VC]', verified_at=now() where id='9cdc7ee2-cb45-4709-8e46-b5cefc093a7b' and verification_status not in ('verified_against_standard','corrected');
-- AD
update public.fields set verification_status='verified_against_standard', verification_quote='quantitatives Maß für die Tätigkeit, die zu einer THG-Emission (3.1.5) oder zum Entzug von THG (3.1.6) führt | BEISPIEL Menge an verbrauchter/verbrauchten Energie, Brennstoffen oder Elektrizität, hergestelltem Material, erbrachten Dienstleistungen, betroffener Grundstücksfläche. — printed p.17', verification_note='md-verified 2026-09-05 (§3.2.1, printed p.17) [VC] — the standard defines the QUANTITY but prints NO unit for it; the encoded unit placeholder "Einheit" is EKOWAI-authored, staged for correction', verified_at=now() where id='c34307a3-c5ee-4e3a-8985-a420705ce9e5' and verification_status not in ('verified_against_standard','corrected');
-- EF_gas
update public.fields set verification_status='verified_against_standard', verification_quote='Faktor, der die THG-Aktivitätsdaten (3.2.1) mit der THG-Emission (3.1.5) verbindet | Anmerkung 1 zum Begriff: Ein THG-Emissionsfaktor könnte eine Oxidationskomponente einschließen. — printed pp.15-16', verification_note='md-verified 2026-09-05 (§3.1.7, printed pp.15-16) [VC] — the standard prints NO unit for the emission factor; the encoded "kg/Einheit" is EKOWAI-authored and is dimensionally inconsistent with the t-valued output of Q-GHG (staged)', verified_at=now() where id='af0f9b59-debc-4336-a80b-9f6ea1dff69c' and verification_status not in ('verified_against_standard','corrected');
-- entzugsfaktor
update public.fields set verification_status='verified_against_standard', verification_quote='Faktor, der die THG-Aktivitätsdaten (3.2.1) mit dem Entzug von THG (3.1.6) verbindet | Anmerkung 1 zum Begriff: Ein THG-Entzugsfaktor könnte eine Oxidationskomponente einschließen. — printed p.16', verification_note='md-verified 2026-09-05 (§3.1.8, printed p.16) [VC] — the standard prints NO unit for the removal factor; the encoded "kg/Einheit" is EKOWAI-authored (staged)', verified_at=now() where id='ae66de98-e805-494d-9e34-6a77ba29dd03' and verification_status not in ('verified_against_standard','corrected');
-- E_gas
update public.fields set verification_status='verified_against_standard', verification_quote='ANMERKUNG Verschiedene Arten von Modellen nutzen mit Emissionsfaktoren multiplizierte Aktivitätsdaten. | Die Organisation muss die Treibhausgasemissionen und den Entzug von Treibhausgasen in Übereinstimmung mit dem ausgewählten Quantifizierungsansatz berechnen (siehe 6.2). — printed p.29', verification_note='md-verified 2026-09-05 (§6.2.3 ANMERKUNG/§6.3, printed p.29) [VC] — the standard prints no displayed equation; "E_gas = AD * EF_gas" is EKOWAI-authored formalisation of the printed ANMERKUNG. The encoded output unit "t" does not follow from AD[Einheit] x EF[kg/Einheit] = kg (staged)', verified_at=now() where id='30114ef9-c958-40bf-91e1-c2b841a46073' and verification_status not in ('verified_against_standard','corrected');
-- E_el
update public.fields set verification_status='verified_against_standard', verification_quote='Emissionen aus importiertem elektrischem Strom, der von der Organisation eingesetzt wird, müssen von der Organisation unter Verwendung des ortsbasierten Ansatzes und Anwendung des Emissionsfaktors, der das betreffende Netz am besten charakterisiert, d.h. einer eigenen Übertragungsleitung, eines lokalen, regionalen oder nationalen netzdurchschnittlichen Emissionsfaktors, quantifiziert werden. — printed p.72', verification_note='md-verified 2026-09-05 (§E.2.1, printed p.72) [VC] — Anhang E is NORMATIV. The encoded output unit "t CO2Aeq" does not follow from EL_imp[kWh] x EF_grid[kg/kWh] = kg (staged)', verified_at=now() where id='763dcf29-9ad8-4ad1-b5ab-c8a6e0b18f04' and verification_status not in ('verified_against_standard','corrected');
-- E_co2e_gas
update public.fields set verification_status='verified_against_standard', verification_quote='Anmerkung 1 zum Begriff: Das KohlendioxidÄquivalent wird berechnet, indem die Masse eines bestimmten THGs mit dessen Treibhauspotential (3.1.12) multipliziert wird. | Einheit zum Vergleich des Strahlungsantriebs eines THGs (3.1.1) mit dem von Kohlendioxid — printed p.17', verification_note='md-verified 2026-09-05 (§3.1.13, printed p.17) [VC]', verified_at=now() where id='444ff7d6-1987-4746-8fa5-829aa99efe7a' and verification_status not in ('verified_against_standard','corrected');
-- EF_grid
update public.fields set verification_status='verified_against_standard', verification_quote='Netzdurchschnittliche Emissionsfaktoren sollten aus dem berichteten Emissionsjahr (sofern verfügbar) oder andernfalls aus dem letzten verfügbaren Jahr stammen. Netzdurchschnittliche Emissionsfaktoren für eingesetzten importierten elektrischen Strom müssen auf dem durchschnittlichen Energieverbrauchsmix des Netzes, aus dem die Elektrizität verbraucht wird, basieren. — printed p.72', verification_note='md-verified 2026-09-05 (§E.2.1, printed p.72) [VC] — the standard constrains the SELECTION of the grid-average factor but prints no numeric value and no unit; the encoded "kg/kWh" is EKOWAI-authored', verified_at=now() where id='de4f1bff-288e-48f0-907b-d3019d4c9579' and verification_status not in ('verified_against_standard','corrected');
-- EL_imp
update public.fields set verification_status='verified_against_standard', verification_quote='Dieser Anhang gibt Anforderungen und eine Anleitung zur Behandlung von importiertem elektrischem Strom, der von der Organisation verbraucht wird, und von durch die Organisation produziertem und exportiertem elektrischem Strom. | Die Organisation muss Emissionen oder den Entzug von importiertem elektrischem Strom, der von der Organisation verbraucht wird, und von durch die Organisation produziertem und exportiertem elektrischem Strom nach Anhang E quantifizieren. — printed pp.72, 29', verification_note='md-verified 2026-09-05 (§E.1/§6.3, printed pp.72, 29) [VC]', verified_at=now() where id='4fa05957-b17a-4cbe-b476-6c602f9bbea4' and verification_status not in ('verified_against_standard','corrected');
-- GWP_gas
update public.fields set verification_status='verified_against_standard', verification_quote='Das aktuelle Treibhauspotential nach IPCC sollte angewendet werden. Falls nicht, muss dies begründet werden. Der Zeitrahmen des Treibhauspotentials muss 100 Jahre betragen. Andere Treibhauspotentialzeitrahmen können verwendet werden, müssen jedoch separat angegeben werden. — printed p.29', verification_note='md-verified 2026-09-05 (§6.3, printed p.29) [VC] — SR-2: §6.3 leaves the GWP SET to an engineer choice ("sollte" IPCC, otherwise justify) but FIXES the time horizon at 100 years; that 100-year constraint is not encoded anywhere (staged)', verified_at=now() where id='b116fd28-ceef-42c4-84c4-69754df2a31d' and verification_status not in ('verified_against_standard','corrected');
-- E_co2e_total
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss die Menge jeder Art von Treibhausgas unter Anwendung geeigneter Treibhauspotentiale in Tonnen $\mathrm{CO}_{2} \mathrm{AIq}$ umrechnen. | j) quantifizierte indirekte THG-Emissionen getrennt nach Kategorien in Tonnen $\mathrm{CO}_{2}$ Äq (5.2.4); — printed pp.29, 37', verification_note='md-verified 2026-09-05 (§6.3/§9.3.1 j), printed pp.29, 37) [VC] — the md transcript renders "CO2 Äq" here as the OCR artefact "\mathrm{CO}_{2} \mathrm{AIq}"; quoted verbatim as the md reads', verified_at=now() where id='b534fcea-fac6-40ec-8fab-089e00d2c1d9' and verification_status not in ('verified_against_standard','corrected');
-- entzug_thg
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation sollte den Entzug von THG quantifizieren. | h) sofern quantifiziert, der Entzug direkter THG in Tonnen $\mathrm{CO}_{2}$ Äq (5.2.2); — printed pp.25, 37', verification_note='md-verified 2026-09-05 (§5.2.2/§9.3.1 h), printed pp.25, 37) [VC] — SOFT: §5.2.2 says "sollte" (should), so this field is correctly is_required=false', verified_at=now() where id='6b9f20ac-c228-403b-920a-ea876f21dcb1' and verification_status not in ('verified_against_standard','corrected');
-- biogen_co2
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss biogene Emissionen und den biogenen Entzug nach Anhang D quantifizieren. | Anthropogene biogene $\mathrm{CO}_{2}$-Emissionen und Entzug müssen quantifiziert und getrennt von anthropogenen Emissionen angegeben werden. Anthropogene biogene Emissionen und Entzüge anderer Treibhausgase (z. B. $\mathrm{CH}_{4}$ und $\mathrm{N}_{2} \mathrm{O}$ ) müssen als anthropogen quantifiziert und angegeben werden. — printed pp.29, 71', verification_note='md-verified 2026-09-05 (§6.3/Anhang D, printed pp.29, 71) [VC] — Anhang D is NORMATIV; it makes ANTHROPOGENIC biogenic CO2 mandatory ("müssen") but NON-anthropogenic optional ("dürfen"), a distinction the single encoded field does not carry (staged)', verified_at=now() where id='6bdc6a2a-7fd0-449d-9653-89ab83034a78' and verification_status not in ('verified_against_standard','corrected');
-- strom_ansatz
update public.fields set verification_status='verified_against_standard', verification_quote='Emissionen aus importiertem elektrischem Strom, der von der Organisation eingesetzt wird, müssen von der Organisation unter Verwendung des ortsbasierten Ansatzes und Anwendung des Emissionsfaktors, der das betreffende Netz am besten charakterisiert, d.h. einer eigenen Übertragungsleitung, eines lokalen, regionalen oder nationalen netzdurchschnittlichen Emissionsfaktors, quantifiziert werden. | Bei der Verwendung von vertraglich geregelten Mitteln bei der Beschaffung ihres elektrischen Stroms darf eine Organisation den marktbasierten Ansatz anwenden, vorausgesetzt die vertraglich geregelten Mittel erfüllen die folgenden Qualitätskriterien: — printed pp.72-73', verification_note='md-verified 2026-09-05 (§E.2.1/§E.2.2, printed pp.72-73) [VC] — the ortsbasiert option is MANDATORY ("müssen"), marktbasiert is a conditional additional option ("darf ... vorausgesetzt"); the enum encodes them as equal alternatives (staged)', verified_at=now() where id='731a86e8-a228-45b9-adf7-2b810445aae0' and verification_status not in ('verified_against_standard','corrected');
-- basisjahr
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss zum Vergleich der THGEmissionen und des Entzugs von Treibhausgasen oder zur Erfüllung der Anforderungen eines THGProgramms oder anderer vorgesehener Nutzungen der Treibhausgasbilanz ein historisches Basisjahr festlegen. | spezifischer historischer Zeitraum, der für den Vergleich der THG-Emissionen (3.1.5) oder des Entzugs von THG (3.1.6) oder anderer THG-bezogener Informationen über einen bestimmten Zeitraum identifiziert wurde — printed pp.30, 19', verification_note='md-verified 2026-09-05 (§6.4.1/§3.2.10, printed pp.30, 19) [VC]', verified_at=now() where id='beb67966-fe7a-4ece-b76f-7ab8aded6d94' and verification_status not in ('verified_against_standard','corrected');
-- basisjahr_bilanz
update public.fields set verification_status='verified_against_standard', verification_quote='Bei der Festlegung des Basisjahrs muss die Organisation: | a) die Treibhausgasemissionen oder entzogene Menge an Treibhausgasen für das Basisjahr unter Verwendung von Daten, die repräsentativ für die aktuelle Berichtsgrenze der Organisation sind, üblicherweise Daten von einem einzelnen Jahr, ein Mittelwert von mehreren Jahren oder ein gleitender Mittelwert, quantitativ bestimmen; | b) ein Basisjahr auswählen, für das verifizierbare Daten zu Treibhausgasemissionen oder dem Entzug von Treibhausgasen zur Verfügung stehen; — printed p.30', verification_note='md-verified 2026-09-05 (§6.4.1 a)/b), printed p.30) [VC]', verified_at=now() where id='bacea67e-743a-495a-847d-c8093a170f77' and verification_status not in ('verified_against_standard','corrected');
-- basisjahr_begruendung
update public.fields set verification_status='verified_against_standard', verification_quote='c) die Auswahl des Basisjahrs erläutern; | Die Organisation darf ihr Basisjahr ändern, sie muss jedoch jede Änderung bezüglich des Basisjahrs begründen. — printed p.30', verification_note='md-verified 2026-09-05 (§6.4.1 c), printed p.30) [VC]', verified_at=now() where id='3dc98acf-09e9-4343-baae-1f518d926d9b' and verification_status not in ('verified_against_standard','corrected');
-- neuberechnung_verfahren
update public.fields set verification_status='verified_against_standard', verification_quote='Um die Repräsentativität der basisjahrbezogenen Treibhausgasbilanz sicherzustellen, muss die Organisation eine basisjahrbezogene Prüfung und Neuberechnung entwickeln, dokumentieren und anwenden, um wesentlichen kumulativen Veränderungen der Basisjahr-Emissionen Rechnung zu tragen, die aus folgenden Faktoren entstehen: | a) einer strukturellen Veränderung der Berichtsoder Organisationsgrenzen (d. h. Fusion, Übernahme oder Auflösung), oder | b) einer Veränderung der Berechnungsmethoden oder Emissionsfaktoren, oder | c) der Aufdeckung eines Fehlers oder mehrerer kumulativer Fehler, die gemeinsam eine wesentliche Bedeutung haben. — printed p.31', verification_note='md-verified 2026-09-05 (§6.4.2 a)-c), printed p.31) [VC]', verified_at=now() where id='11db7d23-8ee3-45ed-8c79-54cef621db95' and verification_status not in ('verified_against_standard','corrected');
-- reduzierungsinitiative
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation darf THG-Reduzierungsinitiativen planen und umsetzen, um THG-Emissionen zu reduzieren oder zu verhindern oder den Entzug von Treibhausgasen zu verbessern. | Falls eine solche Initiative umgesetzt wird, sollte die Organisation Unterschiede der THG-Emission oder des Entzugs von Treibhausgasen durch die Umsetzung von THG-Reduzierungsinitiativen quantifizieren. — printed p.31', verification_note='md-verified 2026-09-05 (§7.1, printed p.31) [VC] — SOFT: §7.1 is permissive ("darf") + recommending ("sollte"); the block gate CR-015 over this field is not supported by the source (staged)', verified_at=now() where id='d7169a25-df4e-462a-a5ee-ea5b60deee58' and verification_status not in ('verified_against_standard','corrected');
-- emissionsgutschrift
update public.fields set verification_status='verified_against_standard', verification_quote='Wenn die Organisation erworbene oder entwickelte Emissionsgutschriften in Berichten anführt, müssen die Emissionsgutschriften separat zu den THGReduzierungsinitiativen aufgelistet werden. — printed p.33', verification_note='md-verified 2026-09-05 (§7.2, printed p.33) [VC] — CONDITIONAL: the "müssen" applies only IF the organisation reports offsets; the unconditional block gate CR-016 over-enforces (staged)', verified_at=now() where id='8c79a983-d5c9-4326-810d-df91f961c618' and verification_status not in ('verified_against_standard','corrected');
-- reduzierungsziel
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation darf Ziele für die Reduzierung von THG-Emissionen festlegen. | Wenn die Organisation ein Ziel im Bericht angibt, müssen die folgenden Informationen spezifiziert und angegeben werden: | - der Zeitraum, auf den sich das Ziel bezieht, einschließlich des Zielbezugsjahrs und des Zielabschlussjahrs; | - die Art des Ziels (Intensität oder absolut); | - im Ziel enthaltene Emissionskategorie; | - die Menge der Reduzierung und ihre Einheit in Übereinstimmung mit der Art des Ziels. — printed p.33', verification_note='md-verified 2026-09-05 (§7.3, printed p.33) [VC] — CONDITIONAL ("darf ... festlegen" / "Wenn ... angibt"); only 2 of the 4 printed items are encoded as fields (staged)', verified_at=now() where id='d8976418-ee9f-4ba3-aa8a-0ded52ab6591' and verification_status not in ('verified_against_standard','corrected');
-- zielart
update public.fields set verification_status='verified_against_standard', verification_quote='Wenn die Organisation ein Ziel im Bericht angibt, müssen die folgenden Informationen spezifiziert und angegeben werden: | - die Art des Ziels (Intensität oder absolut); — printed p.33', verification_note='md-verified 2026-09-05 (§7.3, printed p.33) [VC]', verified_at=now() where id='bff8685d-e8b3-4e78-aa70-d22a1034e9f1' and verification_status not in ('verified_against_standard','corrected');
-- info_management_verfahren
update public.fields set verification_status='verified_against_standard', verification_quote='8.1.1 Die Organisation muss Verfahren zur Verwaltung von THG-Informationen einführen und aufrechterhalten, die: | a) die Konformität mit den Grundsätzen dieses Dokuments sicherstellen; | b) mit der vorgesehenen Nutzung der Treibhausgasbilanz konsistent sind; — printed p.33', verification_note='md-verified 2026-09-05 (§8.1.1 a)/b), printed p.33) [VC] — the md German column of §8.1.1 breaks off after item b); items c)-e) survive only in the English column of the transcript', verified_at=now() where id='45944213-7bc7-46ea-94eb-ab24e490251f' and verification_status not in ('verified_against_standard','corrected');
-- dokumentenaufbewahrung
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss Verfahren zur Dokumentenaufbewahrung und Pflege von Aufzeichnungen einführen und aufrechterhalten. | Die Organisation muss Dokumentationen aufbewahren und pflegen, die die Planung, Erstellung und Aufrechterhaltung der Treibhausgasbilanz belegen, um eine Verifizierung zu ermöglichen. — printed p.35', verification_note='md-verified 2026-09-05 (§8.2, printed p.35) [VC]', verified_at=now() where id='14fb18a6-94c5-4f44-a46b-bf820f9e36f6' and verification_status not in ('verified_against_standard','corrected');
-- unsicherheitsbewertung
update public.fields set verification_status='verified_against_standard', verification_quote='Die Organisation muss die Unsicherheit in Verbindung mit den Quantifizierungsansätzen (z. B. für die Quantifizierung und die Modelle verwendete Daten) bewerten und eine Bewertung durchführen, um die Unsicherheit auf der Ebene der Treibhausgasbilanzkategorie zu bestimmen. | Wenn eine quantitative Abschätzung der Unsicherheit nicht möglich oder kostenintensiv ist, muss dies begründet und eine qualitative Bewertung durchgeführt werden. — printed p.35', verification_note='md-verified 2026-09-05 (§8.3, printed p.35) [VC]', verified_at=now() where id='738de1ab-5cf3-4fcf-8a61-ac3a5973a12a' and verification_status not in ('verified_against_standard','corrected');
-- thg_bericht_erstellt
update public.fields set verification_status='verified_against_standard', verification_quote='Ein Treibhausgasbericht muss erstellt werden, wenn die Organisation ihre Treibhausgasbilanz verifizieren lassen will oder eine öffentliche THGErklärung zur Konformität mit diesem Dokument abgeben möchte. | Die Organisation sollte einen Treibhausgasbericht in Übereinstimmung mit der vorgesehenen Nutzung der Treibhausgasbilanz erstellen, um die Verifizierung der Treibhausgasbilanz zu vereinfachen. Ein Treibhausgasbericht kann z. B. erforderlich sein, um an einem THG-Programm teilzunehmen oder externe oder interne Anwender zu informieren. — printed p.35', verification_note='md-verified 2026-09-05 (§9.1, printed p.35) [VC]', verified_at=now() where id='2fb855f4-cb45-4f41-9cb1-d5a29bac7235' and verification_status not in ('verified_against_standard','corrected');
-- konformitaetserklaerung
update public.fields set verification_status='verified_against_standard', verification_quote='Der Treibhausgasbericht muss Folgendes umfassen: | r) eine Erklärung, dass der Treibhausgasbericht in Übereinstimmung mit diesem Dokument erstellt wurde; — printed pp.37-38', verification_note='md-verified 2026-09-05 (§9.3.1 r), printed pp.37-38) [VC]', verified_at=now() where id='22f1ea9e-4af3-49a8-837e-c0cab633c0ce' and verification_status not in ('verified_against_standard','corrected');
-- gwp_quelle
update public.fields set verification_status='verified_against_standard', verification_quote='t) die in der Berechnung verwendeten Treibhauspotentialwerte und ihre Quellen. Wenn die Treibhauspotentialwerte nicht aus dem aktuellen IPCC-Bericht entnommen werden, werden die Emissionsfaktoren oder die in der Berechnung verwendete Datenbasisreferenz und ihre Quelle einbezogen. — printed p.38', verification_note='md-verified 2026-09-05 (§9.3.1 t), printed p.38) [VC]', verified_at=now() where id='7a2235c1-067c-4c09-90eb-d7928f83ca10' and verification_status not in ('verified_against_standard','corrected');
-- verifizierungsart
update public.fields set verification_status='verified_against_standard', verification_quote='s) eine Offenlegung, in der beschrieben ist, ob die Treibhausgasbilanz, der Treibhausgasbericht oder die Treibhausgaserklärung verifiziert wurden, einschließlich der Art der Verifizierung und des erreichten Grads an Sicherheit; | Um die Informationen über Treibhausgasemissionen und den Entzug von Treibhausgas unparteilich und objektiv zu prüfen, muss die Organisation eine Verifizierung entsprechend den Bedürfnissen der vorgesehenen Anwender durchführen. Grundsätze und Anforderungen sind in ISO 14064-3 beschrieben. — printed pp.38, 40', verification_note='md-verified 2026-09-05 (§9.3.1 s)/§10, printed pp.38, 40) [VC]', verified_at=now() where id='d618521f-95fd-4f47-a5a6-c018578f4046' and verification_status not in ('verified_against_standard','corrected');
-- sicherheitsgrad
update public.fields set verification_status='verified_against_standard', verification_quote='s) eine Offenlegung, in der beschrieben ist, ob die Treibhausgasbilanz, der Treibhausgasbericht oder die Treibhausgaserklärung verifiziert wurden, einschließlich der Art der Verifizierung und des erreichten Grads an Sicherheit; | Grad des Vertrauens in die THG-Erklärung (3.2.5) — printed pp.38, 23', verification_note='md-verified 2026-09-05 (§9.3.1 s)/§3.4.13, printed pp.38, 23) [VC]', verified_at=now() where id='ea0fb890-9965-4b05-8483-01b2eca3ed8c' and verification_status not in ('verified_against_standard','corrected');

-- ==== equations: QUOTE BACKFILL only (verification_status already verified_against_standard; NOT touched) ====
-- Q-GHG
update public.equations set verification_quote='ANMERKUNG Verschiedene Arten von Modellen nutzen mit Emissionsfaktoren multiplizierte Aktivitätsdaten. | Die Organisation muss die Treibhausgasemissionen und den Entzug von Treibhausgasen in Übereinstimmung mit dem ausgewählten Quantifizierungsansatz berechnen (siehe 6.2). — printed p.29', verification_note=coalesce(nullif(verification_note,'') || ' | ', '') || 'md-verified 2026-09-05 (§6.2.3 ANMERKUNG/§6.3, printed p.29) [VC] — quote backfill; verification_status untouched. The standard prints NO displayed equation anywhere; "E_gas = AD * EF_gas" is EKOWAI-authored formalisation of the printed ANMERKUNG. DIMENSIONAL RESIDUE: AD[Einheit] x EF_gas[kg/Einheit] = kg, but E_gas is declared in t', verified_at=now() where id='09b790ad-bda4-4020-9ef9-9384abef9f76' and verification_quote is null;
-- Q-CAT
update public.equations set verification_quote='Anmerkung 1 zum Begriff: Das KohlendioxidÄquivalent wird berechnet, indem die Masse eines bestimmten THGs mit dessen Treibhauspotential (3.1.12) multipliziert wird. | Einheit zum Vergleich des Strahlungsantriebs eines THGs (3.1.1) mit dem von Kohlendioxid — printed p.17', verification_note=coalesce(nullif(verification_note,'') || ' | ', '') || 'md-verified 2026-09-05 (§3.1.13 Anmerkung 1, printed p.17) [VC] — quote backfill; verification_status untouched. Dimensionally consistent: t x dimensionless GWP = t CO2Aeq', verified_at=now() where id='7ac8363d-19a8-4106-94e4-c1b0abe174e2' and verification_quote is null;
-- Q-TOT
update public.equations set verification_quote='Die Organisation muss die Menge jeder Art von Treibhausgas unter Anwendung geeigneter Treibhauspotentiale in Tonnen $\mathrm{CO}_{2} \mathrm{AIq}$ umrechnen. | j) quantifizierte indirekte THG-Emissionen getrennt nach Kategorien in Tonnen $\mathrm{CO}_{2}$ Äq (5.2.4); — printed pp.29, 37', verification_note=coalesce(nullif(verification_note,'') || ' | ', '') || 'md-verified 2026-09-05 (§6.3/§9.3.1 j), printed pp.29, 37) [VC] — quote backfill; verification_status untouched. The standard prints the summation as prose, not as a formula. RESIDUE: E_el (Q-EL) is NOT an input to this sum, so imported-electricity emissions never reach E_co2e_total', verified_at=now() where id='1b725e27-bceb-438e-80cc-35ef7960d4e7' and verification_quote is null;
-- Q-EL
update public.equations set verification_quote='Emissionen aus importiertem elektrischem Strom, der von der Organisation eingesetzt wird, müssen von der Organisation unter Verwendung des ortsbasierten Ansatzes und Anwendung des Emissionsfaktors, der das betreffende Netz am besten charakterisiert, d.h. einer eigenen Übertragungsleitung, eines lokalen, regionalen oder nationalen netzdurchschnittlichen Emissionsfaktors, quantifiziert werden. | ANMERKUNG Der ortsbasierte Ansatz ist ein Verfahren zur Quantifizierung indirekter Emissionen aus Energie auf der Grundlage von durchschnittlichen Emissionsfaktoren der Energieerzeugung für festgelegte geographische Orte, einschließlich lokaler, regionaler oder nationaler Grenzen. — printed p.72', verification_note=coalesce(nullif(verification_note,'') || ' | ', '') || 'md-verified 2026-09-05 (§E.2.1, printed p.72) [VC] — quote backfill; verification_status untouched. Anhang E is NORMATIV but prints no displayed formula. DIMENSIONAL RESIDUE: EL_imp[kWh] x EF_grid[kg/kWh] = kg, but E_el is declared in t CO2Aeq', verified_at=now() where id='4e81dbbd-4211-48b7-8991-02aaf039c3e2' and verification_quote is null;
