-- ============================================================================
-- SR-1 field-verification pack — ISO-14064-2
--   Standard: DIN EN ISO 14064-2:2020-05 / EN ISO 14064-2:2019 (D/E), "Treibhausgase - Teil 2:
--   Spezifikation mit Anleitung zur quantitativen Bestimmung, Ueberwachung und Berichterstattung von
--   Reduktionen der Treibhausgasemissionen oder Steigerungen des Entzugs von Treibhausgasen auf
--   Projektebene (ISO 14064-2:2019); Deutsche und Englische Fassung EN ISO 14064-2:2019".
--   Second edition, supersedes ISO 14064-2:2006. Prod standards.version = "2019 (EN ISO 14064-2:2019)";
--   standard id b6709ca6-6e72-4808-baaa-742f43450dab.
--   This IS a requirements standard ("muss"/"shall"), so block gates are defensible — but ONLY on an
--   UNCONDITIONAL "muss". All 22 gates were checked against the printed sentence each cites; the ones
--   that are not so anchored are listed in iso-14064-2-STAGED-rulings.sql (nothing applied here).
-- Generated: 2026-09-05 — md-verified pass (owner ruling 2026-09-05: the markdown transcript is the
--   verification source; the PDF only where no markdown exists). Grade: VC (SR-3), labelled on every row.
--   Records EVIDENCE only (verification_status / verification_quote / verification_note / verified_at);
--   changes NO structure, no enforcement, no required-ness — all of that sits in the STAGED file, unapplied.
--   Contains ONLY update statements — no begin/commit/rollback (apply-pack.mjs supplies the transaction).
--
-- Source md: C:\Users\Ekowai\Desktop\Guidelines\DWA DIN Scribd\ISO-14064-2\ISO-14064-2-2019-en-es.md
--   (1885 lines, mathpix LaTeX transcript, read completely).
--
-- LANGUAGE CONVENTION — read this before judging any quote below.
--   This is the CEN PARALLEL edition; in the printed standard the two columns are GERMAN (left) and
--   ENGLISH (right). The transcript, however, was made from a copy whose English column had already been
--   MACHINE-TRANSLATED INTO SPANISH (the source PDF's own first page reads "Traducido del ingles al
--   espanol"), and that same machine pass bled single Spanish words back into the German column. Every
--   quote below is therefore the GERMAN column, verbatim as the transcript reads it, because the German
--   text is the one that carries the "muss" / "sollte" / "darf" distinction the gates depend on. Where the
--   machine pass left a Spanish word or an OCR artefact inside a German sentence ("morir" for "die", "en"
--   for "in", "Parámetro", "Cuantitativo Bestimmung", "quantumn", "significantkanten", "señorita",
--   "sichprokent", "kontroliert" with one l, "ausgewähIten" with a capital I), it is REPRODUCED EXACTLY as
--   the transcript prints it — it is not a typo introduced here and it is deliberately not corrected,
--   because a corrected quote would no longer be a literal substring of the source. Runs joined inside one
--   clause are marked " | "; an omitted run inside one clause would be marked "[...]" (none used). Every
--   fragment below was machine-checked to be a literal substring of the md before this pack was written.
--
-- PAGE CONVENTION: "printed p.N" is stated ONCE at the END of each quote ("pp.A, B" = two clauses joined
--   by " | " that sit on different pages; "pp.A-B" = one quote spans a page break). The md itself carries
--   NO page markers (no standalone number lines, no running headers), so pages were DERIVED in two steps:
--     (1) the standard's own Inhalt index (rendered PDF pages 6-7) prints a page for every 1st/2nd-level
--         clause: §1 p.16 · §3.1 p.16 · §3.2 p.19 · §3.3 p.21 · §3.4 p.22 · §4 and §4.1-4.7 p.23 · §5 p.24 ·
--         §6 p.29 · §6.1 p.29 · §6.2 p.30 · §6.3 p.32 · §6.4 p.32 · §6.5 p.34 · §6.6 p.34 · §6.7 p.34 ·
--         §6.8 p.35 · §6.9 p.36 · §6.10 p.36 · §6.11 p.38 · §6.12 p.38 · §6.13 p.38 · Anhang A p.41.
--     (2) for list items and 3rd-level anchors the index has no entry, so each quoted sentence was located
--         on its own page of the rendered PDF (scoop pdftotext -layout, ISO-14064-2-2019-en-es.pdf,
--         67 PDF pages). The PDF's own footers give printed page = PDF page - 4, constant from PDF page 6
--         to the end (PDF p.8 -> "4", p.20 -> "dieciseis" (=16, machine-translated numeral), p.46 -> "42").
--         Every quoted anchor resolves to exactly one PDF page under that mapping and each agrees with (1).
--   IMPORTANT SR-3 NOTE: that PDF is NOT the authentic Beuth German/English print — it is the same
--   machine-translated copy the md was OCR'd from. It was used ONLY to number pages, never to verify text.
--   The grade therefore stays VC, not VA; a VA pass needs the genuine DIN EN ISO 14064-2:2020-05 PDF.
--
-- COUNTS: 60 fields examined · 0 already verified · 60 quoted now · 0 app-metadata exempt · 0 residue.
--   4 equations: all 4 were already verification_status='verified_against_standard' with a NULL
--   verification_quote, so section B is a QUOTE BACKFILL under the guard "verification_quote is null" —
--   verification_status is NOT touched. 22 gates examined, 0 changed here (findings in the STAGED file).
-- Rollback: rollback-iso-14064-2-md-verification-pack.sql
-- ============================================================================

-- ---------------------------------------------------------------------------
-- A. FIELDS — 60 rows (quote + note + verified_at), guarded on the prior status
-- ---------------------------------------------------------------------------

-- ---- worksheet ISO-14064-2-01 ----
-- recognized_source_used
update public.fields set verification_status='verified_against_standard', verification_quote='Der Projektantragsteller muss gängige Kriterien und Verfahren von einer anerkannten Quelle, falls verfügbar, auswählen und anwenden. — printed p.29', verification_note='md-verified 2026-09-05 (§6.1, printed p.29) [VC]', verified_at=now() where id='0be5e745-45cd-4889-8165-a16e8b503096' and verification_status not in ('verified_against_standard','corrected');
-- deviations_documented
update public.fields set verification_status='verified_against_standard', verification_quote='Wenn der Antragsteller des Projekts Kriterien und Verfahren oder relevante aktuelle Leitlinien der Industrie für bewährte Praxis anwendet, die von einer anerkannten Quelle stammen, muss der Antragsteller des Projekts alle Abweichungen von diesen Kriterien und Verfahren dokumentieren und begründen. — printed p.29', verification_note='md-verified 2026-09-05 (§6.1, printed p.29) [VC] — Vorbehalt: die Pflicht gilt nur, wenn Kriterien aus einer anerkannten Quelle verwendet werden UND Abweichungen davon bestehen. Siehe STAGED A-1.', verified_at=now() where id='b8f56e65-f050-41f6-bbea-fd9bb9d1ce48' and verification_status not in ('verified_against_standard','corrected');
-- ghg_programme
update public.fields set verification_status='verified_against_standard', verification_quote='Wenn der Projektantragsteller sich für ein Klimaschutzprogramm anmeldet, muss er sicherstellen, dass das Klimaschutzprojekt die Anforderungen des Klimaschutzprogramms erfüllt. | freiwilliges o verbindliches internationales, nationales o regionales System oder Modell, mit dem die Treibhausgasemissionen — printed pp.29, 22', verification_note='md-verified 2026-09-05 (§6.1 + §3.3.4, printed pp.29, 22) [VC] — Vorbehalt: die Pflicht gilt nur "Wenn der Projektantragsteller sich fuer ein Klimaschutzprogramm anmeldet"; die Normenreihe ist ausdruecklich programm-neutral (Abschnitt 1). Siehe STAGED A-2.', verified_at=now() where id='5d7b5288-28aa-44d8-a952-057f17ea99d2' and verification_status not in ('verified_against_standard','corrected');
-- principle_relevance
update public.fields set verification_status='verified_against_standard', verification_quote='Die THG-QSS, Daten und Methoden sind entsprechend den Bedürfnissen des vorgesehenen Anwenders auszuwählen. — printed p.23', verification_note='md-verified 2026-09-05 (§4.2, printed p.23) [VC]', verified_at=now() where id='b1117257-52c9-4631-a8b9-d41d6a73d4c9' and verification_status not in ('verified_against_standard','corrected');
-- principle_completeness
update public.fields set verification_status='verified_against_standard', verification_quote='Alle relevanten Treibhausgasemissionen und entzogenen Mengen von Treibhausgasen sind einzubeziehen. Alle relevanten Informationen zur Unterstützung der Kriterien und Verfahren sind einzubeziehen. — printed p.23', verification_note='md-verified 2026-09-05 (§4.3, printed p.23) [VC]', verified_at=now() where id='fd10146f-d3b9-4ac8-8a3c-1b4107f07a51' and verification_status not in ('verified_against_standard','corrected');
-- principle_consistency
update public.fields set verification_status='verified_against_standard', verification_quote='Aussagekräftige Vergleiche der treibhausgasbezogenen Informationen sind zu ermöglichen. — printed p.23', verification_note='md-verified 2026-09-05 (§4.4, printed p.23) [VC]', verified_at=now() where id='ce2e386b-faad-4848-97f6-292ab0ff6e45' and verification_status not in ('verified_against_standard','corrected');
-- principle_accuracy
update public.fields set verification_status='verified_against_standard', verification_quote='Systematische Abweichungen und Unsicherheiten sind, soweit praktisch möglich, zu verringern. — printed p.23', verification_note='md-verified 2026-09-05 (§4.5, printed p.23) [VC]', verified_at=now() where id='195df072-72d6-4a1c-873f-95da858d8588' and verification_status not in ('verified_against_standard','corrected');
-- principle_transparency
update public.fields set verification_status='verified_against_standard', verification_quote='Es sind hinreichend geeignete treibhausgasbezogene Informationen offenzulegen, um es den vorgesehenen Anwendern zu ermöglichen, Entscheidungen mit angemessenem Vertrauen zu treffen. — printed p.23', verification_note='md-verified 2026-09-05 (§4.6, printed p.23) [VC]', verified_at=now() where id='3e421b7a-c5f3-4c83-87f4-64f0cc22396e' and verification_status not in ('verified_against_standard','corrected');
-- principle_conservativeness
update public.fields set verification_status='verified_against_standard', verification_quote='Es sind konservative Annahmen, Werte und Verfahren zu verwenden, um sicherzustellen, dass die Reduktionen von Treibhausgasemissionen oder die Steigerungen des Entzugs von Treibhausgasen nicht überschätzt werden. — printed p.23', verification_note='md-verified 2026-09-05 (§4.7, printed p.23) [VC]', verified_at=now() where id='1e2e1cb3-a387-405c-ba99-28fb8c4e2418' and verification_status not in ('verified_against_standard','corrected');

-- ---- worksheet ISO-14064-2-02 ----
-- project_title
update public.fields set verification_status='verified_against_standard', verification_quote='Der Antragsteller des Projekts muss das Projekt und seinen Kontext in einem Plan für ein Klimaschutzprojekt beschreiben, der Folgendes umfasst: | a) Titel, Zweck(e) und Zielsetzung(en) des Projekts; — printed p.30', verification_note='md-verified 2026-09-05 (§6.2 a), printed p.30) [VC]', verified_at=now() where id='471e3312-6051-44bd-a01e-764c21c126ac' and verification_status not in ('verified_against_standard','corrected');
-- project_type
update public.fields set verification_status='verified_against_standard', verification_quote='b) die Art des Klimaschutzprojekts einschließlich Beschreibungen, wie das Projekt die Reduzierung der Treibhausgasemissionen und/ oder die Steigerung des Entzugs erreichen wird und auf welche spezifischen THG sich das Projekt bezieht; — printed p.30', verification_note='md-verified 2026-09-05 (§6.2 b), printed p.30) [VC]', verified_at=now() where id='b9cf42b2-09e2-40a5-83f8-c6840d02e102' and verification_status not in ('verified_against_standard','corrected');
-- targeted_ghgs
update public.fields set verification_status='verified_against_standard', verification_quote='und auf welche spezifischen THG sich das Projekt bezieht; | Anmerkung 1 zum Begriff: Treibhausgase umfassen Kohlendioxid (CO2), Metan (CH4), Stickstoffoxid (N2O), Fluorkohlenwasserstoffe (FKW), Perfluorkohlenwasserstoffe (P-FKW) sowie Schwefelhexafluorid (SF6). — printed pp.30, 17', verification_note='md-verified 2026-09-05 (§6.2 b) + §3.1.1 Anm. 1, printed pp.30, 17) [VC] — Vorbehalt: der Enum-Wert "other" ist EKOWAI-Ergaenzung, gedeckt durch 3.1.1 Anm. 2 (der IPCC-Bericht enthaelt weitere Beispiele), nicht durch eine gedruckte Liste.', verified_at=now() where id='0b4ed4bb-ed1c-48d1-b92d-e5391acb1d45' and verification_status not in ('verified_against_standard','corrected');
-- project_location
update public.fields set verification_status='verified_against_standard', verification_quote='c) Lage des Projekts, einschließlich organisatorischer und geographischer Angaben und Angaben zum physischen Standort, die eine eindeutige Identifizierung und Beschreibung des konkreten Ausmaßes des Projekts ermöglichen; — printed p.30', verification_note='md-verified 2026-09-05 (§6.2 c), printed p.30) [VC]', verified_at=now() where id='703e4a19-1f8e-4c51-ab75-cafb2fa30c08' and verification_status not in ('verified_against_standard','corrected');
-- pre_project_conditions
update public.fields set verification_status='verified_against_standard', verification_quote='d) Bedingungen vor Projektbeginn; — printed p.30', verification_note='md-verified 2026-09-05 (§6.2 d), printed p.30) [VC]', verified_at=now() where id='c54da5ad-0136-45d7-a33b-605a2b28b45f' and verification_status not in ('verified_against_standard','corrected');
-- project_technologies
update public.fields set verification_status='verified_against_standard', verification_quote='e) projektbezogene Technologien, Produkte, Dienstleistungen und erwarteter Umfang der Tätigkeiten; — printed p.30', verification_note='md-verified 2026-09-05 (§6.2 e), printed p.30) [VC]', verified_at=now() where id='25be1e50-81f0-41d9-b151-7cc55187f37f' and verification_status not in ('verified_against_standard','corrected');
-- expected_reductions_co2e
update public.fields set verification_status='verified_against_standard', verification_quote='f) die zusammengefassten Reduzierungen der Treibhausgasemissionen und Steigerungen des Entzugs angegeben in der vom vorgesehenen Anwender benötigten Maßeinheit zur Angabe, z. B. en Tonnen CO2e, die voraussichtlich durch das Klimaschutzprojekt erzielt werden; — printed p.30', verification_note='md-verified 2026-09-05 (§6.2 f), printed p.30) [VC] — Vorbehalt: die Einheit ist NICHT normativ festgelegt - die Norm sagt "in der vom vorgesehenen Anwender benoetigten Massseinheit ... z. B. en Tonnen CO2e". "t CO2e" im Encoding ist das Beispiel der Norm, keine Vorschrift.', verified_at=now() where id='e57bc9fe-366f-497a-8261-7405dbc9ec85' and verification_status not in ('verified_against_standard','corrected');
-- project_risks
update public.fields set verification_status='verified_against_standard', verification_quote='g) die Identifizierung der Risiken, die einen wesentlichen Einfluss auf die Reduzierung der Treibhausgasemissionen oder die Steigerung des Entzugs im Rahmen des Projekts haben könnten, und, sofern anwendbar, alle eventuellen Maßnahmen zur Beherrschung dieser Risiken; — printed p.30', verification_note='md-verified 2026-09-05 (§6.2 g), printed p.30) [VC]', verified_at=now() where id='f7d7c86a-f166-4efa-a920-931a92dcab56' and verification_status not in ('verified_against_standard','corrected');
-- roles_responsibilities
update public.fields set verification_status='verified_against_standard', verification_quote='h) Aufgaben und Verantwortlichkeiten einschließlich Kontaktinformationen des Antragstellers des Projekts und anderer Projektteilnehmer einschließlich der vorgesehenen Anwender, der Rollen und Kontaktinformationen zuständiger Überwachungsbehörden oder Leiter von Klimaschutzprogrammen, zu denen sichprokent; — printed p.30', verification_note='md-verified 2026-09-05 (§6.2 h), printed p.30) [VC]', verified_at=now() where id='0cfb7a43-4bc7-474e-9901-3f577d058e79' and verification_status not in ('verified_against_standard','corrected');
-- eia_summary
update public.fields set verification_status='verified_against_standard', verification_quote='i) eine zusammenfassende | Umweltverträglichkeitsprüfung, wenn eine derartigie Prüfung von der geltenden Gesetzgebung oder Vorschrift in Verbindung mit dem Projekt oder Klimaschutzprogramm gefordert wird; — printed p.31', verification_note='md-verified 2026-09-05 (§6.2 i), printed p.31) [VC]', verified_at=now() where id='40985960-4aaa-4ba4-92d5-584e405777c1' and verification_status not in ('verified_against_standard','corrected');
-- stakeholder_consultation
update public.fields set verification_status='verified_against_standard', verification_quote='j) die relevanten Ergebnisse der Besprechungen mit interessierten Parteien und Mechanismen für die laufende Kommunikation, sofern anwendbar; — printed p.31', verification_note='md-verified 2026-09-05 (§6.2 j), printed p.31) [VC]', verified_at=now() where id='c80fc153-6520-4bc0-b515-3fd2f7b1b1bf' and verification_status not in ('verified_against_standard','corrected');
-- chronological_plan
update public.fields set verification_status='verified_against_standard', verification_quote='k) ein chronologischer Plan oder tatsächliche Termine und die Begründung für Folgendes: | 1) das Datum des Beginns der Projektaktivitäten; | 2) der Zeitraum des Treibhausgasbezugsszenarios; | 3) das Datum des Projektabschlusses; | 4) die Häufigkeit der Überwachung und Berichterstattung und der Projektzeitraum einschließlich relevanter Projektaktivitäten in jedem Schritt des Klimaschutzprojektzyklus, sofern anwendbar; | 5) die Häufigkeit der Verifizierung und Validierung, sofern anwendbar. — printed p.31', verification_note='md-verified 2026-09-05 (§6.2 k), printed p.31) [VC]', verified_at=now() where id='1e2310e2-8ddd-4c51-905e-56cb6efaee86' and verification_status not in ('verified_against_standard','corrected');
-- programme_eligibility_info
update public.fields set verification_status='verified_against_standard', verification_quote='I) sofern anwendbar, erforderliche Informationen, die die Teilnahmeberechtigung eines Klimaschutzprojekts im Rahmen eines Klimaschutzprogramms betreffen, einschließlich rechtlicher, technischer, wirtschaftlicher, branchenspezifischer, sozialer, umweltbezogener, geographischer, standortspezifischer und zeitlicher Information. — printed p.31', verification_note='md-verified 2026-09-05 (§6.2 l), printed p.31) [VC]', verified_at=now() where id='bcb82c05-6175-4e12-b85c-4506cb38759d' and verification_status not in ('verified_against_standard','corrected');
-- baseline_revalidated
update public.fields set verification_status='verified_against_standard', verification_quote='Wenn einem bestehenden Projekt neue Aktivitäten oder Änderungen hinzugefügt werden, muss der Antragsteller das bzw. die Treibhausgasbezugsszenarios und die von den neuen Aktivitäten oder Änderungen betroffenen Emissionen oder entzogenen Mengen im Rahmen des Projekts einschließlich der Anforderungen des Klimaschutzprogramms oder des vorgesehenen Anwenders, sofern anwendbar, prüfen und aktualisieren. | Wenn die Änderungen nicht mit dem validierten Treibhausgasbezugsszenario konsistent sind, muss der Projektantragsteller das Projekt erneut validieren lassen. — printed pp.31-32', verification_note='md-verified 2026-09-05 (§6.2, printed pp.31-32) [VC] — Vorbehalt: beide Pflichten sind bedingt ("Wenn ... hinzugefuegt werden", "Wenn die Aenderungen nicht ... konsistent sind"). Siehe STAGED A-3.', verified_at=now() where id='b0f1bba0-e89e-4b6c-8fc4-ccf4351ffefd' and verification_status not in ('verified_against_standard','corrected');

-- ---- worksheet ISO-14064-2-03 ----
-- ssr_id_criteria
update public.fields set verification_status='verified_against_standard', verification_quote='Der Antragsteller des Projekts muss Kriterien und Verfahren zur Identifizierung und Beurteilung von THG-QSS, die vom Projekt kontrolliert werden, mit dem Projekt in Verbindung stehen oder von diesem beeinflusst werden, auswählen oder festlegen. — printed p.32', verification_note='md-verified 2026-09-05 (§6.3, printed p.32) [VC]', verified_at=now() where id='b1754d51-196c-4569-9eaa-fc0e6b26b12f' and verification_status not in ('verified_against_standard','corrected');
-- project_ssr
update public.fields set verification_status='verified_against_standard', verification_quote='Auf der Grundlage der ausgewähIten oder festgelegten Kriterien und Verfahren muss der Antragsteller des Projekts die für das Projekt relevanten THG- — printed p.32', verification_note='md-verified 2026-09-05 (§6.3, printed p.32) [VC]', verified_at=now() where id='c255a956-85c7-470c-a2b3-20560568db81' and verification_status not in ('verified_against_standard','corrected');
-- ssr_classification
update public.fields set verification_status='verified_against_standard', verification_quote='muss der Antragsteller des Projekts die für das Projekt relevanten THG- | a) kontroliert vom Antragsteller des Projekts, | b) zugehörig zu dem Klimaschutzprojekt oder | c) beeinflusst durch das Klimaschutzprojekt. — printed p.32', verification_note='md-verified 2026-09-05 (§6.3 a)-c), printed p.32) [VC]', verified_at=now() where id='9d79c73c-2582-472c-959d-503e0b49e624' and verification_status not in ('verified_against_standard','corrected');
-- ssr_type
update public.fields set verification_status='verified_against_standard', verification_quote='Prozess, bei dem ein Treibhausgas(3.1.1) en die Atmosphäre freigesetzt wird | Prozess, bei dem ein Treibhausgas(3.1.1) aus der Atmosphäre entzogen wird | Komponente außer der Atmosphäre, die in der Lage ist, Treibhausgase(3.1.1) zu akkumulieren sowie diese zu speichern und freizusetzen — printed p.17', verification_note='md-verified 2026-09-05 (§3.1.2/§3.1.3/§3.1.4, printed p.17) [VC] — Die Norm fuehrt QSS stets als Tripel Quelle/Senke/Speicher; die Aufspaltung in drei Enum-Werte ist Encoding-Konvention, gedeckt durch die drei Einzeldefinitionen 3.1.2/3.1.3/3.1.4.', verified_at=now() where id='53ac9d35-912f-4ea6-86c6-b696cc63d66f' and verification_status not in ('verified_against_standard','corrected');

-- ---- worksheet ISO-14064-2-04 ----
-- baseline_criteria
update public.fields set verification_status='verified_against_standard', verification_quote='Der Antragsteller des Projekts muss Kriterien und Verfahren zur Bestimmung des Treibhausgasbezugsszenarios auswählen oder festlegen und dabei Folgendes berücksichtigen: | a) die Projektbeschreibung, einschließlich identifizierter THG-QSS (siehe 6.3); | b) Bestehende und Alternative Projektarten, Tätigkeiten und Technologien, die gleichwertige Arten und Mengen von Produkten oder Dienstleistungen liefern; | c) Verfügbarkeit, Zuverlässigkeit und Beschränkungen von Daten; | d) weitere relevante Informationen bezüglich derzeitiger oder künftiger Bedingungen wie z. B. rechtlicher, technischer, wirtschaftlicher, soziokultureller, umweltbezogener, geographischer, standortspezifischer und zeitlicher Annahmen oder Prognosen. — printed pp.32-33', verification_note='md-verified 2026-09-05 (§6.4 a)-d), printed pp.32-33) [VC]', verified_at=now() where id='a2753237-9860-442d-a8b0-9954ca91bf0f' and verification_status not in ('verified_against_standard','corrected');
-- functional_equivalence
update public.fields set verification_status='verified_against_standard', verification_quote='Der Antragsteller des Projekts muss die funktionale Gleichwertigkeit in der Art und Qualität der Produkte oder Dienstleistungen nachweisen, die vom Projekt einerseits und dem Bezugsszenario anderseits geliefert werden, und muss gegebenenfalls alle significantkanten Unterschiede zwischen unsuter dem Projektzenario dem Projekt. — printed p.33', verification_note='md-verified 2026-09-05 (§6.4, printed p.33) [VC] — Quellendefekt: der deutsche Satz ist im Transkript UND im Quell-PDF verstuemmelt ("... alle significantkanten Unterschiede zwischen unsuter dem Projektzenario dem Projekt."). Verbatim uebernommen wie gedruckt.', verified_at=now() where id='9fb941fa-a115-4e0c-953f-902bdebbf186' and verification_status not in ('verified_against_standard','corrected');
-- baseline_justification
update public.fields set verification_status='verified_against_standard', verification_quote='Der Antragsteller des Projekts muss Kriterien und Verfahren zur Identifizierung und Begründung des Bezugsszenarios auswählen oder festlegen, beschreiben und anwenden. | Die Begründung des Treibhausgasbezugsszenarios sollte die wahrscheinliche zukünftige Entwicklung des Bezugsszenarios (THG-QSS) berücksichtigen, um den Grundsatz der Konservativität (4.7) zu erfüllen. — printed p.33', verification_note='md-verified 2026-09-05 (§6.4, printed p.33) [VC]', verified_at=now() where id='ed005e63-f616-426d-8c68-e2b7830ef3ca' and verification_status not in ('verified_against_standard','corrected');
-- baseline_conservative
update public.fields set verification_status='verified_against_standard', verification_quote='Bei der Entwicklung des Treibhausgasbezugsszenarios muss der Antragsteller des Projekts die Annahmen, Werte und Verfahren auswählen, die sicherstellen, dass die Reduktionen von Treibhausgasemissionen oder Steigerungen des Entzugs nicht überschätzt werden und diese begründen. — printed p.33', verification_note='md-verified 2026-09-05 (§6.4, printed p.33) [VC]', verified_at=now() where id='144c77b7-25b8-48af-ac41-560b48bb7c36' and verification_status not in ('verified_against_standard','corrected');
-- additionality_demonstrated
update public.fields set verification_status='verified_against_standard', verification_quote='Der Antragsteller des Projekts muss Kriterien und Verfahren auswählen oder festlegen, begründen und anwenden, um nachzuweisen, dass die Reduktionen von Treibhausgasemissionen oder Steigerungen des Entzugs des Projektes zusätzlich im Vergleich zu dem festgelegten Treibhausgasbezugsszenario sind. — printed p.33', verification_note='md-verified 2026-09-05 (§6.4, printed p.33) [VC]', verified_at=now() where id='f8eaa9b4-513b-4fb8-9579-b9c30a514604' and verification_status not in ('verified_against_standard','corrected');

-- ---- worksheet ISO-14064-2-05 ----
-- baseline_ssr
update public.fields set verification_status='verified_against_standard', verification_quote='Bei der Identifizierung von für das Bezugsszenario relevanten THG-QSS muss der Antragsteller des Projekts: | a) die bei der Identifizierung von für das Projekt relevanten THG-QSS angewendeten Kriterien und Verfahren berücksichtigen; | b) bei Bedarf zusätzliche Kriterien zur Identifizierung von relevanten THG-QSS erläutern und anwenden; | c) die im Zusammenhang mit dem Projekt identifizierten THG-QSS mit denen vergleichen, die im Bezugsszenario identifiziert wurden. — printed p.34', verification_note='md-verified 2026-09-05 (§6.5 a)-c), printed p.34) [VC]', verified_at=now() where id='0ea16ba7-eb8f-4742-b03a-e270aaf4006b' and verification_status not in ('verified_against_standard','corrected');
-- ssr_selection_mode
update public.fields set verification_status='verified_against_standard', verification_quote='Der Antragsteller des Projekts muss Kriterien und Verfahren zur Auswahl von THG-QSS entweder für die regelmäßige Überwachung oder für die Abschätzung auf der Grundlage geeigneter und zuverlässiger Daten auswählen oder festlegen. — printed p.34', verification_note='md-verified 2026-09-05 (§6.6, printed p.34) [VC]', verified_at=now() where id='ecfee535-a569-487b-9bf5-fae3903b790e' and verification_status not in ('verified_against_standard','corrected');
-- ssr_exclusion_justification
update public.fields set verification_status='verified_against_standard', verification_quote='Der Projektantragsteller muss eine Begründung vorbringen, wenn er keine THG-QSS, wie im Treibhausgasbezugsszenario angegeben, für die regelmäßige Überwachung ausgewählt hat. — printed p.34', verification_note='md-verified 2026-09-05 (§6.6, printed p.34) [VC] — Der Satz ist die Quelle fuer DIESES Feld, nicht fuer den Enum ssr_selection_mode - REQ-12 zitiert ihn dennoch dort. Siehe STAGED C-2.', verified_at=now() where id='9f3b484e-4ef8-4abc-a64f-fd6875bac83f' and verification_status not in ('verified_against_standard','corrected');

-- ---- worksheet ISO-14064-2-06 ----
-- activity_data
update public.fields set verification_status='verified_against_standard', verification_quote='Faktor, der die THG-Aktivitätsdaten mit der Emisión de THG(3.1.5) verbindet | Faktor, der die THG-Aktivitätsdaten mit dem THGEntzug(3.1.6) verbindet — printed pp.17-18', verification_note='md-verified 2026-09-05 (§3.1.9/§3.1.10, printed pp.17-18) [VC] — Vorbehalt: die Norm definiert "Aktivitaetsdaten" NICHT als eigenen Begriff; sie erscheinen nur als "THG-Aktivitaetsdaten" innerhalb der Faktordefinitionen 3.1.9/3.1.10. Die Einheit "unit-dependent" im Encoding ist EKOWAI-Konvention, keine Normvorgabe.', verified_at=now() where id='e0179bf1-36b5-485b-adef-1b5de22ac06c' and verification_status not in ('verified_against_standard','corrected');
-- emission_factor
update public.fields set verification_status='verified_against_standard', verification_quote='Gegebenenfalls muss der Antragsteller des Projekts Treibhausgasemissions- oder -entzugsfaktoren auswählen oder entwickeln, morir: | - aus einer anerkannten Quelle stammen, | — für die betreffende Treibhausgasquelle oder - senke geeignet sind, | — zum Zeitpunkt derquantantn Bestimmung aktuell sind, | - der vorgesehenen Verwendung des Treibhausgasberichtes entsprechen. — printed p.35', verification_note='md-verified 2026-09-05 (§6.7, printed p.35) [VC] — Vorbehalt: die Anforderung steht unter "Gegebenenfalls" (bedingt); die Norm nennt weder Zahlenwerte noch eine Einheit fuer Emissionsfaktoren. Das Feld traegt im Encoding keine Einheit - siehe STAGED B-1.', verified_at=now() where id='ecba1225-735a-47c2-9f2e-04b6332eea9a' and verification_status not in ('verified_against_standard','corrected');
-- gwp
update public.fields set verification_status='verified_against_standard', verification_quote='Index auf der Grundlage der Strahlungseigenschaften von $\operatorname{THG}(3.1 .1)$, der den Strahlungsantrieb nach einer Impulsemission einer Masseeinheit eines gegebenen THG in der heutigen Atmosphäre über einen gewählten Zeitrahmen im Vergleich zum Strahlungsantrieb von Kohlendioxid (CO2) señorita | Sofern anwendbar, muss der Projektantragsteller die Menge jeder Art von Treibhausgas unter Anwendung des entsprechenden Treibhauspotentials in Einheiten von CO 2 e umrechnen. — printed pp.19, 36', verification_note='md-verified 2026-09-05 (§3.1.14 + §6.8, printed pp.19, 36) [VC] — Vorbehalt: die Norm nennt keinen GWP-Zahlenwert und keinen Zeithorizont; 3.1.14 Anm. 1 verweist auf den juengsten IPCC-Sachstandsbericht. GWP bleibt damit eine Auswahl des Ingenieurs (SR-2), kein standard_fixed-Wert.', verified_at=now() where id='64adbb96-d183-461e-ac7f-6f881b3c7717' and verification_status not in ('verified_against_standard','corrected');
-- ssr_emission_co2e
update public.fields set verification_status='verified_against_standard', verification_quote='Der Antragsteller des Projekts muss Kriterien und Verfahren oder Methoden zur quantumn Bestimmung von Treibhausgasemissionen und/ oder entzogenen Mengen für ausgewählte THGQSS (siehe 6.6) auswählen oder festlegen. | Wenn zusammengefasste Treibhausgasemissionen en CO2e anstelle einzelner Treibhausgasemissionen verwendet werden, muss der Grad der Zusammenführung mit den QSS angegeben werden, die Bedürfnisse des vorgesehenen Anwenders erfüllen undmitdenverwendeten Quantifizierungsverfahren konsistent sein. — printed pp.34-35', verification_note='md-verified 2026-09-05 (§6.7, printed pp.34-35) [VC]', verified_at=now() where id='9d41d3d5-1999-4c03-b02f-688f87cce01e' and verification_status not in ('verified_against_standard','corrected');
-- E_project
update public.fields set verification_status='verified_against_standard', verification_quote='a) jedes relevante Treibhausgas für jede(n) THG-QSS, die/der für das Projekt relevante ist; — printed p.35', verification_note='md-verified 2026-09-05 (§6.7 a), printed p.35) [VC] — Vorbehalt: 6.7 a) verlangt die getrennte Bestimmung je THG und je projektrelevantem QSS. Im Encoding summiert EQ-02 dasselbe Symbol wie EQ-03 - siehe STAGED B-2.', verified_at=now() where id='230588d5-cfcb-4d8d-83bf-d7ca9dc92e76' and verification_status not in ('verified_against_standard','corrected');
-- E_baseline
update public.fields set verification_status='verified_against_standard', verification_quote='b) jede(n) THG-QSS, die/der für das Bezugsszenario ist relevante. — printed p.35', verification_note='md-verified 2026-09-05 (§6.7 b), printed p.35) [VC] — Vorbehalt: 6.7 b) verlangt die getrennte Bestimmung fuer die bezugsszenariorelevanten QSS. Im Encoding summiert EQ-03 dasselbe Symbol wie EQ-02, so dass Projekt und Bezugsszenario rechnerisch nicht getrennt sind - siehe STAGED B-2.', verified_at=now() where id='4a507902-964a-47e8-a782-1c82149e6704' and verification_status not in ('verified_against_standard','corrected');
-- permanence_risk
update public.fields set verification_status='verified_against_standard', verification_quote='Der Antragsteller des Projekts muss Kriterien, Verfahren und/oder Methoden zur Abschätzung des Risikos, dass eine Reduktion der Treibhausgasemissionen oder Steigerung des Entzugs rückgängig gemacht wird (dh die Dauerhaftigkeit einer Reduktion der Treibhausgasemissionen oder Steigerung des Entzugs und fest). — printed p.35', verification_note='md-verified 2026-09-05 (§6.7, printed p.35) [VC] — Quellendefekt: der deutsche Satz bricht im Transkript UND im Quell-PDF ab ("... und fest)."); der vollstaendige Wortlaut ("festlegen und anwenden") ist nur in der spanischen Spalte lesbar. Verbatim uebernommen wie gedruckt.', verified_at=now() where id='21423fdc-d891-46d1-8a8d-a1a3abc352e1' and verification_status not in ('verified_against_standard','corrected');

-- ---- worksheet ISO-14064-2-07 ----
-- leakage
update public.fields set verification_status='verified_against_standard', verification_quote='Treibhausgasquelle (3.1.2), Treibhausgassenke (3.1.3) y Treibhausgasspeicher(3.1.4), die durch ein Proyecto THG(3.2.3) im Zusammenhang mit Änderungen der Marktnachfrage oder des Marktangebots zugehöriger Produkte oder Dienstleistungen oder durch physische Verschiebung beeinflusst werden | Anmerkung 2 zum Begriff: Die Verschiebung vonReduktion von Treibhausgasemissionen(3.1.7) ordenSteigerungen des Entzugs von Treibhausgasen(3.1.8) durch betroffene THG-QSS wird oft als Verlagerung bezeichnet. — printed p.18', verification_note='md-verified 2026-09-05 (§3.1.11, printed p.18) [VC] — Vorbehalt: die Norm nennt "Verlagerung" (leakage) nur in der Begriffsanmerkung 3.1.11 Anm. 2 und rechnet sie ueber die betroffenen THG-QSS ein; ein eigenes Leakage-Glied in der Differenzformel druckt sie NICHT. Das Feld wird von keiner Gleichung konsumiert - siehe STAGED B-3.', verified_at=now() where id='91a79718-8bd0-4b97-bc7a-50704dfec272' and verification_status not in ('verified_against_standard','corrected');
-- emission_reduction
update public.fields set verification_status='verified_against_standard', verification_quote='Reduktionen der Treibhausgasemissionen oder Steigerungen des Entzugs müssen als Differenz zwischen den Treibhausgasemissionen und/oder entzogenen Mengen von den THG-QSS, die für das Projekt sind relevante, und denen, die für das Bezugsszenario sind relevante, quantitativ bestimmt werden. — printed p.36', verification_note='md-verified 2026-09-05 (§6.8, printed p.36) [VC]', verified_at=now() where id='d2c403ea-e4a0-4e51-9f67-7e960c877605' and verification_status not in ('verified_against_standard','corrected');

-- ---- worksheet ISO-14064-2-08 ----
-- qm_procedures
update public.fields set verification_status='verified_against_standard', verification_quote='Der Antragsteller des Projekts muss Qualitätsmanagementverfahren zur Verwaltung von Daten und Informationen festlegen und anwenden, einschließlich der Beurteilung von Unsicherheiten, die für das Projekt und das Bezugsszenario sind relevante. — printed p.36', verification_note='md-verified 2026-09-05 (§6.9, printed p.36) [VC]', verified_at=now() where id='1b2e7617-23e7-48c8-8f77-683e4c3599f4' and verification_status not in ('verified_against_standard','corrected');
-- uncertainty_assessment
update public.fields set verification_status='verified_against_standard', verification_quote='muss Qualitätsmanagementverfahren zur Verwaltung von Daten und Informationen festlegen und anwenden, einschließlich der Beurteilung von Unsicherheiten | Der Antragsteller des Projekts sollte, soweit praktisch möglich, Unsicherheiten im Zusammenhang mit derquantantn Bestimmung von Reduktionen der Treibhausgasemissionen oder Steigerungen des Entzugs verringern. — printed p.36', verification_note='md-verified 2026-09-05 (§6.9, printed p.36) [VC]', verified_at=now() where id='c5cef3ba-4a76-4d32-b9bb-c0a2acb37b43' and verification_status not in ('verified_against_standard','corrected');

-- ---- worksheet ISO-14064-2-09 ----
-- monitoring_purpose
update public.fields set verification_status='verified_against_standard', verification_quote='Der Überwachungsplan muss Folgendes beinhalten, sofern zutreffend: | a) Zweck der Überwachung; — printed p.37', verification_note='md-verified 2026-09-05 (§6.10 a), printed p.37) [VC] — Vorbehalt: die gesamte Liste 6.10 a)-i) steht unter "sofern zutreffend" (bedingt). Siehe STAGED A-6.', verified_at=now() where id='4d749bfe-3529-4593-b5d9-c4ff2c4f4359' and verification_status not in ('verified_against_standard','corrected');
-- monitored_parameters
update public.fields set verification_status='verified_against_standard', verification_quote='b) Liste der gemessenen und überwachten Parámetro; — printed p.37', verification_note='md-verified 2026-09-05 (§6.10 b), printed p.37) [VC]', verified_at=now() where id='fb080a7d-84b3-4946-b00d-cc069ac12a83' and verification_status not in ('verified_against_standard','corrected');
-- reported_data_types
update public.fields set verification_status='verified_against_standard', verification_quote='c) im Bericht anzugebenden Datentypen und Informationen, einschließlich der Maßeinheiten; — printed p.37', verification_note='md-verified 2026-09-05 (§6.10 c), printed p.37) [VC]', verified_at=now() where id='176941ba-3ce9-4641-a058-8e88072fcdf7' and verification_status not in ('verified_against_standard','corrected');
-- data_origin
update public.fields set verification_status='verified_against_standard', verification_quote='d) Ursprung der Daten; — printed p.37', verification_note='md-verified 2026-09-05 (§6.10 d), printed p.37) [VC]', verified_at=now() where id='281e49f5-6450-4737-be23-c2eea2e6c714' and verification_status not in ('verified_against_standard','corrected');
-- monitoring_methodologies
update public.fields set verification_status='verified_against_standard', verification_quote='e) Überwachungsmethodiken, einschließlich Schätzungs-, Simulations-, Mess- und Kalkulationsansätzen und -unsicherheit; — printed p.37', verification_note='md-verified 2026-09-05 (§6.10 e), printed p.37) [VC]', verified_at=now() where id='b1d4b8fc-1831-420f-a11a-98a7a90b46bf' and verification_status not in ('verified_against_standard','corrected');
-- monitoring_frequency
update public.fields set verification_status='verified_against_standard', verification_quote='f) Überwachungshäufigkeit unter Berücksichtigung der Bedürfnisse der vorgesehenen Anwender; — printed p.37', verification_note='md-verified 2026-09-05 (§6.10 f), printed p.37) [VC]', verified_at=now() where id='be767df5-8c46-40aa-a11e-106b2f06fa38' and verification_status not in ('verified_against_standard','corrected');
-- monitoring_roles
update public.fields set verification_status='verified_against_standard', verification_quote='g) Rollen und Verantwortungsbereiche im Rahmen der Überwachung, einschließlich Verfahren zur Autorisierung, Genehmigung und Dokumentation von Änderungen der aufgezeichneten Daten; — printed p.37', verification_note='md-verified 2026-09-05 (§6.10 g), printed p.37) [VC]', verified_at=now() where id='7b4057c1-59c6-425f-9422-828dd2bf6df7' and verification_status not in ('verified_against_standard','corrected');
-- monitoring_controls
update public.fields set verification_status='verified_against_standard', verification_quote='h) Kontrollen, die interne Datenprüfungen für die Eingabe, die Umwandlung und die Ausgabe sowie Verfahren für Korrekturmaßnahmen umfassen; — printed p.37', verification_note='md-verified 2026-09-05 (§6.10 h), printed p.37) [VC]', verified_at=now() where id='7ca8f85d-6807-483d-a6fd-41a057339ba1' and verification_status not in ('verified_against_standard','corrected');
-- ghg_info_system
update public.fields set verification_status='verified_against_standard', verification_quote='i) Treibhausgas-Informationsmanagementsysteme, einschließlich der Lokalisierung, der Aufbewahrung gespeicherter Daten und des Datenmanagements, die Verfahren für die Übertragung von Daten zwischen verschiedenen System- oder Dokumentationsformen beinhalten. — printed p.37', verification_note='md-verified 2026-09-05 (§6.10 i), printed p.37) [VC]', verified_at=now() where id='87e11860-f4fe-489d-9973-497535621460' and verification_status not in ('verified_against_standard','corrected');
-- equipment_calibrated
update public.fields set verification_status='verified_against_standard', verification_quote='Wenn Messgeräte und Überwachungsgeräte verwendet werden, muss der Projektantragsteller sicherstellen, dass kalibrierte oder geprüfte Überwachungs- und Messgeräte zur Anwendung kommen und diese in angemessener Weise gewartet werden. — printed p.37', verification_note='md-verified 2026-09-05 (§6.10, printed p.37) [VC] — Vorbehalt: die Pflicht gilt nur "Wenn Messgeraete und Ueberwachungsgeraete verwendet werden".', verified_at=now() where id='a166153b-d9c7-4e2e-992d-2c4f3aa1f533' and verification_status not in ('verified_against_standard','corrected');

-- ---- worksheet ISO-14064-2-10 ----
-- conformity_documentation
update public.fields set verification_status='verified_against_standard', verification_quote='Der Projektantragsteller muss über eine Dokumentation verfügen, die die Konformität des Klimaschutzprojekts mit den Anforderungen in diesem Dokument nachweist. Diese Dokumentation muss den Verifizierungs- und Validierungserfordernissen (siehe 6.12) entsprechen. — printed p.38', verification_note='md-verified 2026-09-05 (§6.11, printed p.38) [VC]', verified_at=now() where id='9cbda25b-4827-45a1-bea6-a9a71c2b8891' and verification_status not in ('verified_against_standard','corrected');
-- verification_validation_iso14064_3
update public.fields set verification_status='verified_against_standard', verification_quote='Wenn der Projektantragsteller die Verifizierung und/ oder Validierung des Klimaschutzprojekts fordert, muss er sicherstellen, dass die Verifizierung oder Validierung den Grundsätzen und Anforderungen nach ISO 14064-3 entspricht. — printed p.38', verification_note='md-verified 2026-09-05 (§6.12, printed p.38) [VC] — Vorbehalt: die Pflicht gilt nur "Wenn der Projektantragsteller die Verifizierung und/oder Validierung ... fordert". Siehe STAGED A-7.', verified_at=now() where id='e4caa604-fa16-431b-9f1a-dd2c4d29cac8' and verification_status not in ('verified_against_standard','corrected');
-- ghg_report
update public.fields set verification_status='verified_against_standard', verification_quote='Der Antragsteller des Projekts muss einen Treibhausgasbericht erstellen und ihn den vorgesehenen Anwendern zur Verfügung stellen. | - die vorgesehene Anwendung und den vorgesehenen Anwender des Treibhausgasberichts angeben, | - über einen Aufbau und Inhalt verfügen, die den Bedürfnissen des vorgesehenen Anwenders entsprechen. — printed p.38', verification_note='md-verified 2026-09-05 (§6.13, printed p.38) [VC]', verified_at=now() where id='a4f9a065-ce55-4ad3-a273-6b77d5afe620' and verification_status not in ('verified_against_standard','corrected');
-- public_claim_content
update public.fields set verification_status='verified_against_standard', verification_quote='Wenn der Antragsteller des Projekts eine öffentliche Erklärung über Treibhausgase herausgibt, die die Übereinstimmung mit diesem Dokument beansprucht, muss er Folgendes veröffentlichen: | a) eine unabhängige Verifizierungs- oder Validierungserklärung von Dritten, die nach ISO 14064-3 erstellt wurde, oder | b) einen Treibhausgasbericht, der mindestens Folgendes enthält: | 1) den Namen des Antragstellers des Projekts; — printed pp.38-40', verification_note='md-verified 2026-09-05 (§6.13 b) 1)-15), printed pp.38-40) [VC] — Vorbehalt: die Norm gibt eine ALTERNATIVE a) ODER b); Punkt b) 15) ist in der deutschen Spalte leer gedruckt ("15).") - Inhalt nur in der spanischen Spalte. Siehe STAGED A-8/C-1.', verified_at=now() where id='b0ed9ed0-faf8-493f-b9f9-dd9943e02f9b' and verification_status not in ('verified_against_standard','corrected');


-- ---------------------------------------------------------------------------
-- B. EQUATIONS — 4 rows, QUOTE BACKFILL ONLY (verification_status untouched:
--    all 4 are already 'verified_against_standard' with a NULL verification_quote).
-- ---------------------------------------------------------------------------
-- EQ-01: ssr_emission_co2e = activity_data * emission_factor * gwp
update public.equations set verification_quote='Faktor, der die THG-Aktivitätsdaten mit der Emisión de THG(3.1.5) verbindet | Gegebenenfalls muss der Antragsteller des Projekts Treibhausgasemissions- oder -entzugsfaktoren auswählen oder entwickeln, morir: | Sofern anwendbar, muss der Projektantragsteller die Menge jeder Art von Treibhausgas unter Anwendung des entsprechenden Treibhauspotentials in Einheiten von CO 2 e umrechnen. — printed pp.17, 35, 36', verification_note=trim(both ' | ' from coalesce(nullif(verification_note,''),'') || ' | md-verified 2026-09-05 (§3.1.9 + §6.7 + §6.8, printed pp.17, 35, 36) [VC] — Die Norm DRUCKT KEINE FORMEL. Das Rechengeruest Aktivitaetsdaten x Faktor x GWP ist aus 3.1.9 (der Faktor verbindet Aktivitaetsdaten mit der Emission), 6.7 (Faktorauswahl) und 6.8 (GWP-Umrechnung in CO2e) abgeleitet - Synthese des Encodings, keine gedruckte Gleichung.'), verified_at=now() where id='1946f6f0-ee76-4d4f-a0a0-b7240196e734' and verification_quote is null;
-- EQ-02: E_project = SUM(ssr_emission_co2e)
update public.equations set verification_quote='Der Antragsteller des Projekts muss Kriterien und Verfahren oder Methoden zur quantumn Bestimmung von Treibhausgasemissionen und/ oder entzogenen Mengen für ausgewählte THGQSS (siehe 6.6) auswählen oder festlegen. | a) jedes relevante Treibhausgas für jede(n) THG-QSS, die/der für das Projekt relevante ist; — printed pp.34-35', verification_note=trim(both ' | ' from coalesce(nullif(verification_note,''),'') || ' | md-verified 2026-09-05 (§6.7 a), printed pp.34-35) [VC] — Die Norm druckt keine Summenformel; 6.7 a) fordert die getrennte quantitative Bestimmung je THG und je projektrelevantem QSS - die Aggregation ist Synthese des Encodings.'), verified_at=now() where id='a6559b54-578c-4ba8-b224-37345a1269fe' and verification_quote is null;
-- EQ-03: E_baseline = SUM(ssr_emission_co2e)
update public.equations set verification_quote='Der Antragsteller des Projekts muss Kriterien und Verfahren oder Methoden zur quantumn Bestimmung von Treibhausgasemissionen und/ oder entzogenen Mengen für ausgewählte THGQSS (siehe 6.6) auswählen oder festlegen. | b) jede(n) THG-QSS, die/der für das Bezugsszenario ist relevante. — printed pp.34-35', verification_note=trim(both ' | ' from coalesce(nullif(verification_note,''),'') || ' | md-verified 2026-09-05 (§6.7 b), printed pp.34-35) [VC] — Die Norm druckt keine Summenformel; 6.7 b) fordert die getrennte quantitative Bestimmung fuer jeden bezugsszenariorelevanten QSS. WARNUNG: EQ-02 und EQ-03 summieren im Encoding DASSELBE Symbol ssr_emission_co2e, es gibt kein Szenario-Unterscheidungsmerkmal - siehe STAGED B-2.'), verified_at=now() where id='a7d36f0e-158e-4ef9-8c48-918ead93fa85' and verification_quote is null;
-- EQ-04: emission_reduction = E_baseline - E_project
update public.equations set verification_quote='Reduktionen der Treibhausgasemissionen oder Steigerungen des Entzugs müssen als Differenz zwischen den Treibhausgasemissionen und/oder entzogenen Mengen von den THG-QSS, die für das Projekt sind relevante, und denen, die für das Bezugsszenario sind relevante, quantitativ bestimmt werden. — printed p.36', verification_note=trim(both ' | ' from coalesce(nullif(verification_note,''),'') || ' | md-verified 2026-09-05 (§6.8, printed p.36) [VC] — Die Differenzbildung ist gedruckt; die Vorzeichenrichtung (Bezugsszenario minus Projekt) folgt aus 3.1.7 "quantifizierte Reduzierung ... zwischen einem Bezugsscenario und dem Projekt".'), verified_at=now() where id='a7244a73-ebd4-481d-a867-5432768cdd70' and verification_quote is null;
