-- ISO-59020 - VA verification pack (PDF text layer, SR-3 ground truth)
-- Generated 2026-09-08. DO NOT ADD transaction-control statements: apply-pack.mjs supplies the
-- transaction itself and implements --dry-run by discarding it. An inline transaction terminator in
-- this file would silently turn a dry run into a real prod write.
--
-- DOCUMENT IDENTITY (both candidate PDFs were checked before any quoting)
--   Candidate A  ISO-59020-2024-Circular-Economy-Measuring-and-Assessing-Circularity.txt (91 pages)
--       = BS ISO 59020:2024, the BSI (UK) implementation of ISO 59020:2024. Cover: "BSI Standards
--         Publication", ISBN 978 0 539 13961 7, ICS 03.100.01; 13.020.20, "published under the
--         authority of the Standards Policy and Strategy Committee on 31 May 2024". English.
--         PUBLISHED STANDARD (a national adoption of the ISO text) - NOT a draft, NOT a Technical
--         Report, NOT a scoping report. Its ISO body is the identical ISO text, wrapped in a 2-page
--         BSI cover + national foreword at the front and 2 BSI back-matter pages at the end.
--   Candidate B  ISO-59020-Unlocked.txt (89 pages)
--       = ISO 59020:2024(en), "International Standard", First edition, 2024-05, prepared by
--         ISO/TC 323 Circular economy. Title in English and French; body English only.
--         PUBLISHED STANDARD (the ISO publication itself) - NOT a draft, NOT a Technical Report,
--         NOT a scoping report. No ballot/DIS/FDIS notice anywhere in the file.
--   CHOSEN AS AUTHORITATIVE: Candidate B, ISO-59020-Unlocked.txt. Reasons: (1) it is the ISO
--         publication itself, which is what prod records as the standard version ("2024 (First
--         edition 2024-05)") and what every clause reference in this encoding points at, rather
--         than a national adoption of it; (2) its printed pagination maps to text pages by one
--         constant offset with no national front/back matter interleaved. Cross-check: all 13
--         encode-time gate source_quotes and all 13 formula where-lists were searched in BOTH
--         extractions and found in both, identically - the two PDFs do not disagree anywhere this
--         pack relies on, so there is no PDF-vs-PDF finding to report.
--   NEITHER file is a draft. Every row note below therefore reads simply "[VA]" against the
--         PUBLISHED ISO 59020:2024 First edition; no draft caveat is needed or implied.
--
-- Grade: [VA] - the source is the rendered PDF's own text layer, which under SR-3 is ground truth.
--   Source PDFs: C:\Users\Ekowai\Desktop\Ciruclar economy, sustanability and water test\
--   Text layer : pdftotext -layout -enc UTF-8, form feeds preserved, 0 undecodable characters.
-- PAGE CONVENTION (running footers read to establish it):
--   text page N = PDF page N (form feeds preserved).
--   Front matter is roman: PDF p.2 = ii ... PDF p.7 = vii; PDF p.8 carries no folio.
--   Body is arabic with a constant offset: printed page = PDF page - 8
--     (PDF p.9 = printed p.1 ... PDF p.51 = printed p.43 ... PDF p.84 = printed p.76 Bibliography).
--   PDF p.89 is the trailing blank. Every quote carries its printed page ref ONCE, at its end.
-- Language: English (ISO 59020:2024(en); only the title page carries the French title).
--
-- SCOPE / MODALITY COUNT (whole text layer, counted mechanically):
--   Clauses 1-8 (normative body, printed pp.1-30) : shall = 3,  should = 84, "is required to" = 1
--   Annex A     (NORMATIVE,      printed pp.31-43): shall = 8,  should = 33, "is required to" = 1
--   Normative total                                : shall = 11, should = 117  -> ratio 1 : 10.6
--   Annexes B-H (INFORMATIVE,    printed pp.44-76): shall = 0,  should = 24
--   This is a predominantly recommendation-shaped standard. Only 11 sentences can carry a block
--   gate. The full "shall" inventory with printed pages is listed in the STAGED file, together with
--   the four printed "shall" obligations that no gate currently enforces.
--
-- Counts: 83 fields examined / 82 quoted / 1 exempt (app metadata) / 0 residue.
-- Equations: 13 in prod, 13 quoted now / 0 residue - every one of the 13 printed formulae
--   (A.1-A.13) is present in prod and every one was dimensionally checked (see each row note).
-- Gates: 37 read but NOT touched by this pack; findings are in iso-59020-STAGED-rulings.sql.
-- Rollback: rollback-iso-59020-md-verification-pack.sql

-- ============================================================================
-- A. FIELDS - 82 rows quoted verbatim from ISO 59020:2024
-- ============================================================================
-- ISO-59020-01.system_in_focus
update public.fields set verification_status='verified_against_standard', verification_quote='system in focus system that is defined by selected system boundaries (3.2.1) and is the subject of a circularity measurement (3.3.2) and a circularity assessment (3.3.3) — printed p.2', verification_note='VA-verified 2026-09-08 (§3.2.2, printed p.2) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='57e1ea03-8fe4-42af-bc4b-1599d6549a30' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-01.system_level
update public.fields set verification_status='verified_against_standard', verification_quote='Note 1 to entry: Four system levels are being used for measuring and assessing circularity performance (3.3.1): regional, interorganizational, organizational and product level. — printed p.2', verification_note='VA-verified 2026-09-08 (§3.2.2 Note 1, printed p.2 — the four enum values match the four printed levels exactly; §6.5.1-6.5.4 (printed p.13) describe each level) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='3e6204cb-91e9-4f06-b785-c262852fa500' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-02.application_purpose
update public.fields set verification_status='verified_against_standard', verification_quote='What is the purpose of the application (e.g. establishing a baseline, providing input for internal monitoring, internal comparative assertions, information for interested parties such as value chain actors, internal communication to users, experts involved)? — printed p.8', verification_note='VA-verified 2026-09-08 (§5.2, printed p.8 — the printed list is an "e.g." list, so the five encoded options are examples, not a closed printed set) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='6306d541-b669-4088-bfc9-0bc4c5e42376' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-02.circular_economy_principle
update public.fields set verification_status='verified_against_standard', verification_quote='In measuring and assessing the circularity performance of a system in focus, the circular economy principles of ISO 59004 should be considered. These are: | — systems thinking; — value creation; | — value sharing; — resource stewardship; — resource traceability; — ecosystem resilience. — printed pp.5-6', verification_note='VA-verified 2026-09-08 (§4.1, printed pp.5-6 — the six principles are owned by ISO 59004; "should be considered", so the field is correctly optional) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='37276dbb-bf8f-4d97-aa23-458f4e65ddc5' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-02.measurement_principle
update public.fields set verification_status='verified_against_standard', verification_quote='In addition to the general circular economy principles, the following specific measurement and assessment principles should be applied: | — ensure relevant boundaries (see 4.2.2); | — ensure meaningful outcomes (see 4.2.3); — printed p.6', verification_note='VA-verified 2026-09-08 (§4.2.1, printed p.6 — exactly two principles, matching the two enum values) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='11309c54-6458-416e-a7de-cabe0f959b4e' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-02.spatial_boundary
update public.fields set verification_status='verified_against_standard', verification_quote='The spatial scales reflect clear boundaries of the system in focus and its interconnection with the wider socio-economic and environmental other systems. — printed p.6', verification_note='VA-verified 2026-09-08 (§4.2.2.2, printed p.6) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='29e6d9cd-041b-4041-bc6a-969b6b094f09' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-02.temporal_boundary
update public.fields set verification_status='verified_against_standard', verification_quote='The time scale chosen encompasses the entire life cycle of the system from creation through to final end of life and disposal. — printed p.6', verification_note='VA-verified 2026-09-08 (§4.2.2.3, printed p.6) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='a3b2a824-4c35-4d01-87ca-2b381cfe2d77' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-02.framework_stage
update public.fields set verification_status='verified_against_standard', verification_quote='The framework for measuring and assessing circularity performance consists of several interrelated stages which can be repeated as required. — printed p.7', verification_note='VA-verified 2026-09-08 (§5.1, printed p.7 — the three enum values are the three printed stage headings §5.3 Stage 1: Boundary setting, §5.4 Stage 2: Circularity measurement and data acquisition, §5.5 Stage 3: Circularity assessment and reporting (printed pp.8-9)) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='3495d971-cbd6-4b1e-baf1-aa70f9d05df4' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-02.all_stages_documented
update public.fields set verification_status='verified_against_standard', verification_quote='To enable interpretation, transparency and verification of results, it is necessary that all stages are properly documented. — printed p.7', verification_note='VA-verified 2026-09-08 (§5.1, printed p.7 — the printed modal is "it is necessary that", which ISO/IEC Directives Part 2 treats as equivalent to "shall"; the encoded description says "shall", which is the same obligation. Gate CR-004 is only a warn on it — see the STAGED file) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='18c47cd7-86c7-4576-8425-409f6a2d324c' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-03.internal_or_external_use
update public.fields set verification_status='verified_against_standard', verification_quote='— defining whether the results are to be used for internal monitoring or external communication; — printed p.10', verification_note='VA-verified 2026-09-08 (§6.2, printed p.10 — the two enum values are the two printed alternatives) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='0f748505-e3ec-49c0-b025-019f79daf022' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-03.system_boundary
update public.fields set verification_status='verified_against_standard', verification_quote='system boundary boundary representing physical, process, temporal and geographical limits of what is included and what is not included in an assessment — printed p.2', verification_note='VA-verified 2026-09-08 (§3.2.1, printed p.2) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='54284e64-1e32-4340-811a-2709274fffd2' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-03.circular_goal
update public.fields set verification_status='verified_against_standard', verification_quote='Which circular goals (e.g. increasing reused content by X %, increasing recycled material derived from outflow to Y %) are applicable to the measurement? | — defining circular goals to be measured; — printed pp.7/9', verification_note='VA-verified 2026-09-08 (§5.2 (printed p.7) / §6.2 (printed p.9)) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='60c70308-04cd-411e-a1e4-1bdb0daca974' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-03.circularity_aspect
update public.fields set verification_status='verified_against_standard', verification_quote='circularity aspect element of an organization''s activities or solutions that interacts with the circular economy (3.1.1) | EXAMPLE Durability, recyclability, reusability, repairability, recoverability. — printed p.2', verification_note='VA-verified 2026-09-08 (§3.1.4, printed p.2 — the five enum values are the printed EXAMPLE list, which is an open example set, not a closed printed enumeration; the field is correctly optional) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='a021982d-339f-41b6-939c-5139e7dfa14d' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-03.data_quality_requirement
update public.fields set verification_status='verified_against_standard', verification_quote='— defining data quality requirements; | EXAMPLE 2 X % of all measured data for resource inflows and resource outflows (by mass) must be primary. — printed p.10', verification_note='VA-verified 2026-09-08 (§6.2, printed p.10) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='e8a6a59f-ea98-4cd5-ae2e-8ef73414c2ed' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-03.interested_parties
update public.fields set verification_status='verified_against_standard', verification_quote='— defining the interested parties involved (e.g. the users or practitioners carrying out or using the measurement and assessment), the target audience (e.g. to whom the results of the assessment will be communicated, internal and/or external), other interested parties (e.g. related to acquiring the data and assessing the impacts) and organizations outside the system in focus that can be impacted (e.g. companies within the value chain); — printed p.10', verification_note='VA-verified 2026-09-08 (§6.2, printed p.10) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='def0c321-4f00-4f5f-9b47-e76992690db7' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-03.all_flows_quantified
update public.fields set verification_status='verified_against_standard', verification_quote='All resource inflows and outflows of the system in focus shall be quantified, when applicable. — printed p.6', verification_note='VA-verified 2026-09-08 (§4.2.3, printed p.6 — one of only 11 "shall" sentences in the normative part; note the printed scope predicate "when applicable", which gate CR-005 does not carry (see the STAGED file)) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='58296820-400e-4b1d-b894-3dbb77841ccc' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-03.resource_balance_applied
update public.fields set verification_status='verified_against_standard', verification_quote='The boundaries should be set to allow a resource balance to be achieved such that resource inflow is equal to resource outflow. The 100 % formulae on resource inflow and resource outflow should be applied, as explained in Annex A. — printed p.12', verification_note='VA-verified 2026-09-08 (§6.3, printed p.12 (NOT p.11 as the encoded gate quote says) — the printed modal is "should" twice, i.e. a recommendation, yet gate CR-006 blocks on it; see the STAGED file) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='9216567b-d176-49d7-88ff-7f4e82994b14' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-03.measurement_period
update public.fields set verification_status='verified_against_standard', verification_quote='The organization carrying out a circularity measurement and assessment should consider the time period over which data are measured or collected. | If possible, data should be collected over the same period or normalized where this is not possible. — printed pp.12-13', verification_note='VA-verified 2026-09-08 (§6.4.3, printed pp.12-13) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='5657f6f9-6bee-45e4-a0e5-e58d9d74e31a' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-03.temporal_boundary_shortened
update public.fields set verification_status='verified_against_standard', verification_quote='Shorter timescales that do not consider an entire life cycle should be documented in the assessment report. — printed p.12', verification_note='VA-verified 2026-09-08 (§6.4.2, printed p.12) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='b32aebce-31b4-4e15-abb0-01c55a9c48f4' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-03.periodic_monitoring
update public.fields set verification_status='verified_against_standard', verification_quote='The organization can decide to do a periodic measurement of the circularity performance of the system in focus and to assess its impacts to monitor progress. — printed p.13', verification_note='VA-verified 2026-09-08 (§6.4.4, printed p.13 — printed modal is "can", so the field is correctly optional) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='f9664ddc-894b-4ada-bcbf-407a16c19acd' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-04.indicator_category
update public.fields set verification_status='verified_against_standard', verification_quote='The circularity indicators are organized into categories such that material, water and energy are treated separately. This separation is because water and energy both have unique aspects that should be measured to determine the circularity performance. — printed p.17', verification_note='VA-verified 2026-09-08 (§7.3.1, printed p.17 — the five enum values are the five indicator-category rows of Table 3 (printed pp.17-18): Resource Inflows, Resource outflows, Energy, Water, Economic) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='eb66e6b9-c6b3-427e-b246-7be5cd1b6330' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-04.indicator_type
update public.fields set verification_status='verified_against_standard', verification_quote='quantitative indicator measure based on numeric data that can be used for mathematical calculations and statistical analysis | qualitative indicator measure derived from a checklist or descriptive scale without any quantification — printed p.3', verification_note='VA-verified 2026-09-08 (§3.3.5 / §3.3.6, printed p.3) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='48984865-60d4-4f5c-8c89-391b4053e3f1' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-04.selected_core_indicator
update public.fields set verification_status='verified_against_standard', verification_quote='Table 3 lists the name and a brief description of each core circularity indicator along with a reference to the subclause in Annex A that provides additional specifications or recommendations for measurement and calculation formulae. — printed p.16', verification_note='VA-verified 2026-09-08 (§7.3.1, printed p.16; the option list is Table 3 itself, printed pp.17-18 (A.2.2, A.2.3, A.2.4, A.3.2, A.3.3, A.3.4, A.3.5, A.4.2, A.5.2, A.5.3, A.5.4, A.6.2, A.6.3)) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='6f2f9002-8a87-4b01-90ae-2fa94c612ad2' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-04.mandatory_core_indicators_included
update public.fields set verification_status='verified_against_standard', verification_quote='To achieve a balanced measurement, the measurement shall include the mandatory core circularity indicators when measuring the resource inflows and outflows (see 7.3, Table 3, and Clauses A.2 and A.3). — printed p.8', verification_note='VA-verified 2026-09-08 (§5.4, printed p.8 — a printed "shall"; Table 3 (printed pp.17-18) marks A.2.2/A.2.3/A.2.4 and A.3.3/A.3.4/A.3.5 Mandatory and every other core indicator Optional, which is exactly how is_required is set on this standard) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='fd124ae5-535d-4a17-a4d4-99471189277e' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-04.indicator_not_applicable_justified
update public.fields set verification_status='verified_against_standard', verification_quote='If a core circularity indicator is not applicable, the organization should explain why and can count the indicator value as zero. — printed p.17', verification_note='VA-verified 2026-09-08 (§7.3.1, printed p.17) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='0002e3d0-fa39-4ee4-ad1d-cb3f020b44d5' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-04.additional_indicator
update public.fields set verification_status='verified_against_standard', verification_quote='The core circularity indicators can be supplemented by the additional indicators or recommendations addressed in Annex B. — printed p.18', verification_note='VA-verified 2026-09-08 (§7.3.2, printed p.18 — Annex B is INFORMATIVE, and this field is correctly optional; no required flag on this standard rests on an informative annex) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='c551ab32-8594-49a6-ae1a-95710b07d18f' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-04.aggregation_method
update public.fields set verification_status='verified_against_standard', verification_quote='The organization should ensure reliable aggregation in terms of the system boundaries, the indicators used, the source of data, the estimations and assumptions made. — printed p.19', verification_note='VA-verified 2026-09-08 (§7.5, printed p.19; further guidance is in Annex G, which is INFORMATIVE) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='871afd8f-0091-4ea8-996f-7fdf8d06aaa9' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-05.mTI_X
update public.fields set verification_status='verified_against_standard', verification_quote='mTI(X) is the mass of total input material of an inflow (X), in kg or other mass unit. — printed p.33', verification_note='VA-verified 2026-09-08 (§A.2.2, where-list of Formula (A.1), printed p.33 — unit kg matches the printed "in kg or other mass unit") [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='8a6baf16-ff6c-4099-af79-b9a6a180b84a' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-05.mREUI_X
update public.fields set verification_status='verified_against_standard', verification_quote='mREUI(X) is the mass of reused components and products of an inflow (X), in kg or other mass unit; — printed p.33', verification_note='VA-verified 2026-09-08 (§A.2.2, where-list of Formula (A.1), printed p.33) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='361b917e-acdf-4048-8073-4283dd724fc6' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-05.pct_REUI_X
update public.fields set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.1): | %REUI(X) is the average reused content of an inflow (X), in %; — printed p.33', verification_note='VA-verified 2026-09-08 (§A.2.2 (Formula A.1), printed p.33 — Table 3 marks A.2.2 Mandatory, so is_required=true is correct) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='5c3d9c67-df9f-4b84-b451-97cfe23c7588' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-05.mRECI_X
update public.fields set verification_status='verified_against_standard', verification_quote='A material qualifies towards recycled content if it meets the specification of recycled content in ISO 14021. | mRECI(X) is the mass of recycled material of an inflow (X), in kg or other mass unit; — printed p.33', verification_note='VA-verified 2026-09-08 (§A.2.3, printed p.33 — the qualifying test defers to ISO 14021, which is not in the library, so the qualification test itself is NR) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='5673c713-d690-4b97-9e3c-74ff5dadde0f' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-05.pct_RECI_X
update public.fields set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.2): | %RECI(X) is the average recycled content of an inflow (X), in %; — printed p.33', verification_note='VA-verified 2026-09-08 (§A.2.3 (Formula A.2), printed p.33 — Table 3 marks A.2.3 Mandatory) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='d01fbfd9-a9d3-4219-8dd5-aac89b9fef77' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-05.mRENI_X
update public.fields set verification_status='verified_against_standard', verification_quote='For the purpose of calculating this indicator, renewable material is virgin biomass that fulfils the following criteria: | mRENI(X) is the mass of renewable material of an inflow (X), in kg or other mass unit; — printed pp.33-34', verification_note='VA-verified 2026-09-08 (§A.2.4, printed pp.33-34 — the three printed renewable criteria (replenishment rate, sourcing compatible with sustainable development, regenerative practices) are attested nowhere in the encoding; see the STAGED file) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='c54cc28e-e2f7-4923-bc74-f3d2998b0827' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-05.pct_RENI_X
update public.fields set verification_status='verified_against_standard', verification_quote='PRENI(X) is the average renewable content of an inflow (X), in %; — printed p.34', verification_note='VA-verified 2026-09-08 (§A.2.4 (Formula A.3), printed p.34 — Table 3 marks A.2.4 Mandatory) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='4610da06-eb94-4a7e-a7ff-f5e3c46821f9' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-05.pct_linear_inflow
update public.fields set verification_status='verified_against_standard', verification_quote='These four types of content are intended to be mutually exclusive and add up to represent 100 % of the resource inflow (see Figure A.1). The first three types (recycled, reused and virgin, renewable content) are considered as circular; whereas the fourth type (virgin, non-renewable content) is the remaining portion that is from a non-circular source. The non-circular (linear) inflow can be calculated by subtracting the circular inflows from 100 %. — printed p.31', verification_note='VA-verified 2026-09-08 (§A.2.1, printed p.31 — this is the printed basis of the 100 % balance gate CR-014) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='df15b536-271b-40e0-aa38-b605461c2ce6' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-06.tLP_X
update public.fields set verification_status='verified_against_standard', verification_quote='tLP(X) is the lifetime of a product or material (X), in, for example, years; — printed p.36', verification_note='VA-verified 2026-09-08 (§A.3.2, where-list of Formula (A.4), printed p.36 — the printed unit is "in, for example, years", i.e. an example, not a fixed unit; the encoded unit "a" narrows it (STAGED)) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='3791f8e5-822f-4e38-87ee-9dff715b2ed0' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-06.tIALP_X
update public.fields set verification_status='verified_against_standard', verification_quote='tIALP(X) is the industry average lifetime of a product or material (X), in, for example, years; — printed p.36', verification_note='VA-verified 2026-09-08 (§A.3.2, where-list of Formula (A.4), printed p.36) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='e58b4452-d163-49a1-a8af-315e476f5318' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-06.RLP_X
update public.fields set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.4): | RLP(X) is the lifetime ratio of a product or material (X); it is dimensionless; — printed p.36', verification_note='VA-verified 2026-09-08 (§A.3.2 (Formula A.4), printed p.36 — Table 3 marks A.3.2 Optional and §A.3.1 (printed p.35) says it "is not mandatory to calculate", so is_required=false is correct) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='cb8d3a22-a5f4-4c29-832d-a5232e123a78' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-06.mTO_X
update public.fields set verification_status='verified_against_standard', verification_quote='mTO(X) is the total mass of outflow (X), in kg or other mass unit. — printed p.37', verification_note='VA-verified 2026-09-08 (§A.3.3, where-list of Formula (A.5), printed p.37) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='58844536-3fa7-4c59-90ac-ab76e8e483c9' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-06.mREUO_X
update public.fields set verification_status='verified_against_standard', verification_quote='mREUO(X) is the mass of outflow (X) that is reused, in kg or other mass unit; — printed p.37', verification_note='VA-verified 2026-09-08 (§A.3.3, where-list of Formula (A.5), printed p.37) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='1bc16bdc-4aa1-4763-87c2-87c89ffa686a' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-06.pct_REUO_X
update public.fields set verification_status='verified_against_standard', verification_quote='PREUO(X) is the actual reused products and components derived from outflow (X), in %; — printed p.37', verification_note='VA-verified 2026-09-08 (§A.3.3 (Formula A.5), printed p.37 — Table 3 marks A.3.3 Mandatory) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='91b4d023-4977-4483-8f93-bc68c0e214a3' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-06.mRECO_X
update public.fields set verification_status='verified_against_standard', verification_quote='If traceable recyclability data are not available for a specific resource outflow, 0 % should be recorded. | mRECO(X) is the mass of recycled material derived from outflow (X), in kg or other mass unit; — printed p.37', verification_note='VA-verified 2026-09-08 (§A.3.4, printed p.37 — the encoded description "If no traceable data, 0%" is the printed rule) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='b9a96955-5418-4ecc-a3cd-93dffaf1ba6f' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-06.pct_RECO_X
update public.fields set verification_status='verified_against_standard', verification_quote='PRECO(X) is the per cent actual recycled material derived from outflow (X), in %; — printed p.37', verification_note='VA-verified 2026-09-08 (§A.3.4 (Formula A.6), printed p.37 — Table 3 marks A.3.4 Mandatory) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='38577662-77b2-4924-906d-4df0dd354830' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-06.mRENO_X
update public.fields set verification_status='verified_against_standard', verification_quote='mRENO(X) is the mass of outflow (X) that is renewable recirculation, in kg or other mass unit; — printed p.38', verification_note='VA-verified 2026-09-08 (§A.3.5, where-list of Formula (A.7), printed p.38) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='5a336f08-70ba-407e-a4da-78c5e6c13821' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-06.pct_RENO_X
update public.fields set verification_status='verified_against_standard', verification_quote='PRENO(X) is the per cent actual recirculation of outflow (X) in the biological cycle, in %; — printed p.38', verification_note='VA-verified 2026-09-08 (§A.3.5 (Formula A.7), printed p.38 — Table 3 marks A.3.5 Mandatory) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='e58dc111-a6b1-4ac7-888b-6ea00319d5c3' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-06.pct_linear_outflow
update public.fields set verification_status='verified_against_standard', verification_quote='The remaining outflows are considered as linear and do not count towards circularity. | The sum of the circular outflows and the remaining non-circular outflows represent 100 % of the resource outflows from the system in focus, see Figure A.2. — printed p.34', verification_note='VA-verified 2026-09-08 (§A.3.1, printed p.34 — printed basis of the 100 % outflow balance gate CR-019. The sentence "The linear (non-circular) outflow can be calculated by subtracting the circular outflows from 100 %." follows immediately on the same page and is broken across two printed lines at "non-/circular", so the adjacent unbroken sentence is quoted instead) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='b319e908-1e4f-45e0-840a-354d1cc05825' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.EIRENE_X
update public.fields set verification_status='verified_against_standard', verification_quote='EIRENE(X) is the renewable energy (X) inflow, in MJ (or in kWh); — printed p.39', verification_note='VA-verified 2026-09-08 (§A.4.2, where-list of Formula (A.8), printed p.39) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='a5d851a4-5b62-40a7-bf15-1f89298500ff' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.EORENE_X
update public.fields set verification_status='verified_against_standard', verification_quote='EORENE(X) is the renewable energy (X) outflow, in MJ (or in kWh); — printed p.39', verification_note='VA-verified 2026-09-08 (§A.4.2, where-list of Formula (A.8), printed p.39) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='01e03f07-9399-46bb-84a5-e60795fc8e76' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.EITE_X
update public.fields set verification_status='verified_against_standard', verification_quote='EITE(X) is the total energy (X) inflow, in MJ (or in kWh); — printed p.39', verification_note='VA-verified 2026-09-08 (§A.4.2, where-list of Formula (A.8), printed p.39) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='581eace3-9f38-4b0d-9b55-999ea2602ff3' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.EOTE_X
update public.fields set verification_status='verified_against_standard', verification_quote='EOTE(X) is the total energy (X) outflow, in MJ (or in kWh). — printed p.39', verification_note='VA-verified 2026-09-08 (§A.4.2, where-list of Formula (A.8), printed p.39) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='523fb8dc-be76-4985-b82d-30987a22c3c1' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.pct_ECONRE_X
update public.fields set verification_status='verified_against_standard', verification_quote='PECONRE(X) is the average energy (X) consumed that is renewable energy, in %; — printed p.39', verification_note='VA-verified 2026-09-08 (§A.4.2 (Formula A.8), printed p.39 — Table 3 marks A.4.2 Optional) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='66ddbe71-60e4-413b-ab77-d9737b8f96fe' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.energy_unit_common
update public.fields set verification_status='verified_against_standard', verification_quote='A common suitable measurement unit (e.g. MJ, kWh) shall be selected for the quantification of all relevant energies (e.g. thermal, electrical) that are involved in the measurement. — printed p.39', verification_note='VA-verified 2026-09-08 (§A.4.2, printed p.39 — a printed "shall", but scoped to the energy indicators, which Table 3 marks Optional, so is_required=false is the correctly scoped encoding. The printed list is "e.g. MJ, kWh", i.e. open; the encoded enum closes it to exactly MJ/kWh (STAGED)) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='3bf241ae-788d-4de7-9374-0b05b10bd49f' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.VCIW
update public.fields set verification_status='verified_against_standard', verification_quote='VCIW is the volume of water inflow from circular sources, in m3/year; — printed p.41', verification_note='VA-verified 2026-09-08 (§A.5.2, where-list of Formula (A.9), printed p.41 — printed unit m3/year matches the encoded m3/a) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='9f7a4e65-ce0c-4697-a64e-30e5c31a76ca' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.VAIW
update public.fields set verification_status='verified_against_standard', verification_quote='VAIW is the volume of water inflow from all sources, in m3/year. — printed p.41', verification_note='VA-verified 2026-09-08 (§A.5.2 / §A.5.3, where-lists of Formulae (A.9) and (A.10), printed p.41) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='bac59a13-aa8e-455e-ac53-c4ba2dc654a4' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.pct_CWW
update public.fields set verification_status='verified_against_standard', verification_quote='PCWW is the average water withdrawal from circular sources, in %; — printed p.41', verification_note='VA-verified 2026-09-08 (§A.5.2 (Formula A.9), printed p.41 — Table 3 marks A.5.2 Optional) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='b367539d-4fd2-49db-94e1-7df044c8b541' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.VCDW
update public.fields set verification_status='verified_against_standard', verification_quote='VCDW is the volume of circular water discharges, in m3/year; — printed p.41', verification_note='VA-verified 2026-09-08 (§A.5.3, where-list of Formula (A.10), printed p.41) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='ca386188-db5e-493e-a458-22ffe8095bd7' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.pct_CDW
update public.fields set verification_status='verified_against_standard', verification_quote='PCDW is the average circular water discharges, in %; — printed p.41', verification_note='VA-verified 2026-09-08 (§A.5.3 (Formula A.10), printed p.41 — the printed denominator of A.10 is VAIW (water inflow from all sources), which matches Table 3''s description "Per cent (by volume) of total water withdrawn that is discharged in accordance with circularity principles") [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='3a71e8aa-4148-4871-84ba-3f0a2d212b55' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.VTWU
update public.fields set verification_status='verified_against_standard', verification_quote='is the total water consumed in all processes and operations within the facility, in m3 per year; typically, the water used in a process or operation is the amount of water entering the process; — printed p.42', verification_note='VA-verified 2026-09-08 (§A.5.4, where-list of Formula (A.11), printed p.42 — in the printed layout the symbol column (RWRR, VTWU, VTWW) is set beside the definition column, so the symbol token does not sit inline with its own definition; the quote is the definition run for VTWU) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='00963588-9de8-4ee5-9cde-6f9f2290070d' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.VTWW
update public.fields set verification_status='verified_against_standard', verification_quote='is the total water withdrawn from all external sources, in m3 per year; an external source is one from a local supply and not provided by internal processes or operations. — printed p.42', verification_note='VA-verified 2026-09-08 (§A.5.4, where-list of Formula (A.11), printed p.42 — same two-column layout note as VTWU) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='e01f10ce-cf02-4dad-96ed-cb803179eeb2' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.RWRR
update public.fields set verification_status='verified_against_standard', verification_quote='is the ratio (on-site or internal) of water reuse or recirculation; it is dimensionless and | represents the amount of water recycled or reused within the facility after it has been | contained and adequately treated for reuse, as needed; — printed p.42', verification_note='VA-verified 2026-09-08 (§A.5.4 (Formula A.11), printed p.42 — Table 3 marks A.5.4 Optional. The three fragments are the three printed lines of the RWRR definition, which the two-column layout interleaves with the VTWU/VTWW symbol tokens) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='77761a72-44dd-4427-a607-3c517a13017f' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.C
update public.fields set verification_status='verified_against_standard', verification_quote='C is the total revenue generated in monetary units (e.g. $, €); — printed p.43', verification_note='VA-verified 2026-09-08 (§A.6.2, where-list of Formula (A.12), printed p.43 — the printed unit is "monetary units (e.g. $, €)"; the encoded unit EUR picks one of the printed examples (STAGED)) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='92e932f7-e959-4238-8dad-5bb2cb7e1fb1' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.D
update public.fields set verification_status='verified_against_standard', verification_quote='D is the total mass of all linear resource inflows, in kg or other mass unit. — printed p.43', verification_note='VA-verified 2026-09-08 (§A.6.2, where-list of Formula (A.12), printed p.43) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='539327cc-9715-49cf-a5ca-8cf0337f74c4' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.RMP
update public.fields set verification_status='verified_against_standard', verification_quote='RMP is the MP ratio, in monetary units per kg (e.g. $/kg, €/kg); — printed p.43', verification_note='VA-verified 2026-09-08 (§A.6.2 (Formula A.12), printed p.43 — Table 3 marks A.6.2 Optional) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='e5686712-827e-431d-bf5b-5812ca67cf73' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.E
update public.fields set verification_status='verified_against_standard', verification_quote='E is the rate of variation of resource inflow consumption (mass) per unit time; it is dimensionless; — printed p.43', verification_note='VA-verified 2026-09-08 (§A.6.3, where-list of Formula (A.13), printed p.43) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='78e93697-83aa-41ca-8f33-c37038d0ecf2' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.F
update public.fields set verification_status='verified_against_standard', verification_quote='F is the rate of variation of GDP per unit time; it is dimensionless. — printed p.43', verification_note='VA-verified 2026-09-08 (§A.6.3, where-list of Formula (A.13), printed p.43) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='ce2ec69f-15fa-498a-9533-452bb3d190bc' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-07.IRII
update public.fields set verification_status='verified_against_standard', verification_quote='IRII is the RII, expressed as a ratio; — printed p.43', verification_note='VA-verified 2026-09-08 (§A.6.3 (Formula A.13), printed p.43 — Table 3 marks A.6.3 Optional) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='9839e32d-a1b7-4415-ab0d-965af1a12136' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-08.system_breakdown_done
update public.fields set verification_status='verified_against_standard', verification_quote='To enable a systematic data acquisition, and to provide transparency to the acquired data, it is recommended that the system in focus is subdivided into its elementary components for which data acquisition can be practically executed, such as the identification of data sources for general inflows and outflows. — printed p.20', verification_note='VA-verified 2026-09-08 (§7.6.1.2 Step A, printed p.20 — printed modal is "it is recommended that", i.e. a recommendation; gate CR-026 is correctly a warn) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='e1a20088-49c5-4948-8ca6-c4fd7c6a7284' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-08.data_category
update public.fields set verification_status='verified_against_standard', verification_quote='— be categorized as foreground or background, primary or secondary, specific or generic (secondary and generic data should be conservatively applied and not overstate the circularity); — printed p.21', verification_note='VA-verified 2026-09-08 (§7.6.2, printed p.21 — the six enum values are the three printed dichotomies) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='0224960d-b232-4177-a193-b068fea48424' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-08.primary_data_preference
update public.fields set verification_status='verified_against_standard', verification_quote='— strive towards being specific data based on primary data; — printed p.21', verification_note='VA-verified 2026-09-08 (§7.6.2, printed p.21 — the lead-in on the same page is "Acquired data should meet the following requirements:", so this is a recommendation; gate CR-028 is correctly a warn) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='4639aebc-0bf7-4621-af5a-e2b3236bb248' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-08.data_completeness_checked
update public.fields set verification_status='verified_against_standard', verification_quote='Checking whether the information is complete includes, but is not limited to, checking whether for each acquired data item and each selected indicator: | — all data requirements presented under 7.6.2 are met; — printed p.21', verification_note='VA-verified 2026-09-08 (§7.6.1.6 Step E, printed p.21) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='872c83ff-e004-4285-acde-b9322bac110f' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-08.data_normalized
update public.fields set verification_status='verified_against_standard', verification_quote='Data acquired should be balanced and normalized to the common denominator for the system in focus, such as "per provided function", "per product lifetime" or "per yearly production". All these transformations should be documented. — printed p.21', verification_note='VA-verified 2026-09-08 (§7.6.1.5 Step D, printed p.21) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='d02d2034-5012-447b-b43e-fa4783a261fd' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-08.data_traceability
update public.fields set verification_status='verified_against_standard', verification_quote='data traceability ability of data to be tracked to original and verifiable sources | Note 2 to entry: ISO 14033:2019 provides a framework both for how to achieve data traceability as well as how to audit and verify the level to which data traceability has been achieved. — printed p.5', verification_note='VA-verified 2026-09-08 (§3.3.16, printed p.5 — the framework itself lives in ISO 14033, which is not in the library, so the "how" is NR; the definition and the pointer are VA) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='82123c62-3f11-438d-8252-0d4c0192f76f' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-08.documentation_complete
update public.fields set verification_status='verified_against_standard', verification_quote='Figure 9 summarizes the information items that should be documented to enable an end user to evaluate the data quality of the result of a measurement or assessment of circularity. — printed p.22', verification_note='VA-verified 2026-09-08 (§7.7, printed p.22; the four documentation groups a) context and system in focus, b) data sources, c) modelling choices, d) administrative information run printed pp.22-23) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='ee8488f7-7859-4d28-9d89-758462454117' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-08.allocation_method
update public.fields set verification_status='verified_against_standard', verification_quote='allocation partitioning of the inflows and outflows of a process or a system between the system in focus (3.2.2) and one or more other systems | 1) allocation methods used to separate the system in focus from the wider system, cut-off limits and any other choices relevant to setting system boundaries; — printed pp.4/23', verification_note='VA-verified 2026-09-08 (§3.3.15 (printed p.4) / §7.7 c) 1) (printed p.23)) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='a690bee8-bdc2-4b36-872b-bfd9e95ec431' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-09.circularity_performance_statement
update public.fields set verification_status='verified_against_standard', verification_quote='The circularity assessment should result in a comprehensive statement about the circularity performance of the system in focus. — printed p.9', verification_note='VA-verified 2026-09-08 (§5.5, printed p.9) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='a1ea2b50-8d16-41ba-b52e-e635c71cbb85' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-09.criteria_review_done
update public.fields set verification_status='verified_against_standard', verification_quote='In conducting the assessment, the organization is required to review the application of: | a) the circular economy principles in ISO 59004; | b) the principles of measuring and assessing circularity in Clause 4; | c) the core circularity indicators of Clause 7, Table 3 and guidance from Annex A. — printed p.23', verification_note='VA-verified 2026-09-08 (§8.1, printed p.23 — "is required to" is a shall-equivalent under ISO/IEC Directives Part 2, so the block severity of gate CR-031 is defensible even though the word "shall" does not appear) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='e5ec7082-d791-450a-a2bc-631b8ae5d755' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-09.complementary_method
update public.fields set verification_status='verified_against_standard', verification_quote='complementary method method, approach or standard that is used together with circularity measurement (3.3.2) to provide a circularity assessment (3.3.3) — printed p.3', verification_note='VA-verified 2026-09-08 (§3.3.7, printed p.3; examples are in Annex C, which is INFORMATIVE, and the field is correctly optional) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='a9ea4f4a-0281-4021-80af-3dc7b3267ef9' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-09.value_impact_assessed
update public.fields set verification_status='verified_against_standard', verification_quote='While assessing the circularity performance, a broad perspective of sustainability should be considered to maximize the contribution to sustainable development. — printed p.25', verification_note='VA-verified 2026-09-08 (§8.4.1, printed p.25) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='86c433ec-8cf8-46ee-82b3-bd64b548b8ee' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-09.interested_parties_consulted
update public.fields set verification_status='verified_against_standard', verification_quote='In consulting interested parties, users and target audiences, the following needs and requirements should be reviewed: — printed p.29', verification_note='VA-verified 2026-09-08 (§8.5 Step 3, printed p.29) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='cc769ef2-1d50-44b4-b5ed-1de679fca71a' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-09.report_transparency
update public.fields set verification_status='verified_against_standard', verification_quote='In documenting the circularity performance outcome of the core circularity indicators of Annex A and other indicators (see Annex B), the organization should include the best available information to summarize all resource inflows and outflows including non-circular flows of the system in focus. — printed p.29', verification_note='VA-verified 2026-09-08 (§8.6.1 Step 4, printed p.29) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='74f7357e-19ef-4903-9571-19b481b56855' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-09.information_verifiable
update public.fields set verification_status='verified_against_standard', verification_quote='Verifiability of all data documentation is a key criterion to ensure transparency. — printed p.29', verification_note='VA-verified 2026-09-08 (§8.6.2, printed p.29) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='4a082e0b-7f9e-4700-92b8-a7638792d4c6' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59020-09.hazardous_substances_reported
update public.fields set verification_status='verified_against_standard', verification_quote='Organizations responsible for recycling, recovery and recirculation should request information on the chemical composition of materials received or collected in order to ensure correct handling and treatment and lower the risk of mismanagement. — printed p.30', verification_note='VA-verified 2026-09-08 (§8.6.4, printed p.30 — printed modal "should", and the field is correctly optional) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='eb510e9a-7d6b-47a1-afb8-294f01bd228d' and verification_status not in ('verified_against_standard','corrected');

-- ============================================================================
-- B. APP-METADATA EXEMPTION - 1 row (2026-08-01 metadata ruling)
-- ============================================================================
-- ISO-59020-01.standard_edition ("Norm-Ausgabe" / edition of ISO 59020 applied). The identifier
-- ISO 59020:2024, First edition, 2024-05 IS printed on the title page, but the title page is a
-- publisher colophon set in columns, not a normative sentence, and ISO 59020 nowhere defines a
-- field obliging a user to record which edition was applied. Recording it is app/project workflow
-- metadata, so it is exempted rather than given a manufactured quote.
update public.fields set verification_status='inferred_from_worksheet', verification_note='VA-pass 2026-09-08: app/project metadata - the guideline does not define this field; exempt per the 2026-08-01 metadata ruling. (The string "ISO 59020 / First edition / 2024-05" appears on the unnumbered title page, PDF p.1, as column-set colophon text, not as a requirement.)', verified_at=now() where id in ('3dd50c3e-d200-41c2-8ba0-72d43b934f0f') and verification_status not in ('verified_against_standard','corrected');

-- ============================================================================
-- C. EQUATIONS - 13 rows, all 13 printed formulae of normative Annex A
-- ============================================================================
-- Formula (A.1)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.1): | %REUI(X) is the average reused content of an inflow (X), in %; mREUI(X) is the mass of reused components and products of an inflow (X), in kg or other mass unit; mTI(X) is the mass of total input material of an inflow (X), in kg or other mass unit. — printed p.33', verification_note='VA-verified 2026-09-08 (§A.2.2 (Formula A.1), printed p.33 — dimension check: kg / kg x 100 = %, matches the unit of pct_REUI_X. Mandatory core indicator per Table 3) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='62e2cbfd-f530-4450-a9b7-1982fa1f955b' and verification_status <> 'verified_against_standard';
-- Formula (A.2)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.2): | %RECI(X) is the average recycled content of an inflow (X), in %; mRECI(X) is the mass of recycled material of an inflow (X), in kg or other mass unit; mTI(X) is the mass of total input material of an inflow (X), in kg or other mass unit. — printed p.33', verification_note='VA-verified 2026-09-08 (§A.2.3 (Formula A.2), printed p.33 — dimension check: kg / kg x 100 = %, matches the unit of pct_RECI_X. Mandatory core indicator per Table 3) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='3d0e7b99-83ba-447d-9101-df3ab06c11c2' and verification_status <> 'verified_against_standard';
-- Formula (A.3)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.3): | PRENI(X) is the average renewable content of an inflow (X), in %; mRENI(X) is the mass of renewable material of an inflow (X), in kg or other mass unit; mTI(X) is the mass of total input material of an inflow (X), in kg or other mass unitg. — printed p.34', verification_note='VA-verified 2026-09-08 (§A.2.4 (Formula A.3), printed p.34 — dimension check: kg / kg x 100 = %, matches the unit of pct_RENI_X. The trailing "unitg" is a typographical slip in the printed where-list and is quoted verbatim. Mandatory core indicator per Table 3) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='77f9ac60-2373-41f5-aa09-071b9e311ff2' and verification_status <> 'verified_against_standard';
-- Formula (A.4)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.4): | RLP(X) is the lifetime ratio of a product or material (X); it is dimensionless; tLP(X) is the lifetime of a product or material (X), in, for example, years; tIALP(X) is the industry average lifetime of a product or material (X), in, for example, years; — printed p.36', verification_note='VA-verified 2026-09-08 (§A.3.2 (Formula A.4), printed p.36 — dimension check: time / time = dimensionless, matches RLP_X having no unit. Optional core indicator per Table 3; §A.3.1 (printed p.35) states it "is not mandatory to calculate". This is the only equation whose output no gate consumes (see the STAGED file)) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='36c2e3ea-1c39-458c-b1ab-0568b515e4ec' and verification_status <> 'verified_against_standard';
-- Formula (A.5)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.5): | PREUO(X) is the actual reused products and components derived from outflow (X), in %; mREUO(X) is the mass of outflow (X) that is reused, in kg or other mass unit; mTO(X) is the total mass of outflow (X), in kg or other mass unit. — printed pp.36-37', verification_note='VA-verified 2026-09-08 (§A.3.3 (Formula A.5), printed pp.36-37 (the formula on p.36, its where-list on p.37) — dimension check: kg / kg x 100 = %, matches the unit of pct_REUO_X. Mandatory core indicator per Table 3) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='b96ecbfd-5f01-4c9b-af8a-864ebe15982a' and verification_status <> 'verified_against_standard';
-- Formula (A.6)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.6): | PRECO(X) is the per cent actual recycled material derived from outflow (X), in %; mRECO(X) is the mass of recycled material derived from outflow (X), in kg or other mass unit; mTO(X) is the total mass of outflow (X), in kg or other mass unit. — printed p.37', verification_note='VA-verified 2026-09-08 (§A.3.4 (Formula A.6), printed p.37 — dimension check: kg / kg x 100 = %, matches the unit of pct_RECO_X. Mandatory core indicator per Table 3) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='1e0f3bf1-e489-4678-9fa3-84394512a64c' and verification_status <> 'verified_against_standard';
-- Formula (A.7)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.7): | PRENO(X) is the per cent actual recirculation of outflow (X) in the biological cycle, in %; mRENO(X) is the mass of outflow (X) that is renewable recirculation, in kg or other mass unit; mTO(X) is the total mass of outflow (X), in kg or other mass unit. — printed p.38', verification_note='VA-verified 2026-09-08 (§A.3.5 (Formula A.7), printed p.38 — dimension check: kg / kg x 100 = %, matches the unit of pct_RENO_X. Mandatory core indicator per Table 3) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='3fc5b480-968f-4176-bd3b-6eb91f1f6f3b' and verification_status <> 'verified_against_standard';
-- Formula (A.8)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.8): | PECONRE(X) is the average energy (X) consumed that is renewable energy, in %; EIRENE(X) is the renewable energy (X) inflow, in MJ (or in kWh); EORENE(X) is the renewable energy (X) outflow, in MJ (or in kWh); EITE(X) is the total energy (X) inflow, in MJ (or in kWh); EOTE(X) is the total energy (X) outflow, in MJ (or in kWh). — printed p.39', verification_note='VA-verified 2026-09-08 (§A.4.2 (Formula A.8), printed p.39 — dimension check: (MJ - MJ) / (MJ - MJ) x 100 = %, matches the unit of pct_ECONRE_X; all four inputs carry the same encoded unit MJ, so the two differences are dimensionally valid. Optional core indicator per Table 3. The printed denominator can be zero when total inflow equals total outflow; the encoding has no guard for that) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='16e117aa-9d53-4f91-8323-4cb016a18a3d' and verification_status <> 'verified_against_standard';
-- Formula (A.9)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.9): | PCWW is the average water withdrawal from circular sources, in %; VCIW is the volume of water inflow from circular sources, in m3/year; VAIW is the volume of water inflow from all sources, in m3/year. — printed p.41', verification_note='VA-verified 2026-09-08 (§A.5.2 (Formula A.9), printed p.41 — dimension check: (m3/year) / (m3/year) x 100 = %, matches the unit of pct_CWW. Optional core indicator per Table 3) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='c724b258-9a2a-47b4-99b2-7907a0b006dd' and verification_status <> 'verified_against_standard';
-- Formula (A.10)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.10): | PCDW is the average circular water discharges, in %; VCDW is the volume of circular water discharges, in m3/year; VAIW is the volume of water inflow from all sources, in m3/year. — printed p.41', verification_note='VA-verified 2026-09-08 (§A.5.3 (Formula A.10), printed p.41 — dimension check: (m3/year) / (m3/year) x 100 = %, matches the unit of pct_CDW. The denominator is the water INFLOW from all sources, not the discharge total; that is what is printed, and Table 3 describes it the same way) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='55e9a431-e000-4ee9-914c-1fce534ea092' and verification_status <> 'verified_against_standard';
-- Formula (A.11)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.11): | is the ratio (on-site or internal) of water reuse or recirculation; it is dimensionless and | represents the amount of water recycled or reused within the facility after it has been | contained and adequately treated for reuse, as needed; | is the total water consumed in all processes and operations within the facility, in m3 per year; typically, the water used in a process or operation is the amount of water entering the process; | is the total water withdrawn from all external sources, in m3 per year; an external source is one from a local supply and not provided by internal processes or operations. — printed p.42', verification_note='VA-verified 2026-09-08 (§A.5.4 (Formula A.11), printed p.42 — dimension check: (m3/year) / (m3/year) = dimensionless, matches RWRR having no unit. In the printed where-list the symbol column (RWRR, VTWU, VTWW) is set beside the definition column, so the definitions are quoted as separate runs. §A.5.4 (printed p.41) states the ratio "will exceed 1,0 when water is reused or recirculated within the facility". Optional core indicator per Table 3) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='7e69300e-af43-40b2-9f75-ef773d9ffed7' and verification_status <> 'verified_against_standard';
-- Formula (A.12)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.12): | RMP is the MP ratio, in monetary units per kg (e.g. $/kg, €/kg); C is the total revenue generated in monetary units (e.g. $, €); D is the total mass of all linear resource inflows, in kg or other mass unit. — printed p.43', verification_note='VA-verified 2026-09-08 (§A.6.2 (Formula A.12), printed p.43 — dimension check: monetary unit / kg = monetary unit per kg, matches the encoded EUR/kg. Optional core indicator per Table 3) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='e3364b07-c567-4740-882c-d87e0e636a94' and verification_status <> 'verified_against_standard';
-- Formula (A.13)
update public.equations set verification_status='verified_against_standard', verification_quote='The calculation of the circularity indicator is performed by applying Formula (A.13): | IRII is the RII, expressed as a ratio; E is the rate of variation of resource inflow consumption (mass) per unit time; it is dimensionless; F is the rate of variation of GDP per unit time; it is dimensionless. — printed p.43', verification_note='VA-verified 2026-09-08 (§A.6.3 (Formula A.13), printed p.43 — dimension check: dimensionless / dimensionless = dimensionless ratio, matches IRII having no unit. Optional core indicator per Table 3) [VA · ISO 59020:2024 published First edition, PDF text layer]', verified_at=now() where id='fc67093c-8d64-4854-882e-a2f621059041' and verification_status <> 'verified_against_standard';
