-- ISO-59014 — VA verification pack (PDF text layer, SR-3 ground truth)
-- Generated 2026-09-08. DO NOT ADD begin/commit/rollback: apply-pack.mjs supplies the transaction.
--
-- PROVENANCE WARNING (first order): the source document is a DRAFT INTERNATIONAL STANDARD,
--   ISO/DIS 59014:2023(E), ballot 2023-10-16 .. 2024-01-08, TC 207/SC 5 + TC 323, secretariat AFNOR.
--   Its own title page states: "THIS DOCUMENT IS A DRAFT CIRCULATED FOR COMMENT AND APPROVAL. IT IS
--   THEREFORE SUBJECT TO CHANGE AND MAY NOT BE REFERRED TO AS AN INTERNATIONAL STANDARD UNTIL
--   PUBLISHED AS SUCH." It is NOT the published ISO 59014:2024. Clause numbers, wording and the
--   "shall" set can differ in the published edition. prod standards.version already records
--   "Draft International Standard (ISO/DIS 59014:2023(E))" — this pack does not change that.
--   Every quote below is verbatim from the DIS and is valid ONLY for the DIS.
--
-- Grade: [VA] — the source is the rendered PDF's own text layer, which under SR-3 is ground truth.
--   Source PDF : C:\Users\Ekowai\Desktop\Ciruclar economy, sustanability and water test\ISO-59014-Unlocked.pdf
--   Text layer : pdftotext -layout -enc UTF-8, 38 PDF pages, 0 undecodable characters.
-- Page convention: form feeds preserved, so text-file page N = PDF page N.
--   Body printed page = PDF page - 8 (PDF p.9 = printed p.1 ... PDF p.37 = printed p.29).
--   Front matter is roman (PDF p.3 = iii ... PDF p.7 = vii); PDF p.8 and p.38 are blank.
--   Every quote carries its printed page ref once, at the end.
-- Language: English (single-language document; no German or French text present).
-- Document type: a requirements standard, not a Technical Report or guidance document —
--   87 occurrences of "shall" and 13 of "should" in the text layer, so block gates ARE defensible
--   in principle; see the STAGED file for which specific ones are not.
--
-- Counts: 84 fields examined / 83 quoted / 1 exempt (app metadata) / 0 residue.
-- Equations: 0 in prod and 0 in the source — ISO/DIS 59014 contains no formula, no worked example
--   and no numeric limit in its normative text. Nothing to lift, nothing to backfill.
-- Rollback: rollback-iso-59014-md-verification-pack.sql

-- ISO-59014-01.organization_in_focus
update public.fields set verification_status='verified_against_standard', verification_quote='organization person or group of people that has its own functions with responsibilities, authorities, and relationships to achieve its objectives — printed p.4', verification_note='VA-verified 2026-09-08 (§3.17, printed p.4) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='29bd85ec-f851-4cba-af6f-8a86fb79b22e' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-01.recovery_activity_in_focus
update public.fields set verification_status='verified_against_standard', verification_quote='Activities and processes relating to the recovery of secondary materials include collection of recoverable resources, classification, sorting and non-destructive and destructive processes as illustrated in Figure 3. | Figure 3 is a simplification of activities and processes for recovering secondary materials and it is acknowledged that activities related to logistics and storage occur at different stages in the chain of activities and processes. — printed p.7/7', verification_note='VA-verified 2026-09-08 (§5.1 / §6.6, printed p.7/7) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='e473d488-03b3-4436-a415-2ace829e861f' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-02.principle_considered
update public.fields set verification_status='verified_against_standard', verification_quote='The principles are the basis for the requirements and guidance in this document. — printed p.6', verification_note='VA-verified 2026-09-08 (§4.1, printed p.6) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='479918eb-9d88-4fb3-9b31-bff7c3defc2e' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-02.principles_applied_true_fair_consistent
update public.fields set verification_status='verified_against_standard', verification_quote='The application of principles is fundamental to ensure that the achievement and demonstration of the sustainability and traceability of the secondary materials recovery is undertaken in a true, fair and consistent manner. — printed p.6', verification_note='VA-verified 2026-09-08 (§4.1, printed p.6) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='49b6c4ba-e32a-4f83-a8d2-c778f9fa429c' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-03.recovery_pathway
update public.fields set verification_status='verified_against_standard', verification_quote='recovery pathway type and sequence of activities and processes applied to recover products (3.18), components and materials (3.15) from recoverable resources (3.19) | The decision about the recovery pathway is determined by the ways recoverable resources are collected and classified. Annex B provides an example of a methodology for determining the recovery pathway using decision trees that are applied as part of the classification and sorting process. — printed p.5/8', verification_note='VA-verified 2026-09-08 (§3.20 / §5.2, printed p.5/8) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='32596345-f82a-4a47-9264-49f5ac5652e9' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-03.organization_type
update public.fields set verification_status='verified_against_standard', verification_quote='Organizations involved in activities and processes leading to the recovery of secondary materials include, among others, collectors, dismantlers, re-processors, remanufacturers, refiners, depending on the recovery process(es) that the organization conducts. Annex A provides examples of organizations involved in recovery processes. — printed p.8', verification_note='VA-verified 2026-09-08 (§5.3, printed p.8) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='c1429389-d0d7-41a2-93eb-aa4a30864611' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-03.subsistence_activities_present
update public.fields set verification_status='verified_against_standard', verification_quote='subsistence activity SA activity that provides typically self-employed individuals with the minimum to subsist | Activities conducted by an individual or groups of individuals engaged in subsistence activities can occur throughout the activities and processes in Figure 3. — printed p.5/8', verification_note='VA-verified 2026-09-08 (§5.4 / §3.25, printed p.5/8) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='6831df58-c801-4bba-b0ad-4f5093c6928d' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.attest_iso_59014_04_cr_011
update public.fields set verification_status='verified_against_standard', verification_quote='Where the organization has an influence on collection systems design, it shall support the separate collection of recoverable resources (e.g., through the provision of separate containers or separate collection points). — printed p.10', verification_note='VA-verified 2026-09-08 (§6.3, printed p.10) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: attestation carrier for gate CR-011; its label reads "Nachweis: 6.1" but the gate cites §6.3 — label/clause mismatch staged', verified_at=now() where id='d1e3629d-31ac-4602-8795-ef0ebac08426' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.attest_iso_59014_04_cr_017
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall undertake the depollution in such a way that prevents the release of any substances or mixtures to be removed. | Dilution of the concentration of substances or mixtures to be removed shall not be undertaken as part of depollution. — printed p.10/10', verification_note='VA-verified 2026-09-08 (§6.5, printed p.10/10) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: attestation carrier for gate CR-017; its label reads "Nachweis: 6.2" but the gate cites §6.5 — label/clause mismatch staged', verified_at=now() where id='54f3903f-1b4f-4d7c-980c-07b915fce8fa' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.attest_iso_59014_04_cr_018
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall route any resulting hazardous substances and components to proper further treatment. — printed p.11', verification_note='VA-verified 2026-09-08 (§6.5, printed p.11) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: attestation carrier for gate CR-018; its label reads "Nachweis: 6.2" but the gate cites §6.5 — label/clause mismatch staged', verified_at=now() where id='84177f85-b197-4c1d-8a9a-13cb1851f896' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.delivery_identified
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall identify each delivery of recoverable resources received in accordance with the attributes established in the list of attributes and maintain documented information about the results of the identification process of attributes of each delivery as part of its traceability system. — printed p.9', verification_note='VA-verified 2026-09-08 (§6.2, printed p.9) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='9d1e1f98-7f66-4bca-a8cb-b32cabdeec3a' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.recovery_decision_documented
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall document how decisions regarding the recovery pathway for each delivery were made. — printed p.9', verification_note='VA-verified 2026-09-08 (§6.2, printed p.9) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='6b1165ed-4645-4db2-ad4d-648a21d30c83' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.attribute_list_maintained
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall establish, document and maintain a list of attributes relevant to the recoverable resources it handles to facilitate the determination of the recovery pathway and the required recovery processes (see also informative Annex B). | The organization shall keep the list up-to-date with any relevant changes to the recoverable resources handled and the activities and processes applied. — printed p.9/9', verification_note='VA-verified 2026-09-08 (§6.2, printed p.9/9) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='c149725f-b59f-41fe-b2df-f1f419b2777c' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.attribute
update public.fields set verification_status='verified_against_standard', verification_quote='classification <recoverable resources> systematic identification of recoverable resources (3.19) with the purpose of making decisions relating to the recovery of resources according to established attributes | NOTE 1 Examples of attributes include product, component and material type and characteristics, hazard potential, process requirements, repairability, etc. — printed p.2/9', verification_note='VA-verified 2026-09-08 (§3.3 / §6.2 NOTE 1, printed p.2/9) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='f78ce88d-1155-4477-acbd-d603492f973c' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.recovery_pathway_methodology_applied
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall apply a methodology to determine the recovery pathway, for example, the methodology set out in informative Annex B. If an alternative methodology to Annex B is chosen, it shall aim for the best environmental outcome based on life cycle thinking and be documented together with the rationale for the choice. — printed p.9', verification_note='VA-verified 2026-09-08 (§6.2, printed p.9) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='001e1322-8d81-4050-8042-63b5a2db69e4' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.secondary_material_criteria_defined
update public.fields set verification_status='verified_against_standard', verification_quote='The organization involved in activities and processes for recovering secondary materials shall identify or define criteria for secondary materials to be recovered that consider the quality and function with the best environmental and social outcome. — printed p.9', verification_note='VA-verified 2026-09-08 (§6.1, printed p.9) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='45e8cc87-767f-4be1-a72b-6c9c964dd237' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.best_outcome_from_lifecycle_studies
update public.fields set verification_status='verified_against_standard', verification_quote='The best environmental and social outcome shall be inferred from documented studies which apply a life cycle perspective and include at least consideration of energy consumption and resource scarcity. — printed p.9', verification_note='VA-verified 2026-09-08 (§6.1, printed p.9) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='86b721ef-0bfb-46b0-bc71-0b8611e10ec3' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.lca_rationale_documented
update public.fields set verification_status='verified_against_standard', verification_quote='If such studies do not provide sufficient information to define the best environmental outcome when identifying or defining the criteria, the organization shall consider conducting studies in accordance with ISO 14040, ISO 14044 and ISO 14075. If the latter were not applied, a rationale for the choice shall be documented. — printed p.9', verification_note='VA-verified 2026-09-08 (§6.1, printed p.9) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='5c00c14f-a40b-47fd-924b-ac966e086576' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-04.recovery_targets_quant_qual
update public.fields set verification_status='verified_against_standard', verification_quote='Based on the properties of the incoming recoverable resources and considering continual improvement, the organization shall identify quantitative and qualitative targets of secondary materials to be recovered. | EXAMPLE Recycling rate can be considered a target to prevent losses. — printed p.9/9', verification_note='VA-verified 2026-09-08 (§6.1, printed p.9/9) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='1aaf40c8-10ae-44d6-be21-171f8c0a906e' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.separate_collection_supported
update public.fields set verification_status='verified_against_standard', verification_quote='Where the organization has an influence on collection systems design, it shall support the separate collection of recoverable resources (e.g., through the provision of separate containers or separate collection points). — printed p.10', verification_note='VA-verified 2026-09-08 (§6.3, printed p.10) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='14691850-622c-428a-ad8e-c4806f021bb9' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.return_collection_measures_supported
update public.fields set verification_status='verified_against_standard', verification_quote='Where the organization has an influence on collection or return of recoverable resources, it shall support the development and implementation of measures to facilitate the return or collection of recoverable resources returned or collected (e.g., by supporting collectors with materials lists, communication campaigns, and take-back scheme in place). — printed p.10', verification_note='VA-verified 2026-09-08 (§6.3, printed p.10) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='20b35ae5-ddf3-4099-bf32-f5af3658ba07' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.sorted_per_attributes
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall consistently sort recoverable resources in accordance with the identified attributes. | When sorting recoverable resources intended for material recovery, the organization shall employ appropriate sorting technologies and practices that facilitate achieving the criteria defined for secondary materials to be recovered (see 6.1). — printed p.10/10', verification_note='VA-verified 2026-09-08 (§6.4, printed p.10/10) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='cd750d02-7552-4d97-a7f9-2487a6080ce8' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.non_recoverables_to_final_treatment
update public.fields set verification_status='verified_against_standard', verification_quote='After sorting resources that are non-recoverable as materials, these materials shall be sent to proper final treatment at authorized organizations, where available, or to organizations that handles this material in a proper manner. — printed p.10', verification_note='VA-verified 2026-09-08 (§6.4, printed p.10) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='b422cb1e-f4ff-4239-92bf-87acafca8d96' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.sorted_by_traceability_data_held
update public.fields set verification_status='verified_against_standard', verification_quote='To ensure traceability the organization shall sort into collected recoverable resources for which it holds traceability data set out in Clause 8 and those for which it does not. — printed p.10', verification_note='VA-verified 2026-09-08 (§6.4, printed p.10) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='7b71dac6-0310-4a02-a92f-2cbf1f1ba6f7' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.material_types_kept_separate
update public.fields set verification_status='verified_against_standard', verification_quote='Where recoverable resources have been sorted into material types, the organization shall keep them separate to facilitate further processing. — printed p.10', verification_note='VA-verified 2026-09-08 (§6.5, printed p.10) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='774ccf7a-b290-4c6e-8f14-56d876f9b322' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.adequate_infrastructure_maintained
update public.fields set verification_status='verified_against_standard', verification_quote='When preparing for recovering material, the organization shall operate and maintain an adequate infrastructure, technologies and practices that facilitates achieving the criteria defined for secondary materials to be recovered. — printed p.10', verification_note='VA-verified 2026-09-08 (§6.5, printed p.10) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='df435326-5868-42f9-9986-ef606c936dac' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.process_selection_lifecycle_supported
update public.fields set verification_status='verified_against_standard', verification_quote='The selection of non-destructive and destructive processes or any combination thereof shall focus on maximizing the quantity and fulfilling the defined quality criteria of the material recovered with the best environmental and social outcome. The decision regarding the choice of processes shall be supported by using publicly available studies based on life cycle thinking or by conducting a life cycle assessment (LCA in accordance with ISO 14040 and ISO 14044) for comparing the environmental outcomes of the different processing options. — printed p.10', verification_note='VA-verified 2026-09-08 (§6.5, printed p.10) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='c75c3020-f0b0-4f3e-b5e0-b311a6d33927' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.depollution_prevents_release
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall undertake the depollution in such a way that prevents the release of any substances or mixtures to be removed. | Dilution of the concentration of substances or mixtures to be removed shall not be undertaken as part of depollution. — printed p.10/10', verification_note='VA-verified 2026-09-08 (§6.5, printed p.10/10) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='4f7ac477-7951-4b8f-a6ce-8bb9ef285d6a' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.depollution_by_competent_personnel
update public.fields set verification_status='verified_against_standard', verification_quote='Depollution shall be undertaken by personnel who are competent based on appropriate education, training or experience regarding depollution. — printed p.11', verification_note='VA-verified 2026-09-08 (§6.5, printed p.11) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='a911d0f6-31ec-4058-b10b-ded8298e6b7d' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.hazardous_substances_routed
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall route any resulting hazardous substances and components to proper further treatment. — printed p.11', verification_note='VA-verified 2026-09-08 (§6.5, printed p.11) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='dad9735b-3a3b-4831-abfb-42ddeb82172c' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.logistics_facilitates_recovery
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall handle, transport and store recoverable resources in a way that facilitates their subsequent recovery as whole products, components or materials, ensuring the best environmental outcome. | Resources not recovered as materials, components or products shall be handled, transported and stored in a way that facilitates their safe final treatment. — printed p.11/11', verification_note='VA-verified 2026-09-08 (§6.6, printed p.11/11) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='60c224c3-c226-4a9c-bd8a-10108abdf22f' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-05.adequate_packaging_used
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall use adequate transport, storage, packaging methods and packaging materials to prevent environmental and human health risks, damage to recoverable resources and reduce resource use. — printed p.11', verification_note='VA-verified 2026-09-08 (§6.6, printed p.11) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='6c55c7e4-e211-4f47-8bc7-4db98db30543' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-06.context_issues_determined
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall determine issues that are relevant to its purpose and that affect its ability to fulfil the requirements in this document. — printed p.11', verification_note='VA-verified 2026-09-08 (§7.1, printed p.11) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='8611fcb5-36c5-4ae6-b11b-b6ce5dc10946' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-06.interested_parties_identified
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall identify — interested parties that are relevant to its activities and processes; — the interests, rights and concerns of these interested parties; — the requirements of these interested parties that can potentially affect its operations; — active and potential conflicts. — printed p.11', verification_note='VA-verified 2026-09-08 (§7.2, printed p.11) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='34a44cf2-bfc2-4168-8bbb-86735f80e2c0' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-06.two_way_communication_channels
update public.fields set verification_status='verified_against_standard', verification_quote='Stakeholder engagement involves a dialogue between the organization and one or more of its interested parties. Therefore, the organization shall — establish clear and accessible channels for two-way communication with the interested parties identified; — take measures to prevent conflicts with the interested parties identified and grievance mechanisms to resolve active ones. — printed p.11', verification_note='VA-verified 2026-09-08 (§7.2, printed p.11) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='5636815c-5de0-4b59-8fbc-b7c558bb69a5' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-06.collaborative_structure
update public.fields set verification_status='verified_against_standard', verification_quote='The organization should design and implement a collaborative structure or join an existing one with defined aims, roles and responsibilities, procedures and appropriate means that facilitate: — printed p.11', verification_note='VA-verified 2026-09-08 (§7.2, printed p.11) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: source modal is "should" (recommendation), not "shall"', verified_at=now() where id='fbc06ad7-ee26-484f-b499-21bde531f595' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-06.value_chain_code_of_conduct
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall develop a value chain code of conduct, communicate this as expectation of the organization and incorporate the value chain code of conduct requirements into contracts and any other type of agreement. The value chain code of conduct shall refer as a minimum to ethical behaviour, traceability aspects and responsible practices for achieving the quality and targets expected of the secondary material to be recovered. — printed p.12', verification_note='VA-verified 2026-09-08 (§7.3, printed p.12) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='8bfee415-bc80-4175-be13-881878e28b52' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-06.capacity_development_needs_identified
update public.fields set verification_status='verified_against_standard', verification_quote='Based on the properties of the incoming recoverable resources and considering continual improvement, the organization shall identify capacity development needs in the value chain and provide corresponding training options for properly applying the code of conduct. — printed p.12', verification_note='VA-verified 2026-09-08 (§7.3, printed p.12) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='cd0a47dc-493f-4ffe-8d17-90f759b0587d' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-06.procurement_criteria_established
update public.fields set verification_status='verified_against_standard', verification_quote='The organization should establish procurement criteria in accordance with the value chain code of conduct developed. — printed p.12', verification_note='VA-verified 2026-09-08 (§7.3, printed p.12) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: source modal is "should" (recommendation), not "shall"', verified_at=now() where id='923e0a2e-5b35-4dcb-b017-14a6fdf62514' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-07.sa_enabling_environment
update public.fields set verification_status='verified_against_standard', verification_quote='Where applicable, the organization engaging or intending to engage with individuals involved in subsistence activities (SAs) shall create an enabling environment to work collaboratively with organizations or individuals involved in SAs that addresses their identified needs and interests with regards to their well-being and livelihoods. — printed p.12', verification_note='VA-verified 2026-09-08 (§7.4, printed p.12) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='209078d1-afd0-4369-8da5-4eba7ec5df2a' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-07.sa_support_mechanisms
update public.fields set verification_status='verified_against_standard', verification_quote='Where applicable, the organization should develop mechanisms for supporting any individuals involved in subsistence activities (SAs), who are part of its value chain, in the continual improvement of their well-being, livelihoods and professional practices (see also informative Annex C). — printed p.13', verification_note='VA-verified 2026-09-08 (§7.4, printed p.13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: source modal is "should" (recommendation), not "shall"', verified_at=now() where id='e946f2d4-2970-4cbe-8204-4d873ae81cc9' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-07.decent_work_conditions
update public.fields set verification_status='verified_against_standard', verification_quote='At the activities and processes to recover secondary materials, the organization shall: a) Establish decent work conditions in their own operations; — printed p.13', verification_note='VA-verified 2026-09-08 (§7.5 a), printed p.13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='ecc8ef61-dfee-4c70-be91-965919150b6c' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-07.child_forced_labour_prevented
update public.fields set verification_status='verified_against_standard', verification_quote='b) Prevent child labour, forced labour, harassment and any form of discrimination with a specific focus on vulnerable and disadvantaged workers, women and individuals involved in subsistence activities with whom the organization engages; — printed p.13', verification_note='VA-verified 2026-09-08 (§7.5 b), printed p.13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='f14ba1d7-d68d-4ed7-8622-07ff3053f802' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-07.freedom_of_association
update public.fields set verification_status='verified_against_standard', verification_quote='c) Ensure freedom of association and the right to collective bargaining and inform workers of any existing collective bargaining agreement at workplace site(s). If the formation of workers’ associations or unions is prohibited in the country of operations, the organization shall provide other mechanism(s) to engage in a dialogue with workers (such as a health and safety committee with representatives from workers and management); — printed p.13', verification_note='VA-verified 2026-09-08 (§7.5 c), printed p.13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='da8a5982-5387-40fa-a8c7-295f1e17d31e' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-07.ppe_provided
update public.fields set verification_status='verified_against_standard', verification_quote='d) Provide personal protective equipment (PPE); | NOTE PPE includes masks, goggles, gloves, safety helmets, safety equipment and clothing to protect workers from hazards and hazardous waste, components and substances, first aid equipment — printed p.13/13', verification_note='VA-verified 2026-09-08 (§7.5 d), printed p.13/13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='ad5365d2-0805-489b-9067-cc22a9683122' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-07.sanitary_facilities_accessible
update public.fields set verification_status='verified_against_standard', verification_quote='e) Make toilet and sanitary facilities regularly accessible to workers; — printed p.13', verification_note='VA-verified 2026-09-08 (§7.5 e), printed p.13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='28e6272b-a1a5-4895-96d9-a7fe177eae72' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-07.maternity_safety_measures
update public.fields set verification_status='verified_against_standard', verification_quote='f) Put in place safety and health measures and infrastructure for pregnant workers and workers who have recently given birth or are breastfeeding. — printed p.13', verification_note='VA-verified 2026-09-08 (§7.5 f), printed p.13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='86cbb4b8-1176-4020-b686-edf30ffcd001' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-08.communities_informed_of_risks
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall inform affected communities and authorities about any risks to the environment or the community, as well as measures to be implemented for preserving healthy and safe living conditions. — printed p.13', verification_note='VA-verified 2026-09-08 (§7.6.2, printed p.13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='470fa928-aff7-47dc-888f-c12f55ec6f25' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-08.env_social_risks_assessed
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall systematically identify, assess and prioritize environmental and social risks arising from its activities for secondary materials recovery. — printed p.13', verification_note='VA-verified 2026-09-08 (§7.6.2, printed p.13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='9760c53d-7e4c-4246-a717-6c8c793f4a9a' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-08.emergency_communication_procedure
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall provide local communities with a clear communication procedure in case of emergency (e.g., explosion, fire, contamination or accident). — printed p.13', verification_note='VA-verified 2026-09-08 (§7.6.2, printed p.13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='e7ba2c2e-db29-4568-892e-ed27640307ef' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-08.risk_control_measures_implemented
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall implement measures to prevent, reduce or control (separately or in combination) the prioritized risks and resulting potential or actual impacts. | The organization shall develop protocols to be activated in the event of an adverse social impact or environmental impact from emissions or discharge of pollutants or waste. — printed p.13/13', verification_note='VA-verified 2026-09-08 (§7.6.2, printed p.13/13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='b16f91e7-c352-4751-905d-490c7e9fbc5c' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-08.ecosystem_recovery_measures
update public.fields set verification_status='verified_against_standard', verification_quote='Where applicable, the organization shall implement protocols, activities, processes and mechanisms that aid and accelerate the recovery of ecosystems that have been degraded or destroyed by its activities (see, for example, land degradation cases in ISO 14055-1) and should ensure financing for preventive and restorative measure. — printed p.13', verification_note='VA-verified 2026-09-08 (§7.6.2, printed p.13) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='7b034533-cd48-49e5-bcba-182359c5bd56' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-08.harmful_substances_removed
update public.fields set verification_status='verified_against_standard', verification_quote='Where the risks of current practices are not understood, the organization shall seek to identify the risks and develop a plan to resolve or mitigate the risks. | Where the organization has identified that it is not properly managing harmful substances or is engaging in harmful practices, the organization shall remove the substances from the activities and processes or improve practices to make them safer. — printed p.14/14', verification_note='VA-verified 2026-09-08 (§7.6.2, printed p.14/14) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='1ec2c977-08ee-4a00-845c-f0dc646bab10' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-08.health_safety_risk_assessment
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall undertake a risk assessment with regards to health and safety risks at the workplace of the organization for their workers and for individuals involved in SAs with whom the organization is engaging. | The organization shall undertake a risk assessment with regards to health and safety risks to other stakeholders of the organization. — printed p.14/14', verification_note='VA-verified 2026-09-08 (§7.6.3, printed p.14/14) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='73fde5fd-f76f-4eb2-adc3-870d4e3f54e0' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-08.health_safety_risks_communicated
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall take effective measures to communicate about health and safety risks to their workers, individuals involved in SAs with whom the organization is engaging and other stakeholders of the organization. | The organization shall develop protocols to be activated in the event of adverse health and safety impacts. — printed p.14/14', verification_note='VA-verified 2026-09-08 (§7.6.3, printed p.14/14) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='a7159b31-3dca-44e6-b40c-529982e3c2da' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-09.resource_use_minimized
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall identify opportunities to minimize resource use and implement corresponding measures. | — replacing materials made from primary resources with secondary materials, when this represents the best environmental outcome based on life cycle thinking; — printed p.14/14', verification_note='VA-verified 2026-09-08 (§7.7, printed p.14/14) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='7d36d65f-06ed-4b4f-b08d-38853e2d120b' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-09.baseline_of_conformity
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall establish the baseline of conformity with the requirements, effective measures to address them as well as means required to facilitate continual improvement. These shall be part of an action, regular monitoring and evaluation plan. — printed p.15', verification_note='VA-verified 2026-09-08 (§7.8, printed p.15) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='f9bdd8a1-899e-4c59-a36a-e5734468caf7' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-09.recycling_rate
update public.fields set verification_status='verified_against_standard', verification_quote='The recycling rate shall be part of the monitoring and evaluation process. | EXAMPLE Recycling rate can be considered a target to prevent losses. — printed p.15/9', verification_note='VA-verified 2026-09-08 (§7.8 / §6.1, printed p.15/9) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='0e500666-c9b7-4443-9989-87643825bf9f' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-09.effectiveness_monitored
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall document, continuously monitor and regularly evaluate the effectiveness of the measures established against the baseline. | The organization shall remove or change any measures found to be ineffective and support measures with positive results. — printed p.15/15', verification_note='VA-verified 2026-09-08 (§7.8, printed p.15/15) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='56f40ef0-1e12-4317-a628-daec0ec7937c' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-09.code_of_conduct_monitored
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall monitor the application of the code of conduct where it has been agreed to between the organization and the suppliers. — printed p.15', verification_note='VA-verified 2026-09-08 (§7.8, printed p.15) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='a7ef4b28-06f4-4e0b-9f98-ad862c477dd1' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-09.workers_informed_of_results
update public.fields set verification_status='verified_against_standard', verification_quote='Workers shall be informed of the monitoring results. | The organization shall maintain the records of monitoring the performance and support actions to resolve any non-compliances. — printed p.15/15', verification_note='VA-verified 2026-09-08 (§7.8, printed p.15/15) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='15ee1ef2-c8a2-41ec-94d5-2b5bcbdd9e17' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-09.competencies_determined
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall a) determine the necessary operational and managerial competencies of individuals doing work under its control that affects the performance and effectiveness of its activities and processes; b) appoint individuals with the required competencies responsible for the operational activities and processes and activities or management processes with a description of the roles of this position; c) assess whether individuals concerned possess the competencies identified; d) where applicable, take actions to ensure that these individuals are competent on the basis of appropriate education, training, mentoring or experience, and evaluate the effectiveness of the actions taken. — printed p.15', verification_note='VA-verified 2026-09-08 (§7.9.1, printed p.15) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='b0132d35-691d-48f6-a0c7-7eb8c5a76341' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-09.training_needs_identified
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall identify training needs for any organization with whom it engages such as suppliers, sub-contractors and individuals engaged in SAs. | The organization shall plan and conduct training activities in the areas of need. This shall cover, as a minimum, training on the value chain code of conduct of the organization. — printed p.16/16', verification_note='VA-verified 2026-09-08 (§7.9.2, printed p.16/16) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='499cb178-df2d-478b-a677-bb1c9eb4d783' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.assigned_sorting_attributes
update public.fields set verification_status='verified_against_standard', verification_quote='g) assigned attributes for sorting; | p) assigned attributes for sorting. — printed p.16/17', verification_note='VA-verified 2026-09-08 (§8 g) / §8 p), printed p.16/17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: ONE field encodes BOTH the upstream item g) and the downstream item p); the source states them as two separate data items', verified_at=now() where id='22bbdae2-fe4f-414f-8156-976c2770ba10' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.traceability_system_implemented
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall develop and implement a traceability system including procedures and a relevant policy whereby the latter shall be publicly available. | The organization shall collect data about the products, components or materials handled. — printed p.16/16', verification_note='VA-verified 2026-09-08 (§8 / §3.26, printed p.16/16) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='4f10c909-d08c-4338-876a-db5546e8185a' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.traceability_data_inaccessible_justified
update public.fields set verification_status='verified_against_standard', verification_quote='A justification shall be provided if traceability data cannot be accessed. | If data upstream or data downstream cannot be collected, justification shall be provided. — printed p.16/17', verification_note='VA-verified 2026-09-08 (§8, printed p.16/17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='a34d92ba-29c3-4fe8-8cd9-2572e737cd96' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.upstream_org_name_address
update public.fields set verification_status='verified_against_standard', verification_quote='Data shall cover at a minimum: | a) name and address of the organizations in its value chain with which it has contractual relationships, including the collection, processing and delivery of the consignment of products, components or materials, including the names of the responsible staff; — printed p.16/16', verification_note='VA-verified 2026-09-08 (§8 a), printed p.16/16) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='37560312-9b69-4e97-ae53-736154380661' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.upstream_coc_confirmation
update public.fields set verification_status='verified_against_standard', verification_quote='b) confirmation of compliance with the code of conduct (see Clause 7.2.2) from the organizations in its value chain with which it has contractual relationships; — printed p.16', verification_note='VA-verified 2026-09-08 (§8 b), printed p.16) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='2ad29c8f-fb6f-4e13-94b0-74066598890e' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.upstream_receipt_release_dates
update public.fields set verification_status='verified_against_standard', verification_quote='c) date of receipt of the recoverable resource and their date of release or shipment; — printed p.16', verification_note='VA-verified 2026-09-08 (§8 c), printed p.16) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='9e319c08-2396-4b60-9b27-4dd23f8f24ec' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.upstream_consignment_origin
update public.fields set verification_status='verified_against_standard', verification_quote='d) origin (address) of consignment; — printed p.16', verification_note='VA-verified 2026-09-08 (§8 d), printed p.16) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='b2201297-53f5-4d56-bd1c-8dbc6c13ba03' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.upstream_unique_reference
update public.fields set verification_status='verified_against_standard', verification_quote='e) where available, unique reference number of the recoverable resource; if not available, the organization should assign one, — printed p.16', verification_note='VA-verified 2026-09-08 (§8 e), printed p.16) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: the assignment half of e) is a "should" (recommendation), the data item itself is under the "shall cover at a minimum" list', verified_at=now() where id='d3b89da0-cdce-44de-91d5-758b81f6917d' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.classification_system_used
update public.fields set verification_status='verified_against_standard', verification_quote='f) classification system used for classifying products, components or materials; | o) classification system used for classifying products, components or materials; — printed p.16/17', verification_note='VA-verified 2026-09-08 (§8 f) / §8 o), printed p.16/17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: ONE field encodes BOTH the upstream item f) and the downstream item o); the source states them as two separate data items', verified_at=now() where id='80055082-95b8-4904-932d-034898320543' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.processing_inputs_quantity
update public.fields set verification_status='verified_against_standard', verification_quote='h) inputs by mass or volume (in SI units) or number of units, preferably categorized by product, component or material types, according to the Harmonized System (HS code); — printed p.17', verification_note='VA-verified 2026-09-08 (§8 h), printed p.17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: the source offers a CHOICE of basis (mass OR volume in SI units OR number of units); the encoded unit is "-" and does not record which basis was selected (SR-2)', verified_at=now() where id='95df4e62-329b-4572-8b13-9c7da36f9b76' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.inputs_routing_percentage
update public.fields set verification_status='verified_against_standard', verification_quote='i) percentage of the total amount of inputs routed towards different recovery and final treatment pathways (see Annex B), identifying main activities and processes applied including depollution; — printed p.17', verification_note='VA-verified 2026-09-08 (§8 i), printed p.17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='b89382d3-c6ee-4517-bb30-ce9c4b42fa34' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.processing_outputs_quantity
update public.fields set verification_status='verified_against_standard', verification_quote='j) outputs by mass or volume (in SI units) or number of units, preferably categorized by product, component or material types, according to the Harmonized System Codes (HS Codes); — printed p.17', verification_note='VA-verified 2026-09-08 (§8 j), printed p.17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: the source offers a CHOICE of basis (mass OR volume in SI units OR number of units); the encoded unit is "-" and does not record which basis was selected (SR-2)', verified_at=now() where id='332a14d5-8f8e-4ac7-9764-e0ba1d606974' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.downstream_receiver_name_address
update public.fields set verification_status='verified_against_standard', verification_quote='k) name and address of the receiving organizations; — printed p.17', verification_note='VA-verified 2026-09-08 (§8 k), printed p.17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='3bead1b5-0225-43a1-8b0d-152272d1a701' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.downstream_shipment_address
update public.fields set verification_status='verified_against_standard', verification_quote='l) shipment address; — printed p.17', verification_note='VA-verified 2026-09-08 (§8 l), printed p.17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='de30d2b4-af2d-4cde-b32b-5ba08bd0fc31' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.outputs_routing_percentage
update public.fields set verification_status='verified_against_standard', verification_quote='m) percentage of the total amount of outputs routed towards different clients and final treatment pathways (See Annex B), identifying types of products, components or materials; — printed p.17', verification_note='VA-verified 2026-09-08 (§8 m), printed p.17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='7d875dbb-6d38-47e4-9742-ea5164217bc3' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.downstream_unique_reference
update public.fields set verification_status='verified_against_standard', verification_quote='n) unique reference number (e.g. products or components identification or batch number) generated with commonly accepted code systems; if not available, the organization should assign one; — printed p.17', verification_note='VA-verified 2026-09-08 (§8 n), printed p.17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014] — CAVEAT: the assignment half of n) is a "should" (recommendation), the data item itself is under the "shall cover at a minimum" list', verified_at=now() where id='8639fd20-9d8e-4193-9038-6f9ab3679edc' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.depollution_info_accompanies
update public.fields set verification_status='verified_against_standard', verification_quote='Where depollution is carried out, the recoverable resources that have been depolluted shall be accompanied by the following related information when receiving them from upstream or delivering them downstream: — the component, materials, substances or mixtures fully or partially removed; — presence of declared hazardous substances and their concentration; — documentation that demonstrates that the removed components, materials, substances or mixtures have been routed to proper treatment for recovery or final treatment. — printed p.17', verification_note='VA-verified 2026-09-08 (§8, printed p.17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='21d1aeb2-c748-435c-9946-788ce7614baf' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.traceability_claims_recognized_model
update public.fields set verification_status='verified_against_standard', verification_quote='Where the organization intends to communicate about the traceability of the materials, the claims of the organization shall adhere to a recognized model (such as ISO 22095 or an equivalent one). — printed p.17', verification_note='VA-verified 2026-09-08 (§8, printed p.17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='49f94ac7-7d65-4d11-ac23-c76fb36fe916' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.traceability_data_made_available
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall ensure that the relevant requirements for implementation of the traceability system applied are made available effectively across all relevant interested parties, including workers and suppliers with whom the organization has contractual relationships. | Traceability data shall be made available to the organization’s immediate downstream and upstream organizations who may require it. — printed p.17/17', verification_note='VA-verified 2026-09-08 (§8, printed p.17/17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='e38c96cd-8bee-4b85-a2a4-16ccf6bca602' and verification_status not in ('verified_against_standard','corrected');
-- ISO-59014-10.traceability_system_reviewed
update public.fields set verification_status='verified_against_standard', verification_quote='The organization shall determine the internal and external communication relevant to the traceability system applied and develop relevant policies and procedures. | The organization shall undertake regular reviews of the effectiveness of the traceability system and revise any aspect found to be ineffective. — printed p.17/17', verification_note='VA-verified 2026-09-08 (§8, printed p.17/17) [VA · source = ISO/DIS 59014:2023 ballot DRAFT, not the published ISO 59014]', verified_at=now() where id='ab918380-5ef4-45fd-b211-45fa5a2307f6' and verification_status not in ('verified_against_standard','corrected');

-- app/project metadata — exempt per the 2026-08-01 metadata ruling
-- ISO-59014-01.standard_edition
update public.fields set verification_status='inferred_from_worksheet', verification_note='VA-pass 2026-09-08: app/project metadata — the guideline does not define this field; exempt per the 2026-08-01 metadata ruling', verified_at=now() where id in ('b96b8ad7-69bd-4961-b6ce-436598e1ffd7') and verification_status not in ('verified_against_standard','corrected');
