-- VDI-3814-Blatt-2-1 — md verification pack (2026-09-05 pass, run 2026-09-07)
-- Source md : C:\Users\Ekowai\Desktop\Guidelines\DWA DIN Scribd\VDI-3814-Blatt-2\VDI-3814-Blatt-2.md
--             (folder is named "VDI-3814-Blatt-2"; the file's own title block reads "VDI 3814 Blatt 2.1 / Part 2.1",
--              Januar 2019, Ausg. deutsch/englisch, Weissdruck. Sibling PDF: ../VDI-3814-Blatt-2-1.pdf)
-- Pages     : the transcript carries "===== PAGE N =====" markers that coincide 1:1 with the printed page
--             numbers in the running heads ("- 4 - VDI 3814 Blatt 2.1"); the TOC page numbers confirm the
--             mapping. Every quote carries its page ONCE at the end.
-- Artefacts : the pdftotext transcript of this two-column bilingual print occasionally splits a word across
--             the column break ("k urze", "di e", "s ystematische", "Verantwortungsbe- reich"). Those are
--             quoted AS THEY STAND in the transcript rather than silently repaired, so every quote stays
--             byte-verifiable against it (spotcheck-pack.mjs --all: 68/68 >= 85%, mean 99%).
-- Lists     : bullet items are joined with " | " (house style); an omitted run inside one clause is [...].
-- Grade     : [VC] markdown-verified (SR-3: PDF not read this session).
-- Counts    : 69 fields examined / 68 quoted / 1 exempt / 0 residue / 0 equations (none encoded).
-- Rollback  : rollback-vdi-3814-blatt-2-1-md-verification-pack.sql

-- VDI-3814-Blatt-2-1-01 · standard_geltungsbereich
update public.fields set verification_status='verified_against_standard', verification_quote='Die Richtlinienreihe VDI 3814 gilt für die Automation von Gebäuden und Immobilienportfolios. Da die GA dort fachübergreifend die Funktionalität aller Räume (Raumautomation) und Anlagen (Anlagenautomation) inklusive der Managementfunktionen während deren Betrieb und Nutzung bestimmt, gilt diese Richtlinie somit in den Bereichen jener Gewerke, deren Funktionalität durch GA, auch teilweise, erzielt wird [...] — printed p.4', verification_note='md-verified 2026-09-05 (§1, printed p.4) [VC]', verified_at=now() where id='ba3f9398-8a3d-4e48-8e50-c614dca5fa8b' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-01 · planungshandbuch_vorhanden
update public.fields set verification_status='verified_against_standard', verification_quote='Planungshandbuch Bestandteil des zwischen dem Fachplaner (Auftragnehmer – AN) und dem Auftraggeber (AG) geschlossenen Vertrags, der die Grundlage der planerischen Vorgaben des jeweiligen Gewerks beschreibt | Anmerkung 2: Ein Planungshandbuch im Bereich der GA/ Systemintegration muss (z. B. in einem Baukasten) eine makrobasierende Darstellung der einzusetzenden/auszuwählenden Systeme, Automationseinrichtungen, Feldgeräte, Kommunikationsprotokolle und GA-Funktionen beinhalten. — printed p.4-5', verification_note='md-verified 2026-09-05 (§3, printed p.4-5) [VC]', verified_at=now() where id='fb8c57bd-14e6-4dcb-b84d-0ad50b1c92c2' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · projektname
update public.fields set verification_status='verified_against_standard', verification_quote='Eine eindeutige Bezeichnung für das Projekt (Projektname) ist zu vergeben [...] Die Projektbezeichnung ist als Bestandteil der Dokumentenstruktur im gesamten Lebenszyklus des Projekts für alle Dokumente und die Kommunikation mit dem AG durchgängig zu verwenden. — printed p.6', verification_note='md-verified 2026-09-05 (§6.3.1, printed p.6) [VC]', verified_at=now() where id='4e75369f-a330-4cac-8780-c8611f59cc53' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · projektnummer
update public.fields set verification_status='verified_against_standard', verification_quote='Eine eindeutige Bezeichnung für das Projekt (Projektname) ist zu vergeben und es ist gegebenenfalls eine Abkürzung für die Projektbezeichnung festzulegen (insbesondere bei sehr langen Projektbezeichnungen empfehlenswert) sowie eventuell eine eindeutige Projektnummer. — printed p.6', verification_note='md-verified 2026-09-05 (§6.3.1, printed p.6) [VC] — the standard makes the Projektnummer optional ("eventuell") — is_required=false is source-consistent', verified_at=now() where id='b14b13f5-1217-41ee-9bee-bdceeae0561c' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · ag_name
update public.fields set verification_status='verified_against_standard', verification_quote='Grundlegende Informationen zum AG, z. B.: | Name, Adresse | Organisationsform | Vertreter/Bevollmächtigter — printed p.6', verification_note='md-verified 2026-09-05 (§6.2, printed p.6) [VC] — the list is introduced with "z. B." — exemplary, not an exhaustive normative list', verified_at=now() where id='340fd7b7-2e6f-4d29-9e4a-a0dcd2a78c3f' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · ag_organisationsform
update public.fields set verification_status='verified_against_standard', verification_quote='Grundlegende Informationen zum AG, z. B.: | Name, Adresse | Organisationsform | Vertreter/Bevollmächtigter — printed p.6', verification_note='md-verified 2026-09-05 (§6.2, printed p.6) [VC] — the list is introduced with "z. B." — exemplary, not an exhaustive normative list', verified_at=now() where id='7b4d8a18-fa5d-4be8-acb1-b34385aef2d3' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · ag_vertreter
update public.fields set verification_status='verified_against_standard', verification_quote='Grundlegende Informationen zum AG, z. B.: | Name, Adresse | Organisationsform | Vertreter/Bevollmächtigter — printed p.6', verification_note='md-verified 2026-09-05 (§6.2, printed p.6) [VC] — the list is introduced with "z. B." — exemplary, not an exhaustive normative list', verified_at=now() where id='a65194f9-987a-4e1a-942c-3ca7c5ca7692' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · ag_projektleiter
update public.fields set verification_status='verified_against_standard', verification_quote='Grundlegende Informationen zum AG, z. B.: [...] | Projektleiter und dessen Verantwortungsbe- reich, Befugnisse und Kompetenzen — printed p.6', verification_note='md-verified 2026-09-05 (§6.2, printed p.6) [VC] — hyphenation "Verantwortungsbe- reich" is a column-break artifact of the transcript, quoted as printed', verified_at=now() where id='1f9d268f-9aa8-4b8c-bfe4-e47c9913cef8' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · ag_zusatzinfo
update public.fields set verification_status='verified_against_standard', verification_quote='Grundlegende Informationen zum AG, z. B.: [...] | gegebenenfalls weitere wichtige Informationen (z. B. vorsteuerabzugsberechtigt, unterliegt dem öffentlichen Beschaffungsrecht) — printed p.6', verification_note='md-verified 2026-09-05 (§6.2, printed p.6) [VC]', verified_at=now() where id='0787414f-abbc-4093-87dc-2c71367d8fd5' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · projekthintergrund
update public.fields set verification_status='verified_against_standard', verification_quote='Informationen zur Entstehungsgeschichte des Projekts: Was war der Auslöser für das Projekt (z. B. zusätzlicher Platzbedarf wegen der Einführung eines neuen Produkts, Markteinflüsse, [...]), welche historischen Entwicklungen führten zum Projekt? — printed p.6-7', verification_note='md-verified 2026-09-05 (§6.3.2, printed p.6-7) [VC]', verified_at=now() where id='5dfd97a0-5926-4e2f-9a0c-3c654e04464c' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · projekt_kurzbeschreibung
update public.fields set verification_status='verified_against_standard', verification_quote='Hier erfolgt eine k urze Beschreibung der Inhalte des Projekts als Überblick, warum das Projekt durchgeführt und was du rch das Projekt erreicht werden soll. Die Informationen dienen der Einführung und schnellen Übersicht und sind im Folgenden weiter zu detaillieren. — printed p.7', verification_note='md-verified 2026-09-05 (§6.3.3, printed p.7) [VC]', verified_at=now() where id='023cff61-6d9b-4b65-ada6-42fdcd4a5fe4' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · projektumfang
update public.fields set verification_status='verified_against_standard', verification_quote='Es folgt eine detaillierte, eindeutige Beschreibung der Leistungen, die innerhalb des Projekts zu erbringen sind. Gegebenenfalls wird auf Projektschnittstellen zur Abgrenzung der Leistungen oder die Leistungen anderer am Projekt Beteiligter (Projektsteuerer, Planer, ausführende Firmen, AG) verwiesen. — printed p.7', verification_note='md-verified 2026-09-05 (§6.3.4, printed p.7) [VC]', verified_at=now() where id='7afe3fbb-b5b2-4a16-8cb7-0d902bd5542b' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · ziel_beschreibung
update public.fields set verification_status='verified_against_standard', verification_quote='Die Ziele des AG sind zu beschreiben . Diese können z. B. sein: | Terminziele (Zeiträume, Meilensteine usw.) | Kostenziele (Budget, Lebenszyklusorientierung Finanzierung usw.) | Qualitätsziele (Nutzwert, Nachhaltigkeit usw.) — printed p.7', verification_note='md-verified 2026-09-05 (§6.4.1, printed p.7) [VC]', verified_at=now() where id='e22edd60-f126-4302-97f1-394d786c97ff' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · ziel_rang
update public.fields set verification_status='verified_against_standard', verification_quote='Anmerkung: Es empfiehlt sich, diese und gegebenenfalls zusätzliche Ziele als Haupt- und Nebenziele zu spezifizieren. Hauptziele sind unbedingt zu erreichen, Nebenziele müssen nicht zwingend erreicht werden. — printed p.7', verification_note='md-verified 2026-09-05 (§6.4.1 Anmerkung, printed p.7) [VC] — source is an Anmerkung and soft ("empfiehlt sich") — is_required=false is source-consistent', verified_at=now() where id='e60e8022-1b62-4b05-b28f-53949c1c2483' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · prioritaeten_matrix
update public.fields set verification_status='verified_against_standard', verification_quote='Eine der wichtigsten Bestandteile einer Bedarfsermittlung ist die Priorisierung der Ziele. Bei der Festlegung der Prioritäten ist zu beachten, dass zwischen den einzelnen Zielen Wechselwirkungen bestehen, die unbedingt beachtet und mit dem AG abgestimmt werden müssen. | Hierzu empfiehlt es sich, die wichtigsten Parameter für die Bewertung der Qualitäts-, Kosten- und Terminziele strukturiert zu erfassen (z. B. in Form einer Matrix) und mit Prioritäten zu versehen. — printed p.7-8', verification_note='md-verified 2026-09-05 (§6.4.2, printed p.7-8) [VC] — the matrix form itself is only "empfiehlt es sich" (soft) — see STAGED file', verified_at=now() where id='a861774c-0a3f-4816-b080-49110f831c72' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · projektschnittstellen
update public.fields set verification_status='verified_against_standard', verification_quote='Werden zum Projekt weitere Parallelprojekte durchgeführt oder Eigenleistungen vom AG erbracht, entstehen Schnittstellen. | Die Projektschnittstellen sind jeweils einzeln und im Detail zu definieren und zu beschreiben, sofern diese nicht bereits auf andere Weise dokumentiert sind (z. B. in einem Projekt- oder Organisationshandbuch). — printed p.8-9', verification_note='md-verified 2026-09-05 (§6.5, printed p.8-9) [VC] — the obligation is scoped (only if parallel projects/Eigenleistungen exist) and carries an exemption ("sofern ... nicht bereits ... dokumentiert") — see STAGED file', verified_at=now() where id='6ccafd3d-c505-4010-bac0-39292f9d18a9' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · nutzungsprozess_beschreibung
update public.fields set verification_status='verified_against_standard', verification_quote='Es wird empfohlen, jeden Nutzungsprozess mittels einer Prozessbeschre ibung zu dokumentieren. | In den Prozessbeschreibu ngen ist z. B. zu dokumentieren: | Beschreibung des Prozessablaufs (Art/Zweck, Art/Anzahl Personen, Besucher, Arbeitsmittel usw.) | Nutzungszeiten/Ausführungszeiten des Prozesses | Schnittstellen zu anderen Prozessen (Logistik) | erforderliche Ausstattung und technische Ausrüstung für den Prozess | besondere Anforderungen [...] | Nutzereingriffe als Bedienung der Gebäudetechnik — printed p.9-10', verification_note='md-verified 2026-09-05 (§6.6, printed p.9-10) [VC] — the source is a recommendation ("Es wird empfohlen") — see STAGED file', verified_at=now() where id='a40abf3f-d093-4e60-bb28-e65ec5466fc6' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · nutzungsprozess_typ
update public.fields set verification_status='verified_against_standard', verification_quote='Eine Typisierung von Nutzungsprozessen kann z. B. erfolgen nach deren Art: | Sachbearbeitung, einfach | Sachbearbeitung, mehrfach (Open Space) | Sachbearbeitung, barrierefrei | Lagerung | Montage | Produktion | Kopieren, Drucken, Plotten — printed p.9-10', verification_note='md-verified 2026-09-05 (§6.6, printed p.9-10) [VC] — list is exemplary ("kann z. B."); the encoded enum reproduces exactly these 7 values and adds none', verified_at=now() where id='ca331e05-2a4b-433b-b7ef-4d98b189bfa0' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · funktionale_einheit
update public.fields set verification_status='verified_against_standard', verification_quote='Nutzungsprozesse können in den funktionalen Einheiten „Segment", „Raum", „Bereich", „Gebäude" und „Liegenschaft" stattfinden, siehe auch „ Schalenmodell" (VDI 3814 Blatt 1, Abschnitt 5.5). — printed p.9', verification_note='md-verified 2026-09-05 (§6.6, printed p.9) [VC] — the Schalenmodell itself lives in VDI 3814 Blatt 1 — NR from this Blatt', verified_at=now() where id='da26842a-c0d4-4279-896d-682364034307' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-02 · bestandsdokumente
update public.fields set verification_status='verified_against_standard', verification_quote='Die Bestandserfassung versteht sich als eine s ystematische Erfassung und Beschreibung der Dokumente, die bereits beim AG vorliegen und für das betrachtete Projekt rel evante Anforderungen enthalten. Dies können unter anderem sein: | Lastenhefte/Werksnormen (z. B. für GA, Managementsysteme, Informationstechnik) | sonstige Richtlinien und AG-Vorgaben — printed p.10', verification_note='md-verified 2026-09-05 (§6.7, printed p.10) [VC]', verified_at=now() where id='7759fd92-eb26-46df-89ac-c2060fbad76c' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · betreiberkonzept_ziele
update public.fields set verification_status='verified_against_standard', verification_quote='Die Ziele eines Betreiberkonzepts sind: | eine wirtschaftliche Betriebsführung | ein durchgängiges Konzept zur optimalen Nutzung der betrieblichen Einrichtungen | ein umfassendes „Werkzeug" zur Betrachtung, Analyse und Optimierung aller kostenrelevanten Vorgänge der zu betreibenden Objekte [...] | Grundlage eines Kennzahlensystems (Benchmarking) [...] | Basis für einzusetzende Computer-aided-Facility-Management(CAFM)-Systeme | Dokumentation der Umsetzung von Prioritäten (Gebäude-, Anlagen-, Ereignis- usw.) und SLA durch die GA — printed p.11', verification_note='md-verified 2026-09-05 (§7.2, printed p.11) [VC]', verified_at=now() where id='7105b02c-cc48-492a-ad7d-8ea47c75aff2' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · betreiben_teilleistungen
update public.fields set verification_status='verified_against_standard', verification_quote='Für das Betreiben mittels GA sind im Allgemeinen folgende Teilleistungen relevant: | Bedienen und Beobachten | Messen, Steuern, Regeln | Überwachen | Erfassen von Ereignissen | Beheben von Störungen | Erfassen von Verbrauchswerten | Optimieren | Instandhalten | Technisches Monitoring | Berichtswesen und Dokumentation — printed p.12', verification_note='md-verified 2026-09-05 (§7.2, printed p.12) [VC]', verified_at=now() where id='3867c2ec-0c3f-4ba1-957c-3e340c5953a7' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · auslegungsparameter_ga
update public.fields set verification_status='verified_against_standard', verification_quote='Aus den generellen Anforderungen aus dem Betreiberkonzept sind die erforderlichen Auslegungsparameter für die GA abzuleiten, wie | die Anzahl und Ausstattung der erforderlichen Bedien- und Beobachtungseinrichtungen, | die Datenschnittstellen zum CAFM und sonstigen besonderen Anwendungen, | die Vorgaben an Benutzeroberflächen, | die Art, Struktur und IT-Einbindung der erforderlichen Management- und Bediensysteme, | die GA-Bedienkonzepte, | die GA-Organisationsstruktur, und | die Benutzergruppen/Zugriffsrechte usw. — printed p.13-14', verification_note='md-verified 2026-09-05 (§7.2, printed p.13-14) [VC]', verified_at=now() where id='ab629c33-d0af-4834-bbe1-0ff758b7629b' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · betreiberkonzept_nutzer
update public.fields set verification_status='verified_against_standard', verification_quote='Nutzer des Betreiberkonzepts sind alle, die innerhalb einer Liegenschaft oder eines Projekts auf die über die Strukturen der GA erfassten und bereitgestellten Daten oder auf die Ergebnisse der Auswertungen dieser Daten zugreifen. Das sind beispielsweise: | Gebäudeeigentümer | Gebäude-/Objektverantwortliche | Betreiber (intern und extern) | externe Dienstleister — printed p.14', verification_note='md-verified 2026-09-05 (§7.3, printed p.14) [VC] — list is exemplary ("Das sind beispielsweise") — the encoded enum reproduces exactly these 4 and adds none', verified_at=now() where id='9290c244-c1ff-43d5-b9da-ca3eb1931227' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · zu_betreibende_objekte
update public.fields set verification_status='verified_against_standard', verification_quote='Hier sind in Anlehnung an das Schalenmodell gemäß VDI 3814 Blatt 1 die von dem zu erstellenden/anzupassenden Betreiberkonzept eingeschlossenen Liegenschaften mit ihren Gebäuden, Bereichen und gegebenenfalls speziellen Räumen (Raumtypen) und Sondernutzungsflächen aufzulisten. — printed p.14', verification_note='md-verified 2026-09-05 (§7.4, printed p.14) [VC]', verified_at=now() where id='3fdb8e28-94cd-4354-9610-650597aa9b98' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · betreiberstruktur
update public.fields set verification_status='verified_against_standard', verification_quote='Hierfür ist mindestens di e Betreiberstruktur darzustellen. Dies ist nach Möglichkeit mit Nennung der Anzahl der Mitarbeiter in den jeweiligen Zuständigkeitsbereichen und Namen der verantwortlichen Mitarbeiter oder der durch Aufträge gebundenen Fremdfirmen für die na chfolgenden Bereiche zu spezifizieren, z. B.: — printed p.14', verification_note='md-verified 2026-09-05 (§7.5, printed p.14) [VC]', verified_at=now() where id='dcb72784-ac94-4f5e-b7e3-b865fa3ea866' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · betreibermodell
update public.fields set verification_status='verified_against_standard', verification_quote='Dabei ist für die Betreiberorganisation zu unterscheiden zwischen: | Betreiben mit eigenem Personal (Eigenbetreiben) | Betreiben mit fremdem Personal (Fremdbetreiben) | Kombinationen von Eigenbetreiben und Fremdbetreiben — printed p.15', verification_note='md-verified 2026-09-05 (§7.6, printed p.15) [VC]', verified_at=now() where id='170a96af-afa6-42af-a71e-94d49f4c26e6' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · betreiber_arbeitszeiten
update public.fields set verification_status='verified_against_standard', verification_quote='In Abhängigkeit vom Nutzungsprozess und den daraus resultierenden Nutzungszeiten ist zu berücksichtigen, dass das zum Betreiben und Instandhalten der technischen Anlagen erforderliche Personal entsprechend zur Verfügung steht und mit den notwendigen Informationen versorgt wird. Hierbei ist gegebenenfalls eine unterschiedliche Tiefe des Betreibens innerhalb der Arbeitszeit, Bereitschaftszeit und Instandhaltungszeit zu beachten. — printed p.16', verification_note='md-verified 2026-09-05 (§7.6.4, printed p.16) [VC]', verified_at=now() where id='52fbe391-a0a2-4c69-8403-8edbcb3c993b' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · gewerke_anlagen_systeme
update public.fields set verification_status='verified_against_standard', verification_quote='Zur eindeutigen Festlegung der durch das GA-Betreiberkonzept zu betrachtenden Gewerke, Anlagen und Systeme kann Tabelle 1 aus VDI 3814 Blatt 2.2 genutzt werden. Für jede Kostengruppe nach DIN 276-1 werden die zu berücksichtigenden Funktionen sowie die Art des Datenaustauschs mit der Kennzeichnung der Richtung des beabsichtigten Datenflusses angegeben. — printed p.16', verification_note='md-verified 2026-09-05 (§7.6.5, printed p.16) [VC] — the actual table lives in VDI 3814 Blatt 2.2 and the cost groups in DIN 276-1 — NR from this Blatt', verified_at=now() where id='e9dfcd63-58f7-424f-9a25-78aa24a2b651' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · gebaeude_prioritaet
update public.fields set verification_status='verified_against_standard', verification_quote='Die Vergabe der Gebäudeprio ritäten hat einvernehmlich in Abstimmung zwischen den Gebäudeeigentümern und/oder den Betreibern/Nutzern vor oder spätestens mit dem Beginn der technischen Planung zu erfolgen. Die Prioritätsfestlegung für die weitere Bearbeitung im Störfall-, Meldungs- und Informations- management kann wie folgt geschehen: | sehr hoch | hoch | mittel | niedrig — printed p.17', verification_note='md-verified 2026-09-05 (§7.7.1, printed p.17) [VC]', verified_at=now() where id='32ad5803-8c41-4e07-9534-6708830fa27a' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · anlagen_prioritaet
update public.fields set verification_status='verified_against_standard', verification_quote='Anlagen, die für die Gebäude-/Bereichsversorgung zuständig sind (z. B. Kälteversorgung Rechenzentrum), sind mit einer Anlagenpriorität zu versehen, die mindestens der Gebäudepriorität entspricht. | Die Anlagenprioritäten sind vor oder spätestens mit Beginn einer Planung mit dem AG abzustimmen. Die Anlagenpriorität kann z . B. in drei Stufen unterschieden werden [...] | hoch | mittel | niedrig — printed p.18-19', verification_note='md-verified 2026-09-05 (§7.7.1, printed p.18-19) [VC]', verified_at=now() where id='1941514b-58a4-4ef3-9a37-c68b674db8ad' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · sla_definition
update public.fields set verification_status='verified_against_standard', verification_quote='Das zentrale Element dieser Dienstgütevereinbarung ist die Leistungsqualität (z. B. Verfügbarkeit einer klimatechnischen Anlage von 99,98 %). | Folgende Inhalte und Ziele sind in Bezug auf die Erfüllung der vereinbarten Dienstleistungen zwischen AG und AN festzulegen und beeinflussen mittelbar den Einsatz und das Ausmaß der GA: | Rollen, Leistungsbeiträge und Verantwortlichkeiten der Beteiligten | Parameter zur Beurteilung der Dienstleistungsqualität | Prozedur zur Schlichtung von Meinungsunterschieden zwischen den Vertragspartnern — printed p.19', verification_note='md-verified 2026-09-05 (§7.7.2, printed p.19) [VC] — the 99,98 % is an explicit "z. B." example, NOT a normative availability limit', verified_at=now() where id='131c3d2c-6427-4778-9fb1-3ae243c8157c' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-03 · performance_indikatoren
update public.fields set verification_status='verified_against_standard', verification_quote='Zur Kontrolle der Erreichung dieser Zielvorgaben gemäß der SLA werden Leistungserfüllungsindikatoren („performance indicators") verwendet, die mittels der GA überwacht und dem TGM zur Verfügung gestellt werden können, siehe auch VDI 3810 Blatt 5. — printed p.20', verification_note='md-verified 2026-09-05 (§7.7.2, printed p.20) [VC] — descriptive/optional ("können") — is_required=false is source-consistent', verified_at=now() where id='7c092551-8ea1-4916-ad6f-7093887a7fd5' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-04 · lastenheft_erstellt
update public.fields set verification_status='verified_against_standard', verification_quote='Ein GA-Lastenheft stellt die Anforderungen des AG hinsichtlich Bedarf, Nutzung, Liefer- und Leistungsplanung dar und wird sinnvollerweise im Rahmen der Bedarfsplanung oder parallel dazu erstellt. Die Ergebnisse einer Bedarfsplanung sind sinnvollerweise in einem Lastenheft zu dokumentieren. — printed p.20', verification_note='md-verified 2026-09-05 (§8.1, printed p.20) [VC] — soft ("sinnvollerweise"); §8.1 explicitly allows dispensing with a Lastenheft ("Beim Verzicht auf die Erstellung/Verwendung von GA-Lastenheften ...") — see STAGED file', verified_at=now() where id='fc9978b0-ef39-4a9c-8aa5-b54ec69f2e3e' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-04 · redundanz_vorgaben
update public.fields set verification_status='verified_against_standard', verification_quote='Grundsätzlich sind zusätzlich zu den Festlegungen in Abschnitt 8.2 bis Abschnitt 8.14 die folgenden Aspekte zu beachten: | Vorgaben an notwendige Redundanzen für alle Bereiche der GA-Systeme — printed p.21', verification_note='md-verified 2026-09-05 (§8.1, printed p.21) [VC]', verified_at=now() where id='039e2fb0-8224-468a-9b07-185515bd51ea' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-04 · mech_elektr_umgebung
update public.fields set verification_status='verified_against_standard', verification_quote='Grundsätzlich sind zusätzlich zu den Festlegungen in Abschnitt 8.2 bis Abschnitt 8.14 die folgenden Aspekte zu beachten: [...] | einzuhaltende Merkmale hinsichtlich der Mechanik, Elektrik und der Umgebungsbedingun- gen, z. B. Schutzklassen, EMV, Überspannungsschutz und gegebenenfalls Ex-Schutz — printed p.21', verification_note='md-verified 2026-09-05 (§8.1, printed p.21) [VC]', verified_at=now() where id='bb93fa4a-b0bf-46d8-8004-80e708a1da39' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-04 · datenkommunikationsprotokoll
update public.fields set verification_status='verified_against_standard', verification_quote='Die funktionale, interoperable Verbindung von Einrichtungen der Raum- und Anlagenautomation, der Management- und Bedieneinrichtungen sowie zu Einrichtungen für besondere Anwendungen erfolgt mittels Kommunikationseinrichtungen, für die genormte Datenkommunikationsprotokolle vorgegeben werden sollen. | Welche Datenkommunikationsprotokolle sind eingesetzt/sollen eingesetzt werden (BACnet, KNX, Dali usw.)? — printed p.22 | p.13', verification_note='md-verified 2026-09-05 (§8.2.1 (protocol obligation) + §7.2 (the BACnet/KNX/DALI list), printed p.22 and p.13) [VC] — the three enum values are NOT printed in §8.2.1; they come from the §7.2 checklist question and that list is open ("usw.") — see STAGED file', verified_at=now() where id='28082bd0-c433-411e-b104-1dc1e4e6cf4d' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-04 · datenschnittstellen
update public.fields set verification_status='verified_against_standard', verification_quote='Die Art und Anzahl der zu verwendenden Datenschnittstellen sind zu spezifizieren. Insbesondere ist die erforderliche Interoperabilität der beteiligten Teilsysteme eindeutig festzulegen. Hierbei sind insbesondere die Datenschnittstellen zu Management- und Bedieneinrichtungen, Anlagen- und Raumautomationseinrichtungen, Feldgeräten, autarken Automationseinrichtungen und eventuellen Systemen für besondere Aufgaben zu spezifizieren. — printed p.22', verification_note='md-verified 2026-09-05 (§8.2.2, printed p.22) [VC]', verified_at=now() where id='52963d8c-01ed-42ef-8587-8d716c4b4a9a' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-04 · meldungsart
update public.fields set verification_status='verified_against_standard', verification_quote='Die Meldungen innerhalb des GA-Systems sind je nach Ursache, Art und/oder Auswirkung in verschiedene Gruppen zu unterteilen, z. B.: | Gefahrmeldungen | Sicherheitsmeldungen | Systemmeldungen | Störungsmeldungen | Warn-/Wartungsmeldungen | Handmeldungen | Trendlogmeldungen — printed p.22', verification_note='md-verified 2026-09-05 (§8.3.1, printed p.22) [VC] — list is exemplary ("z. B."); the encoded enum reproduces exactly these 7 and adds none', verified_at=now() where id='e5c7fca3-061b-4fa8-a658-cece7a5324b6' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-04 · meldungsuebertragung
update public.fields set verification_status='verified_against_standard', verification_quote='Die Automationsstationen (AS) sowie die Management- und Bedieneinrichtungen (MBE) im GA-System unterstützen die Alarm- und Ereignisbehandlung als Sender/Empfänger mit den folgenden Diensten: | Melden von Wert- und Zustandsänderungen | objektinternes Melden [...] | gegebenenfalls zusätzliches erweitertes Melden [...] | Die zu verwendende Art der Meldungsübertragung oder Kombinationen der oben genannten Verfahren sind mit dem AG abzustimmen. — printed p.23', verification_note='md-verified 2026-09-05 (§8.3.2, printed p.23) [VC]', verified_at=now() where id='57314f9a-8061-4e1f-8dba-b42069e40631' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-04 · meldungsempfaenger
update public.fields set verification_status='verified_against_standard', verification_quote='Die erforderlichen Meldungsempfänger sind mit dem AG zu definieren und die Übertragungswege zu spezifizieren. — printed p.23', verification_note='md-verified 2026-09-05 (§8.3.3, printed p.23) [VC]', verified_at=now() where id='8b1a169a-081f-479a-9690-7eead248a4a7' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-04 · meldung_zustandsuebergang
update public.fields set verification_status='verified_against_standard', verification_quote='Hierbei sind mindestens die Prioritäten für die verschiedenen Zustandsübergänge, z. B. „Meldung kommend", „Meldung gehend", „Systemmeldung", zu spezifizieren. — printed p.23', verification_note='md-verified 2026-09-05 (§8.3.3, printed p.23) [VC] — the three transitions are an explicit "z. B." list — the encoded enum closes an open list', verified_at=now() where id='a070ced1-df46-451b-80ce-c27a94677395' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-04 · meldungsquittierung
update public.fields set verification_status='verified_against_standard', verification_quote='Die Quittierungserfordernisse durch die Meldungsempfänger sind eindeutig festzulegen. Eine Notwendigkeit der Quittierung von Meldungen kann z. B. nur für bestimmte Meldungsarten, wie Störungs-, Handeingriff- und Warnmeldungen, oder aber auch für bestimmte Zustandsübergänge spezifiziert werden. — printed p.23', verification_note='md-verified 2026-09-05 (§8.3.4, printed p.23) [VC]', verified_at=now() where id='bbd31b30-62ce-4851-b6d9-f61a96c4c421' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-05 · feldgeraete_spezifikation
update public.fields set verification_status='verified_against_standard', verification_quote='Die Arten der zu verwendenden Sensoren und Aktoren sowie deren Merkmale sind gemäß den Anforderungen zu spezifizieren, z. B.: | kombinierte Sensoren | Genauigkeit | Bauform | Größe — printed p.24', verification_note='md-verified 2026-09-05 (§8.4, printed p.24) [VC]', verified_at=now() where id='9dc0a5c4-2ada-4f8d-8f34-07ad4c3413da' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-05 · automationseinrichtungen_spez
update public.fields set verification_status='verified_against_standard', verification_quote='Automationseinrichtungen (siehe auch DIN EN ISO 16484-2, Abschnitt 5.3) beinhalten sämtliche parametrierbaren, projektierbaren oder programmierbaren GA-Systemkomponenten für die Anlagen- und Raumautomation. Für diese sind neben dem zu verwendenden Datenkommunikationsprotokoll und der notwendigen Datenschnittstelleneinheiten eventuell zusätzlich notwendige Speicheranforderungen und die Art der manuellen Übersteuerungsmöglichkeiten festzulegen. — printed p.24', verification_note='md-verified 2026-09-05 (§8.5, printed p.24) [VC]', verified_at=now() where id='f125a33f-ebd3-4371-876f-a5f7d66c53d0' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-05 · projektierungstools
update public.fields set verification_status='verified_against_standard', verification_quote='Es ist mit dem AG/Nutzer festzulegen, welche Arten der projektierungs- und sonstigen system- spezifischen technischen Dienstleistungen innerhalb des GA-Systems erforderlich werden, z. B.: | Konfigurierung der Hardware | Programmierung der Anwendungsfunktionen | Konfigurierung der Management- und Bedienfunktionen | Hierfür ist zwischen dem AN und dem AG eine Übergabe/Überlassung der hierfür erforderlichen herstellerspezifischen Tools zu vereinbaren. — printed p.24', verification_note='md-verified 2026-09-05 (§8.5.1, printed p.24) [VC]', verified_at=now() where id='4ced3c64-217b-45e4-b0fc-790782d4337f' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-05 · verhalten_spannungsausfall
update public.fields set verification_status='verified_against_standard', verification_quote='Alle Folgen und Reaktionen im GA-System, die sich aus einem Versorgungsspannungsausfall und Wiederkehr ergeben, sind festzulegen, z. B.: | Meldungsunterdrückung bei Spannungsausfall | Vorgaben zur Pufferung und Sicherung von flüchtigen Speicherinhalten | Nutzung von Vorgabewerten (Defaultwerte) — printed p.24', verification_note='md-verified 2026-09-05 (§8.5.2, printed p.24) [VC]', verified_at=now() where id='08002991-b10a-47f0-967b-b1ebe127f6b3' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-05 · mbe_systemart
update public.fields set verification_status='verified_against_standard', verification_quote='Hierbei sind neben der Art des vorgesehenen Systems (webbasierendes oder Rich-Client-System oder beides) und den eventuell vorgegebenen und einzuhaltenden Betriebssystemen u. a. zu berücksichtigen: — printed p.25', verification_note='md-verified 2026-09-05 (§8.6, printed p.25) [VC]', verified_at=now() where id='8041f900-71e1-4432-ab06-91eca160c525' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-05 · mbe_anforderungen
update public.fields set verification_status='verified_against_standard', verification_quote='Hierbei sind neben der Art des vorgesehenen Systems [...] u. a. zu berücksichtigen: | Applikationen der MBE | Lizenzierung | Benutzermanagement (Benutzer-/Systemverwaltung) | grafische Benutzeroberfläche [...] | Trends | Listen | Zeit-/Kalendermanagement | Bedienung von Datenpunkten | Berichts-, Protokoll- und Reportmanagement | Sicherungs- und Rücksicherungsmanagement (Backup und Restore) | Energiemonitoring/Energiemanagement | MBE-Serverstandort | MBE-Server- und -Client-Hardware | Wartung und Pflege der MBE-Software — printed p.25', verification_note='md-verified 2026-09-05 (§8.6, printed p.25) [VC]', verified_at=now() where id='af331958-69e0-459f-93ce-ea4bec39520f' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-05 · schaltschrank_anforderungen
update public.fields set verification_status='verified_against_standard', verification_quote='Bei den Anforderungen an die Schaltschränke der GA und deren Baugruppen sind u. a. die nachfolgenden Punkte zu berücksichtigen: | Bauweise, Ausführung des Gehäuses (z. B. Farbton) | Montageplatten | Trennung, Schottung Schaltschrank | Türen, Sichttüren und Sichtfenster sowie deren Verschlüsse [...] | Schutzarten und Ausführung der Schutzmaßnahmen [...] | Netzeinspeisung [...] | Überspannungsschutz [...] | Verdrahtung, Leiterfarben | Platzreserve, maximale Füllung (in %) des Kabelkanals — printed p.25-26', verification_note='md-verified 2026-09-05 (§8.7, printed p.25-26) [VC]', verified_at=now() where id='b78900e5-ffc5-457b-89c4-729b046731f2' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-05 · it_netzwerk_anforderungen
update public.fields set verification_status='verified_against_standard', verification_quote='Es ist zu klären, ob ein separates GA-Netzwerk aufgebaut/genutzt wird oder ob eine Integration in ein vorhandenes Unternehmensnetzwerk erfolgen soll. Dies gilt auch für alle im GA-System notwendigen IT-Systeme/Infrastrukturkomponenten [...] Daraus folgend sind Vorgaben für die GA-relevanten IT-Systeme und Netzwerke festzulegen, z. B.: | Installationsanforderungen [...] | Netzwerkmanagement [...] | Verfügbarkeit und Zuverlässigkeit [...] | Hardware- und Softwarevorgaben — printed p.26-27', verification_note='md-verified 2026-09-05 (§8.8, printed p.26-27) [VC]', verified_at=now() where id='df01b3a9-52c4-4867-9522-edf8b50d4a65' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-05 · it_sicherheit
update public.fields set verification_status='verified_against_standard', verification_quote='Daraus folgend sind Vorgaben für die GA-relevanten IT-Systeme und Netzwerke festzulegen, z. B.: [...] | IT-Sicherheit (siehe auch VDMA 24774) | Herstellerebene | Projektierungsebene | Inbetriebnahmeebene | Wartungsebene | Fernservice | Benutzerebene — printed p.26-27', verification_note='md-verified 2026-09-05 (§8.8, printed p.26-27) [VC] — IT-Sicherheit appears only as a bullet inside an exemplary ("z. B.") list — see STAGED file', verified_at=now() where id='d2a2e9fc-3070-44ae-b61c-035edcc34991' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · ga_funktionen
update public.fields set verification_status='verified_against_standard', verification_quote='Die Funktionen der GA werden in VDI 3814 Blatt 3.1 und VDI 3814 Blatt 3.2 beschrieben. Die Auswahl und Verwendung der Funktionen ist in Abhängigkeit von der beschriebenen Automationsaufgabe vorzunehmen. Hilfsmittel dazu werden in VDI 3814 Blatt 4.3 angeboten. — printed p.27', verification_note='md-verified 2026-09-05 (§8.9, printed p.27) [VC] — the function catalogue itself lives in VDI 3814 Blatt 3.1/3.2 — NR from this Blatt', verified_at=now() where id='c3de2a94-b86a-4fd4-b247-756857b79aa6' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · energieeffizienzklasse
update public.fields set verification_status='verified_against_standard', verification_quote='Die anzustrebende Energieeffizienzklasse gemäß DIN EN 15232 ist festzulegen. — printed p.27', verification_note='md-verified 2026-09-05 (§8.10, printed p.27-28) [VC] — the class values (A/B/C/D) are defined in DIN EN 15232, not here — NR from this Blatt', verified_at=now() where id='69e81e36-5938-489e-85fc-5dfc517c883c' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · historisierung_vorgaben
update public.fields set verification_status='verified_against_standard', verification_quote='Die notwendigen Vorgaben bezüglich der Historisierung der Datenspeicherung sind festzulegen, insbesondere wenn es Anforderungen an die historische Speicherdauer gibt oder die Daten gegen jegliche Veränderung zu schützen sind (Audit Trail). Dabei ist mindestens die Art der Speicherung unter Beachtung eventueller Datenbegrenzungen und der zu verwendenden Speichermedien zu definieren. — printed p.28', verification_note='md-verified 2026-09-05 (§8.11, printed p.28) [VC]', verified_at=now() where id='56a6d0bd-861e-4835-8910-4b2e502d40a2' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · aufzeichnung_aufloesung
update public.fields set verification_status='verified_against_standard', verification_quote='Für alle zu erfassenden und aufzuzeichnenden Größen sind die einzustellenden Auflösungen bezogen auf die zugehörigen Einheiten (z. B. 0,1 °C bei Temperaturaufzeichnungen) sowie die Genauigkeit der Zeitstempel vorzugeben. [...] Typische Auflösungen sind Tabelle 1 zu entnehmen. | Tabelle 1. Beispiele für Auflösungen zu erfassender Größen — Messgröße Auflösung Einheit — Raum-/Außentemperatur 0,1 °C — Druck 0,01 bar — Energie – Strom 0,1 Wh — CO2 10 ppm — printed p.28-29', verification_note='md-verified 2026-09-05 (§8.11 / Tabelle 1, printed p.28-29) [VC] — Tabelle 1 is explicitly captioned "Beispiele" — the resolutions are exemplary, not normative limits; is_required=false is source-consistent', verified_at=now() where id='782f9bc0-2982-4e18-a6d1-3c7f6d08ee59' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · cafm_schnittstellen
update public.fields set verification_status='verified_against_standard', verification_quote='Bei der Bedarfsplanung der GA ist grundsätzlich eine Prüfung von Schnittstellen zu anderen Systemen des CAFM zu berücksichtigen. [...] Diese Schnittstellen sind im Rahmen der Planung der GA systematisch zu beschreiben. Dabei sind die Anforderungen des CAFM an die GA zu berücksichtigen. — printed p.29', verification_note='md-verified 2026-09-05 (§8.12, printed p.29) [VC]', verified_at=now() where id='6a78de40-50ed-449b-98ae-8771f083871f' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · systemselbstueberwachung
update public.fields set verification_status='verified_against_standard', verification_quote='Für jedes Projekt sind Anforderungen an die Funktionen der Systemselbstüberwachung und an die Systemreaktionen von Feldgeräten, Automations- sowie Management- und Bedieneinrichtungen im Fehlerfall festzulegen. Für die Überwachung (z. B. Sensorüberwachung, Watchdog-Funktion, Netzwerkkommunikation) und Diagnose (z. B. mittels Protokoll-Analyser) sind bei Bedarf geeignete Funktionen und Hilfsmittel vorzusehen. — printed p.30', verification_note='md-verified 2026-09-05 (§8.13.1, printed p.30) [VC]', verified_at=now() where id='fe50794d-106d-4311-b9b0-026c5502d42b' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · systemzeitverwaltung
update public.fields set verification_status='verified_against_standard', verification_quote='Die Verwaltungsmethoden hinsichtlich Uhrzeit, Datum, Kalender und Zeitzonen sind f ür das gesamte GA-System einheitlich anzugeben. Dabei sind mindestens folgende Punkte festzulegen: | Art der Uhr (Funkuhr, interne oder externe Zeitserver usw.) | externe/interne Uhr und Übernahme bei Teilausfällen | Auflösung und Genauigkeit der Systemzeit | Synchronisation der Zeit im Gesamtsystem | Nutzung unterschiedlicher Zeitzonen und Sommer-/Winterzeitumschaltung | Anpassung von Uhrzeit, Datum, Zeitzonen — printed p.30', verification_note='md-verified 2026-09-05 (§8.13.2, printed p.30) [VC]', verified_at=now() where id='b1160305-fb7b-47fe-8c45-ec0a28058149' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · datenimport_export
update public.fields set verification_status='verified_against_standard', verification_quote='Die notwendigen Datenimport funktionen und Datenexportfunktionen sind eindeutig für alle relevanten Schnittstellen des GA-Systems (z. B. Systeme für besondere Aufgaben) festzulegen. — printed p.30', verification_note='md-verified 2026-09-05 (§8.13.3, printed p.30) [VC]', verified_at=now() where id='95307fb2-aca4-463a-9b8c-29b9baeb431e' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · zugriffsebene
update public.fields set verification_status='verified_against_standard', verification_quote='Um das System vor Missbrauch zu sch ützen, müssen mehrere Zugriffsebenen, die in Profilen definiert sind, f ür alle dialogorientierten Bedienerschnittstellen zur Verf ügung stehen. Die Anzahl und Bedeutung dieser Zugriffsebenen sind festzulegen, z. B.: | kein Passwort | nur Lesen | beschränkter Zugriff auf ausgewählte Informationen | Ebene 1 | Es ist nur tägliche Routinebedienung erlaubt. | Ebene 2 | Zugriff des Bedieners auf alle nicht konfigurierbaren Funktionen | Ebene 3 | Bearbeitungszugriff, erforderlich zur Konfigurierung des gesamten Systems — printed p.30-31', verification_note='md-verified 2026-09-05 (§8.13.4, printed p.30-31) [VC] — the four levels are an explicit "z. B." list — the encoded enum closes an open list', verified_at=now() where id='925edbd8-54f3-4c61-9313-b059f9b43542' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · aktivitaetenspeicher
update public.fields set verification_status='verified_against_standard', verification_quote='Es ist festzulegen, in welcher Form System-, Ereignis- sowie Bedieneraktivitäten und gegebenenfalls zusätzliche Nutzerdaten aufzuzeichnen und zu speichern sind. Der Umfang der aufzuzeichnenden Bedienvorgänge für nachfolgendes Anzeigen auf einem Bildschirm, Ausdrucken und Archivieren ist festzulegen. [...] Hierbei sind der gesetzliche Datenschutz und die Datenschutzvorgaben des jeweiligen AG zu beachten. — printed p.31', verification_note='md-verified 2026-09-05 (§8.13.5, printed p.31) [VC]', verified_at=now() where id='eeb0a8a4-9a32-4278-a3d1-175a688b876e' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · datensicherung_konzept
update public.fields set verification_status='verified_against_standard', verification_quote='Der Prozess zum Erstellen einer Sicherung sowie das Verifizieren und Rekonstruieren des Datenbestands müssen Bestandteil der Systembeschreibung der GA sein und sind einheitlich vorzugeben. [...] Die Art und die Zykluszeiten der erforderlichen Sicherungen sind zu definieren. | Es ist ein Konzept vorzusehen, wie die aufgezeichneten Daten dauerhaft archiviert werden. — printed p.31-32', verification_note='md-verified 2026-09-05 (§8.13.6, printed p.31-32) [VC]', verified_at=now() where id='3646b912-9436-4b49-9682-ee4a812426be' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · fernzugriff
update public.fields set verification_status='verified_against_standard', verification_quote='Alle Einrichtungen und Funktionen, die zur Fernbedienung des GA-Systems eingesetzt werden sollen, sind vorzugeben. Hierbei sind insbesondere die Sicherheitsvorgaben zu berücksichtigen. — printed p.32', verification_note='md-verified 2026-09-05 (§8.13.7, printed p.32) [VC]', verified_at=now() where id='eb5538bc-ed99-4e0d-a1f9-4b5d60923673' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-06 · gewerkespezifische_schnittstellen
update public.fields set verification_status='verified_against_standard', verification_quote='Im Rahmen der Bedarfsplanung empfiehlt es sich, detaillierte einheitliche Spezifizierungen der gewerkespezifischen Schnittstellen gemeinsam mit dem AG vorzunehmen und diese im weiteren Planungsprozess verfeinern zu lassen. [...] | Schnittstellendefinition im Gewerk A | Angaben vom Gewerk A an Gewerk B im Rahmen der Planung [...] | Lieferumfang Schnittstellengewerk A | Lieferumfang Schnittstellengewerk B | Koordinationsinhalte | Verantwortlichkeit | Gewährleistung | Dokumentation — printed p.32-33', verification_note='md-verified 2026-09-05 (§8.14, printed p.32-33) [VC] — the source is a recommendation ("empfiehlt es sich") — see STAGED file', verified_at=now() where id='ee0c29e7-e977-4717-9058-b5378bf11870' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-07 · anforderungen_pruefbar
update public.fields set verification_status='verified_against_standard', verification_quote='Im Lastenheft sind sämtliche Anforderungen aus Anwendersicht einschließlich aller Randbedingungen zu beschreiben. Die Anforderungen müssen quantifizierbar und prüfbar sein. — printed p.6', verification_note='md-verified 2026-09-05 (§6.1, printed p.6) [VC]', verified_at=now() where id='958f0ca8-83dc-4970-a46d-b3abdb567015' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-07 · lastenheft_vollstaendig
update public.fields set verification_status='verified_against_standard', verification_quote='Ein GA-Lastenheft wird grundsätzlich vom AG oder in seinem Auftrag (in der Regel unterstützt durch fachplanerische Kompetenz) vor Beginn einer Planung vollständig und widerspruchsfrei erstellt. — printed p.20', verification_note='md-verified 2026-09-05 (§8.1, printed p.20) [VC]', verified_at=now() where id='c701f6d2-d371-4c0b-9815-95e5e6aed588' and verification_status not in ('verified_against_standard','corrected');
-- VDI-3814-Blatt-2-1-07 · dokumente_gepflegt
update public.fields set verification_status='verified_against_standard', verification_quote='Die im Rahmen der Bedarfsplanung erstellten Dokumente, wie Betreiberkonzepte und Lastenhefte, sind durch den AG kontinuierlich zu pflegen und durch alle Verwender verpflichtend zu beachten. — printed p.5', verification_note='md-verified 2026-09-05 (§5, printed p.5) [VC]', verified_at=now() where id='c8a7f8c2-f0e4-4b66-996f-ccd02c77f5d8' and verification_status not in ('verified_against_standard','corrected');

-- App/project metadata (exempt class, 2026-08-01 ruling): ag_freigabe
update public.fields set verification_status='inferred_from_worksheet', verification_note='md-pass 2026-09-05: app/project metadata — the guideline does not define this field; exempt per the 2026-08-01 metadata ruling', verified_at=now() where id in ('fe1de286-eeea-49b7-8c13-b978ec464cfc') and verification_status not in ('verified_against_standard','corrected');
